### ISSUE TITLE
[macOS] configure-tccdb-macos.sh contains 2 bad rules

### ISSUE THREAD

**Issue by liam-x** [actions/runner-images#8907] opened 2023-11-28 01:07 UTC
### Description

This file contains 2 bad rules:
images/macos/provision/configuration/configure-tccdb-macos.sh

Please see PR #8782 8767 for details.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

don't have public build link

### Is it regression?

not sure

### Expected behavior

The PR https://github.com/actions/runner-images/pull/8767 contain fix.
The correct rule should allow child process of provisioner take screenshot on macOS runner.

### Actual behavior

If you use screencapture command, it can still produce a png file, but the png file does not contain windows elements due to missing screen recording permission.

### Repro steps

open ~/
screencapture ~/Desktop/picture.png

With this bad rule, the picture.png only show an empty macOS wallpaper.
With a good rule, the picture.png should contain a Finder window.

**Comment by sergei-pyshnoi** [comment] 2023-11-28 08:38
Closing as duplicate of https://github.com/actions/runner-images/issues/8782

**Closed by sergei-pyshnoi** 2023-11-28 08:38 UTC
Labels: needs triage, bug report
