### ISSUE TITLE
.NET 8

### ISSUE THREAD

**Issue by ehpmfigueroa** [actions/runner-images#8812] opened 2023-11-15 16:02 UTC
### Tool name

.NET 8

### Tool license

https://github.com/dotnet/core/blob/main/LICENSE.TXT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

8.0.0

### URL for tool's homepage

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by mikhailkoliada** [comment] 2023-11-15 16:41
Duplicate of https://github.com/actions/runner-images/issues/8797 - we track overall effort there

**Closed by mikhailkoliada** 2023-11-15 16:41 UTC
Labels: Area: .NET Core, feature request
