### ISSUE TITLE
On macos-latest and macos-14 Github runners, when I execute curl --unix-socket,  I get: curl: (7) Couldn't connect to server

### ISSUE THREAD

**Issue by lepapareil** [actions/runner-images#9643] opened 2024-04-05 13:08 UTC
### Description

Hi, I'm part of the team developing [Hurl](https://github.com/Orange-OpenSource/hurl), which is based on libcurl for the HTTP layer.

In this context we're doing both Hurl and Curl integration tests.

We use Ubuntu and MacOS runners (both x64 and aarch64) to test our commits, and since a few days, `hurl --unix-socket` still succeeds but `curl --unix-socket` is failing on MacOS runners with `curl: (7) Couldn't connect to server`.

I test it with the preinstalled curl version and with the last brew curl package, but it does not change anything.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-12: Version: 20240329.1
macos-14-arm64: 20240402.2

### Is it regression?

Yes, last succeed on runners:

- macos-12: 20240218.1
- macos-14-arm64: 20240325.1

### Expected behavior

Curl have to be able to connect to unix-socket like nc and hurl. 

### Actual behavior

```
Closing connection
curl: (7) Couldn't connect to server
```

### Repro steps

I created a small project to test this issue at https://github.com/lepapareil/curl-unix-socket-on-macos-github-runner.

The test.yml Github Workflows executes:

- install socat, nc, hurl and curl
- create unix-socket with:
  - `socat UNIX-LISTEN:${socket_file},fork EXEC:"echo 'Received HTTP/0.9'" &`
- test unix-socket with nc, hurl and curl:
  - `nc -U "${socket_file}"`
  - `echo -e 'GET http://dummy' | hurl --verbose --unix-socket "${socket_file}"`
  - `curl --verbose --unix-socket "${socket_file}" http://dummy`

The result is:

- Ubuntu runner: succeed
- MacOs runners: curl throws a `curl: (7) Couldn't connect to server`

![image](https://github.com/actions/runner-images/assets/15672496/62c33d0c-5676-4180-88c9-3492fb33e756)

**Comment by mikhailkoliada** [comment] 2024-04-05 13:19
Hey! looks like duplicate of https://github.com/actions/runner-images/issues/9626 which will be deployed next week.

**Closed by mikhailkoliada** 2024-04-05 13:19 UTC
Labels: Area: Apple, bug report
