### ISSUE TITLE
Hosted-agent: InstallAppleCertificate@2 with OpenSSL 3 stop working with p12 certificates

### ISSUE THREAD

**Issue by Komdosh** [actions/runner-images#8016] opened 2023-08-01 15:09 UTC
### Description

Azure DevOps Task:

```
- task: InstallAppleCertificate@2
  inputs:
    certPwd: '$(p12Password)'
    certSecureFile: 'macOS_developerId.p12'
 displayName: Setup Apple Certificate
```

Error:

```
Error outputting keys and certificates
00E7D85CF87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:341:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not read certificate from <stdin>
```

It was working perfectly a few hours ago, but stopped working after Microsoft host-agent was updated to https://github.com/actions/runner-images/releases/tag/macos-13%2F20230731.2

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-13
Version: 20230731.2
Included Software: https://github.com/actions/runner-images/blob/macos-13/20230731.2/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230731.2

### Is it regression?

Image: macos-13 Version: 20230611.2 
Included Software: https://github.com/actions/runner-images/blob/macos-13/20230611.2/images/macos/macos-13-Readme.md 
Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230611.2

### Expected behavior

InstallAppleCertificate works with apple developer p12 certificate

### Actual behavior

InstallAppleCertificate got error

### Repro steps

Just use apple certificate install task

    - task: InstallAppleCertificate@2
      inputs:
        certPwd: '$(p12Password)'
        certSecureFile: 'macOS_developerId.p12'
     displayName: Setup Apple Certificate

**Comment by mikhailkoliada** [comment] 2023-08-01 15:20
Duplicate of https://github.com/actions/runner-images/issues/8017

**Closed by mikhailkoliada** 2023-08-01 15:20 UTC
Labels: bug report
