### ISSUE TITLE
GitHub Action step is hanging until timeout

### ISSUE THREAD

**Issue by mattyrob** [actions/runner-images#6704] opened 2022-12-06 09:50 UTC
### Description

An GitHub action to run QUnit tests that has worked well for some time stopped working around the 22nd of November. The process runs on Linux using ubuntu-latest.
On finding [this blog article](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04) we have specified the workflow to use ubuntu-20-04 and the workflow is now operational again.

See also report I made in the wrong repository:
https://github.com/actions/runner/issues/2298

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2.299.1

https://github.com/ClassicPress/ClassicPress/actions/runs/3542477755/jobs/5948017123

### Is it regression?

https://github.com/ClassicPress/ClassicPress/actions/runs/3521742250/jobs/5903925683

### Expected behavior

This QUnit test should continue to work and function to completeness without hanging

### Actual behavior

The process runs as expected until the final step where the process hangs without further log output until the process is terminated after running without completing at 6 hours.

### Repro steps

Update the current GitHub Actions configuration to use `ubuntu-latest` and run the action.
Process will reach last stage and hang for 6 hours until being terminated.

On `ubuntu-20.04` the process runs successfully.

**Comment by erik-bershel** [comment] 2022-12-06 10:07
Probably related to this https://github.com/actions/runner-images/issues/6698. I'll be more specific after a little research.

**Comment by Alexey-Ayupov** [comment] 2022-12-06 10:53
Please provide minimal repro steps.

**Comment by mattyrob** [comment] 2022-12-06 11:02
The workflow file affected is here:
https://github.com/ClassicPress/ClassicPress/blob/develop/.github/workflows/javascript-tests.yml

You may be able to see from the [run history](https://github.com/ClassicPress/ClassicPress/actions/workflows/javascript-tests.yml) that we started getting run failures about 2 weeks ago (22 Nov 2022).

The workflow was using `runs-on: ubuntu-latest` and I noted in [this blog](https://github.blog/changelog/2022-12-01-github-actions-larger-runners-using-ubuntu-latest-label-will-now-use-ubuntu-22-04) that specifying a version would help if processes broke. I therefore tried `runs-on: ubuntu-20.04` and the task began running to completion once again.

To reproduce I suppose you could:
1/ clone the [repository](https://github.com/ClassicPress/ClassicPress)
2/ amend the workflow to use `ubuntu-latest` again
3/ run the workflow manually

**Comment by khider** [comment] 2022-12-15 21:07
Same problem. installing the dependencies hangs and eventually times out. Tried to downgrade to Ubuntu-20.04 as suggested above but it didn't fix the problem. 

Link to repo: https://github.com/LinkedEarth/Pyleoclim_util/actions/runs/3707003131/jobs/6282898422

**Comment by MaksimZhukov** [comment] 2023-01-16 19:08
Hello @mattyrob! 
Sorry for the late response and thank you for your patience!
I've tried to reproduce the issue on a clean Ubuntu 22.04 VM and got the same result - test step hangs. It seems to me that your project is not compatible with Ubuntu 22.04 or the issue is related to Ubuntu 22.04 itself.
Have you tried running the tests locally on Ubuntu 22.04?

**Comment by mattyrob** [comment] 2023-01-16 19:47
@MaksimZhukov - thanks for the response.

I don’t personally have access to an Ubuntu machine but I can ask other community members.

We have worked around this issue for now by specifying `Ubuntu-20.04` in the runner.

**Comment by MaksimZhukov** [comment] 2023-01-17 11:53
I am closing the issue since it is not related to GitHub hosted runners.
Feel free to contact us if you have any questions.

**Closed by MaksimZhukov** 2023-01-17 11:53 UTC
Labels: Area: JavaScript and Node.js, OS: Ubuntu, investigate, bug report

**Comment by mattyrob** [comment] 2023-01-19 19:42
@MaksimZhukov - Did you find that the process failed running on Ubuntu 22.04? How is it you are certain this issue is not linked to GitHub hosted runners?

If you can share the results and process of things you tried to reach that conclusion it may help me fix me issue.
