### ISSUE TITLE
linker issue with latest macos arm runner (macos-13-xlarge) with gcc 13 

### ISSUE THREAD

**Issue by hassanctech** [actions/runner-images#9314] opened 2024-02-08 04:04 UTC
### Description

With the latest version of the macos-13-arm64 runner:

```
Operating System
  macOS
  1[3](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7823896735/job/21346917123?pr=244#step:1:3).6.[4](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7823896735/job/21346917123?pr=244#step:1:4)
  22G[5](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7823896735/job/21346917123?pr=244#step:1:5)13
Runner Image
  Image: macos-13-arm[6](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7823896735/job/21346917123?pr=244#step:1:7)4
  Version: 20240204.1
  Included Software: https://github.com/actions/runner-images/blob/macos-13-arm64/20240204.1/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13-arm64%2F20240204.1
```

I'm seeing this linker issue:

```
0  0x1044d7648  __assert_rtn + 72
1  0x10440bfac  ld::AtomPlacement::findAtom(unsigned char, unsigned long long, ld::AtomPlacement::AtomLoc const*&, long long&) const + 1204
2  0x104421924  ld::InputFiles::SliceParser::parseObjectFile(mach_o::Header const*) const + 15164
3  0x10442ee30  ld::InputFiles::parseAllFiles(void (ld::AtomFile const*) block_pointer)::$_7::operator()(unsigned long, ld::FileInfo const&) const + 420
4  0x19cab0440  _dispatch_client_callout2 + 20
5  0x19cac5544  _dispatch_apply_invoke_and_wait + 224
6  0x19cac484c  _dispatch_apply_with_attr_f + 1180
7  0x19cac4a38  dispatch_apply + 96
8  0x1044a93b8  ld::AtomFileConsolidator::parseFiles(bool) + 292
9  0x10444a170  main + 9048
ld: Assertion failed: (resultIndex < sectData.atoms.size()), function findAtom, file Relocations.cpp, line 1336.
collect2: error: ld returned 1 exit status
```

When building my project, with the gcc 13 from homebrew, specified like so:

```
      CC: /opt/homebrew/bin/gcc-13
      CXX: /opt/homebrew/bin/g++-13
```

 I did not receive this error just a couple days ago with the following version:

```
Operating System
  macOS
  1[3](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7788855403/job/21239190089#step:1:3).6.3
  22G[4](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7788855403/job/21239190089#step:1:4)3[6](https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7788855403/job/21239190089#step:1:7)
Runner Image
  Image: macos-13-arm64
  Version: 20240114.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20240114.1/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20240114.1
```

I did a search and found this: https://developer.apple.com/forums/thread/737707?answerId=765558022#765558022

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/awslabs/amazon-kinesis-video-streams-pic/actions/runs/7823896735/job/21346917123?pr=244

### Is it regression?

Yes, provided in the details

### Expected behavior

No linker error, it should work!

### Actual behavior

Linker error:

```
0  0x1044d7648  __assert_rtn + 72
1  0x10440bfac  ld::AtomPlacement::findAtom(unsigned char, unsigned long long, ld::AtomPlacement::AtomLoc const*&, long long&) const + 1204
2  0x104421924  ld::InputFiles::SliceParser::parseObjectFile(mach_o::Header const*) const + 15164
3  0x10442ee30  ld::InputFiles::parseAllFiles(void (ld::AtomFile const*) block_pointer)::$_7::operator()(unsigned long, ld::FileInfo const&) const + 420
4  0x19cab0440  _dispatch_client_callout2 + 20
5  0x19cac5544  _dispatch_apply_invoke_and_wait + 224
6  0x19cac484c  _dispatch_apply_with_attr_f + 1180
7  0x19cac4a38  dispatch_apply + 96
8  0x1044a93b8  ld::AtomFileConsolidator::parseFiles(bool) + 292
9  0x10444a170  main + 9048
ld: Assertion failed: (resultIndex < sectData.atoms.size()), function findAtom, file Relocations.cpp, line 1336.
collect2: error: ld returned 1 exit status
```

### Repro steps

Here's a link to our `ci.yml` file the relevant section which is executed by the GHA runners:  https://github.com/awslabs/amazon-kinesis-video-streams-pic/blob/rc/.github/workflows/ci.yml#L106-L120

**Comment by mikhailkoliada** [comment] 2024-02-08 09:58
Duplicate of https://github.com/actions/runner-images/issues/9273#issue-2114862800

**Closed by mikhailkoliada** 2024-02-08 09:58 UTC
Labels: Area: Apple, OS: macOS, bug report
