### ISSUE TITLE
/imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'zstd' is not recognized as a name of a cmdlet

### ISSUE THREAD

**Issue by zioalex** [actions/runner-images#6200] opened 2022-09-08 09:00 UTC
### Description

I am building the ubuntu-20.04 runner-image and the build fails with:

```
********/
2022-09-08T06:52:34.5
700833Z ##[debug]Match start ind
ex: -1
2022-09-08T06:52:34.5701
554Z ##[debug]Match start index: -1
2022-09-08T06:52:34.5702490Z ##[debug]Match start index: -1
2022-09-08T06:52:34.5703200Z ##[debug]Match start index: -1
2022-09-08T06:52:34.570
38
2022-09-08T07:45:54.0399990Z ##[debug]Parsing log line to extract output...
2022-09-08T07:45:54.0402200Z ##[debug]/*************************************
2022-09-08T07:45:54.0403897Z ##[debug]==> azure-arm: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'zstd' is not recognized as a name of a cmdlet, function, script file, or executable program.

2022-09-08T07:45:54.0405517Z ##[debug]**************************************/
2022-09-08T07:45:54.0407283Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0408246Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0409074Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0409877Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0410665Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0411469Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0412362Z ==> azure-arm: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2022-09-08T07:45:54.0412725Z 
2022-09-08T07:45:54.0413309Z ##[debug]Parsing log line to extract output...
2022-09-08T07:45:54.0414090Z ##[debug]/*************************************
2022-09-08T07:45:54.0415144Z ##[debug]==> azure-arm: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2022-09-08T07:45:54.0416088Z ##[debug]**************************************/
2022-09-08T07:45:54.0416922Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0417723Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0418506Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0419305Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0420101Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0426536Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0427878Z ==> azure-arm: + CategoryInfo          : ObjectNotFound: (zstd:String) [SoftwareReport.Generator.ps1], CommandNotFoundException
2022-09-08T07:45:54.0428237Z 
2022-09-08T07:45:54.0428869Z ##[debug]Parsing log line to extract output...
2022-09-08T07:45:54.0429672Z ##[debug]/*************************************
2022-09-08T07:45:54.0430757Z ##[debug]==> azure-arm: + CategoryInfo          : ObjectNotFound: (zstd:String) [SoftwareReport.Generator.ps1], CommandNotFoundException

2022-09-08T07:45:54.0431718Z ##[debug]**************************************/
2022-09-08T07:45:54.0432559Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0433361Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0434161Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0434954Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0435734Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0436531Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0442718Z ==> azure-arm: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1
2022-09-08T07:45:54.0443102Z 
2022-09-08T07:45:54.0443757Z ##[debug]Parsing log line to extract output...
2022-09-08T07:45:54.0444541Z ##[debug]/*************************************
2022-09-08T07:45:54.0445865Z ##[debug]==> azure-arm: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1

2022-09-08T07:45:54.0446793Z ##[debug]**************************************/
2022-09-08T07:45:54.0447632Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0448419Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0449224Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0450193Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0450990Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0451786Z ##[debug]Match start index: -1
2022-09-08T07:45:54.0995247Z ==> azure-arm: Provisioner failed with "Script exited with non-zero exit status: 1. Allowed exit codes are: [0]", retrying with 3 trie(s) left
2022-09-08T07:45:54.1000761Z 
...
2022-09-08T07:46:21.7848425Z ==> azure-arm: time="2022-09-08T07:46:21Z" level=warning msg="Failed to decode the keys [\"machine\"] from \"/usr/share/containers/containers.conf\"."
2022-09-08T07:46:21.7849100Z 
2022-09-08T07:46:21.7849920Z ##[debug]Parsing log line to extract output...
2022-09-08T07:46:21.7850722Z ##[debug]/*************************************
2022-09-08T07:46:21.7854585Z ##[debug]Match start index: -1
2022-09-08T07:46:21.7855372Z ##[debug]Match start index: -1
2022-09-08T07:46:21.7856190Z ##[debug]Match start index: -1
2022-09-08T07:46:21.7857379Z ##[debug]Match start index: -1
2022-09-08T07:46:21.7858180Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8206807Z ==> azure-arm: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'zstd' is not recognized as a name of a cmdlet, function, script file, or executable program.
2022-09-08T07:46:25.8207403Z 
2022-09-08T07:46:25.8208547Z ##[debug]Parsing log line to extract output...
2022-09-08T07:46:25.8209275Z ##[debug]/*************************************
2022-09-08T07:46:25.8210357Z ##[debug]==> azure-arm: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : The term 'zstd' is not recognized as a name of a cmdlet, function, script file, or executable program.

2022-09-08T07:46:25.8211281Z ##[debug]**************************************/
2022-09-08T07:46:25.8211995Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8212695Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8213487Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8214182Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8214891Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8215572Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8224895Z ==> azure-arm: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2022-09-08T07:46:25.8225568Z 
2022-09-08T07:46:25.8226207Z ##[debug]Parsing log line to extract output...
2022-09-08T07:46:25.8226900Z ##[debug]/*************************************
2022-09-08T07:46:25.8227846Z ##[debug]==> azure-arm: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

2022-09-08T07:46:25.8228670Z ##[debug]**************************************/
2022-09-08T07:46:25.8229535Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8230233Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8230948Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8231643Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8232336Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8233027Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8233879Z ==> azure-arm: + CategoryInfo          : ObjectNotFound: (zstd:String) [SoftwareReport.Generator.ps1], CommandNotFoundException
2022-09-08T07:46:25.8234191Z 
2022-09-08T07:46:25.8234744Z ##[debug]Parsing log line to extract output...
2022-09-08T07:46:25.8235421Z ##[debug]/*************************************
2022-09-08T07:46:25.8236346Z ##[debug]==> azure-arm: + CategoryInfo          : ObjectNotFound: (zstd:String) [SoftwareReport.Generator.ps1], CommandNotFoundException

2022-09-08T07:46:25.8237171Z ##[debug]**************************************/
2022-09-08T07:46:25.8237896Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8238592Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8239286Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8239977Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8240656Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8241348Z ##[debug]Match start index: -1
2022-09-08T07:46:25.8247407Z ==> azure-arm: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1
2022-09-08T07:46:25.8247910Z 


```
I've checked and the zstd package has been downloaded correctly:

```
2022-09-08T07:42:42.3006571Z     azure-arm: ==> Installing zstd
2022-09-08T07:42:42.3006731Z 
2022-09-08T07:42:42.3007238Z ##[debug]Parsing log line to extract output...
2022-09-08T07:42:42.3007917Z ##[debug]/*************************************
2022-09-08T07:42:42.3008679Z ##[debug]    azure-arm: ==> Installing zstd

2022-09-08T07:42:42.3009357Z ##[debug]**************************************/
2022-09-08T07:42:42.3010074Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3010771Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3011468Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3012162Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3012856Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3013533Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3504259Z     azure-arm: ==> Pouring zstd--1.5.2.x86_64_linux.bottle.3.tar.gz
2022-09-08T07:42:42.3504582Z 
2022-09-08T07:42:42.3505462Z ##[debug]Parsing log line to extract output...
2022-09-08T07:42:42.3506254Z ##[debug]/*************************************
2022-09-08T07:42:42.3507266Z ##[debug]    azure-arm: ==> Pouring zstd--1.5.2.x86_64_linux.bottle.3.tar.gz

2022-09-08T07:42:42.3508119Z ##[debug]**************************************/
2022-09-08T07:42:42.3508959Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3510120Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3510910Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3511730Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3512533Z ##[debug]Match start index: -1
2022-09-08T07:42:42.3513335Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7470444Z     azure-arm: 🍺  /home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.2: 31 files, 2.6MB
2022-09-08T07:42:43.7471861Z 
2022-09-08T07:42:43.7474437Z ##[debug]Parsing log line to extract output...
2022-09-08T07:42:43.7480937Z ##[debug]/*************************************
2022-09-08T07:42:43.7490089Z ##[debug]    azure-arm: 🍺  /home/linuxbrew/.linuxbrew/Cellar/zstd/1.5.2: 31 files, 2.6MB

2022-09-08T07:42:43.7491152Z ##[debug]**************************************/
2022-09-08T07:42:43.7492182Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7493000Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7493790Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7494637Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7495438Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7496233Z ##[debug]Match start index: -1
2022-09-08T07:42:43.7497192Z     azure-arm: ==> Running `brew cleanup zstd`...

```
And consequently the build failed:
```
2022-09-08T07:47:28.8317576Z ==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
2022-09-08T07:47:28.8317966Z 
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current image version: '20220905.1'

### Is it regression?

20220828.1

### Expected behavior

The image is build correctly

### Actual behavior

The build fails.

### Repro steps

Run the build pipeline

**Comment by al-cheb** [comment] 2022-09-08 09:02
Hello @zioalex.
We are working on this issue related to the new brew version 3.6.0.

**Comment by zioalex** [comment] 2022-09-08 09:28
Is there anyway to specify the image Version to use?

**Comment by al-cheb** [comment] 2022-09-08 09:35
> Is there anyway to specify the image Version to use?

There is no way to specify image version. You could fork the repo and temporary remove brew installation.

**Comment by zioalex** [comment] 2022-09-08 11:12
In the release page I still see version Homebrew 3.5.10 (https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) and not the 3.6.0.

**Comment by naikrovek** [comment] 2022-09-09 00:54
> In the release page I still see version Homebrew 3.5.10 (https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md) and not the 3.6.0.

I'm sure it will be updated.  If they update the documentation before they fix the image generation, the documentation will be wrong.  If they fix the image generation before the documentation is updated, the documentation will be wrong.  

I would rather they fix the problem, first.

**Comment by raherrebrugh** [comment] 2022-09-12 06:38
Also applies to Ubuntu 18.04

**Comment by mikhailkoliada** [comment] 2022-09-12 15:34
Should be fixed, please update your main and try again.

**Closed by mikhailkoliada** 2022-09-12 15:34 UTC
Labels: OS: Ubuntu, Area: Common Tools, investigate, bug report

**Comment by zioalex** [comment] 2022-09-15 16:49
When will it be part of a release?
Alessandro Surace

**Comment by mikhailkoliada** [comment] 2022-09-15 17:18
@zioalex we currently rolled this change back as brew now installs gcc@11 on ubuntu18 and 20 and this also conflicts with toolchain provided by ubuntu itself, we are working on the fix, hopefully it will be in the next week's release

**Comment by shapleya** [comment] 2022-09-19 04:26
This is still happening trying to build ubuntu-20.04

**Comment by koaminakligo-eaton** [comment] 2022-09-20 14:25
> @zioalex we currently rolled this change back as brew now installs gcc@11 on ubuntu18 and 20 and this also conflicts with toolchain provided by ubuntu itself, we are working on the fix, hopefully it will be in the next week's release

@al-cheb @mikhailkoliada Is this ubuntu20 issue about 'zstd not recognize' fixed yet. I am having the same issue. Thank you

**Comment by naikrovek** [comment] 2022-09-20 18:48
if you are having the same issue, it isn't fixed, yet, is it?

**Comment by naikrovek** [comment] 2022-09-21 17:27
> > if you are having the same issue, it isn't fixed, yet, is it?
> 
> It's fixed

Then why are you having this exact problem?  Am I misunderstanding?

**Comment by koaminakligo-eaton** [comment] 2022-09-21 17:34
> > > if you are having the same issue, it isn't fixed, yet, is it?
> > 
> > 
> > It's fixed
> 
> Then why are you having this exact problem? Am I misunderstanding?

I had that problem last Friday when I was updating our VM. I updated the latest changes yesterday, and the issue is fixed.
