### ISSUE TITLE
Exisintg non-brew python 3.11 break brew install of python@3.11

### ISSUE THREAD

**Issue by assignUser** [actions/runner-images#6868] opened 2023-01-03 17:54 UTC
### Description

If we try to install python@3.10 or python@3.11 via a formula, dependency or manually via brew _after_ running `brew update` the sym linking fails, which causes the install to fail. We came across this issue when testing the homebrew formulae for apache/arrow.

Also discussed here https://github.com/orgs/Homebrew/discussions/3895

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-11 Version: 20221215.1
Image: macos-12  Version: 20221215.1

https://github.com/assignUser/test-repo-a/actions/runs/3823624240/jobs/6504985599#step:2:119

### Is it regression?

Yes, we have been running these builds for years at this point but I was unable to pinpoint the exact  date were the failures begun (due to log limits)

### Expected behavior

python 3.11/3.10 is installed and sym linked by brew  (or detected as installed) 

### Actual behavior

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'
```

### Repro steps

1. `brew update` to detect the broken linkage 
2. `brew install python@3.11`

**Comment by mikhailkoliada** [comment] 2023-01-03 18:33
Duplicate of https://github.com/actions/setup-python/issues/577

**Closed by mikhailkoliada** 2023-01-03 18:33 UTC
Labels: needs triage, bug report
