### ISSUE TITLE
[Windows] Python call os.getenv("APPDATA") returns None

### ISSUE THREAD

**Issue by qpavsmi** [actions/runner-images#7019] opened 2023-01-31 09:44 UTC
### Description

On GitHub Windows runners calling ``os.getenv("APPDATA")`` returns None. This started happening at some date between 18th of January and last week. Do you recommend another way to access environment variables in Python code or is this a bug?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version: 20230123.1

https://github.com/qpavsmi/KQCircuits/actions/runs/4041928988/jobs/6972154059

### Is it regression?

Version: 20230109.1

### Expected behavior

Test suite should pass or at least the assertion ``assert os.getenv("APPDATA") is not None`` should not fail

### Actual behavior

The temporary assertion ``assert os.getenv("APPDATA") is not None`` fails when it didn't before

### Repro steps

Include ``assert os.getenv("APPDATA") is not None`` at some point of the test suite execution and see it fail

**Comment by bogdan-damian-bgd** [comment] 2023-01-31 12:05
Hello @qpavsmi, we'll take a look at it.

**Comment by bogdan-damian-bgd** [comment] 2023-01-31 13:37
Hi, we cannot reproduce the issue when calling `os.getenv("APPDATA")` or `assert os.getenv("APPDATA") is not None`. It works as expected - take a look [here](https://github.com/bogdan-damian-bgd/action-tests/actions/runs/4054560100/jobs/6976536520).

We will close the issue now, if you have any questions feel free to reach us.

**Closed by bogdan-damian-bgd** 2023-01-31 13:37 UTC
Labels: OS: Windows, bug report

**Comment by qpavsmi** [comment] 2023-01-31 13:43
OK, thank you for trying! Will try to search for the issue cause on my deployment
