### ISSUE TITLE
"An image label with the label unsupported-vmimage does not exist" using `macos-13-arm64`

### ISSUE THREAD

**Issue by albyrock87** [actions/runner-images#8945] opened 2023-12-04 11:16 UTC
### Description

Everything was working fine until one hour ago, then suddenly I'm getting the following error:
```
##[warning]An image label with the label unsupported-vmimage does not exist.
,##[error]The remote provider was unable to process the request.
Pool: [Azure Pipelines](https://dev.azure.com/centralreach01/472e2055-b6ee-4ef4-9bcd-bae6e680286c/_settings/agentqueues?poolId=&queueId=18)
Image: macos-13-arm64
```

I also tried to use `macos-14-arm64`, but in that case the error says that:
```
##[warning]An image label with the label macos-14-arm64 does not exist.
```

I also tried to use `macos-14`, but in that case the error says that:
```
##[warning]An image label with the label macos-14 does not exist.
```

Then I tried using `macos-13` but that image is not up to date (no .NET8, and I don't like to install .NET 8 from scratch every time).

This looks very similar to https://github.com/actions/runner-images/issues/8926

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

-

### Is it regression?

Yes, last successful build was using 20231115.2

### Expected behavior

The `macOS-13-arm64` image is found and runs as expected

### Actual behavior

The `macOS-13-arm64` image appears to be not found.

### Repro steps

1. Create an Azure pipeline using macOS-13-arm64
2. Run it a bunch of times

**Comment by mikhailkoliada** [comment] 2023-12-04 11:27
Closing as duplicate of https://github.com/actions/runner-images/issues/8879#issuecomment-1835868196 as stated in the comment Azure DevOps only supports what listed in the table, while macOS 14 is not supported yet at all.

**Closed by mikhailkoliada** 2023-12-04 11:27 UTC
Labels: Area: Image administration, bug report

**Comment by mmrazik** [comment] 2023-12-04 17:46
>Definitely not a duplicate of 8879 which is to do with slow AzureDevOps pool providers.

You are right about this but the previous comment was mostly referring to the specific comment which mentions [supported vmImages in ADO](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software ).

`macos-13-arm64` is an undocumented vmImage and I believe it is not working on GH either (`macos-13-xl` is). The pricing model is also different. 
That said, I hear and acknowledge the feedback (as someone who works on ADO).

**Comment by qwertylolman** [comment] 2023-12-06 09:30
we also started to receive this error today :(

**Comment by Nathan-Molby** [comment] 2023-12-06 20:19
https://github.com/actions/runner-images/issues/8971
