### ISSUE TITLE
Update/Add OpenTuFu

### ISSUE THREAD

**Issue by ctrl-matters** [actions/runner-images#9684] opened 2024-04-15 09:30 UTC
### Tool name

opentofu

### Tool license

Mozilla Public License, version 2.0

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Approximate size

25MB

### Brief description of tool

Opensource fork of terraform as terraform switched to Business Source License

### URL for tool's homepage

https://opentofu.org/

### Provide a basic test case to validate the tool's functionality.

```bash
tofu --version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
# Download the installer script:
curl --proto '=https' --tlsv1.2 -fsSL https://get.opentofu.org/install-opentofu.sh -o install-opentofu.sh
# Alternatively: wget --secure-protocol=TLSv1_2 --https-only https://get.opentofu.org/install-opentofu.sh -O install-opentofu.sh

# Give it execution permissions:
chmod +x install-opentofu.sh

# Please inspect the downloaded script

# Run the installer:
./install-opentofu.sh --install-method deb

# Remove the installer:
rm install-opentofu.sh
```

**Comment by MaksimZhukov** [comment] 2024-04-15 11:12
Hello @ctrl-matters!
I am closing this feature request as a duplicate of [this one ](https://github.com/actions/runner-images/issues/9507).

**Closed by MaksimZhukov** 2024-04-15 11:12 UTC
Labels: needs triage, feature request
