### ISSUE TITLE
Update Xcode 16 RC (16A242) to Xcode 16 (16A242d)

### ISSUE THREAD

**Issue by enricenrich** [actions/runner-images#10629] opened 2024-09-16 21:52 UTC
### Tool name

Xcode

### Tool license

Propietary with open-source components

### Add or update?

- [ ] Add
- [X] Update

### Desired version

16 (16A242d)

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by enricenrich** [comment] 2024-09-16 21:54
_Related to this issue: https://github.com/actions/runner-images/issues/10583_

Today, Apple released an update for Xcode 16 (16A242d) ([ref.](https://developer.apple.com/news/releases/)), disabling the previous RC version (16A242) from being used to upload builds to App Store Connect.

**Comment by sarathrajsrinivasan** [comment] 2024-09-16 22:01
Hi @enricenrich, 

We are looking into it. Will keep you posted.

**Comment by bgoncal** [comment] 2024-09-17 13:40
Any ETA? Sorry to ask that, I know Apple does not make your life that easy during this period 😅

**Comment by erik-bershel** [comment] 2024-09-17 20:01
Hey @enricenrich and @bgoncal!

PR merged. `Xcode 16` will be delivered with the next `macOS-14` image rollout.

**Comment by enricenrich** [comment] 2024-09-17 20:09
Thanks for the update, @erik-bershel. When will be the next `macOS-14` image rollout?

**Comment by erik-bershel** [comment] 2024-09-17 20:18
> When will be the next macOS-14 image rollout?

ASAP. But no promises here. We understand your need and will try to release it out of the schedule.

**Comment by yosi199** [comment] 2024-09-19 04:56
thanks guys, am also looking forward for it

**Comment by erik-bershel** [comment] 2024-09-19 08:32
Rollout in progress, changes to track: https://github.com/actions/runner-images/pull/10647

**Comment by fousa** [comment] 2024-09-20 07:05
> Rollout in progress, changes to track: #10647

Any idea what the throughput time is?

**Comment by prasanjitsahoo** [comment] 2024-09-20 11:52
Hi @fousa, VM rollout is done.

**Closed** 2024-09-20 11:54 UTC
Labels: Area: Apple, OS: macOS, feature request

**Comment by BrentMifsud** [comment] 2024-09-20 17:19
thanks for the quick turnaround. The App Store was throwing errors when trying to submit new builds with the release candidate. Hopefully this resolves it.

**Comment by Light407** [comment] 2024-09-22 15:17
Updated to XCode 16.0 (also tried 16.1) in our Build Pipeline and getting this error:

`xcrun: error: unable to find utility "actool", not a developer tool or in PATH`

Any ideas on what this is? Any help really appreciated

**Comment by Light407** [comment] 2024-09-22 19:03
This seems to work for 16.1 but other versions give actool issue:


`sudo xcode-select -switch /Applications/Xcode_16.1_beta_2.app`

**Comment by erik-bershel** [comment] 2024-09-23 11:26
Hey @Light407!

Try switching Xcode with [maxim-lobanov/setup-xcode](https://github.com/maxim-lobanov/setup-xcode). I think the issue is hiding in a version switching somehow.

**Comment by MatMor** [comment] 2024-09-27 19:28
Hey @Light407, we fighted with the same issue. At the end, this worked on our end:
`sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer`

**Comment by jwidmer** [comment] 2024-10-04 18:28
In case anyone else finds themselves here wondering why Xcode 16.0 is not found:
We were setting the path for 16.0 in the path as:
sudo xcode-select -switch /Applications/Xcode_16.0.app/Contents/Developer

but for 16.0 the path is just:
sudo xcode-select -switch /Applications/Xcode_16.app/Contents/Developer

Notice Xcode_16.app instead of Xcode_16.0.app

We used:
find /Applications/ -name "Xcode*.app" -type d
to check the path.

**Comment by daltonclaybrook** [comment] 2024-10-04 22:29
@jwidmer FYI, the paths of Xcode installations are documented in the image README files:

https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md#xcode
