### ISSUE TITLE
MacOS-12 Agent: Cocoapods is broken

### ISSUE THREAD

**Issue by joshuapoq** [actions/runner-images#6149] opened 2022-08-26 13:13 UTC
### Description

Cocoapods is no longer loading on the `macos-12` hosted agents. This was working fine yesterday and we do not install any other gems.
```
/usr/local/lib/ruby/site_ruby/3.0.0/rubygems/specification.rb:2288:in `raise_if_conflicts': Unable to activate cocoapods-core-1.11.3, because public_suffix-5.0.0 conflicts with public_suffix (~> 4.0) (Gem::ConflictError)
```

I reported this earlier via the developercommunity but we've already gone many hours with failing builds so I'm raising here.
https://developercommunity.visualstudio.com/t/MacOS-12-Agent:-Cocoapods-is-broken/10132099

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failing version (today): `20220823.1`

Working version (yesterday): `20220815.1`

### Is it regression?

Yes

### Expected behavior

Cocoapods should continue to function.

### Actual behavior

Cocoapods does not load and our apps cannot be built.

### Repro steps

We use `fastlane_require("cocoapods")` with `fastlane`.

1. Create a `Fastfile` in `./fastlane/Fastfile`.
```
fastlane_require("cocoapods")
```
2. Run `fastlane` command...

**Comment by mikhailkoliada** [comment] 2022-08-26 14:17
@joshuapoq Hello!

We will take a look.

**Comment by miketimofeev** [comment] 2022-08-26 14:40
@joshuapoq could you please add this line before executing Fastlane? `gem uninstall public_suffix -v 5.0.0` there are two `public_suffix` versions available on the image (4.0.7 & 5.0.0) and that fact seems to be a root cause of the issue. We are currently investigating where both versions came from and what can be done to resolve the issue. Sorry for the inconvenience.

**Comment by miketimofeev** [comment] 2022-08-31 17:11
@joshuapoq the new image with a workaround has been deployed. I'm going to close the issue but please let me know if the issue persists.
Thank you!

**Closed by miketimofeev** 2022-08-31 17:11 UTC
Labels: Area: Ruby, OS: macOS, investigate, bug report

**Comment by joshuapoq** [comment] 2022-12-14 09:55
This is back again with public suffix `5.0.1` I'll redeploy the fix on our side. @miketimofeev
