### ISSUE TITLE
Xamarin app build for Android fails from one day to another

### ISSUE THREAD

**Issue by florian-berger** [actions/runner-images#8881] opened 2023-11-23 10:18 UTC
### Description

Hi,

we are building our Xamarin.Forms app for multiple years via Azure DevOps on a hosted machine with the `windows-latest` image.

The last successful build was on November 13th. Yesterday on November 22nd, we needed to build again, and now the Android build fails. Based on the error message, it looks like the required Java SDK is no longer installed.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20231115.2.0
Included Software: https://github.com/actions/runner-images/blob/win22/20231115.2/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231115.2

### Is it regression?

Yes. Worked in a previous `windows-latest`, but now it's no longer working.

### Expected behavior

The Android app is able to be built.

### Actual behavior

Build is failing:

```
##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): Error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0.
Download the latest JDK at: https://aka.ms/msopenjdk
Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Java SDK 11.0 or above is required when using $(TargetFrameworkVersion) v12.0. [D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Download the latest JDK at: https://aka.ms/msopenjdk [D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj]
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Legacy.targets(254,5): error XA0031: Note: the Android Designer is incompatible with Java SDK 11.0: https://aka.ms/vs2019-and-jdk-11 [D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj]
Done Building Project "D:\a\1\s\MobileApp\MobileApp\MobileApp.Android\MobileApp.Android.csproj" (SignAndroidPackage;PackageForAndroid target(s)) -- FAILED.

Build FAILED.
```

### Repro steps

We have the following Pipeline definition:
```yml
- job: Android
  timeoutInMinutes: 45
  pool:
    vmImage: 'windows-latest'

  variables:
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)/'

  steps:
  - task: NuGetToolInstaller@1
    displayName: Download NuGet.exe

  - task: NuGetCommand@2
    displayName: Restore NuGet packages
    inputs:
      command: 'restore'
      restoreSolution: '**/MobileApp.sln'
      feedsToUse: 'config'
      nugetConfigPath: 'NuGet.config'

  - task: DownloadSecureFile@1
    name: keystore
    displayName: 'Download Keystore file for signing'
    inputs:
      secureFile: 'android.keystore'

  - task: XamarinAndroid@1
    displayName: 'Build Android app'
    inputs:
      projectFile: '**/*Droid*.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'
      msbuildArguments: '-restore -t:SignAndroidPackage -p:AndroidPackageFormat=aab -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=$(keystore.secureFilePath) -p:AndroidSigningStorePass=$(keystorePassword) -p:AndroidSigningKeyAlias="[ALIAS_OF_OUR_SIGNING_KEY]" -p:AndroidSigningKeyPass=$(keystorePassword) -p:AndroidNdkDirectory="$(ANDROID_NDK_HOME)"'
```

**Comment by mikhailkoliada** [comment] 2023-11-23 10:41
Duplicate of https://github.com/actions/runner-images/issues/8837

**Closed by mikhailkoliada** 2023-11-23 10:41 UTC
Labels: Area: Android, Area: Xamarin, OS: Windows, bug report
