### ISSUE TITLE
Update Windows Images to Include Chrome / Chrome Driver v116

### ISSUE THREAD

**Issue by krypton1981** [actions/runner-images#8114] opened 2023-08-17 21:58 UTC
### Tool name

Chrome / Chrome Driver Update - v116

### Tool license

Apache v2.0

### Add or update?

- [ ] Add
- [X] Update

### Desired version

Latest 116 Stable

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by shamil-mubarakshin** [comment] 2023-08-18 07:28
Hello @krypton1981,
`v116` will be included in upcoming image rollout, which should start next week and take around a week to complete

**Comment by ybm-25** [comment] 2023-08-22 23:43
Hey @shamil-mubarakshin,

I have a question related to this change, my Pipelines started failing today, due to apparently Chrome browser isn't installed in the Current image version: '20230820.1.0' 

![image](https://github.com/actions/runner-images/assets/142949075/5e1fa2a2-db65-4280-9d54-ffc6ca6eb45a)

I reviewed the Included Software: https://github.com/actions/runner-images/blob/win19/20230820.1/images/win/Windows2019-Readme.md and I see that Chrome should be installed.

So I was wondering if this is due to image rollout, or if it's a different problem??

I saw that the image 20230820.1.0 is still in pre-release, but as far as I know the Agent pool: Azure Pipelines doesn't let you select the version and it has already started using 20230820.1.0 instead of 20230814.1.0 where Chrome was installed.

**Comment by ybm-25** [comment] 2023-08-23 17:36
Sure @shamil-mubarakshin, 

I'm testing a Desktop application that opens a Browser (the one defined as default in the OS) when click on a link, currently I'm using Chrome, so as a precondition the test sets Google Chrome as the default browser in Settings -> Default apps -> Web browser. 

*This had been working in versions prior to 20230820.1.0

The error in the Pipeline is due to the fact that Google Chrome is no longer listed in the options to choose it as the default browser.

Error Message:
   OneTimeSetUp: OpenQA.Selenium.WebDriverException : An element could not be located on the page using the given search parameters.

Image 20230820.1.0
![image](https://github.com/actions/runner-images/assets/142949075/ddb1726b-890d-473b-a970-0b29b061a661)

Here an screenshot for previous Image version (20230814.1.0)

![image](https://github.com/actions/runner-images/assets/142949075/fda521e3-1bf9-40d5-b0db-3484345a1c20)

**Comment by Artem-Babich** [comment] 2023-08-29 07:13
Hi!

I'm from the TestCafe team. I would like to add some important notes to this issue. First of all, that was an unexpected update that broke our tests. We have a tool that is used to determine installed browsers. After this change, this tool cannot find Chrome. Also, we have a strong policy to run tests only in real browsers and not their forks. So, we cannot accept this change in our CI. That is why we decided to remove this chrome and install the real one. I kindly ask you to specify this important breaking change [in your ReadMe file](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#browsers-and-drivers). Now, it looks like you didn't change anything but you actually changed the browser version and the browser itself.

**Comment by JonnyBurger** [comment] 2023-08-29 09:38
Another regression is that now the `<video>` tag inside Chrome does not support MP4's anymore, whereas previously it did, since Chrome for Testing was not compiled with proprietary codecs like the normal Chrome version.

**Comment by mathiasbynens** [comment] 2023-08-29 12:49
Hi, Chrome for Testing (CfT) lead here. I want to assure everyone that we are aware that proprietary codecs are currently not yet enabled on CfT. We are working hard to make that happen as soon as possible. The tracking issue for this is crbug.com/1457118 (internal, sorry).

@GitHub folks, Chrome for Testing can be installed alongside Chrome. Perhaps one solution here might be to install CfT side-by-side, and keep the default browser as regular Chrome for now to avoid unexpected breakages? Then at some point in the future we could consider changing the default from Chrome to Chrome for Testing.

**Comment by shamil-mubarakshin** [comment] 2023-08-30 16:32
Given the discrepancies between two browsers and use cases in images, it has been decided to roll Chrome for Testing changes back. Rollout will start next week and will take around a week to complete.

**Comment by ybm-25** [comment] 2023-08-30 17:33
> Given the discrepancies between two browsers and use cases in images, it has been decided to roll Chrome for Testing changes back. Rollout will start next week and will take around a week to complete.

Sounds good 😇, thanks @shamil-mubarakshin

**Comment by mikhailkoliada** [comment] 2023-09-07 11:59
chrome for testing was reverted as said above and the old version rolled out to all the customers.

**Closed by mikhailkoliada** 2023-09-07 11:59 UTC
Labels: awaiting-deployment, OS: Windows, Area: Common Tools, feature request

**Comment by mathiasbynens** [comment] 2023-09-20 07:41
> I want to assure everyone that we are aware that proprietary codecs are currently not yet enabled on CfT. We are working hard to make that happen as soon as possible. The tracking issue for this is [crbug.com/1457118](https://crbug.com/1457118) (not public, sorry).

**Update:** as of Chrome for Testing 119.0.6018.4 proprietary media codecs are supported. See https://github.com/GoogleChromeLabs/chrome-for-testing/issues/18#issuecomment-1727136828 for details.
