### ISSUE TITLE
GitHub unable to read RAILWAY_TOKEN

### ISSUE THREAD

**Issue by Ethaneral** [actions/runner-images#7523] opened 2023-05-03 04:26 UTC
### Description

Hi, under the error I can clearly see the the RAILWAY_TOKEN, the secrets is setup properly. 
All previous steps of GitHub Actions successful.
RAILWAY_TOKEN also properly setup.

I had verified that the RAILWAY_TOKEN is correct to the letter. 
I had try placing env under the railway up steps

    - name: Deploy #REF: https://docs.railway.app/deploy/deployments#deploy-triggers
      if: ${{ success() }} #only if previous steps all successful
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

and here:

  build_golang: 
    runs-on: ubuntu-latest 
    if: ${{ !startsWith(github.event.head_commit.message, '#NORUN') }} #start of string only, REF: https://docs.github.com/en/actions/learn-github-actions/expressions
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

But still gives me below error despite the TOKEN is visibly available:

railway up
  shell: /usr/bin/bash -e {0}
  env:
    RAILWAY_TOKEN: ***
    SLACK_WEBHOOK_URL: ***
Project Token not found
Error: Process completed with exit code 1.

Weird Github bug please help.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

For GitHub Actions

### Is it regression?

no

### Expected behavior

Deploy to Railway normally

### Actual behavior

ERROR:

railway up
  shell: /usr/bin/bash -e {0}
  env:
    RAILWAY_TOKEN: ***
    SLACK_WEBHOOK_URL: ***
Project Token not found
Error: Process completed with exit code 1.

### Repro steps

Push to GitHub branches to auto trigger GitHub Action for deployment of golang app to Railway

**Comment by Alexey-Ayupov** [comment] 2023-05-03 09:42
Hello @Ethaneral, it looks like the problem is not in our images. Could you please log this issue to the https://github.com/actions/runner repository?
We are going to close this issue here. If you have any questions regarding our images feel free to reach us.

**Closed by Alexey-Ayupov** 2023-05-03 09:42 UTC
Labels: Area: Go, OS: Ubuntu, bug report
