### ISSUE TITLE
Github action job is cancled by remote provider.

### ISSUE THREAD

**Issue by senser-adi** [actions/runner-images#7897] opened 2023-07-11 09:11 UTC
### Description

Hi
In the last few days one of the Github actions jobs on my pipeline is canceled.
Note that some of the steps pass, and it's being canceled in the middle 

Job is running on a standard runner, ubuntu-latest 
 
I see the following message under "Annotations":
**Received request to deprovision: The request was cancelled by the remote provider.**

There were similar issues in the past with Azure runners - but are closed: [https://github.com/actions/runner-images/issues/2575](url)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.305.0'

### Is it regression?

no

### Expected behavior

Job should pass (was until now for months)

### Actual behavior

Job starts, runs for quite a long time, part of the steps pass, and then in one of the steps is shown as "canceled". 
All other steps become with a red X

### Repro steps

It's a private repo

**Comment by Alexey-Ayupov** [comment] 2023-07-11 13:18
Hello @senser-adi, as you properly noticed the issue is the very same as https://github.com/actions/runner-images/issues/2575, however, related to the GitHub backend. We will take a look, but we cannot do much about it.
Could you please provide the URL to the failed run?

**Comment by Alexey-Ayupov** [comment] 2023-07-21 14:51
Hello @senser-adi, sorry for the long response.
According to our telemetry, we have found that your workflow has a step `env-test`  that highly utilizes CPU and Memory. Because of high utilization, the agent become no longer available.

Here you have two options:
1. modify `env-test` step to reduce it's CPU/Memory usage
2. Switch to GitHub LargerRunner or self-hosted runner with more powerful VM spec. [Standard runners ](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)only have 2 CPU/7 GB Rams.

I will close this issue. If you have other questions feel free to reach us.

**Closed by Alexey-Ayupov** 2023-07-21 14:51 UTC
Labels: OS: Ubuntu, bug report

**Comment by liangyuanpeng** [comment] 2024-05-30 05:28
@Alexey-Ayupov 

Hi, I'm having this problem too and it seems to only happen with my PRs. I don't see CI using more resources than the limit. Could you help check it out? Thanks.
https://github.com/karmada-io/karmada/actions/runs/9297158841?pr=4801

It first appeared in my personal repo. I use CI to compile kubernetes.  https://github.com/liangyuanpeng/lanactions/actions/runs/9295898959

Is it possible that there is something wrong with my account?

**Comment by liangyuanpeng** [comment] 2024-05-30 05:39
It seems this is not an isolated phenomenon : https://github.com/actions/runner-images/issues/9848#issuecomment-2137929870

**Comment by amogh-jahagirdar** [comment] 2024-05-31 03:15
We've also been hitting this more frequently recently as well:

https://github.com/apache/iceberg/actions/runs/9289254669/job/25562692790?pr=10386
https://github.com/apache/iceberg/actions/runs/9290212169/job/25565947690?pr=10396

Is it possible to reopen this issue? It does seem like this is a wider issue across different projects happening more recently.

**Comment by oferEz** [comment] 2024-07-15 12:53
Same with me, I get the Error: "Received request to deprovision: The request was cancelled by the remote provider."
Private repo

**Comment by maximveksler** [comment] 2024-12-15 16:03
private repo "Received request to deprovision: The request was cancelled by the remote provider" on CodeQL action.
