### ISSUE TITLE
Hang when trying to build Ubuntu 22.04 image

### ISSUE THREAD

**Issue by nnellanspdl** [actions/runner-images#8192] opened 2023-08-29 13:51 UTC
### Description

Hi team,

I am using an Azure DevOps Pipeline to run the `GenerateResourcesAndImages.ps1` script to build an Ubuntu 22.04 image.

I'm getting hung up when the script runs the file `/scripts/installers/git.sh`.  Here are the final lines of output:

```
    azure-arm.build_vhd: Downloading 'https://github.com/mislav/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz' to '/tmp/hub/hub-linux-amd64-2.14.2.tgz'...
    azure-arm.build_vhd: Download completed
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed
```

After this, it simply hangs here until the Azure DevOps Pipelines job times out.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

refs/tags/ubuntu22/20230821.1

### Is it regression?

Unsure

### Expected behavior

The script to complete successfully

### Actual behavior

The git.sh script hangs and the process does not advance after that.

### Repro steps

Simply run the `GenerateResourcesAndImage` script.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-29 17:53
Hey @nnellanspdl. Thank you for reporting. Are you trying to build new pipeline for image generation from scratch or did you have this pipeline working before but it have broken recently? And may I also ask you to share you pipeline definition so we understand how exactly generation is being started?

**Comment by nnellanspdl** [comment] 2023-08-29 18:01
This pipeline has successfully built older versions of the image.  Here is the relevant snippets from my pipeline.

```yaml
resources:
  repositories:
    - repository: runner-images
      type: github
      name: actions/runner-images
      ref: refs/tags/ubuntu22/20230821.1

stages:
- stage:
  displayName: 'Build Image using GitHub Scripts'
  jobs:
  - job:
    timeoutInMinutes: 360
    steps:
    - checkout: self
    - checkout: runner-images
    - task: AzureCLI@2
      env:
        VNET_RESOURCE_GROUP: $(packerVnetResourceGroup)
        VNET_NAME: $(packerVnet)
        VNET_SUBNET: $(packerSnet)
      inputs:
        connectedServiceNameARM: $(packerServiceConnection)
        addSpnToEnvironment: true
        scriptType: pscore
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)/runner-images
        powerShellErrorActionPreference: SilentlyContinue
        failOnStandardError: false
        powerShellIgnoreLASTEXITCODE: true
        inlineScript: |

          Write-Output "Building the image"
          Import-Module ./helpers/GenerateResourcesAndImage.ps1
          GenerateResourcesAndImage `
            -SubscriptionId $(packerSubscriptionId) `
            -ResourceGroupName "$(packerResourceGroup)" `
            -ImageType $(packerImageType) `
            -AzureLocation "$(packerRegion)" `
            -AzureClientId $env:servicePrincipalId `
            -AzureClientSecret $env:servicePrincipalKey `
            -AzureTenantId $env:tenantId `
            -Force `
            -EnableHttpsTrafficOnly $true
```

**Comment by vpolikarpov-akvelon** [comment] 2023-08-30 14:09
Thank you, we will take a look.

By the way, I noticed that you reference exact release. It's better to use `main` branch because releases become outdated very quick as software publishers change the way they distribute it. Could you please try building using the code from the latest commit of `main` branch?

**Comment by mikhailkoliada** [comment] 2023-09-14 08:26
Hello! I am going to close the issue for now as we are missing additional information, to reproduce the problem, as soon as you have that, please feel free to reach us out again.

**Closed by mikhailkoliada** 2023-09-14 08:26 UTC
Labels: OS: Ubuntu, Area: Image administration, bug report

**Comment by suchowolec** [comment] 2023-09-14 09:18
I have the same problem:
![image](https://github.com/actions/runner-images/assets/3300136/9ea3c868-fa71-4922-b2e1-cdc1951c30c6)
Version: https://github.com/actions/runner-images/commit/5ffd15d8
![image](https://github.com/actions/runner-images/assets/3300136/40a6a140-9b1e-4d80-89da-88810b8df4a4)

**Comment by nnellanspdl** [comment] 2023-09-14 13:11
Not sure why this was closed.  Building from main is not a good practice.  Why do you even maintain versions at all, if you're just going to tell people to build from main?

**Comment by suchowolec** [comment] 2023-09-14 13:38
I've been trying to build an image since august 25 from the main branch and it still fails. These are my [logs](https://github.com/actions/runner-images/files/12609469/builds_logs.txt), nothing can be concluded there.

**Comment by vpolikarpov-akvelon** [comment] 2023-09-18 11:36
> Not sure why this was closed. Building from main is not a good practice. Why do you even maintain versions at all, if you're just going to tell people to build from main?

@nnellanspdl, those versions are not actually revisions that you can choose from. They are merely waypoints in a continuous development process designed to assist with the management of update deployments. It would be really nice to be able to build an image from any of the releases we have in repository, but it's impossible because deployment heavily depends on the external resources that are tend to update as well so image generation scripts quickly become outdated. We make an effort to update them as quick as possible but it's impossible to backport script updates to the older releases. Therefore, the most viable option is to use cutting-edge scripts and build using main branch.

**Comment by suchowolec** [comment] 2023-09-18 12:44
Some time ago we wanted to automate this process and wanted to run it on a build agent with a pipeline. Unfortunately, our build agent is hidden behind a private virtual network and therefore we had to change the script a bit.
Before running the function I replace this fragment: 
`"-var "allowed_inbound_ip_addresses=$($AllowedInboundIpAddresses)" `
with this one:
`"-var "virtual_network_resource_group_name=$($vnetRg)" $newLine -var "virtual_network_name=$($vnetName)" $newLine -var "virtual_network_subnet_name=$($vnetSubnetName)""`
(I had to remove some '`' characters for proper formatting)
The last successfully completed pipeline took place on March 16 and here is [packer-log.txt](https://github.com/actions/runner-images/files/12647776/packer-log.txt) file as a proof that everything worked as expected.
This Saturday I tried to run the script from my local machine and everything worked as expected, so from the local machine everything worked, while on the CI I haven't tried yet. I'll try to create an image on CI again in a while and let you know if it works. I will definitely try to set this option what you suggested @vpolikarpov-akvelon.

**Comment by nnellanspdl** [comment] 2023-09-18 12:59
> > Not sure why this was closed. Building from main is not a good practice. Why do you even maintain versions at all, if you're just going to tell people to build from main?
> 
> @nnellanspdl, those versions are not actually revisions that you can choose from. They are merely waypoints in a continuous development process designed to assist with the management of update deployments. It would be really nice to be able to build an image from any of the releases we have in repository, but it's impossible because deployment heavily depends on the external resources that are tend to update as well so image generation scripts quickly become outdated. We make an effort to update them as quick as possible but it's impossible to backport script updates to the older releases. Therefore, the most viable option is to use cutting-edge scripts and build using main branch.

I have to create images for my own use, I need to know which 'version' those images are based on.  I need to know specifically what software is included as well as their specific versions.  I can do this by specifying a specific version of the image, as well as referencing the readme file for that specific version.  

I can't just say "our images are based on main from august 8th, I can't tell you specifically which versions of software are on there."

With that being said, I only try to build images using the most recent version that you publish, because I realize the underlying software and associated scripts change frequently.

**Comment by mikhailkoliada** [comment] 2023-09-18 13:06
@nnellanspdl a tagged version may have become obsolete due to a minor change in the installation script, if you would like to have the most stable builds we highly recommend you sticking to main, (unfortunately) we do not support the tagged builds as @vpolikarpov-akvelon rightly mentioned, as of the versions of the software installed in the image, you can always generate your own readme file and see what is installed in the image and later share it with your target audience

**Comment by nnellanspdl** [comment] 2023-09-18 13:09
You're not really listening to what I'm saying.  When I'm building new images, I only use the latest version available at that time.  I realize the script changes frequently.  I do not try to build images based on versions that are weeks/months old.

Anyways, this is off-topic of the real issue.

**Comment by vpolikarpov-akvelon** [comment] 2023-09-18 13:34
> That way I know specifically which version I am using (and not a version of main from some date). Doing it this way also allows me to utilize the readme for that tag, which lists the exact versions of software that are included in the tag.

I understand your concern, but there's a key point to consider here. Many installation scripts are designed to fetch the latest released version, and the README is generated after all components have been installed. It accurately reflects the state of the image at the moment it was generated. However, if you build your image, for instance, a day after our 'release,' it's possible that some software versions have been updated. Consequently, if you're keen on having precise information about the software versions in your image, it's advisable to rely on a software report generated specifically for your images rather than ours.

Regarding the actual issue you're facing, could you please attempt to build the image with bash debugging enabled (with `set -x`) for the `git.sh` script, as I [previously suggested](https://github.com/actions/runner-images/issues/8192#issuecomment-1723142708)? This will help us debugging the issue more effectively.

**Comment by nnellanspdl** [comment] 2023-09-23 16:46
It appears that the NVA in my build environment is blocking outbound port 22.  Therefore, the following command in the git.sh script is failing:  `ssh-keyscan -t rsa,ecdsa,ed25519 github.com`.  I will work with my networking team to have that opened up.

And thanks for the info about the image generation.
