### ISSUE TITLE
Add [pnpm] - Azure DevOps

### ISSUE THREAD

**Issue by egg-r** [actions/runner-images#6460] opened 2022-10-24 20:26 UTC
### Tool name

pnpm

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest v7.x.x release

### Brief description of tool

pnpm is fast, disk space efficient Node package manager.
today, many monorepo developers use this pnpm. (vite, svelte, ...)
I also use it. very fast and helpful.
Please see the link below for more information.

https://pnpm.io/motivation
https://pnpm.io/feature-comparison

### URL for tool's homepage

https://pnpm.io/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
The documentation says to run "npm install -g pnpm" to install it.  We have a stance of not installing tools during runtime, but rather baking them into the image.  To keep pipelines from altering the base OS and tools installed.

https://pnpm.io/installation
```

**Comment by egg-r** [comment] 2022-10-24 20:30
Greetings,

I created this request as a duplicate of #2279 , but for Azure DevOps usage.  Rather than for Github Actions.  Sorry if this is also a duplicate, but I'm unaware of functionality to specify pnpm as the package manager like what's described for the Github Action.

**Comment by erik-bershel** [comment] 2022-10-25 07:29
@egg-r 
Hi! Yes, it is still a duplicate of #2279. And yes, for Azure DevOps there really is no separate module that can install the requested tool in "one line" or something like that. But you can look at the [official instructions](https://pnpm.io/next/continuous-integration) for use or the [example](https://stackoverflow.com/questions/73117288/how-to-use-pnpm-on-azure-pipelines) of use in the community.

**Closed by erik-bershel** 2022-10-25 07:29 UTC
Labels: feature request

**Comment by baidarka** [comment] 2025-12-16 21:00
Please add pnpm to the Azure DevOps toolset.
