### ISSUE TITLE
`pkg-config` was removed from macos-latest runners

### ISSUE THREAD

**Issue by cavokz** [actions/runner-images#7159] opened 2023-02-20 17:46 UTC
### Description

Since (probably) https://github.com/actions/runner-images/commit/d7312cfd5d20e517841ec9513df8db8373ce0828 `pkg-config` is not present any more in the macos-latest runners. Nothing is mentioned in the version tracking though.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

# Broken
Runner image version: 20230214.2
Job link: https://github.com/elastic/geneve/actions/runs/4225687985/jobs/7338324192

# Working
Runner image version: 20230205.1
Job link: https://github.com/elastic/geneve/actions/runs/4196117124/jobs/7277667028

### Is it regression?

See "Working" above.

### Expected behavior

A build using `pkg-config` does not fail because of missing `pkg-config`.

### Actual behavior

A build using `pkg-config` fails:
```
pkg-config: exec: "pkg-config": executable file not found in $PATH
```

### Repro steps

Follow my "broken job link" above and press "re-run all failed jobs".

**Comment by erik-bershel** [comment] 2023-02-20 17:50
You can track that issue here: https://github.com/actions/runner-images/issues/7128
PR merged: https://github.com/actions/runner-images/pull/7125

**Closed by erik-bershel** 2023-02-20 17:50 UTC
Labels: needs triage, bug report

**Comment by andreasabel** [comment] 2023-02-20 19:20
@ mikhailkoliada : PR #7125 fixed this but did not seem to add any tests.
If a tool like `pkg-config` can disappear just like this from the image, then it looks like you do not have enough tests.
A minimal test would invoke just `pkg-config --version` to see that the program is at least present.

Without regression tests, you will play whack-a-mole in all eternity.
