### ISSUE TITLE
New image for ubuntu-latest docker issues

### ISSUE THREAD

**Issue by BBTristanBenschop** [actions/runner-images#10646] opened 2024-09-19 07:41 UTC
### Description

When starting a docker container in our devops pipeline since last night we receive the error:

Docker.DotNet.DockerApiException : Docker API responded with status code=Conflict, response={"message":"container f111f68d35dc63185d89a5d93600a4af7fdb01513d9e17f873aa400c3dc0c6da is not running"}

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We are using ubuntu-latest

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az366-67'
Current agent version: '3.243.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20240915.1.0'
Agent running as: 'vsts'

the last working version is:

Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az634-412'
Current agent version: '3.243.1'
Operating System
Runner Image
Runner Image Provisioner
Current image version: '20240908.1.0'
Agent running as: 'vsts'

### Is it regression?

Current image version: '20240908.1.0'

### Expected behavior

To properly startup the docker container so that our tests can be ran inside the container.

### Actual behavior

Fails to start docker container

### Repro steps

Start a docker container

**Comment by SpaceOgre** [comment] 2024-09-19 07:44
We are seeing this problem as well, tested in ubuntu 24.04 as well and same problem there.

**Comment by josefinbrandt** [comment] 2024-09-19 07:45
We also have this problem.

**Comment by BBTristanBenschop** [comment] 2024-09-19 07:51
Temporarily fix for us is switching to ubuntu-20.04 image where this issue doesn't exist.

**Comment by kishorekumar-anchala** [comment] 2024-09-19 08:23
Hi @SpaceOgre @BBTristanBenschop ,
Kindly share below things 

1. The specific DevOps pipeline configuration related to starting the Docker container.
2. The exact command or script used to start the Docker container.

**Comment by robinbaxon** [comment] 2024-09-19 09:09
Can confirm that we experience this issue on our side as well.
We reverted our workflows to use ubuntu-20.04 (which gave us the ubuntu-20.04.6 revision of the image) and that work. Thanks for the tip @BBTristanBenschop.

**Comment by BBTristanBenschop** [comment] 2024-09-19 09:32
@kishorekumar-anchala  we use a very similar setup as SpaceOgre including the use of TestContainers. It fails on running the tests which makes use of TestContainer library.

**Comment by kwuite** [comment] 2024-09-19 10:00
> Temporarily fix for us is switching to ubuntu-20.04 image where this issue doesn't exist.

Our mssql container failed in CI/CD with really odd messages like:
```
This program has encountered a fatal error and cannot continue running at Thu Sep 19 08:41:27 2024
The following diagnostic information is available:

         Reason: 0x00000001
         Signal: SIGABRT - Aborted (6)
          Stack:
                 IP               Function
                 ---------------- --------------------------------------
                 000056207ec88a5a std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000056207ec88559 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000056207ec8745c std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 00007f0982d7b4b0 killpg+0x40
                 00007f0982d7b428 gsignal+0x38
                 00007f0982d7d02a abort+0x16a
                 000056207ec1add4 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000056207ecdf7a8 void google::protobuf::internal::arena_delete_object<google::protobuf::Message>(void*)+0x2a38
                 000056207ecdf500 void google::protobuf::internal::arena_delete_object<google::protobuf::Message>(void*)+0x2790
                 000056207ec2ab36 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
                 000056207ec2a7d0 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > c
        Process: 9 - sqlservr
         Thread: 73 (application thread 0xf4)
    Instance Id: a672206a-cf56-49cc-9c29-89a1990f3f36
       Crash Id: a1fba965-828c-4d91-bf1c-8cb2a0709c68
    Build stamp: 52ec5c991c015cbdd504002245460be8a9a9b6c41343aaab03cf768750a6c2df
   Distribution: Ubuntu 16.04.6 LTS
     Processors: 2
   Total Memory: 8324341760 bytes
      Timestamp: Thu Sep 19 08:41:27 2024
     Last errno: 2
Last errno text: No such file or directory
```
We noticed, the runner images have been update by Github.

This was our Github Action Host machine image from a few days ago
```
Runner Image
Image: ubuntu-22.04
  Version: 20240908.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240908.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240908.1
```
This is the version we see today, that fail.
```
Runner Image
  Image: ubuntu-22.04
  Version: 20240915.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240915.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1
```
I believe the Linux kernel change from 6.5 to 6.8 is the reason this is failing.

:tada:We fixed our issue by using the Ubuntu 20.04 runner image because both 22 and 24 have been affected as you can read in this issue on Github: https://github.com/actions/runner-images/issues/10646

to fix docker issues in your workflow.yml, make the following change:
```
runs-on: ubuntu-20.04
```

**Comment by kiview** [comment] 2024-09-19 14:40
Related issue:
https://github.com/actions/runner-images/issues/10649

**Comment by HofmeisterAn** [comment] 2024-09-19 19:57
It looks like another workaround is bumping the image to:

    mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04

**Comment by jupjohn** [comment] 2024-09-20 00:18
> It looks like another workaround is bumping the image to:
> 
> ```
> mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
> ```

If you don't want to upgrade to SQLServer 2022, I've confirmed the tag `2019-CU26-ubuntu-20.04` is the lowest working version on both `ubuntu-22.04` and `ubuntu-24.04`.

**Comment by kishorekumar-anchala** [comment] 2024-09-24 09:34
Hi @BBTristanBenschop @SpaceOgre ,

We tried with below change and it got successful , could you please use below workaround .

https://github.com/RaviAkshintala/testcontainers-dotnet/actions/runs/10993413941/workflow#L38

**Comment by kishorekumar-anchala** [comment] 2024-09-24 09:48
Hi @SpaceOgre @BBTristanBenschop ,

   We request you to try below workaround.
   
   https://github.com/RaviAkshintala/testcontainers-dotnet/actions/runs/10993413941/workflow#L38

**Comment by SpaceOgre** [comment] 2024-09-25 07:06
> It looks like another workaround is bumping the image to:
> 
> ```
> mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
> ```

This works well for us and we will go with this solution, just a heads up to anyone else reading this:
To get a newer image of SQL server to work you will need TestContainers v3.10 since the sqlcmd has been moved and a fix for that is available starting in 3.10

**Comment by SpaceOgre** [comment] 2024-09-25 07:10
> Hi @SpaceOgre @BBTristanBenschop ,
> 
> We request you to try below workaround.
> 
> https://github.com/RaviAkshintala/testcontainers-dotnet/actions/runs/10993413941/workflow#L38

Is the workaround to start the docker image manually and not through TestContainers? Not sure I follow completely.
The fix provided by @HofmeisterAn works well and we are going with that.

But it would be good if it was possible to specify exactly wich runner version we are using and not just the OS-version, if something like this happens again since it was a bit of a problem this time.

**Comment by BBTristanBenschop** [comment] 2024-09-25 07:24
We have also opted to increase the image version of the sql server. We don't call docker directly, its hidden somewhere in TestContainers package.

**Comment by urnie** [comment] 2024-09-27 09:49
I'll add my two cents here saying that our workflows (that start up a dockerized SQL server 2019) stopped working when the `ubuntu-22.04.4` was updated to `ubuntu-22.04.5` ([release 20240915.1](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240915.1) and [release 20240922.1](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240922.1)). Looking at the changelog, there's some Docker-related version updates, but I don't know if and how they can cause this bug.

The patch number (.4 and .5) can't be specified by the developer ([source](https://github.com/actions/runner-images/discussions/8802#discussioncomment-7628116)), which makes sense, as they contain security updates.

This workaround by @BBTristanBenschop worked for me:
> Temporarily fix for us is switching to ubuntu-20.04 image where this issue doesn't exist.

However I was left wondering that if the patch update from ubuntu-22.04.4 to 22.04.5 broke something, why hasn't the same (breaking) patch been applied to ubuntu-20.04, which still works?

**Comment by kishorekumar-anchala** [comment] 2024-10-10 06:33
Hi @SpaceOgre @BBTristanBenschop ,

   Could you try with the new image version (20241006.1) . it might fix your issue.

**Comment by kishorekumar-anchala** [comment] 2024-10-11 08:11
Hi @SpaceOgre @BBTristanBenschop ,

  Could you please share your confirmation on this issue ?

**Comment by kishorekumar-anchala** [comment] 2024-10-14 06:38
HI @SpaceOgre @BBTristanBenschop ,

We hope that this has been fixed and we are closing this issue. Thank you !

**Closed by kishorekumar-anchala** 2024-10-14 06:38 UTC
Labels: OS: Ubuntu, bug report
