### ISSUE TITLE
Support Linux ARM64 build images

### ISSUE THREAD

**Issue by darena-patrick** [actions/runner-images#9260] opened 2024-01-30 21:33 UTC
### Tool name

ARM64 Linux

### Tool license

new processor architecture

### Add or update?

- [X] Add
- [ ] Update

### Desired version

arm64

### Brief description of tool

Now that Azure supports ARM64 could we please get GitHub actions to support building Linux ARM64 binaries using ARM64 machines?

Using cross-compiling on x86_64 systems is about 5x slower.

### URL for tool's homepage

https://azure.microsoft.com/en-us/blog/now-in-preview-azure-virtual-machines-with-ampere-altra-armbased-processors/

### Provide a basic test case to validate the tool's functionality.

```bash
Build docker images using the runner and attempt to run them on Apple M1 Silicon.
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by darena-patrick** [comment] 2024-01-30 21:34
The previous issue #5631 is locked - but I would like to request an update on this effort. 

- Is this currently being worked on?
- If this is coming soon - are there any dates or milestones that can be shared?

**Comment by mikhailkoliada** [comment] 2024-01-30 21:48
hey! As you rightly mentioned it is a duplicate of https://github.com/actions/runner-images/issues/5631 and no comments here means no tangible updates at least yet, please follow the tick and when we have updates, we'll post it there!

**Closed by mikhailkoliada** 2024-01-30 21:48 UTC
Labels: feature request
