### ISSUE TITLE
Add `sbt` to macOS 13 and macOS 14

### ISSUE THREAD

**Issue by mkurz** [actions/runner-images#9837] opened 2024-05-13 09:53 UTC
### Tool name

sbt

### Tool license

Apache 2.0 license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

latest

### Brief description of tool

sbt (originally Simple Build Tool, nowadays often believed to stand for Scala Build Tool or used as its own proper name) is an open-source build tool created explicitly for Scala and Java projects

### URL for tool's homepage

https://github.com/sbt/sbt

### Provide a basic test case to validate the tool's functionality.

```bash
sbt -version
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

yes

**Comment by mkurz** [comment] 2024-05-13 09:54
macOS 12 had `sbt` (https://www.scala-sbt.org/) installed by default, see:
https://github.com/actions/runner-images/blob/1a952817bed9a3d317964a9879da9b694e9fc0e1/images/macos/macos-12-Readme.md?plain=1#L60

Unfortunately all your macOS 13 and macOS14 images do not provide `sbt` anymore. Is there any reason for that? Would be nice if you could add it back, thanks!

I added a pull request here:
- #9830

(I know currently you can not accept PRs for macOS but maybe this PR makes things easier for you guys)

THANKS!

**Comment by mkurz** [comment] 2024-05-13 10:26
Currently we have to keep using `macos-12` to keep testing our repos, see 
- https://github.com/sbt/sbt-pull-request-validator/pull/42

**Comment by erik-bershel** [comment] 2024-05-13 10:34
Hey @mkurz!
Thank you for such detail request. But currently we have no plans to add `sbt` on `macOS-13`/`macOS-14`. Closing as a duplicate of https://github.com/actions/runner-images/issues/9369.
Can be simply workarounded by `brew install sbt` during runtime.

**Closed by erik-bershel** 2024-05-13 10:34 UTC
Labels: Area: Scala, OS: macOS, feature request

**Comment by mkurz** [comment] 2024-05-13 10:38
> But currently we have no plans to add `sbt` on `macOS-13`/`macOS-14`

Why not? What is the reason for dropping `sbt` after you provided it for the `macos-12` images? Thanks!

**Comment by erik-bershel** [comment] 2024-05-13 11:32
> Why not? What is the reason for dropping sbt after you provided it for the macos-12 images? Thanks!

Just general maintenance concern. Currently, the base runners are too heavy and unstable due to the number of pre-installed packages. We try to optimise images by using only those packages that would be difficult to install at runtime or without which it would be fundamentally difficult or useless to use a runner.
