### ISSUE TITLE
Cannot write to `/usr/local/share` on `macos-14` runner

### ISSUE THREAD

**Issue by douglascamata** [actions/runner-images#9272] opened 2024-02-01 19:02 UTC
### Description

Actions are not being able to write to `/usr/local/share` in the new M1 runner under the `macos-14` image.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

* Failed build attempting to write to `/usr/local/share` on `macos-14`: https://github.com/douglascamata/setup-docker-macos-action/actions/runs/7745920249/job/21122954463#step:3:1

Notice that the other runners, `macos-12` and `macos-13` all went fine: 
* Passing build on `macos-13`: https://github.com/douglascamata/setup-docker-macos-action/actions/runs/7745920249/job/21122954116
* Passing build on `macos-12`: https://github.com/douglascamata/setup-docker-macos-action/actions/runs/7745920249/job/21122953846

This is the source workflow file: https://github.com/douglascamata/setup-docker-macos-action/blob/main/action.yml#L58

### Is it regression?

Yes, broken on `macos-14` and works on all other runners.

### Expected behavior

I should be able to write to `/usr/local/share` on `macos-14`, like I can on `macos-13` and `macos-12`.

### Actual behavior

I can't.  

### Repro steps

In a `macos-14`, try to create folders and files under `/usr/local/share`.

**Comment by Vyazovoy** [comment] 2024-02-02 03:04
@douglascamata, looks like `macos-13` image has `runner:admin` permissions for `/usr/local/share`. But `macos-14` has `root:wheel`.
So to workaround it you could try to run `sudo chown runner:admin /usr/local/share` before the command that fails in your script.

**Comment by MaksimZhukov** [comment] 2024-02-02 13:17
Hello @douglascamata! 
I think this is the default behaviour and it can be reproduced locally.
I am closing the issue. Please let us know if you have any questions or concerns

**Closed by MaksimZhukov** 2024-02-02 13:17 UTC
Labels: needs triage, bug report
