### ISSUE TITLE
Cloud Foundry CLI download endpoint now returns 404 for Windows 2019 builds

### ISSUE THREAD

**Issue by angaaruriakhil** [actions/runner-images#11091] opened 2024-12-03 15:12 UTC
### Description

When running the following script as part of a Windows 2019 build, https://github.com/actions/runner-images/blob/main/images/windows/scripts/build/Install-CloudFoundryCli.ps1, the endpoint is no longer accessible and returns a 404 not found error. 

I have tried in my web browser on my personal machine as well and the endpoint no longer returns a binary. 

This makes windows 2019 builds fail. 

```
==> azure-arm.build_vhd: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/scripts/build/Install-CloudFoundryCli.ps1
    azure-arm.build_vhd: Downloading package from https://packages.cloudfoundry.org/stable?release=windows64-exe&source=github to C:\Users\packer\AppData\Local\Temp\stablerelease=windows64-exe&source=github...
    azure-arm.build_vhd: WARNING: Package download failed in 0.89 seconds
    azure-arm.build_vhd: WARNING: Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
==> azure-arm.build_vhd: Package download failed after 0.92 seconds
    azure-arm.build_vhd: WARNING: Request returned 404 Not Found. Aborting download.
==> azure-arm.build_vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:204 char:13
==> azure-arm.build_vhd: +             throw "Package download failed after $totalSeconds second ...
==> azure-arm.build_vhd: +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.build_vhd:     + CategoryInfo          : OperationStopped: (Package downloa...er 0.92 seconds:String) [], RuntimeException
==> azure-arm.build_vhd:     + FullyQualifiedErrorId : Package download failed after 0.92 seconds
==> azure-arm.build_vhd:
==> azure-arm.build_vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

We are using self hosted VMSS

### Is it regression?

Yes

### Expected behavior

Script should download the cloud foundry exe successfully

### Actual behavior

404 Not Found

### Repro steps

Clone down runner-images repo and use it to run a build of Windows 2019 with Hashicorp Packer

**Comment by vidyasagarnimmagaddi** [comment] 2024-12-03 16:57
Hi @angaaruriakhil
There is an open issue in the [repo](https://github.com/cloudfoundry/cli/issues/3324) for the same, We will revert after analysis. regards

**Comment by vidyasagarnimmagaddi** [comment] 2024-12-05 10:41
Hi @angaaruriakhil ,Earlier the version for 8.9.0 is not found, 
We have tested now  `https://packages.cloudfoundry.org/stable?release=windows64-exe&source=github` , now downloading. Could you please try at your end. and revert if any issue . thanks.

**Comment by vidyasagarnimmagaddi** [comment] 2024-12-06 04:36
Hi @angaaruriakhil ,
The issue is resolved now, We are closing this issue . thanks

**Closed by vidyasagarnimmagaddi** 2024-12-06 04:36 UTC
Labels: OS: Windows, bug report
