### ISSUE TITLE
Add Haskell tools to macos-14

### ISSUE THREAD

**Issue by mpilgrem** [actions/runner-images#9280] opened 2024-02-02 19:37 UTC
### Tool name

GHCup, GHC, Stack, Cabal (the tool)

### Tool license

Open source

### Add or update?

- [X] Add
- [ ] Update

### Desired version

The current versions, as for the other `macos-*` runners. For `macos-12`, they are currently: GHCup 0.1.20.0, GHC 9.8.1, Stack 2.13.1 and Cabal 3.10.2.1.

### Brief description of tool

The Haskell tools are the same ones as provided with the other `macos-*` runners. They all come in macOS/AArch64 versions.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by mikhailkoliada** [comment] 2024-02-02 22:34
Marking as a duplicate of https://github.com/actions/runner-images/issues/9242 as rationale is the same, currently we have no plans to add Haskell to new macOS runners but may reconsider in the future.

**Closed by mikhailkoliada** 2024-02-02 22:34 UTC
Labels: feature request
