### ISSUE TITLE
DevOps UI Testing: Application with WebView2 (fixed runtime) cannot load WebView2

### ISSUE THREAD

**Issue by softworkz** [actions/runner-images#9537] opened 2024-03-19 19:28 UTC
### Description

We are running UI Tests with WinAppDriver and EdgeDriver for an MSIX app package.

The application uses WebView2 with the runtime in fixed version distribution mode.
When starting the application, it hangs on initializing the WebView2, which never gets started.

It works when changing the application to use the existing webview runtime.

The application doesn't have any issues on elsewhere. I've tested it on a range of different VMs with various OS versions and I can't reproduce this anywhere else.
I've spent two days on trying to find out the reason without success. The problem is that whatever I try takes 15 (test change) or 50 minutes (app change) until I see the result. It's like when you have a console with a long lag of output and I'm also about to run out of ideas of what I could try.

I wonder whether there's any way to get remote desktop access to an agent machine for troubleshooting or whether I can setup a VM with the original agent image in some way for troubleshooting this issue?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Agent name: 'Hosted Agent'
Agent machine name: 'fv-az763-77'
Current agent version: '3.236.1'
Microsoft Windows Server 2022
10.0.20348
Datacenter
Image: windows-2022
Version: 20240310.1.0
##[group]Runner Image Provisioner
2.0.359.1
Current image version: '20240310.1.0'

### Is it regression?

Unknown

### Expected behavior

App with WebView2 can successfully initialize the webview.

### Actual behavior

App with WebView2 cannot successfully initialize the webview.

### Repro steps

- Start application
- Wait 10s
- Check process list for msedgewebview2

**Comment by Alexey-Ayupov** [comment] 2024-03-19 20:51
Hello @softworkz. Unfortunately you cannot establish remote desktop connection to Azure DevOps hosted runners. However, you can build your own image using [this](https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md) instruction. Then you can create a [self-hosted agent](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/windows-agent?view=azure-devops) based on the created image and try to reproduce the issue.
Meanwhile we also will try to find a solution, but for that we need more understandable repro steps. Maybe a code snippet or detailed algorithm. It will drastically speed up the debugging process.

**Comment by softworkz** [comment] 2024-03-19 21:16
It can be reproduced with a single PowerShell task:

```powershell
Set-PSDebug -Trace 1

Add-AppxPackage -Path "$(System.DefaultWorkingDirectory)/WinArtifacts/WinUIStore/MyApp.Client.WinUI_$(MyAppVersionPlain1)_Test/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix"

$msixPath = "$(System.DefaultWorkingDirectory)/WinArtifacts/WinUI/MyApp.Client.WinUI_$(MyAppVersionPlain1)_x64.msix"

# Install the MSIX package
Add-AppxPackage -Path $msixPath


Get-AppxPackage MyApp.Client.WinUI

Start-Process shell:AppsFolder\MyApp.Client.WinUI_wjpzhde6g1vst!App

Start-Sleep 30

tasklist
```

After that, looking in the task list for the presence of "msedgewebview2.exe".

**Comment by softworkz** [comment] 2024-03-20 10:11
The screenshot I'm taking on the agent shows an error for the fixed runtime (didn't get that with my actual application):

![image](https://github.com/actions/runner-images/assets/4985349/615b1883-0662-48e3-836b-769f1cb00271)


I have tested this again on different machines, including Windows 10 and it's working everywhere just not on those agents.

**Comment by MaksimZhukov** [comment] 2024-03-26 10:13
Hello @softworkz!
Thank you for creating the test application and public Azure DevOps pipeline!
Unfortunately, I don't see the commands you use in your pipeline and could not adjust the steps from [your comment](https://github.com/actions/runner-images/issues/9537#issuecomment-2008149888).
Could you please provide us with the repro steps so that we can reproduce the issue from our side?

**Comment by softworkz** [comment] 2024-03-26 11:17
Hi, I can add you as owner to the DevOps project. Is your ...@a.....n.com address still current?

**Comment by MaksimZhukov** [comment] 2024-03-26 13:26
Is it possible for you to share repro steps without adding me to your project?

**Comment by softworkz** [comment] 2024-03-26 21:04
It's a release pipeline with three tasks:


![image](https://github.com/actions/runner-images/assets/4985349/720c2c9a-f640-4436-be61-d1c421b15645)


## 1. PowerShell: Install App

```powershell
dir $(AppType)

$certPath = Get-ChildItem -Path "$(AppType)/WebView2_WinUI3_Sample (Package)_*_x64.cer" -File | Select-Object -ExpandProperty FullName

certutil.exe -addstore TrustedPeople $certPath

Add-AppxPackage -Path "$(AppType)/Dependencies/x64/Microsoft.VCLibs.x64.14.00.appx"
Add-AppxPackage -Path "$(AppType)/Dependencies/x64/Microsoft.VCLibs.x64.14.00.Desktop.appx"
Add-AppxPackage -Path "$(AppType)/Dependencies/x64/Microsoft.WindowsAppRuntime.1.5.msix"

$msixPackagePath = Get-ChildItem -Path "$(AppType)/WebView2_WinUI3_Sample (Package)_*_x64.msix" -File | Select-Object -ExpandProperty FullName
Add-AppxPackage -Path $msixPackagePath


Get-AppxPackage a6e38587-f17a-4a2e-8022-248694f372b3

```

## 2. PowerShell: Run App

```powershell
Start-Process shell:AppsFolder\a6e38587-f17a-4a2e-8022-248694f372b3_yps17xarsp2at!App

Start-Sleep 30

tasklist
```

## 3. Take Screenshot


```yaml
steps:
- task: jessehouwing.agent-screenshot.agent-screenshot.agent-screenshot@1
  displayName: 'Take a screenshot of the agent desktop.'
  condition: succeededOrFailed()
```

Here's the pipeline exported as JSON:  [TestRelease.json](https://github.com/actions/runner-images/files/14764609/TestRelease.json)

The Job runs twice with the variable `AppType` once being `webview2_fixedruntime`  and second time `webview2_systemruntime`.

The downloaded artifacts are the two zips which you can find here: https://github.com/softworkz/WebView2_WinUI3_Sample/releases/tag/Test_01

Let me know when you got any questions.

**Comment by MaksimZhukov** [comment] 2024-04-24 09:06
Hello @softworkz!
Sorry for the late reply!
During the investigation, it turned out that the issue can be reproduced on a clean virtual machine created in Azure. I am going to close the issue since the root cause comes from Azure and is not related to runner-images. Please report your problem to the [Microsoft developer community](https://developercommunity.visualstudio.com/home)

**Closed by MaksimZhukov** 2024-04-24 09:06 UTC
Labels: OS: Windows, bug report

**Comment by lfderm** [comment] 2024-11-28 11:31
@MaksimZhukov Please re-open. This has nothing to do with Azure or build pipelines. It also happens when installing an app with fixed WebView2 runtime on the Administrator account on Windows Server and trying to launch it. The problem does not occur on other user accounts, only on Administrator.
