### ISSUE TITLE
Pipeline with ubuntu-latest not working 

### ISSUE THREAD

**Issue by krohm** [actions/runner-images#6583] opened 2022-11-16 18:40 UTC
### Description

When using the ubuntu-latest the Agents using the 2 versions 20221027.1 and 20221114.1
With 20221114.1 we got inside our Powershell script now:

```
VERBOSE: Too many command line arguments. Did you mean to use -chdir?

Execution of { &"$TerraformPath" init -upgrade -backend=false $TerraformNoColor } by tfcsi.ps1: line 1180 failed with exit code 1
At /home/vsts/work/1/s/tfcsi.ps1:217 char:17
+                 throw $errorMessage
+                 ~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Execution of { &"$T…ed with exit code 1:String) [], RuntimeException
+ FullyQualifiedErrorId : Execution of { &"$TerraformPath" init -upgrade -backend=false $TerraformNoColor } by tfcsi.ps1: line 1180 failed with exit code 1
##[error]Script failed with exit code: 1

```
Workaround at the moment is to use ubuntu-22.04, which currently only have the Version: 20221027.1

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20221114.1 

### Is it regression?

20221027.1

### Expected behavior

Sould run in both image version in the same behaviour

### Actual behavior

as the agents in ubuntu-latest are switching, the behaviour is not reliable

### Repro steps

Try to run a powershell script

**Comment by mikhailkoliada** [comment] 2022-11-16 18:46
please provede repro steps

**Comment by bbattah** [comment] 2022-11-16 19:42
Perhaps not the original repro but try this:

Define an azure devops pipeline that includes an azurepowershell@5 task.
In this task, build an $apimContext and attempt to use a line like:
 Try{
$abc = Get-AzApiManagementNamedValue -Context $apimContext -Name "SomeNamedValue"
}}
Catch [system.exception]
{
    Write-Error "An error occurred while reading value from APIM, $($_.Exception.Message)  Inner Exception: $($_.Exception.InnerException)"    
	throw
} 

See an error like:
'Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient' threw an exception.  
Inner Excpetion: System.ArgumentException: GenericArguments[0], 'System.String', on 'T MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the constraint of type 'T'.  ---> System.Security.VerificationException: Method System.Linq.Enumerable.MaxInteger: type argument 'System.String' violates the constraint of type parameter 'T'.    at System.RuntimeMethodHandle.GetStubIfNeeded(RuntimeMethodHandleInternal method, RuntimeType declaringType, RuntimeType[] methodInstantiation)    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)    --- End of inner exception stack trace ---    at System.RuntimeType.ValidateGenericArguments(MemberInfo definition, RuntimeType[] genericArguments, Exception e)    at System.Reflection.RuntimeMethodInfo.MakeGenericMethod(Type[] methodInstantiation)    at AutoMapper.TypeDetails.<>c.<BuildPublicNoArgExtensionMethods>b__30_7(<>f__AnonymousType18`2 <>h__TransparentIdentifier1)    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()    at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)    at System.Linq.Enumerable.UnionIterator`1.FillSet()    at System.Linq.Enumerable.UnionIterator`1.ToArray()    at AutoMapper.TypeDetails.BuildPublicNoArgExtensionMethods(IEnumerable`1 sourceExtensionMethodSearch)    at AutoMapper.TypeDetails..ctor(Type type, ProfileMap config)    at AutoMapper.ProfileMap.TypeDetailsFactory(Type type)    at AutoMapper.LockingConcurrentDictionary`2.<>c__DisplayClass2_1.<.ctor>b__1()    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)    at System.Lazy`1.CreateValue()    at AutoMapper.LockingConcurrentDictionary`2.GetOrAdd(TKey key)    at AutoMapper.ProfileMap.CreateTypeDetails(Type type)    at AutoMapper.Configuration.Conventions.NameSplitMember.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers, IMemberConfiguration parent)    at AutoMapper.Configuration.Conventions.MemberConfiguration.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceType, Type destType, Type destMemberType, String nameToSearch, LinkedList`1 resolvers)    at AutoMapper.TypeMapFactory.<>c__DisplayClass1_0.<MapDestinationPropertyToSource>b__0(IMemberConfiguration _)    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)    at AutoMapper.TypeMapFactory.MapDestinationPropertyToSource(ProfileMap options, TypeDetails sourceTypeInfo, Type destType, Type destMemberType, String destMemberInfo, LinkedList`1 members)    at AutoMapper.TypeMapFactory.CreateTypeMap(Type sourceType, Type destinationType, ProfileMap options)    at AutoMapper.ProfileMap.BuildTypeMap(TypeMapRegistry typeMapRegistry, ITypeMapConfiguration config)    at AutoMapper.ProfileMap.Register(TypeMapRegistry typeMapRegistry)    at AutoMapper.MapperConfiguration.Seal()    at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression)    at AutoMapper.MapperConfiguration..ctor(Action`1 configure)    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient.ConfigureMappings()    at Microsoft.Azure.Commands.ApiManagement.ServiceManagement.ApiManagementClient..cctor()


Consider that this symptom is reasonably close to an ongoing issue here:
 https://github.com/Azure/azure-powershell/issues/18721
 
 Consider that the identical script will run successfully with PS versions as shown by an agent here:
 2022-11-16T18:16:13.0912993Z PSVersion                      7.2.7
2022-11-16T18:16:13.0913784Z PSEdition                      Core
2022-11-16T18:16:13.0914132Z GitCommitId                    7.2.7
2022-11-16T18:16:13.0915683Z OS                             Linux 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP …
2022-11-16T18:16:13.0916118Z Platform                       Unix
2022-11-16T18:16:13.0916660Z PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
2022-11-16T18:16:13.0917059Z PSRemotingProtocolVersion      2.3
2022-11-16T18:16:13.0917426Z SerializationVersion           1.1.0.1
2022-11-16T18:16:13.0918056Z WSManStackVersion              3.0

And will fail when run by an agent with version shown here:

2022-11-16T18:23:16.7437859Z PSVersion                      7.3.0
2022-11-16T18:23:16.7438753Z PSEdition                      Core
2022-11-16T18:23:16.7439141Z GitCommitId                    7.3.0
2022-11-16T18:23:16.7440163Z OS                             Linux 5.15.0-1022-azure #27~20.04.1-Ubuntu SMP …
2022-11-16T18:23:16.7440552Z Platform                       Unix
2022-11-16T18:23:16.7441023Z PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
2022-11-16T18:23:16.7441374Z PSRemotingProtocolVersion      2.3
2022-11-16T18:23:16.7442851Z SerializationVersion           1.1.0.1
2022-11-16T18:23:16.7443629Z WSManStackVersion              3.0

The main difference is the pscore version - which appears to be "floating" between two instances of the same VM image tag: 
    pool:
      vmImage: 'ubuntu-20.04'

**Comment by erik-bershel** [comment] 2022-11-16 22:46
Hey @krohm 
Issue connected to newly released PowerShell 7.3 - that is true. You may temporary avoid it by using ubuntu-22.04 label. We are already working on the problem. But it will be very cool if you share the information about difficulties you encountered with the tool development team.

**Comment by mikeharder** [comment] 2022-11-17 01:30
The original issue reported by @krohm might be a breaking change in PowerShell 7.3 argument passing.  I just opened a new issue for this: https://github.com/actions/runner-images/issues/6586.

**Comment by ksaffarian** [comment] 2022-11-17 04:31
well, I mentioned it earlier :)
https://github.com/actions/runner-images/issues/6583

**Comment by erik-bershel** [comment] 2022-11-17 09:24
@krohm 
We are already working on the issue. To temporarily stop the problem, we will return the previous versions of the images to work. We will report on the following decisions separately.

**Comment by mikhailkoliada** [comment] 2022-11-17 11:30
Duplicate of https://github.com/actions/runner-images/issues/6586

**Closed by mikhailkoliada** 2022-11-17 11:30 UTC
Labels: Area: Scripting and command line, OS: Ubuntu, bug report
