### ISSUE TITLE
Degraded performance on macos-12: `swift test` is very slow

### ISSUE THREAD

**Issue by DelevoXDG** [actions/runner-images#8521] opened 2023-10-11 09:44 UTC
### Description

For two weeks now, I'm observing significant performance drop when running `swift test` on macos-12 runner.

Here are jobs before and after the issue first appeared: 
* Before: https://github.com/software-mansion/starknet.swift/actions/runs/6339726649/job/17219484552
* Right after: https://github.com/software-mansion/starknet.swift/actions/runs/6339833865/job/17219857552

Specifically, the step that causes the issue is `"Run tests"` where basically some env vars are exported and `swift test --disable-sandbox` is ran.

As you can see, there are barely any changes in the PR that triggered 2) workflow. Moreover, the logs seem to be nearly identical, and from timestamps and logs of `swift test` in 2) workflow you can see that everything test-related (fetching deps, building, running tests themselves) takes no more than 3 minutes. Also, running `swift test --disable-sandbox` on XCode 15 locally appears to cause no issue.

This leads me to believe this is the issue with macos-12 runner. Since then, every run takes more than 20 minutes (compared to 5 minutes before). Strangely, the issue appeared on the same runner version.

Last occurrence: https://github.com/software-mansion/starknet.swift/actions/runs/6480013686/job/17594678037 - timed out after 6 hours.

UPD: randomly, the job completed in 5 minutes after the previous one kept running for 6 hours: https://github.com/software-mansion/starknet.swift/actions/runs/6480901632/job/17597358691
This one is non-deterministic 😄 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Last occurrence: https://github.com/software-mansion/starknet.swift/actions/runs/6480013686/job/17594678037 (`20230921.4`)
~~First occurrence: https://github.com/software-mansion/starknet.swift/actions/runs/6339833865/job/17219857552~~ https://github.com/software-mansion/starknet.swift/actions/runs/6328364493/job/17186354775 (`20230916.1`)

### Is it regression?

~~`20230921.4` https://github.com/software-mansion/starknet.swift/actions/runs/6339726649/job/17219484552~~
``
`20230901.1 ` 
### Expected behavior

Job finishes within ~5 minutes.

### Actual behavior

Job lasts more than 20/30/60 minutes.

### Repro steps

1. Create a workflow that uses `macos-12` runner
2. Use `swift test --disable-sandbox` in a step
3. Run said workflow

**Comment by vpolikarpov-akvelon** [comment] 2023-10-11 11:09
Hey @DelevoXDG. Thank you for reporting, we will take a look.

**Comment by ilia-shipitsin** [comment] 2023-10-16 11:08
Hello, @DelevoXDG 

since you are telling that you see issues on the same image version `20230921.4`, it means the issue does not depend on image.
However, this issue tracker is related to runner images.

**Comment by ilia-shipitsin** [comment] 2023-10-16 15:05
@EricHorton has found what is likely the cause of slowness

```
The slow workflow they linked ran the tests pretty fast. The slow part was the build step before it. It takes about 4 minutes to install rustfmt and then about 15 minutes to compile everything. The download step seems pretty quick.

That appears to be the common theme. All the slow workflows I’m looking at are rebuilding that dependency:
https://github.com/software-mansion/starknet.swift/actions/runs/6472988781/job/17574738848?pr=107
https://github.com/software-mansion/starknet.swift/actions/runs/6472494781/job/17573270645?pr=106
https://github.com/software-mansion/starknet.swift/actions/runs/6472468575/job/17573190854?pr=106
https://github.com/software-mansion/starknet.swift/actions/runs/6472288973/job/17572606677?pr=106
https://github.com/software-mansion/starknet.swift/actions/runs/6339833865/job/17219857552?pr=101
In contrast, the quick workflows already have it cached.
https://github.com/software-mansion/starknet.swift/actions/runs/6482377135/job/17602446517?pr=109#step:11:14
https://github.com/software-mansion/starknet.swift/actions/runs/6480901632/job/17597358691?pr=106#step:11:14
https://github.com/software-mansion/starknet.swift/actions/runs/6338873875/job/17216854289?pr=98#step:11:14
https://github.com/software-mansion/starknet.swift/actions/runs/6337833576/job/17213698601?pr=98#step:11:14
```

**Comment by DelevoXDG** [comment] 2023-10-16 16:07
@ilia-shipitsin 
Hi, thanks for your reply. As for @EricHorton's observations, it is true that some build are running slow because of another step that builds rust dependency and this is expected. The runs I'm having problems with, however, mostly have the build step skipped:
1. https://github.com/software-mansion/starknet.swift/actions/runs/6480013686/job/17594678037
2. https://github.com/software-mansion/starknet.swift/actions/runs/6482703180/job/17602729488
The error occurs when `swift test` is getting executed.

> can you add curl 'https://api.ipify.org?format=json' to a pipeline and collect some data

Will send it later.

**Comment by ilia-shipitsin** [comment] 2023-10-16 21:10
@DelevoXDG , we tried to follow your steps and we went wrong direction. Do you have a smaller repro maybe ?

**Comment by ilia-shipitsin** [comment] 2023-10-17 15:14
@DelevoXDG , couple of ideas

1) I tried to add "-v", test passed fast. I'm surprized. https://github.com/ilia-shipitsin/starknet.swift/actions/runs/6548962065/job/17784830336  I did have a hope to see what's the test doing

2) I suspect it may be something on screen, can you add taking screenshot with some delay ?

```
      - name: Run tests
        run: |
          export DEVNET_PATH=${{ github.workspace }}/starknet-devnet-rs/target/release/starknet-devnet
          export SCARB_PATH="$(which scarb)"
          export SNCAST_PATH="$(which sncast)"
          swift test --disable-sandbox -v &
          sleep 1800
          screencapture swift.jpg

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: swift
          path: swift.jpg
```

I really wonder will we see something on screen or not

**Comment by ilia-shipitsin** [comment] 2023-10-17 15:52
I captured a screenshot https://github.com/ilia-shipitsin/starknet.swift/actions/runs/6549279747

nothing on the screen.

verbose output looks like app sent something over network and waits for responce

![image](https://github.com/actions/runner-images/assets/125650415/55c9dbfa-a663-41da-a15b-28278ee05e10)

**Comment by ilia-shipitsin** [comment] 2023-10-17 20:23
> @ilia-shipitsin Hi, thanks for ideas.
> 
> > I tried to add "-v", test passed fast. I'm surprized.
> 
> As I described in the issue, this problem appears randomly. One run can take 6 hours and timeout, the next one takes 5 minutes. It started happening on PR that contained barely any changes and no changes to workflow.
> 
> > verbose output looks like app sent something over network and waits for responce
> 
> This is something that gets send locally (as part of the testing workflow), so it's probably not getting stuck here. And you can later see how much time it took to run all the tests:
> 
> > Executed 62 tests, with 0 failures (0 unexpected) in 58.431 (58.959) seconds
> 
> Similarly, it doesn't take much time to fetch, compile deps and build. In some runs, it just gets stuck after build is successful and nothing happens afterwards: https://github.com/software-mansion/starknet.swift/actions/runs/6482703180/job/17602729488


it would be nice to have some debug from app side, what's doing when it hangs.
from my observation it looks like "something on app level"

**Comment by DelevoXDG** [comment] 2023-10-18 08:07
> it would be nice to have some debug from app side, what's doing when it hangs.
from my observation it looks like "something on app level"

Seems unlikely that it's something on app level. After build is complete (and it takes 60 seconds), the testing part won't start. It would hard to provide any logs where the app hangs, because there are no logs indicating that app was ever used and had a chance to hang:
https://github.com/software-mansion/starknet.swift/actions/runs/6551611362/job/17793174727?pr=111

But I also made a mistake. This seems to be the first time the issue was present was earlier:
https://github.com/software-mansion/starknet.swift/actions/runs/6328364493/job/17186354775
And the runner version was: `20230916.1`. And it only happened once on that version. This issue started to occur repeatedly with `20230921.4`. The issue  was not present on `20230901.1 ` and earlier.

**Comment by ilia-shipitsin** [comment] 2023-10-19 08:19
@DelevoXDG , can you elaborate on "testing part won't start" ?

I'm not very familiar with swift, from my point of view

1. "swift test" is dedicated step currently
2. I added "-v" to "swift test" step

I see activity from "swift test", is it still a build process  ? 
how can we identify test start ?

**Comment by DelevoXDG** [comment] 2023-10-20 09:19
@ilia-shipitsin 
> can you elaborate on "testing part won't start" ?

What I mean is that `swift test` includes both building the package and running the tests. In a successful run, it looks like this: 
```
Build complete! (57.95s)
Test Suite 'All tests' started at 2023-10-11 09:59:04.687
```
The runs that timeout, however, will get stuck after the build is complete, and no tests are run.

**Comment by ilia-shipitsin** [comment] 2023-10-20 09:42
can we split "swift test" into 2 steps ? i.e. build itself and test itself.

**Comment by christoff-1992** [comment] 2023-10-23 11:05
> @ilia-shipitsin
> 
> > can you elaborate on "testing part won't start" ?
> 
> What I mean is that `swift test` includes both building the package and running the tests. In a successful run, it looks like this:
> 
> ```
> Build complete! (57.95s)
> Test Suite 'All tests' started at 2023-10-11 09:59:04.687
> ```
> 
> The runs that timeout, however, will get stuck after the build is complete, and no tests are run.

I am also experiencing the same/similar issue, the build completes and it hangs for some considerable time before the tests are run. Usually in-between this time (locally) the host is booting up the simulator and waiting for it to become responsive. This would normally take a couple of seconds. However on Azure it's averaging around 15mins for the same task to complete.

Running against macOS-13 and Xcode 15.0.0.

> 023-10-20T15:17:47.8345950Z ▸ Linking xxxxxTests
> 2023-10-20T15:17:49.6682010Z ▸ Running script 'SwiftGen'
> 2023-10-20T15:17:51.1883420Z ▸ Running script '[CP] Embed Pods Frameworks'
> 2023-10-20T15:17:59.0741650Z ▸ Running script '[CP] Copy Pods Resources'
> 2023-10-20T15:17:59.7292400Z ▸ Touching xxxxx.xctest (in target 'xxxx' from project 'xxxxx')
> 2023-10-20T15:17:59.7689620Z ▸ Touching xxxx.app (in target 'xxxx' from project 'xxxx')
> 2023-10-20T15:37:06.9789510Z All tests
> 2023-10-20T15:37:07.0792820Z Test Suite xxxxxTests.xctest started

You can see from the logs there's some significant time between the last 'Touching' action and 'All tests'. Unfortunately it's an unknown to what's happening here, in-between, as the logs don't spit anything out. Most likely as it's just sat waiting for the simulator to boot and become responsive.

**Comment by ilia-shipitsin** [comment] 2023-10-23 14:59
@christoff-1992 , let's not mix issues altogether.
we indeed observe slowness on running simulators, however

1) that slowness is somewhat reproducible. i.e. all builds are slow in the same way
2) we still do not know whether something started or not during "swift test"

I do not think we can benefit from mixing all issues altogether.

**Comment by ilia-shipitsin** [comment] 2023-10-30 09:37
I tried to split into 2 steps

```
      - name: Build
        run: |
          export DEVNET_PATH=${{ github.workspace }}/starknet-devnet-rs/target/release/starknet-devnet
          export SCARB_PATH="$(which scarb)"
          export SNCAST_PATH="$(which sncast)"
          swift build

      - name: Test
        run: |
          export DEVNET_PATH=${{ github.workspace }}/starknet-devnet-rs/target/release/starknet-devnet
          export SCARB_PATH="$(which scarb)"
          export SNCAST_PATH="$(which sncast)"
          swift test --disable-sandbox -v
```

currently test passed ~10 times both in split-mode and original single step mode.
hopefully, XCode-15.0.1 upgrade fixed some swift behaviour.

I'm closing issue. feel free to re-open if the issue will occur again

**Closed by ilia-shipitsin** 2023-10-30 09:37 UTC
Labels: Area: Apple, OS: macOS, bug report
