### ISSUE TITLE
Agent 3.241.0 with Ubuntu Image version 20240624.1.0 fails during publishing .Net 8 project

### ISSUE THREAD

**Issue by eholman** [actions/runner-images#10147] opened 2024-07-01 12:20 UTC
### Description

Without changing anything in the software, the pipeline is failing now, of a Hosted Agent. It has an updated runner image as well as an updated agent version. Agent version 3.241.0 on a windows runner image (20240624.1.0) doesn't have the issue. The previous Agent version 3.240.1 with Ubuntu 22.04 runner image version 20240616.1.0 was executing without any issues.

Version of .Net Core CLI task is the same, 2.240.0

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link
```
Starting: Initialize job
Agent name: 'Hosted Agent'
Agent machine name: 'fv-az632-294'
Current agent version: '3.241.0'
Operating System
Ubuntu
22.04.4
LTS
Runner Image
Image: ubuntu-22.04
Version: 20240624.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240624.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240624.1
Runner Image Provisioner
2.0.370.1
Current image version: '20240624.1.0'
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: NuGetToolInstaller (1.238.1)
Downloading task: NuGetAuthenticate (1.238.1)
Downloading task: NuGetCommand (2.238.1)
Downloading task: DotNetCoreCLI (2.240.0)
Downloading task: PublishPipelineArtifact (1.238.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: UseGitLongPaths = true Source: $(USE_GIT_LONG_PATHS) 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC) 
   Knob: ProcessHandlerSecureArguments = false Source: $(AZP_75787_ENABLE_NEW_LOGIC_LOG) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: ProcessHandlerEnableNewLogic = true Source: $(AZP_75787_ENABLE_NEW_PH_LOGIC) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: FailJobWhenAgentDies = true Source: $(FAIL_JOB_WHEN_AGENT_DIES) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
   Knob: MountWorkspace = true Source: $(AZP_AGENT_MOUNT_WORKSPACE) 
   Knob: LogTaskNameInUserAgent = true Source: $(AZP_AGENT_LOG_TASKNAME_IN_USERAGENT) 
   Knob: Rosetta2Warning = true Source: $(ROSETTA2_WARNING) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job
```
### Is it regression?

Version `20240616.1.0` worked fine

### Expected behavior

I expect that the publishing of the .NET 8 Azure Functions project to succeed like it did in the previous version

### Actual behavior
```
Starting: Publish Project
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.240.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/usr/bin/dotnet publish /home/vsts/work/1/s/xx.csproj --configuration Release --no-restore --output /home/vsts/work/1/a/xx
/usr/share/dotnet/sdk/8.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(404,5): error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again. [/home/vsts/work/1/s/xx.csproj]
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [
  '/home/vsts/work/1/s/xx.csproj'
]
Finishing: Publish Project
```

### Repro steps

1. Create a yaml pipeline with ubuntu-latest as vmimage
2. Build Azure Function project with .NET 8
3. Publishing via DotNetCoreCli@2
```
      - task: DotNetCoreCLI@2
        displayName: Publish Project
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/*Application.csproj'
          arguments: --configuration Release --no-restore --output $(Build.ArtifactStagingDirectory)
```

**Comment by eholman** [comment] 2024-07-01 13:20
Locally I'm using .NET 8 SDK 
`8.0.302 [C:\Program Files\dotnet\sdk]`
---
Yaml pipeline:
```
trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: templates
      type: git
      name: xx.Templates

stages:
  - stage: Debug
    jobs:
  - template: jobs/build-deploy-function-app.yaml@templates
    parameters:
      project: erp
```

build-deploy-function-app.yaml:
```
parameters:
  - name: project
    type: string

stages:
  - stage: Build
    displayName: Build ${{ parameters.project }}
    jobs:
    - template: build-function-app.yaml
```

build-function-app.yaml:
```
jobs:
  - job: Build
    steps:
      - checkout: self
        
      - task: NuGetToolInstaller@1
        displayName: Install NuGet

      - task: NuGetAuthenticate@1
        displayName: NuGet Authenticate

      - task: NuGetCommand@2
        displayName: Restore packages
        inputs:
          command: restore
          restoreSolution: '**/*.sln'
          feedsToUse: select
          vstsFeed: 914be17c-6022-437a-a540-0b119c08aebc

      - task: DotNetCoreCLI@2
        displayName: Publish Project
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/*Application.csproj'
          arguments: --configuration Release --no-restore --output $(Build.ArtifactStagingDirectory)

      - task: PublishPipelineArtifact@1
        displayName: Publish Function App as Pipeline Artifact
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifact: functionApp
```

**Comment by kishorekumar-anchala** [comment] 2024-07-01 14:30
Hi @eholman ,

  Could you please try by adding below task before restore task .
  
```
  - task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true
```

Kindly share the logs , if you still facing the issue to investigate further. Thankyou !

**Comment by eholman** [comment] 2024-07-01 14:34
Just tried updating the installer task but it's still failing. What logs do you need?

**Comment by kishorekumar-anchala** [comment] 2024-07-02 03:28
> @kishorekumar-anchala Just tried updating the installer task but it's still failing. What logs do you need?

1) At which task it is failing ?
2) Share me the logs of failed task

**Comment by eholman** [comment] 2024-07-02 05:12
Still the same task that fails

```
Publish Project

[View raw log](https://dev.azure.com/xx/a74b7163-2ae5-4662-b6d5-4562aa45faca/_apis/build/builds/1700/logs/16)

Starting: Publish Project
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.240.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
/usr/bin/dotnet publish /home/vsts/work/1/s/xx.csproj --configuration Release --no-restore --output /home/vsts/work/1/a/xx
/usr/share/dotnet/sdk/8.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(404,5): error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again. [/home/vsts/work/1/s/xx.csproj]
##[error]Error: The process '/usr/bin/dotnet' failed with exit code 1
##[warning].NET 5 has some compatibility issues with older Nuget versions(<=5.7), so if you are using an older Nuget version(and not dotnet cli) to restore, then the dotnet cli commands (e.g. dotnet build) which rely on such restored packages might fail. To mitigate such error, you can either: (1) - Use dotnet cli to restore, (2) - Use Nuget version 5.8 to restore, (3) - Use global.json using an older sdk version(<=3) to build
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : [
  '/home/vsts/work/1/s/xx.csproj'
]
Finishing: Publish Project
```

**Comment by kishorekumar-anchala** [comment] 2024-07-02 07:03
Duplicate of [10139](https://github.com/actions/runner-images/issues/10139) and it will take care with 10139 . Thank you !

**Closed by kishorekumar-anchala** 2024-07-02 07:03 UTC
Labels: bug report
