### ISSUE TITLE
macOS > 12 images do not have miniconda installed

### ISSUE THREAD

**Issue by s-weigand** [actions/runner-images#9889] opened 2024-05-17 17:25 UTC
### Description

I recently got an [issue that setting up conda fails on `macos-latest`](https://github.com/s-weigand/setup-conda/issues/432).
This is related to [`macos-latest` changing form `macos-12` to `macos-14`](https://github.com/actions/runner-images/commit/da5ebb36223a06890092a423a0466b28ea2de595), where the `macos-13` and `macos-14` images do not have miniconda preinstalled.

[`macos-12` Packer template](https://github.com/actions/runner-images/blob/845c5ee866b1e70af19d7723e5818c7ac57915dc/images/macos/templates/macOS-12.pkr.hcl#L237-L271)

[`macos-13` Packer template](https://github.com/actions/runner-images/blob/532cfd5c07ad1213e5d1b607430c2d69a5fc2683/images/macos/templates/macOS-13.anka.pkr.hcl#L234-L257)

[`macos-14` Packer template](https://github.com/actions/runner-images/blob/845c5ee866b1e70af19d7723e5818c7ac57915dc/images/macos/templates/macOS-14.anka.pkr.hcl#L234-L257)

If this is desired I would give a PR a shot where I would add the miniconda installation to the newer macos versions and make [install-miniconda.sh](https://github.com/actions/runner-images/blob/5a6e2158591c3f3b0c732691694d061fea8f792e/images/macos/scripts/build/install-miniconda.sh) compatible with arm64.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-14-arm64

### Is it regression?

N/A

### Expected behavior

Miniconda is installed and the `CONDA` environment variable pointing to the root installation folder is set as it was in `macos-12`.

### Actual behavior

Miniconda is not installed and the `CONDA` environment variable is not set.

### Repro steps

Minimal example of a pipeline that would fail

```yaml
jobs:
    build:
        runs-on: macOS-latest
        steps:
            - uses: s-weigand/setup-conda@v1
```

**Comment by MaksimZhukov** [comment] 2024-05-20 08:40
Hello @s-weigand!
I am closing the issue as a duplicate of [this one](https://github.com/actions/runner-images/issues/9262). Please find all the details there

**Closed by MaksimZhukov** 2024-05-20 08:40 UTC
Labels: needs triage, bug report
