### ISSUE TITLE
Windows 2019 / 2022 - There is no such global user or group: installer

### ISSUE THREAD

**Issue by palten08** [actions/runner-images#9171] opened 2024-01-15 18:49 UTC
### Description

When generating Windows 2019 or 2022 images, provisioning will fail on windows-shell-provisioner3234695829

`azure-arm.image: C:\Users\packer>net user installer <sensitive> /add /passwordchg:no /passwordreq:yes /active:yes /Y
==> azure-arm.image: The syntax of this command is:
    azure-arm.image:
    azure-arm.image: C:\Users\packer>net localgroup Administrators installer /add
==> azure-arm.image:
==> azure-arm.image: NET USER
==> azure-arm.image: [username [password | *] [options]] [/DOMAIN]
    azure-arm.image:
==> azure-arm.image:          username {password | *} /ADD [options] [/DOMAIN]
==> azure-arm.image:          username [/DELETE] [/DOMAIN]
    azure-arm.image: C:\Users\packer>winrm set winrm/config/service/auth @{Basic="true"}
==> azure-arm.image:          username [/TIMES:{times | ALL}]
==> azure-arm.image:          username [/ACTIVE: {YES | NO}]
==> azure-arm.image:
==> azure-arm.image: There is no such global user or group: installer.
==> azure-arm.image:
==> azure-arm.image: More help is available by typing NET HELPMSG 3783.
==> azure-arm.image:
    azure-arm.image: Auth
    azure-arm.image:     Basic = true
    azure-arm.image:     Kerberos = true
    azure-arm.image:     Negotiate = true
    azure-arm.image:     Certificate = false
    azure-arm.image:     CredSSP = false
    azure-arm.image:     CbtHardeningLevel = Relaxed
    azure-arm.image:
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: C:\Users\PETELU~1\AppData\Local\Temp\powershell-provisioner3138207987
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.image: Step "StepProvision" failed
==> azure-arm.image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

No

### Expected behavior

Provisioning should work with no issues

### Actual behavior

Provisioning is failing

### Repro steps

1. Import-Module .\helpers\GenerateResourcesAndImage.ps1
2. GenerateResourcesAndImage -SubscriptionId "" -ResourceGroupName "" -ImageGenerationRepositoryRoot . -ImageType "Windows2022" -AzureLocation ""

**Comment by mikhailkoliada** [comment] 2024-01-16 00:40
Duplicate of https://github.com/actions/runner-images/issues/1184

**Closed by mikhailkoliada** 2024-01-16 00:40 UTC
Labels: needs triage, bug report
