### ISSUE TITLE
Android emulator on macos blank screenshots and videos

### ISSUE THREAD

**Issue by kopax-polyconseil** [actions/runner-images#6814] opened 2022-12-20 11:17 UTC
**Describe the bug**

We use GitHub action for end to end testing for iOS and Android app, in case of failure, we take screenshots and video of the tests.

It works fine locally for both iOS and Android, in GitHub action, it works with iOS simulator, but on Android, the screenshots and video are transparent and black

- Issue was reported to appium https://github.com/appium/appium/issues/17837 , but they advised us to ask here.
- Duplicate also here https://github.com/wix/Detox/issues/3578

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- github action workflow: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/.github/workflows/e2e-android-app.yml
- code to do screenshot: https://github.com/pass-culture/pass-culture-app-native/blob/8ee2e682c8b0d299e8aa64586efc627a9b6b65ab/e2e/config/wdio.shared.conf.ts#L159-L174

Appium log : https://github.com/pass-culture/pass-culture-app-native/actions/runs/3573959420/jobs/6008640936

### Is it regression?

NA

### Expected behavior

We expect to be able to take video and screenshot within the macos runner

### Actual behavior

This is how it look like for the screenshots
![image](https://user-images.githubusercontent.com/77674046/204536866-98d297de-90b4-4716-b725-0879831baa0f.png)

This is the video shot in CI:

<video src="https://user-images.githubusercontent.com/77674046/204561099-597271b2-9bcd-4b68-ba41-e7273432b2b6.mp4"></video>
This is the video log: [wdio-0-0-Video-reporter.log](https://github.com/appium/appium/files/10114136/wdio-0-0-Video-reporter.log)

### Repro steps

See below for workflow, this is an example of workflow that have the problem : https://github.com/pass-culture/pass-culture-app-native/actions/runs/3574751323

**Expected behavior**
We expect to have proper screenshots and video of our app

### Relates to

- https://github.com/actions/runner/issues/2287 
- https://github.com/appium/appium/issues/17837#issuecomment-1331365186

**Comment by igorboskovic3** [comment] 2022-12-20 11:51
Hi @kopax-polyconseil we will take a look, could you provide minimalistic repro steps?

**Comment by kopax-polyconseil** [comment] 2022-12-20 13:08
Hello @igorboskovic3 

This is our repository:

- https://github.com/pass-culture/pass-culture-app-native <- [workflow](https://github.com/pass-culture/pass-culture-app-native/blob/master/.github/workflows/e2e-android-app.yml#L204)
- https://github.com/pass-culture/pass-culture-app-native/tree/test-fix-android-screenshot <- branch attempt with skiagl (same workflow)

It is inspired from https://github.com/webdriverio/appium-boilerplate  a minimal reproduction, you will need this workflow: https://github.com/webdriverio/appium-boilerplate/pull/134/files and you will have to add in `wdio.shared.conf.ts`, this reporter configuration:

Install `wdio-video-reporter` with `yarn add -D wdio-video-reporter` 

Import within [wdio.shared.conf.ts](https://github.com/webdriverio/appium-boilerplate/blob/main/config/wdio.shared.conf.ts#L113): `import video from 'wdio-video-reporter'` 

Use this reporter config:

```tsx

```
  reporters: [
    'spec',
    [
      video,
      {
        saveAllVideos: false, // If true, also saves videos for successful test cases
        videoSlowdownMultiplier: 4, // Higher to get slower videos, lower for faster videos [Value 1-100]
        outputDir: process.cwd(),
      },
    ],
  ],
```

```

Download the demo app : https://github.com/webdriverio/native-demo-app/releases/download/v0.4.0/Android-NativeDemoApp-0.4.0.apk and place it in `apps`, see https://github.com/webdriverio/appium-boilerplate/blob/main/config/wdio.android.app.conf.ts#L29

To run `yarn android.app` locally or in ci. It will record locally but not in CI.

This should help, if this is too broad, I can fork the repo and do this conf.  for you

**Comment by igorboskovic3** [comment] 2022-12-21 14:01
Hi @kopax-polyconseil, this is performance issue, we had similar issues earlier, for [example this one](https://github.com/actions/runner-images/issues/6369). Github Actions builds run on virtual machines with the limited GPU capabilities and it is know problem with the poor performance, causing e2e testing to be problematic. From the workflow file I see you already use AppCenter - do you know it has ability to run the apps on  the real Android devices?

**Comment by kopax-polyconseil** [comment] 2022-12-21 14:30
Yes we use appcenter to launch app on both emulator and real device, why ?

**Comment by dsame** [comment] 2022-12-21 15:35
@kopax-polyconseil running the tests from github actions pipelines is "emulator within emulator" and the emulated device does not have access to the GPU and CPU features. Besides that the emulator requires an amount of memory he can get and behaves unpredictable because debug sessions starts before the some android services have been launched.

**Comment by kopax-polyconseil** [comment] 2022-12-21 16:30
What is your conclusion ? 
This ticket will not be resolve (and cannot) ?
Your advice is to use larger runner or use self hosted?

**Comment by igorboskovic3** [comment] 2022-12-22 15:36
Hi @kopax-polyconseil ,we need to perform deeper investigation and resolve it, if possible, in meantime you can use self-hosted runner, since we don't have large runners for MacOS yet. Thanks

**Comment by bduverger** [comment] 2023-01-03 22:01
Hi @igorboskovic3 @kopax-polyconseil, we have the same issue with macos-latest. We just test on a MacBook Pro 2019 (intel core i9) with macOS 12.6 and again we have black screenshots.

Let me know if I can help with more informations.

ty

**Comment by zommerfelds** [comment] 2023-01-30 10:05
I have a similar setup as the OP (using ReactiveCircus/android-emulator-runner) and I'm getting blank screenshots. I want to note that the issue is a bit undeterministic: maybe every 20th screenshot works.

**Comment by vpuonti** [comment] 2023-02-06 12:27
Hi, 
I'm facing a similar issue with screenshots (not using this runner image though, since I'm running in Azure Pipelines). 
A bit of Googling around led me here: https://issuetracker.google.com/issues/259111479#comment3 
I have not tested updating to emulator canary (version 32.1.4+), but might be worth checking out?

**Comment by m-wayne** [comment] 2023-02-07 05:27
> Hi, I'm facing a similar issue with screenshots (not using this runner image though, since I'm running in Azure Pipelines). A bit of Googling around led me here: https://issuetracker.google.com/issues/259111479#comment3 I have not tested updating to emulator canary (version 32.1.4+), but might be worth checking out?
> 
> e: Updated to latest canary version of emulator and managed to take screenshots via `adb` locally. Before they were blank when using `-gpu swiftshader_indirect`. I'll try throwing errors on local UI tests and post an edit once I know how on-device screenshots turn out. I'm using Espresso 3.5.0's `takeScreenshot()` API to make the screenshots.
> 
> e2: After the emulator update screenshots taken with `takeScreenshot()` are no longer blank. 🎉 Tested locally, I see no reason why this wouldn't also work in the pipeline.

Updating to emulator canary solved this issue for me! Thanks for the suggestion @vpuonti

**Comment by kopax-polyconseil** [comment] 2023-02-07 08:28
How do you update the emulator to canary ? I am using `ReactiveCircus/android-emulator-runner`

**Comment by vpuonti** [comment] 2023-02-07 08:48
You could try using `channel=3` flag when using this runner. 
See doc for `channel` flag here: https://github.com/ReactiveCircus/android-emulator-runner/blob/main/README.md

In Azure Pipelines I used this step:
```
    - bash: $ANDROID_HOME/tools/bin/sdkmanager --install "emulator" --channel=3
      displayName: Install latest Canary version of emulator
```

**Comment by kopax-polyconseil** [comment] 2023-02-07 08:59
Do you use this step just before calling ReactiveCircus/android-emulator-runner and it is enough to switch ? I am having a try right now

**Comment by vpuonti** [comment] 2023-02-07 09:02
@kopax-polyconseil 

The step I posted is only for my Azure Pipelines step, which does not use this Runner. Sorry for confusion. 

For your setup adding `channel: canary` should be sufficient, since the runner does it's own SDK & emulator setup under the hood. LMK how it works out.

**Comment by kopax-polyconseil** [comment] 2023-02-07 09:11
Ok, I will have a try here: https://github.com/pass-culture/pass-culture-app-native/actions/runs/4112262054

**Comment by vpuonti** [comment] 2023-02-07 09:22
Only reason is I'm stuck on Azure DevOps for the time being. 😄

**Comment by erik-bershel** [comment] 2023-04-06 08:18
Hello @vpuonti! Is it possible to update info about situation with the issue?

**Comment by erik-bershel** [comment] 2023-06-26 09:52
@kopax-polyconseil Since @vpuonti  have discovered the workaround and due to inactivity, I am forced to close this issue. Please feel free to open new one in case of other concern.

**Comment by kopax-polyconseil** [comment] 2023-07-05 15:28
What is the workaround? We still have the issue.

**Comment by erik-bershel** [comment] 2023-07-06 10:31
Hey @kopax-polyconseil,
What a pity! I will return the issue for additional investigation.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-10 12:09
Hey @kopax-polyconseil. May I ask you to provide updated repro steps so we can continue investigation? As a starting poing it would be helpful to have a workflow that we can fork and play with.

**Comment by kopax-polyconseil** [comment] 2023-08-14 10:56
Hi @vpolikarpov-akvelon, the repo steps are the one as in the ticket description, and the project repo is still the same.

Unfortunately, we (me and other developer) had so much troubles using github runner reliably to perform e2e in CI that our organization took the decision to stop investing time in it, I doubt the decision will now change.

I just reply here in the hope this will help others.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-14 13:56
Well, since this issue is not relevant anymore and there is a workaround (install canary version of emulator), I'm closing this issue. If you have any other questions or problem is still relevant feel free to crate a new issue with fresh information. Thank you.

**Closed by vpolikarpov-akvelon** 2023-08-14 13:56 UTC
Labels: OS: macOS, investigate, bug report

**Comment by vaind** [comment] 2024-09-03 17:44
This is still/again an issue. Using `canary` emulator doesn't help

**Comment by erik-bershel** [comment] 2024-09-03 18:18
Hey @vaind!

Are you sure that you faced the same? Now we are straggling with the next issue: https://docs.veertu.com/anka/anka-virtualization-cli/nested-virtualization/#android-emulators

**Comment by vaind** [comment] 2024-09-03 20:09
Actually, I'm facing this issue on Linux, while I've just noticed the original issue relates to macos runner

**Comment by erik-bershel** [comment] 2024-09-03 20:31
> Actually, I'm facing this issue on Linux, while I've just noticed the original issue relates to macos runner

It will be better to start a new issue then with complete information to investigate
