### ISSUE TITLE
rasdial constantly returns error 809 (timeout)

### ISSUE THREAD

**Issue by cpeled** [actions/runner-images#9027] opened 2023-12-14 12:59 UTC
### Description

starting 20231205.1.0, when trying to connect to VPN, rasdial.exe constantly returns error 809.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

  Image: windows-2022
  Version: 20231211.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20231211.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20231211.1

Image: windows-2019
  Version: 20231205.1.0
  Included Software: https://github.com/actions/runner-images/blob/win1[9](https://github.com/nsofnetworks/zero/actions/runs/7155009510/job/19483146213#step:1:10)/20231205.1/images/windows/Windows2019-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win19%2F20231205.1

### Is it regression?

20231126.1.0

### Expected behavior

connect to VPN using rasdial.exe

### Actual behavior

i get error 809 (timeout)

### Repro steps

1. run github action with "runs-on" windows-latest or windows-2019
2. disable firewall: netsh advfirewall set allprofiles state off
3. verify DNS to VPN server (record is resolved successfully)
4. try to connect to vpn: rasdial.exe <INTERFACE>

**Comment by erik-bershel** [comment] 2023-12-14 13:53
Hello @cpeled!
Unfortunately, we will not be able to test this feature quickly from our side. Could you provide a little more information about the VPN server you want to connect to? At least the service and geolocation, ideally the address and/or name. I also ask you to provide a link to the unsuccessful launch, regardless of whether it occurred in a private or public repository.

**Comment by cpeled** [comment] 2023-12-14 14:09
Hi @erik-bershel and thanks for your quick response!

the VPN is a private (company property), but we use a standard IPSEC tunnel to connect. server side is strongswan based.
I tried several geolocations, all of them failed.

link to unsuccessful launch (private repo): https://github.com/nsofnetworks/zero/actions/runs/7203593180/job/19623687923

**Comment by cpeled** [comment] 2023-12-17 08:34
Hi again @erik-bershel ,

Currently due to this issue, our production build is broken.
This is a major issue for us and we'll appreciate any help.
While you're testing it, is there a way for us to continue using the old image, so we'll have a working CI?
(even temporary until further investigation)

Best,
Chen

**Comment by uvtrip** [comment] 2023-12-17 09:13
Hi @erik-bershel, 

IPSEC uses the following ports, maybe they got blocked now:
UDP port 500 for Internet Key Exchange (IKE) to manage encryption keys, and UDP port 4500 for IPSec NAT-Traversal (NAT-T)

Thanks,
Yuval

**Comment by erik-bershel** [comment] 2023-12-18 10:38
Hey @cpeled!

Unfortunately, there is currently no way to force use of one or another version of the image.

**Comment by uvtrip** [comment] 2023-12-19 08:07
Hey @erik-bershel 

can you confirm that the ports i mentioned above are still open on the VMs?

**Comment by sergei-pyshnoi** [comment] 2023-12-29 12:09
@uvtrip Yes, we can confirm, ports 500 and 4500 not busy on VM. Unfortunately, we can`t say nothing for now about outside VM network.

**Comment by sergei-pyshnoi** [comment] 2024-01-10 10:20
Hello @cpeled . Unfortunately without proper repro steps (code, pipeline etc.) we cannot reproduce your behavior. I am closing this issue for now. But if you have more detailed repro steps feel free to mention me for reopening issue.

**Closed by sergei-pyshnoi** 2024-01-10 10:21 UTC
Labels: OS: Windows, investigate, bug report
