### ISSUE TITLE
Windows 2022 - Visual Studio 17.11

### ISSUE THREAD

**Issue by erezgeva** [actions/runner-images#10575] opened 2024-09-09 11:03 UTC
### Description

Hi,

The new VC++ 17.11 have an issue with the STL.
See:  https://developercommunity.visualstudio.com/t/1711-fails-to-compile-templated-code-un/10730785

Is there a way to use the older Windows 2022 image?
The one before the new [What’s New for C++ Developers in Visual Studio 2022 17.11](https://devblogs.microsoft.com/cppblog/whats-new-for-cpp-developers-in-visual-studio-2022-17-11/)

Erez

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Same errors you see in https://developercommunity.visualstudio.com/t/1711-fails-to-compile-templated-code-un/10730785

### Is it regression?

The one before Visual Studio 17.11

### Expected behavior

Proper compiling without errors.

### Actual behavior

We get errors similar to https://developercommunity.visualstudio.com/t/1711-fails-to-compile-templated-code-un/10730785

### Repro steps

Just run the tests using C++ STL

**Comment by vidyasagarnimmagaddi** [comment] 2024-09-13 07:35
Hi , @erezgeva .Thanks for reporting. We are looking for some mitigation. The image is old because there was a regression in F# which forced us to rollback the image and we have been waiting for a new Visual Studio release (17.11.3) that has the fix.

**Comment by RaviAkshintala** [comment] 2024-09-18 10:37
Hi @erezgeva The new image (20240915.1) has been successfully rolled out, resolving the issue. Please sync your main branch. Thank you!

**Comment by RaviAkshintala** [comment] 2024-09-20 09:14
@erezgeva I hope the issue has been resolved, If you have any queries please reach out to us. I am closing this issue now,Thanks.

**Closed by RaviAkshintala** 2024-09-20 09:14 UTC
Labels: OS: Windows, bug report
