### ISSUE TITLE
Failure to install `linux-tools` on Ubuntu 22.04 runner

### ISSUE THREAD

**Issue by abensonca** [actions/runner-images#7567] opened 2023-05-10 15:33 UTC
### Description

Attempting to install `linux-tools` on a standard Ubuntu 22.04 runner fails - seemingly due to a version mismatch.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230426.1

https://github.com/galacticusorg/galacticus/actions/runs/4930903131/jobs/8813431490

### Is it regression?

Yes - last successful build https://github.com/galacticusorg/galacticus/actions/runs/4898411401/jobs/8748182950

### Expected behavior

`apt install -y linux-tools-$(uname -r) linux-tools-generic` should successfully complete and provide a working `perf` command.

### Actual behavior

Fails with the message:
```
The following packages have unmet dependencies:
 linux-tools-5.15.0-1036-azure : Depends: linux-azure-tools-5.15.0-1036 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

Seems to be related to the recent (05/09/2023) release which updated to Kernel Version: `5.15.0-1037-azure`

### Repro steps

On a standard Ubuntu 22.04 runner this can be reproduced using:

```
  apt -y update && apt -y upgrade && apt autoremove
  apt install -y linux-tools-$(uname -r) linux-tools-generic
```

**Comment by sergei-pyshnoi** [comment] 2023-05-11 09:02
Hello @abensonca. We will take a look.

**Comment by sergei-pyshnoi** [comment] 2023-05-12 10:53
@abensonca Cannot reproduce error.
Here is my run: https://github.com/sergei-pyshnoi/make-simple/actions/runs/4958006138/jobs/8870359427
Look like problem is gone with version `20230507.1` of image.
I am closing issue for now but if you have additional questions, feel free to ask.

**Closed by sergei-pyshnoi** 2023-05-12 10:53 UTC
Labels: Area: Packages, OS: Ubuntu, bug report
