### ISSUE TITLE
[Request] Add pnpm

### ISSUE THREAD

**Issue by eterv** [actions/runner-images#6356] opened 2022-10-05 03:38 UTC
### Tool name

pnpm

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

7.13.1 or latest

### Brief description of tool

pnpm is fast, disk space efficient Node package manager.
today, many monorepo developers use this pnpm. (vite, svelte, ...)
I also use it. very fast and helpful.
Please see the link below for more information.

https://pnpm.io/motivation
https://pnpm.io/feature-comparison

### URL for tool's homepage

https://pnpm.io/

### Provide a basic test case to validate the tool's functionality.

```bash
pnpm -v
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Acturally I don't know.
Please see the link below for more information.

https://pnpm.io/installation
```

### Tool installation time in runtime

maybe less then 10 seconds

**Comment by mikhailkoliada** [comment] 2022-10-05 06:51
A duplicate of https://github.com/actions/runner-images/issues/2279

**Closed by mikhailkoliada** 2022-10-05 06:51 UTC
Labels: needs triage, feature request

**Comment by egg-r** [comment] 2022-10-17 15:00
Hi @mikhailkoliada ,

For Azure DevOps pipelines, I'd have to install pnpm though right each time it's needed?  The mentioned duplicate is for a Github Action task for functionality.  I was researching this morning if pnpm was installed already in image, and wanted to ask here before creating a new issue/request to add.
