### ISSUE TITLE
Support Windows Kernel Dump Collection

### ISSUE THREAD

**Issue by nibanks** [actions/runner-images#3858] opened 2021-08-05 13:03 UTC
### Tool name

Windows Kernel Dump Collection

### Tool license

N/A

### Add or update?

- [X] Add
- [ ] Update

### Desired version

N/A

### Approximate size

N/A

### Brief description of tool

We (Microsoft Windows developers) are onboarding more Windows kernel development to public (GitHub) repositories and leveraging Azure Pipelines to run the CI. One major limitation right now is the inability to collect the kernel dump that gets created if/when the Windows driver crashes during testing. Somehow, we need to get the kernel dump file and make it externally available so that the developer may download it and analyze the crash.

- Full kernel dumps need to be enabled ([msdn](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump#enable-memory-dump-setting)).
- Somehow, the yaml should indicate that a kernel dump may be result from a job/task.
- If/when the dump is created (and you lose contact with the agent, because it reboots), we should be able to continue executing jobs/tasks if continue on failure is set.
- The dump either needs to be in a well known location or should be specified by the yaml where to put/upload it.

### URL for tool's homepage

https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump

### Provide a basic test case to validate the tool's functionality.

```bash
The [NotMyFault tool](https://docs.microsoft.com/en-us/windows/client-management/generate-kernel-or-complete-crash-dump#use-the-notmyfault-tool) should be trivially used to generate a kernel dump on demand to validate the process end to end.
```

### Virtual environments affected

- [ ] Ubuntu 16.04
- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] macOS 10.15
- [ ] macOS 11
- [X] Windows Server 2016
- [X] Windows Server 2019

### Can this tool be installed during the build?

```bash
N/A. Since this requires handling a reboot (kernel crash) during a job it requires more than just installing something.
```

### Tool installation time in runtime

N/A

### Are you willing to submit a PR?

Not currently

**Comment by nibanks** [comment] 2021-08-05 13:16
Seems that the dump collection behavior can be configured via the Windows registry:

- Key: `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\CrashControl`
   - Set `CrashDumpEnabled` (`REG_DWORD`) to `1`.
   - Set `DumpFile` (`REG_EXPAND_SZ`) to the output location (defaults to `%SystemRoot%\MEMORY.DMP`).

And then **reboot**. I assume it should be trivial to add these to the image build scripts. Just have the dumps go to a well known (default probably is fine) location.

The real complexity then comes with automatic collection, upload and then continued execution after the reboot.

**Comment by dibir-magomedsaygitov** [comment] 2021-08-05 13:17
Hello @nibanks. Thank you for your request. We will consider adding Windows Kernel Dump Collection to our images.

**Comment by catthehacker** [comment] 2021-08-05 13:27
I think this should be split into 2 requests.
One is for https://github.com/actions/virtual-environments to prepare Windows environments for proper memory dump configuration
Second is for https://github.com/actions/runner for:
> If/when the dump is created (and you lose contact with the agent, because it reboots), we should be able to continue executing jobs/tasks if continue on failure is set.

This would require for VMs to have dedicated space for memory dump (since standard temp/volatile disk on Azure does not guarantee data persistence across restart) but that depends on how runners are configured from Azure side.
If it's a non-persistent VDI, memory dump will need to have dedicated persistent space.

**Comment by nibanks** [comment] 2021-08-05 13:38
Thanks @catthehacker. I have opened an issue there (above) as well.

**Comment by maxim-lobanov** [comment] 2021-08-05 15:36
I think rebooting machine during the build is not possible by design (at least for Hosted machine) and it is not something that can be easily implemented without significant rework of Azure Pipelines Agent. But it is better to clarify with Agent team since we are not experts in this area. 

@nibanks , small correction, the second request about reboot should go to https://github.com/microsoft/azure-pipelines-agent repo because you need this request for Azure DevOps. `actions/runner` repo is for GitHub Actions Agent. They are pretty different.

As for the configuring dump collection behavior on images, we don't have objections to implement this feature but I would prefer to wait confirmation from Agent team that they can handle the second part because I guess dumping logs don't make sense without reboot.

**Comment by nibanks** [comment] 2021-09-21 14:21
I created microsoft/azure-pipelines-agent#3540 to track supporting the reboot that occurs when a bugcheck happens. In parallel, I'd like to make sure the Windows machines are configured to collect full Windows kernel dumps to a well-known location. The following would just need to be added to the setup script for agents (before the final reboot).
```
# Configure dump file collection.
reg add HKLM\SYSTEM\CurrentControlSet\Control\CrashControl /v DumpFile /t REG_EXPAND_SZ /d C:\memory.dmp /f
reg add HKLM\SYSTEM\CurrentControlSet\Control\CrashControl /v CrashDumpEnabled /t REG_DWORD /d 1 /f
reg add HKLM\SYSTEM\CurrentControlSet\Control\CrashControl /v Overwrite /t REG_DWORD /d 1 /f
reg add HKLM\SYSTEM\CurrentControlSet\Control\CrashControl /v AlwaysKeepMemoryDump /t REG_DWORD /d 1 /f
```

**Comment by mikhailkoliada** [comment] 2023-12-15 14:58
Hey! It looks like we did not progress here over the past few years. Given that it hard depends on the ability of the runner to reboot itself, I am closing the issue until this functionality is in prod (if ever?). @nibanks if you have concerns / questions feel free to reach me out, but generally we are hard blocked / can't do anything right now.

**Closed by mikhailkoliada** 2023-12-15 14:58 UTC
Labels: OS: Windows, Area: Common Tools, external, feature request

**Comment by nibanks** [comment] 2023-12-15 15:06
@mikhailkoliada our requirements haven't changed. We still need support for this feature, and without it we continue to experience the pain of requiring manual, local repros when kernel code crashes. Who do I need to escalate this to?
