### ISSUE TITLE
Headless Chrome crashes during npm run test on ubuntu-latest

### ISSUE THREAD

**Issue by BenLuts** [actions/runner-images#6686] opened 2022-12-05 06:59 UTC
### Description

Since last friday we can not run npm test anymore. The process fails to launch Chome Headless.

`05 12 2022 06:32:42.413:INFO [karma-server]: Karma v6.4.0 server started at http://localhost:9876/
05 12 2022 06:32:42.415:INFO [launcher]: Launching browsers ChromeHeadless with concurrency unlimited
05 12 2022 06:32:42.460:INFO [launcher]: Starting browser ChromeHeadless
05 12 2022 06:32:44.909:ERROR [launcher]: Cannot start ChromeHeadless
	
DevTools listening on ws://127.0.0.1:9222/devtools/browser/f93225f1-51cf-4a41-a932-7df8503c560e
[1205/063243.725972:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
[1205/063243.883740:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 2 time(s)
[1205/063244.058874:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 3 time(s)
[1205/063244.209427:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 4 time(s)
[1205/063244.356800:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 5 time(s)
[1205/063244.504552:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 6 time(s)
[1205/063244.504592:FATAL:gpu_data_manager_impl_private.cc(918)] The display compositor is frequently crashing. Goodbye.
`

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20221127.1

### Is it regression?

ubuntu-latest on December 1st was working fine.

### Expected behavior

Headless Chrome starts correctly

### Actual behavior

The display compositor is frequently crashing

### Repro steps

npm install karma
ng test --watch=false --project prd --browsers=ChromeHeadless

**Comment by mikhailkoliada** [comment] 2022-12-05 07:38
Hello, Please provide the minimal workflow with all the dependencies to reproduce the issue.

**Comment by BenLuts** [comment] 2022-12-05 09:32
We install the angular CLI
`npm i @angular/cli`

We create a demo angular application by doing
`ng new angular-tour-of-heroes`

We then run
`ng test --watch=false --browsers=ChromeHeadless`

Depencies needed is npm 16.x.x

**Comment by BenLuts** [comment] 2022-12-05 09:43
Issue at first glance appears to be similar to this old issue https://github.com/puppeteer/puppeteer/issues/5661#issuecomment-614814537

**Comment by KirillMetrik** [comment] 2022-12-07 10:55
Hello,
experiencing exactly the same issue. We use Azure DevOps with `ubuntu-latest` for building and testing our Angular application.
Since yesterday the karma tests started to fail with an error:
```
ERROR [launcher]: Cannot start ChromeHeadless
	
DevTools listening on ws://127.0.0.1:9222/devtools/browser/4e745292-ddc4-4e8b-930d-b364004d1296
[1206/154355.308842:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[1206/154355.657144:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=159
[1206/154355.657177:WARNING:gpu_process_host.cc(1299)] The GPU process has crashed 1 time(s)
[1206/154355.684671:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[1206/154355.807485:ERROR:gpu_process_host.cc(991)] GPU process exited unexpectedly: exit_code=159
[1206/154355.807532:WARNING:gpu_process_host.cc(1299)] The GPU process has crashed 2 time(s)
```
After downgrading to ubuntu-20.04 the problem is gone.

**Comment by BenLuts** [comment] 2022-12-08 07:31
Downgrading to ubuntu-20.04 does fix the problem.

**Comment by mikhailkoliada** [comment] 2022-12-14 11:44
Hello! @BenLuts  we can not guarantee that your code will work on ubuntu-22.04 at all due to version differences. From the log you provided we have not found faulty places we could fix on our side, that's why I am going to close the issue. Feel free to reach us out again if you have questions left.

**Closed by mikhailkoliada** 2022-12-14 11:44 UTC
Labels: OS: Ubuntu, investigate, bug report
