### ISSUE TITLE
Visual Studio Enterprise 2022	17.7.34031.279 includes v143 out-of-support components and lacks the latest version

### ISSUE THREAD

**Issue by v-lomer** [actions/runner-images#8544] opened 2023-10-12 21:40 UTC
### Description

We noticed that Visual Studio Enterprise 2022 17.7.34031.279 CL.exe being used locally was newer than the version in the image. It appears the issue is related to the older v143 component versions being installed in the image.

CMake was finding these components for CXX/C compiler with the image:

> C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x64/cl.exe

While that version of Visual Studio's latest v143 toolchain comes with CXX/C compiler, which matches our local visual studio installations:

> C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe

To get the latest v143 toolchain and compiler, we issued an `update --removeOos true` and also added the (latest) versions of the various v143 components.

```
'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
'Microsoft.VisualStudio.Component.VC.CLI.Support',
'Microsoft.VisualStudio.Component.VC.Tools.ARM64',
'Microsoft.VisualStudio.Component.UWP.VC.ARM64',
'Microsoft.VisualStudio.Component.VC.Tools.ARM',
'Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre',
'Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre',
'Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre'
```

We also verified this issue by having our yaml output the components installed in the image and applied them to a clean Visual Studio installation locally. And, verified that there are a number of out-of-support components with respect to the v143 toolchain. Having the VS Installer remove these components allowed for the installation to use the latest CL.exe.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230924.1.0
Included Software: https://github.com/actions/runner-images/blob/win22/20230924.1/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230924.1

### Is it regression?

maybe

### Expected behavior

Visual Studio 2022 components where possible should include the `(Latest)` version

### Actual behavior

The `(Latest)` version of the v143 toolchain is not installed, while several out-of-support versions are installed. This prevents the latest CXX/C compiler from being used. Instead an older version of the CXX/C compiler is used.

### Repro steps

Using CMake with a Visual Studio generator, notice that the CL.exe being used is not the latest version.

**Comment by v-lomer** [comment] 2023-10-12 23:18
We found the v143 toolchain issue when trying to enable Address Sanitizer in our CI builds for the Win32 applications we produce. Currently, with ~15 minute duration of Visual Studio update command in yaml, we can work around the issue, but this is not ideal and indicates a larger issue with the Visual Studio installation provided with the image.

**Comment by vpolikarpov-akvelon** [comment] 2023-10-13 05:28
Hey there. Thank you for reporting. Could you please share links to any workflow that is broken by this issue for us to investigate?

Also I would like to ask you how do you specify compiler version and do you set exact compiler update number somehow.

**Comment by v-lomer** [comment] 2023-10-16 19:17
This build, [18969875](https://dev-mc.visualstudio.com/DefaultCollection/Minecraft/_build/results?buildId=18969875), shows that the image Version: 20230924.1.0 finds MSVC 19.35.32217.1 and cl.exe from VC/Tools/MSVC/14.35.32215.

But, that version of Visual Studio should have MSVC 19.37.32825.0 and cl.exe from VC/Tools/MSVC/14.37.32822 available. But, they don't appear to be installed when querying Visual Studio configuration. And there are several Out-Of-Service versions installed.

The Address Sanitizer changes we wanted to utilize in CI are addressed in the newer toolset that is part of this Visual Studio installation and only in the latest version of cl.exe (which was not installed).

In our pipeline yaml for the build linked, we added the following components for Visual Studio AND we also used the `--removeOos true` which fixed the Visual Studio installation.

```
            'Microsoft.VisualStudio.Component.VC.Tools.x86.x64',
            'Microsoft.VisualStudio.Component.VC.CLI.Support',
            'Microsoft.VisualStudio.Component.VC.Tools.ARM64',
            'Microsoft.VisualStudio.Component.UWP.VC.ARM64',
            'Microsoft.VisualStudio.Component.VC.Tools.ARM',
            'Microsoft.VisualStudio.Component.VC.Runtimes.ARM.Spectre',
            'Microsoft.VisualStudio.Component.VC.Runtimes.ARM64.Spectre',
            'Microsoft.VisualStudio.Component.VC.Runtimes.x86.x64.Spectre'
```

**Comment by v-lomer** [comment] 2023-10-16 19:30
Running the following on the Image does not show the `latest` v143 individual components as installed, and none of the `Microsoft.VisualStudio.Component.VC.14.37.17.*` components are listed as installed.

> Get-VSSetupInstance -All -Prerelease | Select-VSSetupInstance -Latest | Select-Object -Expand packages | Where-Object type -in 'workload', 'component' | Select-Object -Expand Id | ConvertTo-Json

**Comment by vpolikarpov-akvelon** [comment] 2023-10-17 13:33
> These are missing from the image:

Actually all these components are installed. You command prints them as well. Also they are listed in [Readme](https://github.com/actions/runner-images/blob/4d9ce81db6b8cc0c712e6359e1d011adeead31cb/images/win/Windows2022-Readme.md). Could you please verify once more?

> This build, [18969875](https://dev-mc.visualstudio.com/DefaultCollection/Minecraft/_build/results?buildId=18969875), shows that the image Version: 20230924.1.0 finds MSVC 19.35.32217.1 and cl.exe from VC/Tools/MSVC/14.35.32215.

Unfortunately, you project is private so I can't access and review you pipeline definition and logs. Could you share it manually?

**Comment by v-lomer** [comment] 2023-10-17 17:10
Our main branch builds still show the older compiler version.

-- The CXX compiler identification is MSVC 19.35.32217.1
-- The C compiler identification is MSVC 19.35.32217.1
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.35.32215/bin/HostX64/x64/cl.exe

While, my branch shows the component lists after installing the components (since they were missing). I will add logic to dump the list before making VS changes.

**Comment by v-lomer** [comment] 2023-10-18 18:34
Looking into reproducing the issue more with a narrower focus shows that issuing a VS update with `--removeOos true` fixes the issue for us.

Component output before making any changes shows the following components:
> Microsoft.VisualStudio.Component.VC.14.37.17.* (18 entries)
> Microsoft.VisualStudio.Component.VC.14.35.17.* (18 entries)
Where the VC.14.35.17 components are found by the cmake generator command we are using, instead of the latest VC.14.37.17 components.

However, after issuing the VS Update with `--removeOos true`, which removes all of the Microsoft.VisualStudio.Component.VC.14.35.17.* components and our generator shows the expected version is being used.

**Comment by madskristensen** [comment] 2023-10-25 17:13
17.8 has been out for a while. It would be great to get it updated on the image. VS extension developers often need the very latest version to build their extensions correctly.

**Comment by vpolikarpov-akvelon** [comment] 2023-10-26 09:45
Hey @madskristensen, 17.8 is in preview still. It's unlikely to be installed until officially released.

**Comment by mikhailkoliada** [comment] 2023-10-27 13:54
Marking as a duplicate of https://github.com/actions/runner-images/issues/8654 as we seem to remove some old  components there, lets keep the discussion there too

**Closed by mikhailkoliada** 2023-10-27 13:54 UTC
Labels: Area: C/C++, OS: Windows, bug report
