### ISSUE TITLE
Missing php on macos

### ISSUE THREAD

**Issue by dixyes** [actions/runner-images#9790] opened 2024-05-06 08:16 UTC
### Description

This document said PHP 8.3.6 is included: https://github.com/actions/runner-images/blob/main/images/macos/macos-14-Readme.md
but I cannot find it anywhere: https://github.com/dixyes/ghactionsplay/actions/runs/8966009058/job/24620638240

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.316.0'
Operating System
  macOS
  14.4.1
  23E224
Runner Image
  Image: macos-14-arm64
  Version: 20240422.3
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240422.3/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240422.3
Runner Image Provisioner
  2.0.369.1+55cddbb57f254a369b6e7b3b508cebdbee5d24be
GITHUB_TOKEN Permissions
  Actions: write
  Attestations: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Complete job name: where is php in macos-14

### Is it regression?

unknown

### Expected behavior

Add php in that arm64 image or use "macos-14"(not "macos-14-arm64") for "runs-on: macos-14"

### Actual behavior

The job runs with "macos-14-arm64" when I specified "runs-on: macos-14", and it's without php installed

### Repro steps

https://github.com/dixyes/ghactionsplay/blob/641563aef3462ff3d74baef5d7b9a67b9ac5422f/.github/workflows/where-is-php.yml

**Comment by erik-bershel** [comment] 2024-05-07 09:38
Hey @dixyes!

It's a duplicate of https://github.com/actions/runner-images/issues/9437.
We are not going to add PHP for now due to a maintenance concerns. The decision might be reconsidered later.

**Closed by erik-bershel** 2024-05-07 09:38 UTC
Labels: Area: PHP, OS: macOS, feature request
