### ISSUE TITLE
Update GH CLI to the latest version

### ISSUE THREAD

**Issue by xiehan** [actions/runner-images#7982] opened 2023-07-26 10:38 UTC
### Description

https://github.com/actions/runner-images/blob/ubuntu22/20230716.1/images/linux/Ubuntu2204-Readme.md claims that the installed GH CLI is the latest minor version (v2.32) but in my recent experience, it seems to regularly complain when trying to use newer commands, suggesting that is not actually the version that is installed.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

  Image: ubuntu-22.04
  Version: 20230716.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230716.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230716.1

https://github.com/hashicorp/cdktf-aws-cdk/actions/runs/5662005438/job/15341078274
https://github.com/hashicorp/cdktf-aws-cdk/actions/runs/5542948954/job/15012524595

### Is it regression?

Not sure

### Expected behavior

Newer GH CLI commands like `gh run cancel` and `gh pr close -c` are available.

https://cli.github.com/manual/gh_run_cancel
https://cli.github.com/manual/gh_pr_close

### Actual behavior

```bash
Run gh run cancel $RUN_ID 
unknown command "cancel" for "gh run"

Usage:  gh run <command> [flags]

Available commands:
  download
  list
  rerun
  view
  watch
Error: Process completed with exit code 1.
```

```bash
Run gh pr close $PR_ID -d -c 'Closing this PR because there are no changes after the self-mutation.'
unknown shorthand flag: 'c' in -c

Usage:  gh pr close {<number> | <url> | <branch>} [flags]

Flags:
  -d, --delete-branch   Delete the local and remote branch after close
  
Error: Process completed with exit code 1.
```

### Repro steps

See above.

**Comment by sergei-pyshnoi** [comment] 2023-07-26 11:34
Hello @xiehan . Unfortunately I cant reproduce the issue. I created [test workflow](https://github.com/sergei-pyshnoi/make-simple/actions/runs/5668086925/job/15358085562) with `gh --version` and `gh run --help` . As result:
```
gh version 2.32.0 (2023-07-11)
https://github.com/cli/cli/releases/tag/v2.32.0
List, view, and watch recent workflow runs from GitHub Actions.

USAGE
  gh run <command> [flags]

AVAILABLE COMMANDS
  cancel:      Cancel a workflow run
  delete:      Delete a workflow run
  download:    Download artifacts generated by a workflow run
  list:        List recent workflow runs
  rerun:       Rerun a run
  view:        View a summary of a workflow run
  watch:       Watch a run until it completes, showing its progress

FLAGS
  -R, --repo [HOST/]OWNER/REPO   Select another repository using the [HOST/]OWNER/REPO format

INHERITED FLAGS
  --help   Show help for command

LEARN MORE
  Use 'gh <command> <subcommand> --help' for more information about a command.
  Read the manual at https://cli.github.com/manual
```

Can you please provide more detailed repro or link to failed workflow?

**Comment by xiehan** [comment] 2023-07-26 11:36
Links to failed workflow runs were in my original issue (click on Workflow File on the left to see the corresponding YAML files):

https://github.com/hashicorp/cdktf-aws-cdk/actions/runs/5662005438/job/15341078274
https://github.com/hashicorp/cdktf-aws-cdk/actions/runs/5542948954/job/15012524595

**Comment by sergei-pyshnoi** [comment] 2023-07-26 14:33
@xiehan 
Unfortunately still can not reproduce issue.
Successful run with closing PR: https://github.com/sergei-pyshnoi/make-simple/actions/runs/5669840449/job/15363448222
Successful run witch canceling run: https://github.com/sergei-pyshnoi/make-simple/actions/runs/5670098409/job/15364237637

**Comment by sergei-pyshnoi** [comment] 2023-07-31 09:36
Hello @xiehan. Due to the inability to reproduce the problem, I close this thread. The problem doesn`t look like runner-image related because all the commands GH CLI runs successfully on the same image version. If you have additional questions, feel free to ask.

**Closed by sergei-pyshnoi** 2023-07-31 09:36 UTC
Labels: Area: Scripting and command line, OS: Ubuntu, bug report
