### ISSUE TITLE
Azure PowerShell modules no longer available in parallel jobs

### ISSUE THREAD

**Issue by krowlandson** [actions/runner-images#7034] opened 2023-02-02 12:09 UTC
### Description

We have a "cleanup" script written in PowerShell which uses `ForEach-Object -Parallel {}` to process a number of long running tasks in parallel.

This was previously working fine, and is still working when run outside of a GitHub Runner on the latest PowerShell and module versions.

When we run this in a GitHub Action, we now get the following error:

```
WARNING: The command Set-AzContext is part of Azure PowerShell module "Az.Accounts" and it is not installed. Run "Install-Module Az.Accounts" to install it.
WARNING: The intelligent recommendation feature is in preview. Help us improve it by sharing your experience: https://go.microsoft.com/fwlink/?linkid=2202436
Set-AzContext: 
Line |
  10 |          Set-AzContext -Context $using:ctx | Out-Null
     |          ~~~~~~~~~~~~~
     | The term 'Set-AzContext' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
Error: Error: The process '/usr/bin/pwsh' failed with exit code 1
```

Adding a step to manually install or import the required module(s) result in an `AzKeyStore is locked` error.

The function in which we run this task can be found here:

https://github.com/Azure/Enterprise-Scale/blob/bfc27d4abc1a26c1731b88717c6e87dc4a5c910c/src/Alz.Tools/functions/Alz.Tools.ps1#L727-L786

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230129.2
Failed build: https://github.com/Azure/Enterprise-Scale/actions/runs/4073786079/jobs/7018132785

Working build: https://github.com/Azure/Enterprise-Scale/actions/runs/3830643465/jobs/6519179619

### Is it regression?

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20221212.1

### Expected behavior

When launching parallel jobs in PowerShell, all installed modules should be available for use within the new runspaces.

### Actual behavior

We observe the error described above.

### Repro steps

See sequences described above and visible in our public jobs.

**Comment by bogdan-damian-bgd** [comment] 2023-02-02 12:44
Hello @krowlandson, we'll take a look at it.

**Comment by erik-bershel** [comment] 2023-02-02 18:23
Hey @krowlandson, 
Can I ask you to check your action workflow with using of 9.0.1 option for Az.Modules? After a little check I found that Az.Accounts works better from that bundle.
For example:
``` 
      - name: Run eslzArm deployment (DESTROY)
        uses: azure/powershell@v1
        with:
          inlineScript: ./src/scripts/Invoke-ActionRunEslzArmDeployment.ps1 -Destroy
          azPSVersion: "9.0.1"
```
And I ask you to provide some simple workflow for reproducing your issue. Because I suspect that in the course of my investigation, I stumbled upon a completely different bug.

**Comment by krowlandson** [comment] 2023-02-07 09:53
Will give this a try and report back. Thank you @erik-bershel 👍🏻

**Comment by krowlandson** [comment] 2023-02-09 17:03
@erik-bershel we're not having much luck with the above:

![image](https://user-images.githubusercontent.com/12268562/217885399-b6dd4da3-6e27-40b6-8520-d970a76181e8.png)

https://github.com/Azure/Enterprise-Scale/actions/runs/4135302588/jobs/7147570428

I don't think I've missed anything obvious, so any thoughts why it's not respecting the version  being specified?

**Comment by erik-bershel** [comment] 2023-02-12 16:00
Hello again @krowlandson!
About azure/powershell@v1 with azPSVersion option. I am not sure. It might be connected with installation method used by action maintainers. You may open an issue if you want in repo here: https://github.com/Azure/powershell.
But speaking about your current concern connected with using of Set-AzContext in parallel jobs I still need some simple workflow to repro that issue with using of standard runners.

**Comment by krowlandson** [comment] 2023-02-13 21:33
Will see if I can work something out @erik-bershel 👍🏻

**Comment by daltondhcp** [comment] 2023-02-15 07:08
ICYMI, the KeyStore/Parallel issue was fixed in Az PowerShell 9.4.0/Az.Accounts 2.11.2.
https://github.com/Azure/azure-powershell/issues/20455

**Comment by krowlandson** [comment] 2023-02-16 20:09
> ICYMI, the KeyStore/Parallel issue was fixed in Az PowerShell 9.4.0/Az.Accounts 2.11.2. [Azure/azure-powershell#20455](https://github.com/Azure/azure-powershell/issues/20455)

Thanks for the cross reference @daltondhcp... we'll see if we can get our tests completing successfully on this version (assuming it's available within the runners) 👍🏻

**Comment by erik-bershel** [comment] 2023-02-16 20:36
@krowlandson new images with latest Azure in process. We'll inform you after deploying Ubuntu images.

**Comment by erik-bershel** [comment] 2023-02-23 19:13
Hey @krowlandson! How Powershell@0 action with latest azPSVersion works right now for you? We still didn't deployed images with preinstalled Az PowerShell 9.4.0 because of maintenance concerns so I a bit worried about your experience with runners.

**Comment by jtracey93** [comment] 2023-02-23 19:18
Hey @erik-bershel, @krowlandson has changed roles recently, but will still be interested in this, so pikcing this up on his behalf.

Right now our workflow for the step is set to:
```
- name: Run eslzArm deployment (DESTROY)
        uses: azure/powershell@v1
        with:
          inlineScript: ./src/scripts/Invoke-ActionRunEslzArmDeployment.ps1 -Destroy
          azPSVersion: "9.0.1"
```
https://github.com/Azure/Enterprise-Scale/blob/ec81326e1c23f427780879bb25db609e993257af/.github/workflows/test-portal.yml#L127-L131

Are you saying we should now remove the ` azPSVersion: "9.0.1"` line and re-test so it pulls the latest?

Let me know and I can update and test and report back 👍

Also linking to our issue for correlation https://github.com/Azure/Enterprise-Scale/issues/1199

**Comment by erik-bershel** [comment] 2023-02-23 20:09
Hey @jtracey93! I checked it again and found that it would not help. I'll come back tomorrow with additional info.

**Comment by jtracey93** [comment] 2023-02-23 20:12
Thanks @erik-bershel

**Comment by jtracey93** [comment] 2023-02-24 17:50
Looking good @erik-bershel, https://github.com/Azure/Enterprise-Scale/actions/runs/4264732142/jobs/7423187672

**Comment by erik-bershel** [comment] 2023-02-24 19:18
@jtracey93 nice. Let's summarise. As a result, the main problem was a bug in the Azure Powershell repo - https://github.com/Azure/azure-powershell/issues/20455. The second issue is a bug or undocumented behaviour for the [azure/powershell@v1](https://github.com/Azure/powershell) action regarding the use of the azPSVersion option (not sure about that part). Given that we found a temporary solution and the problem was initially outside our area of responsibility, I have to close this issue. 
And I would recommend contacting [azure/powershell@v1](https://github.com/Azure/powershell) colleagues to resolve the issue with versioning. Because the situation may one way or another repeat in the future (who knows when another bug would visit us).

**Closed by erik-bershel** 2023-02-24 19:19 UTC
Labels: Area: Scripting and command line, OS: Ubuntu, bug report
