### ISSUE TITLE
macos-15 on macos-13-xlarge runners label 

### ISSUE THREAD

**Issue by marciorgb** [actions/runner-images#10813] opened 2024-10-18 17:16 UTC
### Description

Upon running multiple parallel jobs on runners with the label `macos-13-xlarge`, we sometimes receive the macOS 15 operating system instead of the expected macOS 13.7

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

- Image: macos-13-arm64
- Version: 20241014.21

And

- Image: macos-15-arm64
- Version: 20241014.193

### Is it regression?

No

### Expected behavior

The label act as expected and the macos-13-xlarge only calls the Macos 13.7 OS

### Actual behavior

With multiple jobs at the same time the `macos-13-xlarge` label also runs in the Macos 15.9 OS

### Repro steps

Create a workflow with matrix that start multiple jobs  (10+) at the same time and sometimes the operational system is the macos 15

```
name: Workflow disptach test

on:
  workflow_dispatch: ~

jobs:
  run:
    strategy:
      matrix:
        tests: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    runs-on: macos-13-xlarge
    steps:
      - name: Echo
        run: |
          echo "TRUE"
```

**Comment by sjan** [comment] 2024-10-18 18:19
Hi i'm seeing this issue too. My workflow is configured to run on `macos-13-xlarge` Sometimes it resolves correctly

![2024-10-18_14-17](https://github.com/user-attachments/assets/9f22ffc8-364c-4c3a-9e56-b2249c7b7bfd)


sometimes it resolves incorrectly
![2024-10-18_14-18](https://github.com/user-attachments/assets/c36896d5-63c6-45e2-a32a-37cd2063bd3a)

**Comment by mcagabe19** [comment] 2024-10-18 18:35
that's why I get architecture mismatch on building

**Comment by sarathrajsrinivasan** [comment] 2024-10-18 22:36
Hi @marciorgb / All,

We are looking into it. Will keep you posted.

**Comment by erik-bershel** [comment] 2024-10-18 23:17
Hey @marciorgb, @sjan, and @marciorgb! 👋 

The issue has been resolved. 🎉  We will conduct a separate investigation into the causes and work to prevent such situations in the future. I'll keep this work item on board till Monday as a notification for others who was affected.

**Comment by marciorgb** [comment] 2024-10-20 15:50
Hi @erik-bershel and @sarathrajsrinivasan, tks for the swift response!

**Comment by erik-bershel** [comment] 2024-10-21 16:55
Closing as resolved.

**Closed by erik-bershel** 2024-10-21 16:55 UTC
Labels: bug, OS: macOS, Area: Image administration, bug report
