### ISSUE TITLE
1 [main] unzip (3392) C:\Program Files\Git\usr\bin\unzip.exe: *** fatal error - cygheap base mismatch detected - 0x800000000/0x210351408.

### ISSUE THREAD

**Issue by iocmet** [actions/runner-images#7016] opened 2023-01-31 03:19 UTC
### Description

Im getting error from title when running this step
`- name: Download WinDivert binaries`
`       shell: msys2 {0}`
`      run: |`
`        wget https://reqrypt.org/download/WinDivert-2.2.0-A.zip -O ~/windivert.zip`
`        unzip ~/windivert.zip -d ~/windivert`

Log: https://github.com/iocmet/roblox-dissector-build-fixed/actions/runs/4050331938/jobs/6967620626

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I don't understand how to get it and where is "Set up job"

### Is it regression?

No

### Expected behavior

Successfull build

### Actual behavior

Getting error on one of steps

### Repro steps

I don't know

**Comment by bogdan-damian-bgd** [comment] 2023-01-31 08:40
Hello @iocmet, seems like I cannot reproduce the issue on windows-2022 - take a look ([log](https://github.com/bogdan-damian-bgd/action-tests/actions/runs/4052154111/jobs/6971245469)).

**Comment by bogdan-damian-bgd** [comment] 2023-01-31 14:46
It seems that this issue regarding wget and unzip is non reproducible and I am going to close it now. If you have any questions feel free to reach us.

**Closed by bogdan-damian-bgd** 2023-01-31 14:46 UTC
Labels: OS: Windows, bug report
