### ISSUE TITLE
Windows 19/22: Kootlin installation returning filename as hash and not SHA

### ISSUE THREAD

**Issue by System-Admins-ath** [actions/runner-images#8743] opened 2023-11-06 11:11 UTC
### Description

![image](https://github.com/actions/runner-images/assets/94194707/737d522d-8a32-46e8-8b0f-8292f3b2188b)

This is caused by the following commit:
https://github.com/actions/runner-images/commit/cdbbd8a4455b608075cbf785bf0e969c13681890#diff-dab464f40fa820fd1da84661fb6885c6c1fc088efcf3624f4da514c3fd54b672

### Platforms affected

- [X] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/commit/cdbbd8a4455b608075cbf785bf0e969c13681890#diff-dab464f40fa820fd1da84661fb6885c6c1fc088efcf3624f4da514c3fd54b672

### Is it regression?

win22/20231024.1

### Expected behavior

Should use "15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0" as HASH

### Actual behavior

Returning "kotlincompiler1920zip" as expected HASH

### Repro steps

Build win22 image

**Comment by shamil-mubarakshin** [comment] 2023-11-06 12:20
Hello @System-Admins-ath, thanks for reporting.
We will have a look

**Comment by erik-bershel** [comment] 2023-11-06 13:18
Hey @System-Admins-ath! 
I checked - the builds are going through. I suspect that you are starting a build from a branch the same way as here: https://github.com/actions/runner-images/issues/8732. 
So I'm going to close this item as a duplicate since it's not a bug. Feel free to ask clarifying questions if you have them. Or you can submit a new issue in case you have other concerns.

**Closed by erik-bershel** 2023-11-06 13:18 UTC
Labels: Area: Packages, OS: Windows, bug report
