### ISSUE TITLE
Intermittent SSL issue trying to load iOS certificates

### ISSUE THREAD

**Issue by OliverBrown-Next** [actions/runner-images#10934] opened 2024-11-08 09:44 UTC
### Description

We have recently started getting SSL errors when trying to install iOS certificates. Our workflow related to this has not changed for a long time. It does work sometimes (with the same certificates) so I don't believe there are any problems with the certificates.

This happens on macOS 15 20241106.316 but we only very recently switched to macOS 15 and it happened on macOS 14 too.

```
Starting: Install Dist Apple certificate
==============================================================================
Task         : Install Apple certificate
Description  : Install an Apple certificate required to build on a macOS agent machine
Version      : 2.246.5
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/install-apple-certificate
==============================================================================
/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/EnterpriseDistribution.p12 -nokeys -passin pass:*** | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates
40CBBC50F87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:355:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not find certificate from <stdin>
##[warning]Error parsing certificate. This might be caused by an unsupported algorithm. If you're using old certificate with a new OpenSSL version try to set -legacy flag in opensslPkcsArgs input.
##[error]Error: /usr/local/bin/openssl failed with return code: 1
Finishing: Install Dist Apple certificate


```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [X] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-15
Version: 20241106.316

### Is it regression?

Yes

### Expected behavior

Certificate install correctly.

### Actual behavior

Certificates not installed.

### Repro steps

Attempt to install iOS certificates. I don't know if it something specific to the certificates I'm using though.

**Comment by OliverBrown-Next** [comment] 2024-11-08 10:09
Based on the discussion (and looking at recent runs) I suspect this was intermittent on macOS 14 as the updated agent was rolling out, but is every time on macOS 15.

**Comment by susmitamane** [comment] 2024-11-08 12:31
@OliverBrown-Next We will look into the issue and keep you posted with updates.

**Comment by thisisthekap** [comment] 2024-11-11 12:00
Seems like macos-15 20241106.316 requires us to add `opensslPkcsArgs: -legacy` to the InstallAppleCertificate@2 task. But for older image versions (e.g. macos-15 20241022.244) we must not add this line (otherwise the build fails because the legacy argument seems to be unsupported for that case).

The issue that we are currently facing: macOS-15 20241106.316 does not seem to be rolled out to all hosted agents as of now.

**Comment by thedee** [comment] 2024-11-13 15:52
I get this same error when doing:
vmImage: 'macos-15'
sudo xcode-select -s /Applications/Xcode_16.app/Contents/Developer

**Comment by amit-thapa** [comment] 2024-11-15 12:14
> Seems like macos-15 20241106.316 requires us to add `opensslPkcsArgs: -legacy` to the InstallAppleCertificate@2 task. But for older image versions (e.g. macos-15 20241022.244) we must not add this line (otherwise the build fails because the legacy argument seems to be unsupported for that case).
> 
> The issue that we are currently facing: macOS-15 20241106.316 does not seem to be rolled out to all hosted agents as of now.

This is what is currently happening to me macos-15 20241106.316 works like a charm and macos-15 20241022.244 doesn't.

**Comment by amit-thapa** [comment] 2024-11-15 12:15
> even with opensslPkcsArgs: -legacy this problem happens

Depends which version of macos-15 was assigned to the runner

**Comment by rkops-bd** [comment] 2024-11-15 12:17
> > Seems like macos-15 20241106.316 requires us to add `opensslPkcsArgs: -legacy` to the InstallAppleCertificate@2 task. But for older image versions (e.g. macos-15 20241022.244) we must not add this line (otherwise the build fails because the legacy argument seems to be unsupported for that case).
> > The issue that we are currently facing: macOS-15 20241106.316 does not seem to be rolled out to all hosted agents as of now.
> 
> This is what is currently happening to me macos-15 20241106.316 works like a charm and macos-15 20241022.244 doesn't.

can confirm!

**Comment by brentpi** [comment] 2024-11-15 13:28
I converted my key using the following guide; and the issue is resolved:

https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3

Can confirm that legacy, provider legacy, etc did not work prior to having to convert the key.

**Comment by amit-thapa** [comment] 2024-11-15 16:18
> I converted my key using the following guide; and the issue is resolved:
> 
> https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3
> 
> Can confirm that legacy, provider legacy, etc did not work prior to having to convert the key.

Hi, what did you use to convert it just regular cmd ?

**Comment by sven-s** [comment] 2024-11-15 16:20
I have the same problem also with the image 20241106.316. 

`
/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/Certificate.p12 -nokeys -passin pass:xxxxxx | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space
Error outputting keys and certificates
40FB9549F87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:355:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Could not find certificate from <stdin>
##[warning]Error parsing certificate. This might be caused by an unsupported algorithm. If you're using old certificate with a new OpenSSL version try to set -legacy flag in opensslPkcsArgs input.
##[error]Error: /usr/local/bin/openssl failed with return code: 1
Finishing: Install cert
`

Image 20241022.244 runs fine for me, but how to set the image version as a demand?

**Comment by CPRmichel** [comment] 2024-11-18 12:57
Same error in our pipelines, when is a fix planned?

**Comment by amit-thapa** [comment] 2024-11-18 13:17
> https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3

As already mentioned in one of the comments, use this link https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3 to covert your current p12 file to covert it to support openssl 3. I used git bash to get the commands working as it already has open ssl installed in it. This conversion did work me and I am no longer getting that same error.

**Comment by amit-thapa** [comment] 2024-11-18 13:38
> I have the same problem also with the image 20241106.316.
> 
> `/usr/local/bin/openssl pkcs12 -in /Users/runner/work/_temp/Certificate.p12 -nokeys -passin pass:xxxxxx | /usr/local/bin/openssl x509 -sha1 -noout -fingerprint -subject -dates -nameopt utf8,sep_semi_plus_space Error outputting keys and certificates 40FB9549F87F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:crypto/evp/evp_fetch.c:355:Global default library context, Algorithm (RC2-40-CBC : 0), Properties () Could not find certificate from <stdin> ##[warning]Error parsing certificate. This might be caused by an unsupported algorithm. If you're using old certificate with a new OpenSSL version try to set -legacy flag in opensslPkcsArgs input. ##[error]Error: /usr/local/bin/openssl failed with return code: 1 Finishing: Install cert`
> 
> Image 20241022.244 runs fine for me, but how to set the image version as a demand?
> 
> Edit: I converted the certificate with the link provided and now everything runs fine. @amit-thapa I used just the terminal on my mac, on windows I would try the git bash
> 
> Edit again: While the new certificate is running fine with image version 20241106.316, it fails with image version 20241022.244. There is something really rotten.

That is weird, I did a re-run of the pipelines a couple of times this morning and it used macos-15 20241022.244 both times and it ran fine both times. I have a different issue now but not related to that one. I also removed the following lines below

`opensslPkcsArgs: -legacy`

But I do agree there are lots of inconsistencies and errors throughout macos-15 runner. I have this error now https://github.com/actions/runner-images/issues/10686#issuecomment-2476456471

**Comment by gabsamples6** [comment] 2024-11-19 17:32
Hi 
Is there any news of a fix ? none of the work around work for me.
Thanks

**Comment by erik-bershel** [comment] 2024-11-22 15:28
Hey there! Heads up! 👋 

Unfortunately, an unpleasant situation arose where we could not create the image for technical reasons 😞, but now it fixed. 🥳 The fix will be delivered in the next release cycle, approximately by Wednesday. Currently, about two-fifths of all `macos-15` ADO agents contain `OpenSSL@3`, which causes the error. The remaining agents are not affected by the problem because they contain the outdated but expected by tasks `OpenSSL@1.1.1`.

**Comment by erik-bershel** [comment] 2024-11-26 16:32
Heads up! 👋

New runners deployed. 🥳 Due to the way the deployment works, you may encounter an outdated image (`ADO` `macos-15` only) for the next few hours, the next image is not affected by the issue.

We will leave the announcement of the `OpenSSL@1` removal open and will publish an update there sooner or later. Please subscribe to it if you are interested: https://github.com/actions/runner-images/issues/10817

**Closed by erik-bershel** 2024-11-26 16:32 UTC
Labels: bug, OS: macOS, Area: Common Tools, bug report

**Comment by pmahend1** [comment] 2024-12-10 17:23
> I converted my key using the following guide; and the issue is resolved:
> 
> https://www.docuseal.com/docs/convert-legacy-p12-pfx-files-to-support-openssl-3
> 
> Can confirm that legacy, provider legacy, etc did not work prior to having to convert the key.

Thank you. My P12 was exported very recently on macos-15, I wonder why Apple would generate P12 with older ssl.
