### ISSUE TITLE
Update/Add [App Center CLI]

### ISSUE THREAD

**Issue by pramodKarande** [actions/runner-images#7665] opened 2023-06-03 10:25 UTC
### Tool name

App Center CLI

### Tool license

NA

### Add or update?

- [X] Add
- [ ] Update

### Desired version

2.13.7

### Brief description of tool

Hi team,

App Center CLI tool is missing on macOS-12 images which are available on macOS-12.
I am planning to use a macOS-13 image but my App Center tests are failing with the error "##[error]Unhandled: Could not find the App Center CLI. Install appcenter-cli using npm."

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by shamil-mubarakshin** [comment] 2023-06-05 08:38
Hi @pramodKarande,
Currently there are no plans on adding the tool. Available options are to use macOS 11/12 runners or to install App Center CLI in runtime on macOS 13 runner.

Duplicate of https://github.com/actions/runner-images/issues/7514.

**Closed by shamil-mubarakshin** 2023-06-05 08:39 UTC
Labels: duplicate, Area: Scripting and command line, OS: macOS, feature request

**Comment by pramodKarande** [comment] 2023-06-06 09:32
HI @shamil-mubarakshin ,
Thank you for the info. 
but can you help me with how to install App Center CLI in runtime?
with any sample task snippet

**Comment by shamil-mubarakshin** [comment] 2023-06-06 10:47
@pramodKarande,

You can use following step for Azure DevOps:
```
- bash: |
     npm install -g appcenter-cli
  displayName: 'Install Appcenter CLI'
```
