### ISSUE TITLE
homebrew Python link failure causes all macOS runner actions to fail

### ISSUE THREAD

**Issue by BenWibking** [actions/runner-images#8529] opened 2023-10-11 17:10 UTC
### Description

Running `brew install python` in our macOS runners causes all of the actions to fail:

```
==> Upgrading python3
  3.11.5 -> 3.11.6 

==> Pouring python@3.11--3.11.6.ventura.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/2to3-3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3-3.11
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/idle3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3.11
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/pydoc3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3.11
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3-config
/usr/local/bin/python3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
/usr/local/bin/python3.11-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11-config
==> /usr/local/Cellar/python@3.11/3.11.6/bin/python3.11 -Im ensurepip
==> /usr/local/Cellar/python@3.11/3.11.6/bin/python3.11 -Im pip install -v --no-
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.11/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.11/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.11

gdbm (`dbm.gnu`) is no longer included in this formula, but it is available separately:
  brew install python-gdbm@3.11
`dbm.ndbm` changed database backends in Homebrew Python 3.11.
If you need to read a database from a previous Homebrew Python created via `dbm.ndbm`,
you'll need to read your database using the older version of Homebrew Python and convert to another format.
`dbm` still defaults to `dbm.gnu` when it is installed.

For more information about Homebrew and Python, see: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.11/3.11.6: 3,[28](https://github.com/quokka-astro/quokka/actions/runs/6459693655/job/17612437989?pr=423#step:4:29)4 files, [61](https://github.com/quokka-astro/quokka/actions/runs/6459693655/job/17612437989?pr=423#step:4:62)MB
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner image version: 20231002.1
Link to the failed build: https://github.com/quokka-astro/quokka/actions/runs/6459693655/job/17612437989?pr=423

### Is it regression?

N/A

### Expected behavior

It should install Python successfully.

### Actual behavior

It fails to link Python, which then causes the entire build action to fail.

### Repro steps

Run brew install python3:
  brew install python3
  shell: /bin/bash -e {0}
  env:
    BUILD_TYPE: Release

**Comment by mikhailkoliada** [comment] 2023-10-11 17:13
Duplicate of https://github.com/actions/runner-images/issues/8500

**Closed by mikhailkoliada** 2023-10-11 17:13 UTC
Labels: Area: Apple, OS: macOS, bug report

**Comment by awawa-dev** [comment] 2023-11-10 18:02
Still randomly the problem occurs with the new version:

`
 ==> Upgrading python@3.11
  3.11.5 -> 3.11.6_1 

==> Pouring python@3.11--3.11.6_1.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'
`

**Comment by fwcd** [comment] 2023-11-16 20:08
Same for me: https://github.com/fwcd/d2/actions/runs/6895589453/job/18759868074

**Comment by awawa-dev** [comment] 2023-11-16 23:17
And again: https://github.com/awawa-dev/HyperHDR/actions/runs/6897412769/job/18765513784
Interestingly, re-run the job usually helps.
