### ISSUE TITLE
Ubuntu 22 slow OpenGL software rendering

### ISSUE THREAD

**Issue by quyykk** [actions/runner-images#8371] opened 2023-09-24 20:02 UTC
### Description

On the Ubuntu 22 runner OpenGL software rendering is much slower than it is on Ubuntu 20. See logs:

https://github.com/quyykk/opengl-test/actions/runs/6292077189

The logs show an average decrease of 300fps, which doesn't sound like a lot, but in our use-case the CI run can take up to twice as long as on the Ubuntu 20 runners.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230917.1.0

### Is it regression?

no

### Expected behavior

The Ubuntu 22 runners should be approximately as fast as the 20 runners.

### Actual behavior

The 22 runners are slow at OpenGL rendering.

### Repro steps

1. Run glxgears
2. Compare to 20 runner
3. Notice fewer fps

**Comment by ilia-shipitsin** [comment] 2023-09-25 08:09
we'll have a look.

small question, if you create Ubuntu 22 in Azure, does it work fast or slow ? I mean is your issue related exactly to runners or it applies to Azure in general ?

**Comment by quyykk** [comment] 2023-09-26 21:24
I can't really test on Azure, sory.

**Comment by codybak4** [comment] 2023-09-26 21:33
@ilia-shipitsin #slow

**Comment by ilia-shipitsin** [comment] 2023-09-26 21:59
@quyykk , I see that linux kernel was updated 5.15 --> 6.2

https://github.com/actions/runner-images/compare/ubuntu22/20230911.1...ubuntu22/20230917.1

I suspect it may be related to opengl regression. however, someone has to test

![image](https://github.com/actions/runner-images/assets/125650415/5e0f0ca5-f306-4920-8dea-b30ddc835999)

**Comment by vpolikarpov-akvelon** [comment] 2023-09-27 14:50
Hey @quyykk. Both jobs in the workflow you've linked run on Ubuntu 20.04. It seems like there might be a simple typo, but this detail is quite important.

I've actually tried running your workflow on both versions of Ubuntu runners as well as on vanilla Ubuntu VMs in Azure, and I didn't find any connection between the OS version and performance. Keep in mind that performance can vary from one run to another since different agents handle the jobs, and they may experience different levels of load.

If you have solid evidence suggesting that the OS version makes a difference, please share it with us. We'll be more than happy to conduct a more in-depth investigation.

**Comment by quyykk** [comment] 2023-09-27 15:10
Hey @vpolikarpov-akvelon, I apologize this is pretty embarrassing :sweat_smile: It was indeed a typo.

I've reran the workflow: https://github.com/quyykk/opengl-test/actions/runs/6327793486

Funnily enough I get the same results as when both were on Ubuntu 20. 

> If you have solid evidence suggesting that the OS version makes a difference, please share it with us. We'll be more than happy to conduct a more in-depth investigation.

I don't really have solid evidence, but just anecdotes that the Ubuntu 22 job is consistently always much slower than the Ubuntu 20 job. Maybe it's a coincidence, and the cause is that more people are using Ubuntu 22 so the machines are under more load?

**Comment by vpolikarpov-akvelon** [comment] 2023-10-03 08:57
Hey @quyykk. I've run the workflow multiple times and gathered some data. I couldn't spot any connection between the OS versions and their computing power. The benchmark results tend to vary with each run, but it's not tied to the image version. So, I'm going to close this discussion. If you have any other questions, please don't hesitate to ask here, or you can open a new issue

**Closed by vpolikarpov-akvelon** 2023-10-03 08:57 UTC
Labels: OS: Ubuntu, bug report
