### ISSUE TITLE
Add Xcode 15 

### ISSUE THREAD

**Issue by TheNightmanCodeth** [actions/runner-images#8282] opened 2023-09-13 20:41 UTC
### Tool name

Xcode 15 RC

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

RC

### Approximate size

Around 20 GB with all runtimes I believe

### Brief description of tool

Xcode IDE Release Candidate

### URL for tool's homepage

https://developer.apple.com/download/applications/

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
no
```

**Comment by shamil-mubarakshin** [comment] 2023-09-14 07:22
We will work on adding the tool

**Comment by mikhailkoliada** [comment] 2023-09-14 20:06
Added to the image, will be released in the next week or 2 at most

**Comment by mikhailkoliada** [comment] 2023-09-18 22:42
looks like apple made final 15.0 release, we are going to target this one

**Comment by FrankSolleveld** [comment] 2023-09-19 09:24
> looks like apple made final 15.0 release, we are going to target this one

Does this mean we will have Xcode 15 available this week or next week?

**Comment by erikng** [comment] 2023-09-19 17:02
Is this going to delay the rollout? The build is identical and I really need the github runners updated so I can unblock some releases.

**Comment by dungi** [comment] 2023-09-19 17:04
Same. We are just waiting for the new runners, to release and test our apps.

**Comment by yosi199** [comment] 2023-09-20 07:31
Same here - we are awaiting a release for xcode 15 support and some iOS 17 simulators

**Comment by eseay** [comment] 2023-09-21 12:29
> will be released in the next week or 2 at most

Is there any way we can expedite this timeline? I'd echo the comments of the others on here.

This essentially tells large teams who have put investment into automation using GitHub Actions that if they want to ship iOS 17-supported features on day 1, they should circumvent Actions altogether and do things the old fashioned indie way. That's neither good for the teams and their products nor the platform itself.

**Comment by erikng** [comment] 2023-09-21 14:05
Not to mention that the macOS 13 runner is still "beta" with macOS 14 coming out next week. I still don't understand how GitHub continues to be this far behind. As a developer it's frustrating that GitHub is behind me, a sole developer of products, with larger enterprise customers relying on my ability to maintain the software.

**Comment by mikhailkoliada** [comment] 2023-09-22 10:48
Hi all! We are targeting new macOS 13 rollout next Monday (25th of September) so I'd say it will be fully available to anybody on September 26th

**Comment by drager** [comment] 2023-09-22 11:11
Just tried to upload an app to appstore using xcode 15.0 and macos 13 (worked fine last week):
 >Asset validation failed Invalid Toolchain. Your app was built with an unsupported SDK or version of Xcode. If you plan to submit this build to the App Store, make sure you are using the versions listed in https://help.apple.com/xcode/mac/current/#/devf16aefe3b or later

**Comment by allenhumphreys** [comment] 2023-09-22 15:49
@mikhailkoliada @drager No automated builds to testflight using Xcode 15 until 25 September, the productivity loses caused by using GitHub actions are mounting.

**Comment by mikhailkoliada** [comment] 2023-09-25 12:40
Everything has been deployed now.

**Closed by mikhailkoliada** 2023-09-25 12:40 UTC
Labels: awaiting-deployment, Area: Apple, OS: macOS, feature request

**Comment by pchelnikov** [comment] 2023-09-25 13:39
@will-lumley it will be `Xcode_15.0.app`

<img width="547" alt="Screenshot 2023-09-25 at 15 39 01" src="https://github.com/actions/runner-images/assets/1557594/21cd886c-2844-4488-978b-5cc57a80c8eb">

**Comment by will-lumley** [comment] 2023-09-25 13:41
Thanks @pchelnikov - appreciate it :)

**Comment by rocxteady** [comment] 2023-10-12 14:23
I can't find the Xcode 15. When I print Xcode versions all I get this:
```
Run sudo ls -1 /Applications | grep "Xcode"
Xcode.app
Xcode_13.1.0.app
Xcode_13.1.app
Xcode_13.2.1.app
Xcode_13.2.app
Xcode_13.3.1.app
Xcode_13.3.app
Xcode_13.4.1.app
Xcode_13.4.app
Xcode_14.0.1.app
Xcode_14.0.app
Xcode_14.1.0.app
Xcode_14.1.app
Xcode_14.2.0.app
Xcode_14.2.app
```

**Comment by dungi** [comment] 2023-10-12 15:37
> I can't find the Xcode 15. When I print Xcode versions all I get this:
> 
> ```
> 
> Run sudo ls -1 /Applications | grep "Xcode"
> 
> Xcode.app
> 
> Xcode_13.1.0.app
> 
> Xcode_13.1.app
> 
> Xcode_13.2.1.app
> 
> Xcode_13.2.app
> 
> Xcode_13.3.1.app
> 
> Xcode_13.3.app
> 
> Xcode_13.4.1.app
> 
> Xcode_13.4.app
> 
> Xcode_14.0.1.app
> 
> Xcode_14.0.app
> 
> Xcode_14.1.0.app
> 
> Xcode_14.1.app
> 
> Xcode_14.2.0.app
> 
> Xcode_14.2.app
> 
> ```

You need to run at least a macOS-13 runner or later.

**Comment by rocxteady** [comment] 2023-10-12 15:39
> > I can't find the Xcode 15. When I print Xcode versions all I get this:
> > ```
> > 
> > Run sudo ls -1 /Applications | grep "Xcode"
> > 
> > Xcode.app
> > 
> > Xcode_13.1.0.app
> > 
> > Xcode_13.1.app
> > 
> > Xcode_13.2.1.app
> > 
> > Xcode_13.2.app
> > 
> > Xcode_13.3.1.app
> > 
> > Xcode_13.3.app
> > 
> > Xcode_13.4.1.app
> > 
> > Xcode_13.4.app
> > 
> > Xcode_14.0.1.app
> > 
> > Xcode_14.0.app
> > 
> > Xcode_14.1.0.app
> > 
> > Xcode_14.1.app
> > 
> > Xcode_14.2.0.app
> > 
> > Xcode_14.2.app
> > ```
> 
> You need to run at least a macOS-13 runner or later.

Yea, my bad. I thought macOS-13 is the latest one. Thanks.

**Comment by zippo227** [comment] 2023-12-20 23:28
Here is the code I added to my build action to select macos 13, list the available xcode versions, and in my case select xcode 15.1

`jobs:
  buildiOS:
    runs-on: macos-13
	
    steps:

      #Ensure the xcode version is available		
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      #Select your required version
      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer`
