### ISSUE TITLE
Missing JAVA_HOME with runner macos-13-xlarge in 50% of the scenarios

### ISSUE THREAD

**Issue by SachaTe** [actions/runner-images#8722] opened 2023-11-02 19:26 UTC
### Description

It has been stated in the [macos-13-arm-64 README](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md) that JAVA_HOME should be defined by default and that multiple versions of JAVA are installed. However, despite using the same workflow and runner, the JAVA_HOME definition is missing 50% of the time. 

As an example, let's consider a workflow defined as: 

```
name: Test

on:
  workflow_dispatch:

jobs:
  build-and-test:
    strategy:
      matrix:
        config:
          - name: 'MacOS M1 Runner'
            runner: 'macos-13-xlarge'

      fail-fast: false

    runs-on: ${{ matrix.config.runner }}

    steps:
      - name: Test Print
        run: env
```

When running the same script multiple times, the `env` results are inconsistent, with the JAVA variables missing in certain cases.

 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-13-xlarge

### Is it regression?

No

### Expected behavior

The env variables should be consistent

### Actual behavior

Env variables are not consistent and some are missing

### Repro steps

Run the above workflow and compare env outputs

**Comment by erik-bershel** [comment] 2023-11-02 19:47
Hey @SachaTe! Can I ask you to check the versions of the agents on which you checked the variables? Are the same results returned for all agents or only for a specific one?
Example:
<img width="927" alt="Screenshot 2023-11-02 at 20 46 25" src="https://github.com/actions/runner-images/assets/110455084/d24ee63c-c2dd-4654-b03b-52e674cab4f5">

**Comment by SachaTe** [comment] 2023-11-02 20:09
> Hey @SachaTe! Can I ask you to check the versions of the agents on which you checked the variables? Are the same results returned for all agents or only for a specific one? Example: <img alt="Screenshot 2023-11-02 at 20 46 25" width="927" src="https://user-images.githubusercontent.com/110455084/280110510-d24ee63c-c2dd-4654-b03b-52e674cab4f5.png">

Same version in both;

The one with the bug (i.e. missing JAVA_HOME) has this;
![image](https://github.com/actions/runner-images/assets/9659247/2f2c74c9-3302-4eb1-9014-53d24d4c6015)

The working one with the defined JAVA_HOME has this;
![image](https://github.com/actions/runner-images/assets/9659247/3a8ecce0-c23c-4db4-b6e0-7831e84d14cf)

**Comment by erik-bershel** [comment] 2023-11-02 20:11
@SachaTe not quite, but close. Can you open the upstream tab with the runner version of the image, not the provisioner version?

**Comment by SachaTe** [comment] 2023-11-02 20:16
My mistake, here it is. Unfortunately the repo is private.

The one with the bug (i.e. missing JAVA_HOME) has this;
![image](https://github.com/actions/runner-images/assets/9659247/f4f39ba3-c172-4552-8746-8f50a81ef6ab)

The working one with the defined JAVA_HOME has this;
![Screenshot 2023-11-02 at 4 15 04 PM](https://github.com/actions/runner-images/assets/9659247/3dd7dded-3e80-4b04-84f6-3ff852d6395d)

**Comment by erik-bershel** [comment] 2023-11-02 20:19
@SachaTe no worries, it's fine. I'm glad we found out the reason. Your issue is related to inconsistent images. Will be fixed soon. Might be also tracked here: https://github.com/actions/runner-images/issues/8697

**Comment by erik-bershel** [comment] 2023-11-03 09:02
Hey @SachaTe issue resolved now.

**Closed by erik-bershel** 2023-11-03 09:02 UTC
Labels: Area: Java, OS: macOS, bug report

**Comment by SachaTe** [comment] 2023-11-03 10:07
@erik-bershel I noticed the reference #8697 is still open. Has this issue been closed because it's resolved or because we are tracking it with the other one?

**Comment by erik-bershel** [comment] 2023-11-03 10:47
@SachaTe it's because the root cause of inconsistency is still here with us. So it's decided to keep one related item open to coordinate affected users. Over the next few days we will prevent the problem from recurring by monitoring it daily. When we are sure that we were able to block the source, we will close the main ticket.
