### ISSUE TITLE
Set NuGet's `maxHttpRequestsPerSource` setting to a reasonable value for Linux

### ISSUE THREAD

**Issue by pjquirk** [actions/runner-images#9787] opened 2024-05-03 18:37 UTC
### Description

We've seen at least one occurrence of connection limits being hit during `dotnet restore` on a Linux larger runner, though impact could be larger. According to the [documentation](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#config-section) (see emphasis):

> `maxHttpRequestsPerSource`
> 	Controls the maximum number of parallel requests sent from NuGet to every package source for package dependency resolution and downloads. **The default value on dotnet.exe is `Int32.MaxValue` which is derived from `HttpClientHandler.MaxConnectionsPerServer` property.** This setting has no impact on dotnet.exe for Mac OS because the throttling limit is set to 16 to avoid too many open files error. The default value for NuGet client tools that runs on .NET Framework such as Visual Studio and nuget.exe is 64 on Windows and 1 on Mono. The default value for Packages.config style projects is set to `Environment.ProcessorCount`. Configuring `maxHttpRequestsPerSource` property to a value less than the default could impact NuGet performance.

For larger projects this can result in intermittent connection timeouts as the VM can no longer connect to the pool's load balancer (which is restricted to 1024 connections from an individual VM). Some examples from other software:

- npm defaults to 50: https://docs.npmjs.com/cli/v6/using-npm/config#maxsockets
- Chrome defaults to 6: https://superuser.com/questions/499114/how-to-increase-chromes-connections-per-server

We could just use the same limit as Windows of 64 or Mac of 16, there's no real heuristic for it other than not being "unlimited".

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [x] GitHub Actions - Larger Runners

### Runner images affected

- [x] Ubuntu 20.04
- [x] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

All current Linux images

### Is it regression?

No

### Expected behavior

Limited connections being made from `nuget restore` and `dotnet restore` on Linux, which lessens chance of intermittent connection timeouts.

### Actual behavior

Projects with many packages on the same source can have intermittent connection timeouts.

### Repro steps

N/A

**Comment by erik-bershel** [comment] 2024-05-07 09:31
Hey @pjquirk!
We'll take a look ASAP. Thank you for bringing it into our attention.

**Comment by erik-bershel** [comment] 2024-09-05 13:24
Hey @pjquirk!

It seams that the issue lost the owner. 😿 We did some research and I may say next. Overall, your idea seems sound. 🙇 
But as usual, there are some nuances. If we set limits different from the preset ones, then this will have exactly the same effect on projects with a small and medium number of packages/dependencies. For some, downloads will speed up, for others, they will slow down. We do not really welcome such changes. Especially in this case. 
- Firstly, the problem is easily bypassed on the project side by using your own `nuget.config` file. 
- Secondly, this is the method [recommended](https://learn.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#how-settings-are-applied) by `Microsoft` documentation to avoid configuration inconsistencies. 
- Thirdly, because we stopped providing `Nuget` (as `Mono` dependency) on `Ubuntu-24.04` and I am not sure whether we will return to this practice.

Given all this I am going to close this request.

**Closed by erik-bershel** 2024-09-05 13:24 UTC
Labels: Area: .NET Core, OS: Ubuntu, bug report
