### ISSUE TITLE
~5 second dns lookups after switch to runner version 20230611.1

### ISSUE THREAD

**Issue by ddebrunner** [actions/runner-images#7735] opened 2023-06-16 13:12 UTC
### Description

A couple of days ago our GitHub action runs started picking up runner image  Version: 20230611.1 and we started to see fairly frequent test timeouts which seem to be due to ~5s dns lookups.
```
Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230611.1
```

Further testing shows occasional ~5s dns loops regardless of the target host.

With the older runner 20230517.1 we did not see the same issue.
```
Current runner version: '2.304.0'
Operating System
Runner Image
  Image: ubuntu-22.04
  Version: 20230517.1
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System
  Ubuntu
  22.04.2
  LTS
Runner Image
  Image: ubuntu-22.04
  Version: 20230611.1

### Is it regression?

20230517.1

### Expected behavior

dns lookups less than 5s

### Actual behavior

dns lookups of ~5s

### Repro steps

Create a workflow using curl or other tool to time dns lookups and error if larger than expected.

**Comment by vpolikarpov-akvelon** [comment] 2023-06-16 13:24
Hi, @ddebrunner. Could you share a link to the workflow run where you observe this issue?

**Comment by ddebrunner** [comment] 2023-06-16 13:28
@vpolikarpov-akvelon Here's a workflow (the code in the repo is unrelated, just the workflow matters):

https://github.com/ddebrunner/hello-world-docker-action/actions/runs/5274409991/workflow

It has a number of runs, including (luckily) 20230517.1 and 20230611.1.

Here's one example of a 5s dns lookup:
https://github.com/ddebrunner/hello-world-docker-action/actions/runs/5274409991/jobs/9574667047#step:2:15

```
dnslookup: 5.091109 | connect: 5.093857 | appconnect: 5.167457 | pretransfer: 5.167531 | redirect: 0.000000 | starttransfer: 5.201334 | total: 5.201471 | size: 136
```

We see similar times with other hosts, e.g. `www.google.com`

**Comment by ddebrunner** [comment] 2023-06-16 13:32
@vpolikarpov-akvelon just did run number #8 in that workflow and it has 8 dns lookups > 3s.

(sorry it's a manual process to look for excessive times)

**Comment by vpolikarpov-akvelon** [comment] 2023-06-16 16:19
Well, I was able to reproduce this, but it happens quite rare. As for me it looks like some kind of network issue and it may be related to underlying Azure infrastructure but not image itself. The fact that you started observing this while image rollout have been taking place may be coincident. Let's wait a couple of days and monitor it.

By the way, there is no magical about 5 seconds duration of DNS lookup. According to the [documentation](https://manpages.ubuntu.com/manpages/trusty/man5/resolver.5.html) it's the default value for name lookup timeout in Ubuntu. If you want you can change it like this:
```bash
echo "options timeout:1" | sudo tee -a /etc/resolv.conf
```
But be careful because there is also attempts number limit that is capped to 5 with the default of 2. In case of temporary network issue that lasts more then (timeout * attempts) you will get name resolution error.

**Comment by vpolikarpov-akvelon** [comment] 2023-06-21 12:46
Hey @ddebrunner. Do you still observe this phenomenon?

**Comment by vpolikarpov-akvelon** [comment] 2023-06-23 07:29
Well, I'm closing this thread for now. Feel free to comment here or file another ticket if you still have problems.

**Closed by vpolikarpov-akvelon** 2023-06-23 07:29 UTC
Labels: OS: Ubuntu, investigate, bug report
