### ISSUE TITLE
Chrome crashes when launched with the latest Ubuntu 22.04 image

### ISSUE THREAD

**Issue by ankur22** [actions/runner-images#7797] opened 2023-06-27 08:29 UTC
### Description

We're seeing an issue with our CI pipeline where all the integration tests fail (the ones that spin up and connect to a chrome instance), due to the Chrome instances crashing. We think it's due to the version of the runner image. Locally these tests run and pass. The exact errors we're seeing when Chrome crashes is:

```bash
signal: segmentation fault (core dumped)
```

The last successful CI pipeline ran for this [commit](https://github.com/grafana/xk6-browser/commit/0fc72a91b8ebaeeea92b624c48c2ea6b2b37d7df). In a [commit](https://github.com/grafana/xk6-browser/commit/4fdce45873f1d872e7582ea8271b9f9bda42bbe0) I made to main on the same day about an hour after, the integration tests started to fail for one of the workflows, which you can find [here](https://github.com/grafana/xk6-browser/actions/runs/5276735080/jobs/9549080290).

Since then we've been unable to successfully run our CI pipelines in any of ours branches (until yesterday where we upgraded to a larger instance of the runner which seems to be running a newer version (20230619.1.0)). We've tried to diagnose the issue on our end, looking at trace logs from Chrome, debugging our codebase but nothing seems to resolve the issue.

I took another look at the logs from the first occurrence of this issue in this [workflow](https://github.com/grafana/xk6-browser/actions/runs/5276735080), and noticed that the runner image used in the ones that passed differ from the runner image where the workflow fails:

```diff
 ##[debug]Starting: Set up job
 Current runner version: '2.304.0'
 Operating System
   Ubuntu
   22.04.2
   LTS
 Runner Image
   Image: ubuntu-22.04
+   Version: 20230611.1
-   Version: 20230517.1
+   Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230611.1/images/linux/Ubuntu2204-Readme.md
-   Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230517.1/images/linux/Ubuntu2204-Readme.md
+   Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230611.1
-   Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230517.1
 Runner Image Provisioner
   2.0.236.1
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version: 20230611.1
Link: https://github.com/grafana/xk6-browser/actions/runs/5276735080/jobs/9549080290

### Is it regression?

20230517.1

### Expected behavior

The instance of Chrome doesn't crash with `signal: segmentation fault (core dumped)`.

### Actual behavior

Chrome crashes with `signal: segmentation fault (core dumped)`.

### Repro steps

1. Fork the repo: https://github.com/grafana/xk6-browser from commit 970b5e766192e858f4998391cf484827ff990057.
2. Enable the actions.
3. Create a branch with a minor change in the readme.
4. Push the branch.
5. Create a PR.
6. The pipeline will fail.

**Comment by erik-bershel** [comment] 2023-06-27 09:34
Hey @ankur22 we'll take a look. Thx for the repro steps!

**Comment by vpolikarpov-akvelon** [comment] 2023-06-27 16:49
Hey @ankur22. I tried running your workflow multiple times with different versions of golang and Chrome. Looks like tests fail randomly sometimes without any regularity. Neither I found any correlation between failures and software updates.

Also I see that there was a successful build in you repo today: https://github.com/grafana/xk6-browser/actions/runs/5386308631.

Therefore I assume that it's something about tests itself or about some dependent software but not runner images.

**Comment by ankur22** [comment] 2023-06-28 09:43
Hi @vpolikarpov-akvelon,

Thanks for taking the time to investigate the issue.

> I have taken the time to thoroughly test your workflow using various versions of golang and Chrome. After multiple runs, it appears that the tests fail randomly, without any discernible pattern.

Yes, unfortunately we do have many flaky integration tests which cause the CI pipeline to fail. It was not uncommon for at least one of the four jobs to fail in the test workflow (e.g. this failure [here](https://github.com/grafana/xk6-browser/actions/runs/5268343568/jobs/9542493683)).

What we never witnessed before was all four of the jobs failing in the test workflow.

> I would also like to draw your attention to a successful build in your repository today: [link to the successful build](https://github.com/grafana/xk6-browser/actions/runs/5386308631).

As of 26th of June, we have upgraded our test workflow to work with a larger runner (ubuntu-latest-8-cores). This runner is running the image version `20230619.1.0`. We haven't changed any of the tests, all we have done is work with a different runner.

I have created a new branch and [PR](https://github.com/grafana/xk6-browser/pull/958) off of the latest `main` version where the tests were passing. This new branch does two things:
1. Reverts back to working with the [normal](https://github.com/grafana/xk6-browser/pull/958/commits/2744cb39fbbce991e29b75802082ea9772ab45c2) `ubuntu-latest` runner.
2. [Skip](https://github.com/grafana/xk6-browser/pull/958/commits/ed42db76c0e0583681a47d066b086104547b865b) the known flakey tests.

In both these commits the pipeline has started to [fail](https://github.com/grafana/xk6-browser/actions/runs/5399277485/jobs/9806198728) again where non of the test jobs pass. The reason is that Chrome is crashing with `signal: segmentation fault (core dumped)`. This is running on runner image version `20230619.1.0`.

I suspect if you were to run this PR against the runner image prior to this one (`20230517.1`) the test workflow will pass (or maybe one of the jobs will fail due not skipping a flaky test).

I hope this helps makes things a little clearer as to what the issue we're running into is.

**Comment by ankur22** [comment] 2023-06-29 08:42
Thanks @ilia-shipitsin for debugging the issue.

While I was taking a look at the release notes for this project, i noticed that both the standard and large runners are running the same image (at least they were yesterday) which is `20230619.1.0`. Our pipeline fails when ran on the standard runner but passes on the larger runner. So now i'm confused as to what's going on. Does the image change in anyway when ran on the different sized runners?

**Comment by ilia-shipitsin** [comment] 2023-06-29 08:48
@ankur22 , image propagation is not immediate indeed, and may be confusing.

however, the image version shown under "Set up job" is correct, if you see identical versions, images are identical

![image](https://github.com/actions/runner-images/assets/125650415/1af95e78-d9d3-45d2-9bc3-384d27e818ff)

**Comment by ankur22** [comment] 2023-06-29 09:25
@ilia-shipitsin,

I see, so the images don't differ between the standard and larger runners.

I've just [re-ran the failed jobs](https://github.com/grafana/xk6-browser/actions/runs/5399277485/jobs/9831640216) from yesterday's investigative [PR](https://github.com/grafana/xk6-browser/pull/958), and now the image is version `20230625.1.0`, but it's still failing with the same issue when Chrome is started on the standard runner 😞 Do you still think it's an issue with Chrome and not the standard runner?

**Comment by ilia-shipitsin** [comment] 2023-06-29 09:36
to make sure, please add `/usr/bin/chromium --version` to see whether they differ or not.

as for bug, it was confirmed on chrome side https://bugs.chromium.org/p/chromium/issues/detail?id=1458834
it is claimed to be fixed in newer version

**Comment by ilia-shipitsin** [comment] 2023-06-29 09:38
> @ilia-shipitsin,
> 
> I see, so the images don't differ between the standard and larger runners.
> 
> I've just [re-ran the failed jobs](https://github.com/grafana/xk6-browser/actions/runs/5399277485/jobs/9831640216) from yesterday's investigative [PR](https://github.com/grafana/xk6-browser/pull/958), and now the image is version `20230625.1.0`, but it's still failing with the same issue when Chrome is started on the standard runner 😞 Do you still think it's an issue with Chrome and not the standard runner?

it is 100% on the chrome side since we have segfault and core dump and backtrace.
on the image side we just install chrome/chromium avaialable when image is generated

**Comment by ankur22** [comment] 2023-06-29 09:59
> it was confirmed on chrome side https://bugs.chromium.org/p/chromium/issues/detail?id=1458834
it is claimed to be fixed in newer version

Brilliant, thanks!

> to make sure, please add /usr/bin/chromium --version to see whether they differ or not.

The image version on standard and larger runner is currently different but they're both running chrome version `114.0.5733.0`.

For the time being I'll wait until the runner image updates to Chrome version `114.0.5735.26` or above and retest on the standard runner.

**Comment by ankur22** [comment] 2023-07-07 14:49
I can confirm that once we work with the latest runner and google chrome (not chromium) binary it all works as expected. You can close this ticket. Thanks for all your help!

**Closed** 2023-07-10 10:02 UTC
Labels: awaiting-deployment, OS: Ubuntu, Area: Common Tools, bug report
