### ISSUE TITLE
App Center CLI is missing on macos-13 runners

### ISSUE THREAD

**Issue by JonathanEsposito** [actions/runner-images#7846] opened 2023-07-03 16:43 UTC
### Tool name

App Center CLI

### Tool license

MIT license

### Add or update?

- [X] Add
- [ ] Update

### Desired version

any version

### Brief description of tool

Command-line interface for App Center.

### URL for tool's homepage

https://github.com/microsoft/appcenter-cli

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
It could but it was installed by default on the macos-12 runners..

npm install --location=global appcenter-cli
```

**Comment by shamil-mubarakshin** [comment] 2023-07-04 07:39
Hello @JonathanEsposito,
Currently there are no plans on adding the tool mainly due to maintenance concerns. Available options are to use macOS 11/12 runners or to install App Center CLI in runtime on macOS 13 runner.

Duplicate of https://github.com/actions/runner-images/issues/7514.

**Closed by shamil-mubarakshin** 2023-07-04 07:39 UTC
Labels: duplicate, Area: Scripting and command line, OS: macOS, feature request
