### ISSUE TITLE
Add Xcode 14.3.1 Release Candidate

### ISSUE THREAD

**Issue by guojiubo** [actions/runner-images#7630] opened 2023-05-24 02:56 UTC
### Tool name

Xcode 14.3.1 Release Candidate

### Tool license

Apple, Inc.

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Xcode 14.3.1 Release Candidate

### Approximate size

7.01 GB

### Brief description of tool

Xcode IDE

### URL for tool's homepage

https://developer.apple.com/xcode/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
No.
```

**Comment by guojiubo** [comment] 2023-05-24 02:57
> Runner images where you need the tool

This should be macOS 13, but there's no such option, so I selected macOS 12.

**Comment by hakonk** [comment] 2023-05-30 07:56
@vpolikarpov-akvelon Any timeline for when Xcode 14.3.1 will be added? It contains a crucial fix for Swift Concurrency that I'm sure many consumers of the `macos-13` image rely on.

**Comment by vpolikarpov-akvelon** [comment] 2023-05-30 08:56
@hakonk We are working on updates rollout and have a plan to complete on 5 June, but it subject to change. Sorry for the inconvenience.

**Comment by eseay** [comment] 2023-05-30 18:19
@vpolikarpov-akvelon I can confirm what @hakonk is saying. This Xcode patch release includes a crucial fix to a bug causing launch crashes for all of our users who are on early versions of iOS 15.

**Comment by msrutek-paylocity** [comment] 2023-06-02 08:50
Btw. Xcode 14.3.1 got a stable release build `14E300c` yesterday. (And it's different from the RC1 build `14E300b`).

**Comment by Baza207** [comment] 2023-06-06 20:08
Is there a timeline update here? The PR for this seems to have been approved for a while now (to update the README docs at least) https://github.com/actions/runner-images/pull/7652

**Comment by msaps** [comment] 2023-06-08 07:52
Looks like #7652 was merged but with the RC1 build of Xcode 14.3.1 (14E300b) rather than the stable 14E300c build

**Comment by shamil-mubarakshin** [comment] 2023-06-09 08:20
@guojiubo, @hakonk, @msrutek-paylocity, @msaps, @Baza207,
Image has been updated with Xcode 14.3.1 RC1.  Xcode 14.3.1 Release is expected next week, but subject to a change.
I am closing the issue for now, feel free to reopen in case of any

**Closed by shamil-mubarakshin** 2023-06-09 08:20 UTC
Labels: awaiting-deployment, Area: Apple, OS: macOS, feature request
