### ISSUE TITLE
[Ubuntu 24.04] The futex facility returned an unexpected error code.

### ISSUE THREAD

**Issue by kasper93** [actions/runner-images#9977] opened 2024-06-03 17:43 UTC
### Description

There are futex related errors after upgrading to 24.04. Works fine on 22.04.
```
The futex facility returned an unexpected error code.
Aborted (core dumped)
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
  Image: ubuntu-24.04
  Version: 20240516.4.0
```
https://github.com/mpv-player/mpv/actions/runs/9354665913/job/25748023066

### Is it regression?

Yes, works correctly on ubuntu-22.04 images.

### Expected behavior

Things does not crash.

### Actual behavior

During apt-get install there are futex errors. This also happens after when `wine` is used.
```
The futex facility returned an unexpected error code.
Aborted (core dumped)
```

### Repro steps

You can see workflow in this PR https://github.com/mpv-player/mpv/pull/14169

To reproduce, use the same command:
```
sudo apt-get install -y ccache g++-mingw-w64 gcc-multilib meson nasm ninja-build pkg-config wine wine32
```

**Comment by sergei-pyshnoi** [comment] 2024-06-04 08:55
Closing as duplicate https://github.com/actions/runner-images/issues/9937

**Comment by kasper93** [comment] 2024-06-04 09:08
> Closing as duplicate #9937

Cool, but it is completely different issue. I'm not reporting here `Error: The operation was canceled.`, nor I mentioned it anywhere in my report. I'm reporting futex issue, that has been present since the beginning.

You can refer to this job https://github.com/mpv-player/mpv/actions/runs/9183725744/job/25254900078 if it makes easier.

Note that there are multiple aborts during dpkg configuration step (in Install Dependencies) and finally it crashes when trying to run the binary.

**Comment by lhdjply** [comment] 2024-06-06 06:44
Same problem
https://github.com/lvgl/lvgl/actions/runs/9396173814/job/25876858344?pr=6241

**Comment by mikhailkoliada** [comment] 2024-06-06 17:24
Hello! That is expected as the `CONFIG_COMPAT_32BIT_TIME` kernel option is not enabled on ubuntu24 (and likely will never be), we do not patch kernel ourselves as we take the stock azure's sku, as a result we can not help solving this, unfortunately.

**Closed by mikhailkoliada** 2024-06-06 17:24 UTC
Labels: Area: C/C++, OS: Ubuntu, bug report

**Comment by kasper93** [comment] 2024-06-06 19:55
Thank you for looking into it, I expected it to be kernel configuration difference, as I tested locally and it was working ok. I kinda expected you spin custom kernel, but if it is stock `linux-azure` one, it make sense to keep it as-is. That's means we cannot run the 32-bit build and tests on 24.04, unfortunately. Well, at least 64-bit works if I don't enable multilib.

**Comment by aescolar** [comment] 2024-06-25 09:08
@mikhailkoliada I understand GitHub just takes the Azure VM, but losing support for building and running 32bit binaries is major thing (which also would break our CI in Zephyr). What would it take to have CONFIG_COMPAT_32BIT_TIME enabled back in these images' kernel?

**Comment by aescolar** [comment] 2024-06-27 19:06
I need to ask you to please reopen this ticket, because this ubuntu24.04 image is badly broken in this regard.
The issue may be inherited from the Azure's image but it is still present on the github runners,
so please reopen it and do not close it until it is resolved.

In very short the issue is the following:
The kernel image used in this VM is compiled with CONFIG_COMPAT_32BIT_TIME=n, unlike the vanilla Ubuntu 24.04 kernel images.
But, the glibc:i386 distributed for this image is compiled needing the syscalls enabled with that option.
i.e. **This kernel configuration is just incompatible with the provided glibc**

In detail:
glibc when built for 32bit, if not told which kernel is built for, will decide if the time_t value fits or not in a 32bit time_t, and do either the 32 or 64bit syscall:
https://sourceware.org/git/?p=glibc.git;a=blob;f=nptl/futex-internal.c;h=0bb1dd51f66802521afd71b9246222ed0ea0d862;hb=refs/heads/release/2.39/master#l90
calls with no deadline (NULL) fit in the 32bit version, but as the kernel does not provide this syscall, glibc will just get  a ENOSYS, and glibc will error out aborting the program
```
abort (abort.c:79)
__libc_message_impl.cold (libc_fatal.c:132)
__libc_fatal (libc_fatal.c:141)
futex_fatal_error (futex-internal.h:87)
__futex_abstimed_wait_common (futex-internal.c:119)
```
after printing "The futex facility returned an unexpected error code.\n": 
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/nptl/futex-internal.h;h=0e87e92d15ab92f5069463719a494e97d9800431;hb=refs/heads/release/2.39/master#l87

For reference, this is the current vanilla ubuntu24.04 kernel for x86_64 and this config:
```
$ uname -a
Linux <redacted> 6.8.0-35-generic #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
$ grep CONFIG_COMPAT_32BIT_TIME /boot/config-$(uname -r)
CONFIG_COMPAT_32BIT_TIME=y
```
On the other hand this is the kernel and config for this ubuntu 24.04 image now:
```
Linux <> 6.8.0-1008-azure #8-Ubuntu SMP Fri May 17 10:44:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
# CONFIG_COMPAT_32BIT_TIME is not set
```
Please note that building and running 32bit binaries in a 64bit system is not a weird thing.
It is how one tests that a program works for 32bit targets even though the test machine is a 64bit machine.
It is how we test embedded SW designed for 32bit systems on a 64bit machine.
It is something you need to run your old 32bit libraries for which porting them to 64bits is not reasonable.
These are not bizarre usecases, and it is clearly going to affect lots of major projects as you can see from the issues already linked to this issue.

One can have a perfectly correct 32bit binary in all regards (including no Y2039 issues), but due to the glibc and kernel distributed with this image end up with this error.

**Comment by kasper93** [comment] 2024-06-27 19:32
Maybe we should report this issue to Canonical. I don't think it is GitHub issue specifically. I think it is reasonable to use linux-azure kernel for the cloud applications. It is unfortunate that i386 multilib is not working in this case.

**Comment by aescolar** [comment] 2024-08-14 11:49
The fixes kernel is now on https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240811.1 
=> the issue is resolved in this version.
Thanks
