### ISSUE TITLE
watchman 2023.10.09.00 fails to install on macOS 13 with brew

### ISSUE THREAD

**Issue by MrAlex94** [actions/runner-images#8500] opened 2023-10-09 20:12 UTC
### Description

An updated formula was pushed to brew at https://github.com/Homebrew/homebrew-core/pull/150278, which seems to have broken our workflows.

One of its dependencies, python 3.11, fails to install properly:

```shell
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.11

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.11

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/2to3-3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3-3.11
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/idle3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3.11
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/pydoc3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3.11
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3-config
/usr/local/bin/python3.11 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
/usr/local/bin/python3.11-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11-config
```

A similar issue seems to be here: https://github.com/actions/runner-images/issues/6507

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20231002.1
https://github.com/WaterfoxCo/Waterfox/actions/runs/6459520795/job/17540110440

### Is it regression?

Unsure

### Expected behavior

Brew should be able to install packages without conflicts.

### Actual behavior

Brew fails to install a package, `watchman`.

### Repro steps

`brew install watchman`

**Comment by vpolikarpov-akvelon** [comment] 2023-10-10 05:52
Hi there,

Thanks for bringing this to our attention. It seems like there's a minor hiccup with installing watchman due to a recent Python 3.11 update.

You've got a couple of options to work around this issue:

1. Ignore the Error and Link Manually Later:
   You can simply ignore the error during the initial Homebrew installation process. Let Homebrew finish its job, and once it's done, you can run one of the suggested commands to handle the symlink conflict. You can use:

   ```bash
   brew link --overwrite python@3.11
   ```

   This will resolve the symlink issue.

2. Upgrade Python First:
   If you prefer not to ignore Homebrew's exit code, you can upgrade Python to the latest version manually. You can do this, ignore any exit code errors during the Python upgrade, and then run the command to overwrite the symlinks as mentioned above. After that, proceed with your regular Homebrew installation:

   ```bash
   brew install watchman
   ```

Remember, this isn't a problem with the runner itself. It's just a temporary situation caused by the new Python 3.11 release not being available on the runner yet. Once the updated Python is available on the runner, this issue should resolve itself.

If you have any further questions or run into any more problems, feel free to ask.

**Comment by MrAlex94** [comment] 2023-10-10 09:44
Thanks - yes, brew will continue but unfortunately our scripts error out on any dependency errors (and I'm sure many others will face this as well).

> It's just a temporary situation caused by the new Python 3.11 release not being available on the runner yet.

Do you know when that might happen? Looks like this has been an issue for a while, https://github.com/actions/setup-python/issues/577 and especially since 3.11 was added to runners in https://github.com/actions/runner-images/issues/6459?

Any homebrew package that has python 3.11 as a dependency will fail, from the looks of it.

I do realise homebrew likely shouldn't be taking over `/usr/local` as it's meant for all programs to use, but it's the de facto package manager for macOS.

**Comment by vpolikarpov-akvelon** [comment] 2023-10-10 10:19
> Do you know when that might happen? Looks like this has been an issue for a while, [actions/setup-python#577](https://github.com/actions/setup-python/issues/577) and especially since 3.11 was added to runners in #6459?

I meant, version 3.11.6 have been released a couple of days ago and it didn't manage to the runner yet. Unfortunately, it's happening every time Python 3.11 updates and we don't have any permanent solution for that. Please use workaround till runner includes Python 3.11.5, and we will try to roll update out as soon as possible.

**Comment by mikhailkoliada** [comment] 2023-10-26 08:56
Should be fixed now!

**Closed by mikhailkoliada** 2023-10-26 08:56 UTC
Labels: awaiting-deployment, Area: Python, OS: macOS, bug report
