### ISSUE TITLE
Master.Dacpac missing content.

### ISSUE THREAD

**Issue by PawelWelsbergAtBerryWorld** [actions/runner-images#7224] opened 2023-03-02 14:00 UTC
### Description

Building sqlproj (Microsoft Azure SQL Database) with a reference to the master database (master.dacpac) fails if there are some sys elements used.
The problem is with a new version of master.dacpac. It no longer references many of sys schema stored procedures. It is one third of the previous size (22k vs. 67k). The new master.dacpac file if you open (unzip/view model.xml) it has:
`<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.4" DspName="Microsoft.Data.Tools.Schema.Sql.SqlAzureDatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">`

Versus what it used to be:
`<DataSchemaModel FileFormatVersion="1.2" SchemaVersion="2.9" DspName="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider" CollationLcid="1033" CollationCaseSensitive="False" xmlns="http://schemas.microsoft.com/sqlserver/dac/Serialization/2012/02">`

Note: new file has lower SchemaVersion.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win22%2F20230226.1

### Is it regression?

https://github.com/actions/runner-images/releases/tag/win22%2F20230219.1

### Expected behavior

sys references in the SqlProj file using master.dacpac reference (Microsoft Azure SQL Database) should be resolved

### Actual behavior

References are not resolved. Errors thrown:
Procedure: ... has an unresolved reference to object [sys].[sp_xml_preparedocument]

### Repro steps

1. Create an SQL Project.
2. Make sure it is Microsoft Azure SQL Database target platform
3. Add Database Reference to System database (keep defaults in the window)
4. Add a simple sp to it accessing sys. For example:
CREATE PROCEDURE [dbo].[Procedure1]
AS
	SELECT * from [sys].[dm_db_stats_properties];
RETURN 0
5. Try to build it in the pipeline.

**Comment by LoGA80** [comment] 2023-03-02 17:14
I believe the errors I receive are due to the same root cause:

`2023-03-02T12:40:00.2981340Z ##[error]*** An error occurred during deployment plan generation. Deployment cannot continue.
2023-03-02T12:40:00.3157394Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_page_info]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3201320Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_page_info].[object_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3250935Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[last_updated]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3573102Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3720811Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[rows_sampled]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3763151Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[steps]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3833530Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[unfiltered_rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3895702Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[modification_counter]' could not be resolved. No such element exists.
2023-03-02T12:40:00.3935678Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4003742Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[last_updated]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4068542Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4145591Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[rows_sampled]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4211797Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[steps]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4293720Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[unfiltered_rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4374656Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[dm_db_stats_properties].[modification_counter]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4444136Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4511068Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4594179Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[object_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4679003Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[index_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4769613Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[allocation_units]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4837139Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[allocation_units].[container_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.4927447Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[partition_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5017696Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5110261Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[allocation_units].[total_pages]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5205934Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[allocation_units].[used_pages]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5306542Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5397230Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5464339Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[object_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5555595Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[index_id]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5648930Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[partitions].[rows]' could not be resolved. No such element exists.
2023-03-02T12:40:00.5715297Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[sp_set_session_context]' could not be resolved. No such element exists.
2023-03-02T12:40:00.6494722Z ##[error]Error SQL0: The reference to the external element with the name '[master]|[sys].[sp_set_session_context]' could not be resolved. No such element exists.
2023-03-02T12:40:00.6598679Z ##[error]System.Management.Automation.RemoteException
2023-03-02T12:40:00.6625319Z ##[error]An error occurred while adding references.  Deployment cannot continue.`

It started to come today.

2023-03-02T12:37:53.4009591Z Image: windows-2022
2023-03-02T12:37:53.4009757Z Version: 20230226.1

When one of my release pipelines was lucky to use the previous version, it ran successfully.

2023-03-02T10:55:21.1112066Z Image: windows-2022
2023-03-02T10:55:21.1112289Z Version: 20230219.1

**Comment by rdsimes** [comment] 2023-03-03 01:20
@PawelWelsbergAtBerryWorld 
Have you found any workarounds ? We've been unable to satisfactorily work around this and had most of our pipelines failing for the past 36 hours

**Comment by mikhailkoliada** [comment] 2023-03-03 07:14
Marking as a duplicate of #7219 as origin is the same

**Comment by PawelWelsbergAtBerryWorld** [comment] 2023-03-03 07:14
As a workaround can copy working master.dacpac file localy:
1. Open in Visual Studio that can build the project (may need to downgrade Visual Studio to 17.4.5 version).
2. Check the full path of the file used (in properties of the "master" reference)
3. Copy the file to the project folder
4. Add Database Reference ...
5. Use Data-tier Application (.dacpac) with the file.

**Closed by mikhailkoliada** 2023-03-03 07:14 UTC
Labels: needs triage, bug report
