### ISSUE TITLE
MacOS: mDNSResponder is turned off during CI and it's failing to make requests to localhost

### ISSUE THREAD

**Issue by damusix** [actions/runner-images#9628] opened 2024-04-03 22:28 UTC
### Description

See https://github.com/hapijs/hapi/actions/runs/8545413008

This issue is replicable on a local mac that doesn't have any sharing features enabled (file sharing, screen sharing, display mirroring, etc; anything that enables mdnsresponder). I have been able to successfully replicate the issue on my M2 on the latest MacOS version (14)

See https://discussions.apple.com/thread/7707202?sortBy=best for reference

This doesn't allow any tests that use the `ifconfig` given network for running a local server. For example, I tried opening a server using the node builtin`http` and the library `@hapi/hapi` and was unable to access any routes via browser or curl to local DNS.

It seems this is a functioning workaround: https://github.com/actions/runner-images/issues/9346#issuecomment-1957461928 but it seems silly to have to patch what should be an inherent feature of an OS. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

See https://github.com/hapijs/hapi/actions/runs/8545413008

### Is it regression?

works in macos-11 (see https://github.com/hapijs/.github/commit/6c1069a71572334379e643c6cb6242b6916cc83e)

### Expected behavior

to be able to bind programs to `$(hostname -f)` and  `$(hostname -s)`

### Actual behavior

requests never resolve

### Repro steps

Run [@hapijs/hapi ](https://github.com/hapijs/hapi) tests in `mac-latest`

**Comment by Alexey-Ayupov** [comment] 2024-04-05 11:09
Hello @damusix, we understand that the problem exists, however if you run `sudo launchctl list com.apple.mDNSResponder.reloaded` you will see that mDNSResponder service is up and running.
We will continue to investigate the issue, please check progress on the #8649 issue.

Duplicate of #8649

**Closed by Alexey-Ayupov** 2024-04-05 11:09 UTC
Labels: duplicate, Area: Apple, OS: macOS, bug report
