### ISSUE TITLE
ubuntu22.04 install llvm faild

### ISSUE THREAD

**Issue by qicosmos** [actions/runner-images#9735] opened 2024-04-24 09:34 UTC
### Description

https://github.com/qicosmos/cinatra/actions/runs/8813963128/job/24192836432?pr=563

```
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
Repository: 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main'
Description:
Archive for codename: llvm-toolchain-jammy-17 components: main
More info: http://apt.llvm.org/jammy/
Adding repository.
Adding deb entry to /etc/apt/sources.list.d/archive_uri-http_apt_llvm_org_jammy_-jammy.list
Adding disabled deb-src entry to /etc/apt/sources.list.d/archive_uri-http_apt_llvm_org_jammy_-jammy.list
+ apt-get update
Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:7 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:8 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Hit:6 https://apt.llvm.org/jammy llvm-toolchain-jammy-17 InRelease
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Runner Image
  Image: ubuntu-22.04
  Version: 20240422.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240422.1/images/ubuntu/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240422.1
```
https://github.com/qicosmos/cinatra/actions/runs/8813963128/job/24192836432?pr=563

### Is it regression?

https://github.com/qicosmos/cinatra/actions/runs/8794320506/job/24133571446

### Expected behavior

install clang-17 and clang++-17 ok.

### Actual behavior

install failed

### Repro steps

git action script:

```
      - name: Install newer Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh 17
```

**Comment by mikhailkoliada** [comment] 2024-04-24 09:37
Duplicate of https://github.com/actions/runner-images/issues/9735

**Closed by mikhailkoliada** 2024-04-24 09:37 UTC
Labels: bug report

**Comment by qicosmos** [comment] 2024-04-24 09:38
How to solve the problem? just happed today
