### ISSUE TITLE
Update CMake

### ISSUE THREAD

**Issue by zhaoqiu-china** [actions/runner-images#6670] opened 2022-12-01 05:41 UTC
### Tool name

CMake

### Tool license

BSD 3-clause

### Add or update?

- [ ] Add
- [X] Update

### Desired version

3.25.1

### Brief description of tool

In CMake 3.25.0, setting `CMAKE_TRY_COMPILE_CONFIGURATION` to a value other than "Debug" causes the `COPY_FILE` feature of `try_compile` to break. related issue https://gitlab.kitware.com/cmake/cmake/-/issues/24180

In particular, OpenCV 4.6.0 fail to build when use 'CMake 3.25.0'.
https://github.com/opencv/opencv/issues/22784

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

**Comment by mikhailkoliada** [comment] 2022-12-01 07:34
Duplicate of #6627

**Closed by mikhailkoliada** 2022-12-01 07:34 UTC
Labels: needs triage, feature request
