### ISSUE TITLE
Error when running Windows 2019 build

### ISSUE THREAD

**Issue by connorfanning96** [actions/runner-images#7434] opened 2023-04-13 05:41 UTC
### Description

Windows 2019 build looks to run a database test for 'mongo.exe' which appears to be removed in the latest version in the image (5.0.16). It was still present in 5.0.15 but appears to no longer be there causing the test to fail and the rest of the packer  to exit. 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

unable to produce 

### Is it regression?

c60c6b67ab2ad0fe76347ebbcd512b87917ef51a 

### Expected behavior

The tests succeed and the image update completes. 

### Actual behavior

Test is failing to run successfully causing an exit. 
 azure-arm.managed-image: Running tests from 'C:\image\Tests\Databases.Tests.ps1'
    azure-arm.managed-image: Describing MongoDB
    azure-arm.managed-image:  Context Version
    azure-arm.managed-image:    [-] mongo 753ms (518ms|235ms)
    azure-arm.managed-image:     CommandNotFoundException: The term 'mongo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    azure-arm.managed-image:     at <ScriptBlock>, C:\image\Tests\Databases.Tests.ps1:8
    azure-arm.managed-image:    [+] mongod 252ms (250ms|1ms)
    azure-arm.managed-image:  Context Service
    azure-arm.managed-image:    [+] mongodb service is stopped 222ms (216ms|6ms)
    azure-arm.managed-image:    [+] mongodb service is disabled 48ms (47ms|1ms)
    azure-arm.managed-image: Tests completed in 4.46s
    azure-arm.managed-image: Tests Passed: 3, Failed: 1, Skipped: 0 NotRun: 12
    azure-arm.managed-image:
    azure-arm.managed-image:
    azure-arm.managed-image: Containers            : {[-] C:\image\Tests\Databases.Tests.ps1}
==> azure-arm.managed-image: Test run has failed

### Repro steps

Run image build pipeline.

**Comment by mikhailkoliada** [comment] 2023-04-13 08:21
Duplicate of https://github.com/actions/runner-images/issues/7435

**Closed by mikhailkoliada** 2023-04-13 08:21 UTC
Labels: OS: Windows, bug report
