### ISSUE TITLE
Apt update fails on Runner ubuntu-latest-4-cores

### ISSUE THREAD

**Issue by LarsTheiss** [actions/runner-images#9737] opened 2024-04-24 11:05 UTC
### Description

```
  test-make-setup:
    runs-on: ubuntu-latest-4-cores
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y ...
```

```
Run sudo apt-get update
Get:[1](https://github.com/***#step:2:1) file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:[6](https://github.com/***#step:2:7) https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.315.0'
Runner name: 'ubuntu-latest-4-cores_fd843dc[2](https://github.com/***#step:1:2)3fbe'
Runner group name: 'Default Larger Runners'

### Is it regression?

ubuntu-latest-4-cores_01730b073c74

### Expected behavior

successful  apt update with version Runner name: 'ubuntu-latest-4-cores_01730b073c74'

### Actual behavior

apt update fails with signing issue

### Repro steps

run action with runner  ubuntu-latest-4-cores and call sudo apt-get update in a step

**Comment by mikhailkoliada** [comment] 2024-04-24 11:06
Duplicate of https://github.com/actions/runner-images/issues/9733

**Closed by mikhailkoliada** 2024-04-24 11:06 UTC
Labels: bug report
