### ISSUE TITLE
ChromeDriver started failing with Fontconfig error: No writable cache directories with latest release

### ISSUE THREAD

**Issue by j15e** [actions/runner-images#9884] opened 2024-05-17 14:58 UTC
### Description

Our frontend build using ChromeDriver on a larger runner started failing today with the error below.

It looks like some Chrome default settings files are missing or something. Is anyone else facing this problem?

I am not totally sure that the ChromeDriver font error is the underlying problem; it could be something that when the timeout occurs, it outputs the latest logs from Chrome, but this is only a warning.

```
2024-05-17T14:36:43.8527939Z         message: >
2024-05-17T14:36:43.8528573Z             Error: Browser timeout exceeded: 10s
2024-05-17T14:36:43.8529770Z             Error while executing test: Integration | Component | form/datetime: it renders correctly
2024-05-17T14:36:43.8530850Z             Stderr: 
2024-05-17T14:36:43.8531523Z              Fontconfig error: No writable cache directories
2024-05-17T14:36:43.8533370Z             [0517/143502.052627:INFO:config_dir_policy_loader.cc(118)] Skipping mandatory platform policies because no policy file was found at: /etc/opt/chrome/policies/managed
2024-05-17T14:36:43.8536308Z             [0517/143502.058563:INFO:config_dir_policy_loader.cc(118)] Skipping recommended platform policies because no policy file was found at: /etc/opt/chrome/policies/recommended
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

2024-05-17T14:06:33.2447324Z Current runner version: '2.316.1'
2024-05-17T14:06:33.2453251Z Runner name: 'Didacte-Large-1_624d438d4a38'
2024-05-17T14:06:33.2454091Z Runner group name: 'didacte-large-runners'
2024-05-17T14:06:33.2454910Z Machine name: 'runner'
2024-05-17T14:06:33.2471015Z ##[group]Operating System
2024-05-17T14:06:33.2471547Z Ubuntu
2024-05-17T14:06:33.2471879Z 22.04.4
2024-05-17T14:06:33.2472290Z LTS
2024-05-17T14:06:33.2472580Z ##[endgroup]
2024-05-17T14:06:33.2472948Z ##[group]Runner Image
2024-05-17T14:06:33.2473461Z Image: ubuntu-22.04
2024-05-17T14:06:33.2473853Z Version: 20240516.1.0
2024-05-17T14:06:33.2474812Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240516.1/images/ubuntu/Ubuntu2204-Readme.md
2024-05-17T14:06:33.2476301Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240516.1

https://github.com/hooktstudios/didacte/actions/runs/9129534188/job/25104319472

### Is it regression?

Yes

### Expected behavior

No error

### Actual behavior

Fontconfig error: No writable cache directories

### Repro steps

Every build we run since using the 2.316.1 release.

**Comment by erik-bershel** [comment] 2024-05-17 17:41
Hey @j15e!

Seems as a new version regression as for me. We may try investigate it. Before it we need you to publish some repro steps for us to work on since we have no access to the private repositories. It would be great if you could test the issue with the same browser and a similar OS if you are unable to provide reprosteps. Then we will at least understand where the problem is - in the image or in the browser/browser driver.

**Comment by j15e** [comment] 2024-05-17 19:03
Hi, thanks for the quick feedback. It will be hard to reproduce everything we have in our private repo, could you get access to it if I open a support ticket? We have an Enterprise account.

**Comment by erik-bershel** [comment] 2024-05-17 19:51
Nope. We cannot access users' private repos anyway.

**Comment by erik-bershel** [comment] 2024-06-03 10:38
Hey @j15e!
I'm forced to close this item since there are no repro steps. Feel free to ping us if some available. I may add also that we cannot rollback Chrome and Chrome Driver anyway since it's a matter of security. Best approach here is to work with Chrome developers to resolve a reason on one of the sides.

**Closed by erik-bershel** 2024-06-03 10:38 UTC
Labels: Area: Testing and code coverage, OS: Ubuntu, investigate, bug report
