### ISSUE TITLE
Unable to make builds for Unity on arm64 machines

### ISSUE THREAD

**Issue by StephenHodgson** [actions/runner-images#10105] opened 2024-06-21 16:33 UTC
### Description

Previously I had been able to make automated builds on `macos-14-arm64` but recent changes seem to have broken this. 

I get an error about FMOD trying to initialize but then failing the build after some timeout.
I am able to make automated builds on my self hosted runner with the same tooling as the vanilla GitHub hosted runner.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.317.0'
Operating System
  macOS
  14.5
Runner Image
  Image: macos-14-arm64
  Version: 20240611.1
  Included Software: https://github.com/actions/runner-images/blob/macos-14-arm64/20240611.1/images/macos/macos-14-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240611.1
Runner Image Provisioner
  2.0.370.1+55cddbb57f254a369b6e7b3b508cebdbee5d24be

### Is it regression?

yes

### Expected behavior

I can perform automated building with Unity Game Engine and Github Actions Runners

### Actual behavior

```
FMOD failed to initialize the output device.: "A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted. " (57)
Forced to initialize FMOD to to the device driver's system output rate 44100, this may impact performance and/or give inconsistent experiences compared to selected sample rate 48000
FMOD failed to initialize the output device.: "A call to a standard soundcard driver failed, which could possibly mean a bug in the driver or resources were missing or exhausted. " (57)
FMOD initialized on nosound output
```

### Repro steps

https://github.com/RageAgainstThePixel/unity-build/pull/8

**Comment by erik-bershel** [comment] 2024-06-25 15:14
Hey @StephenHodgson!

Sorry to see that something went wrong. 😞 This item requires dipper investigation and will take some time to handle the exact root cause. I see that your repo is public so we'll use it as a source for the investigation.

**Comment by vinaynaikr08** [comment] 2024-07-11 13:05
We are unable to reproduce the issue due to the lack of a Unity License. It appears that there have been changes in the backend, specifically with the sound driver on the host. Unfortunately, there is little we can do about this at the moment. Therefore, we will close the issue for now.

If you have any other questions feel free to reach us.

**Closed by vinaynaikr08** 2024-07-11 13:05 UTC
Labels: Area: Packages, OS: macOS, Area: Image administration, investigate, bug report

**Comment by StephenHodgson** [comment] 2024-07-11 13:31
Well that's disappointing.

You don't need a license to test this with my action workflow I publish. Just use personal.

**Comment by jakeobrien** [comment] 2024-09-19 17:29
@StephenHodgson We are having a similar issue. Feels like there might have been a change in how audio drivers work in MacOS that is making them unavailable to unity's built-in audio engine - which uses fmod. We also can build locally but cannot on CI, possibly because Unity is running in headless (-nographics) mode? 

Have you had any luck resolving?

**Comment by StephenHodgson** [comment] 2024-09-19 21:13
@jakeobrien I actually [ended opening another issue](https://github.com/actions/runner-images/issues/10219) and it is currently tracked there
