### ISSUE TITLE
Signature thumbprint do not match expected

### ISSUE THREAD

**Issue by philcart** [actions/runner-images#9188] opened 2024-01-17 23:55 UTC
### Description

==> azure-arm.image: Waiting for machine to restart...
==> azure-arm.image: A system shutdown is in progress.(1115)
    azure-arm.image: pkrvms4osbkppd6 restarted.
==> azure-arm.image: #< CLIXML
==> azure-arm.image: <Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
==> azure-arm.image: Machine successfully restarted, moving on
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: C:/Dev/runner-images/images/windows/templates/../scripts/build/Install-VisualStudio.ps1
    azure-arm.image: Downloading Bootstrapper ...
    azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 1 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]
==> azure-arm.image: Step "StepProvision" failed
==> azure-arm.image: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

main branch cloned at
https://github.com/actions/runner-images/commit/192a94d178e6df98256745c2bb8ef99998aa95fd

### Is it regression?

N/A

### Expected behavior

New Windows2022 runner image built

### Actual behavior

Errors with the above message

### Repro steps

1. Start Windows PowerShell as Administrator
2. Run build as per docs located at https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md
3. Run command using an existing Azure Resource Group ==> **GenerateResourcesAndImage -SubscriptionId "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -ResourceGroupName "my-resource-group" -AzureLocation "Australia Southeast" -ImageType "Windows2022"**

**Comment by sergei-pyshnoi** [comment] 2024-01-18 08:28
Hello @philcart . Thanks for your report. We will merge fix as as possible.

**Comment by mikhailkoliada** [comment] 2024-01-18 09:49
Should be fixed in `main`!

**Closed by mikhailkoliada** 2024-01-18 09:49 UTC
Labels: OS: Windows, Area: Image administration, bug report

**Comment by tgw-lgu** [comment] 2024-02-01 09:35
Same issue again on latest win22 release branch "releases/win22/20240128":
![image](https://github.com/actions/runner-images/assets/99336523/55b08180-7eb2-4d97-95cc-d12edc6f70ec)
I saw, that the image thumbprint was updated 19h ago on main in "images/windows/toolsets/toolset-2022.json".
Can you please merge the change to the release branch. Thank you.

**Comment by lightray55** [comment] 2024-03-13 02:45
I can confirm that I've hit this issue again today:
```==> azure-arm.image: Machine successfully restarted, moving on
==> azure-arm.image: Provisioning with Powershell...
==> azure-arm.image: Provisioning with powershell script: C:/a/1/s/runner-images/images/windows/templates/../scripts/build/Install-VisualStudio.ps1
    azure-arm.image: Downloading Bootstrapper ...
    azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 1 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
...
==> Some builds didn't complete successfully and had errors:
--> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0 3010]
```
I would like to echo the above comment requesting a longer term solution for this rather than a manual update.

**Comment by piotrgradzinski** [comment] 2024-03-13 10:48
I'm experiencing the same problem and I've updated the signature for VS. #9502

**Comment by achechen** [comment] 2024-03-13 12:02
I would also like to see a long term solution to signatures not matching issue. This happens too often and wastes a lot of time. It is really annoying to wait 2-3 hours for a build and to see that it failed because the signature of a single tool has changed.

**Comment by LokeshNagireddy** [comment] 2024-05-03 10:50
i got a similar issue for AzureCLI from few days.

2024-05-02T21:04:29.1761743Z ==> azure-arm.image: Provisioning with powershell script: /agent/_work/3/s/runner-images/images/windows/templates/../scripts/build/Install-AzureCli.ps1
2024-05-02T21:04:41.9840385Z     azure-arm.image: Install the latest Azure CLI release
2024-05-02T21:04:41.9845413Z     azure-arm.image: Downloading package from https://aka.ms/installazurecliwindowsx64 to C:\Users\packer\AppData\Local\Temp\bj43jtiz.msi...
2024-05-02T21:04:50.8294601Z     azure-arm.image: Package downloaded in 8.81 seconds
2024-05-02T21:04:52.6240392Z ==> azure-arm.image: **Signature thumbprint do not match expected.**
2024-05-02T21:04:52.6243750Z ==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
2024-05-02T21:04:52.6248599Z ==> azure-arm.image: +         **throw "Signature thumbprint do not match expected."**
2024-05-02T21:04:52.6252653Z ==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2024-05-02T21:04:52.6256881Z ==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
2024-05-02T21:04:52.6260757Z ==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

------------------------------------------------

Can you please upgrade the signature and let me know.
i look forwad for your response.

Thank you,
Regards,
Lokesh N

**Comment by devneutz** [comment] 2024-07-17 14:33
Same here again
