### ISSUE TITLE
Update [set cmd as the Default shell for windows]

### ISSUE THREAD

**Issue by Streamlet** [actions/runner-images#7963] opened 2023-07-23 15:39 UTC
### Tool name

cmd as the Default shel

### Tool license

with system

### Add or update?

- [ ] Add
- [X] Update

### Desired version

with system

### Brief description of tool

Powershell is powerfull but not so widely used like cmd.exe .

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

**Comment by sergei-pyshnoi** [comment] 2023-07-24 07:01
Hello @Streamlet . Using PowerShell is by design by default. Also changing it, can impact large amount of other users that using default shell in their workflow. You can specify shell in your workflow like this:
```
...
steps:
  - name: Display the path
    run: echo $PATH
    shell: bash
...

```
I am closing this issue for now, but if you have additional questions feel free to ask.

**Closed by sergei-pyshnoi** 2023-07-24 07:01 UTC
Labels: needs triage, feature request

**Comment by Streamlet** [comment] 2023-07-24 15:05
I know how to set default shell in my workflow.

But powershell is really not widely used in the world.
I think Github should follow the most developers' choice. (Although Microsoft supports Github)
