### ISSUE TITLE
Mono installation issues on Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by ross-bohr** [actions/runner-images#9877] opened 2024-05-17 09:26 UTC
### Description

Running the VM image build for Ubuntu 20.04 and 22.04 has installation issues with Mono (installation is successful on Ubuntu 24.04.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Azure DevOps Agent version: 3.238.0

### Is it regression?

It probably is, due to change in mono installation location on their end

### Expected behavior

Mono should be able to install successfully on Ubuntu 20.04 and 22.04

### Actual behavior

[Ubuntu20.04.txt](https://github.com/actions/runner-images/files/15346779/Ubuntu20.04.txt)

### Repro steps

1. Run build for Ubuntu 20.04 or 22.04
2. You'll get the error as on the attached file

**Comment by erik-bershel** [comment] 2024-05-17 10:05
Hey @ross-bohr!
Our nightly build were successful: [ubuntu-20.04](https://dev.azure.com/github/runner-images/_build/results?buildId=135754), [ubuntu-22.04](https://dev.azure.com/github/runner-images/_build/results?buildId=135753). I'll run it again just in case ([ubuntu-20.04](https://dev.azure.com/github/runner-images/_build/results?buildId=135760), [ubuntu-22.04](https://dev.azure.com/github/runner-images/_build/results?buildId=135761&view=results)).
Seems to be transitive or related to your Azure org network/firewall settings since the main issue is:
``` Connection failed [IP: 13.107.246.40 443] ```

**Comment by erik-bershel** [comment] 2024-05-17 10:07
Also regarding `ubuntu-24.04` comment: 
> installation is successful on Ubuntu 24.04

There is no Mono on `ubuntu-24.04`, so I almost sure that there is a connection issue on your side.

**Comment by erik-bershel** [comment] 2024-05-17 10:50
Works fine:
```
    azure-arm.build_image: Get:170 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 msbuild-sdkresolver all 1:16.10.1+xamarinxplat.2021.05.26.14.00-0xamarin2+ubuntu2004b1 [257 kB]
    azure-arm.build_image: Get:171 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 msbuild-libhostfxr amd64 3.0.0.2019.04.16.02.13-0xamarin4+ubuntu2004b1 [166 kB]
    azure-arm.build_image: Get:172 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 msbuild all 1:16.10.1+xamarinxplat.2021.05.26.14.00-0xamarin2+ubuntu2004b1 [8980 kB]
    azure-arm.build_image: Get:173 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 mono-complete amd64 6.12.0.200-0xamarin2+ubuntu2004b1 [32.6 kB]
    azure-arm.build_image: Get:174 https://download.mono-project.com/repo/ubuntu stable-focal/main amd64 nuget all 6.6.1.2.bin-0xamarin3+ubuntu2004b1 [1623 kB]
    azure-arm.build_image: Preconfiguring packages ...
```
Closing item as not reproducible. Please, check your org network and security configs.

**Closed by erik-bershel** 2024-05-17 10:50 UTC
Labels: OS: Ubuntu, Area: Image administration, bug report
