### ISSUE TITLE
Broken C++ library in macOS runner

### ISSUE THREAD

**Issue by CendioOssman** [actions/runner-images#7164] opened 2023-02-21 10:02 UTC
### Description

Including `<map>` for C++ on macOS results in this error in the C++ headers:

```
...
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/chrono:1583:12: error: reference to unresolved using declaration
   static time_t     to_time_t  (const time_point& __t) _NOEXCEPT;
          ^
/Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/ctime:79:1: note: using declaration annotated with 'using_if_exists' here
using ::time_t _LIBCPP_USING_IF_EXISTS;
```

This error started when the macOS runner was updated from 20230205.1 to 20230214.2. The build tools seem to be the same in both images, though, which makes this very surprising.

I cannot reproduce this locally with the current version of Xcode, which is why this seems to be a GitHub specific bug.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230214.2

https://github.com/TigerVNC/tigervnc/actions/runs/4211716928/jobs/7310247105

### Is it regression?

Yes

### Expected behavior

Code should compile fine, like it did with image 20230205.1:

### Actual behavior

Crashes as described above.

### Repro steps

Unclear. I have not tried to produce a minimal test case.

Looking at the crashing file, though, it seems like this should be sufficient to trigger the problem:

```c
#include <string.h>
#include <time.h>
#include <map>
```

**Comment by CendioOssman** [comment] 2023-02-21 10:03
Note that I first reported this to GitHub support, as ticket #2023887.

**Comment by bogdan-damian-bgd** [comment] 2023-02-21 18:16
Hi @CendioOssman, seems I cannot reproduce the issue with using just simple repro code [example](https://github.com/bogdan-damian-bgd/action-tests/blob/main/test-macos-cpp-01.cpp) (workflow [output](https://github.com/bogdan-damian-bgd/action-tests/actions/runs/4235497450/jobs/7359190239#step:3:1)). 
Could you provide some more clear repro steps?

Also, maybe your issue can be related to this [PR](https://github.com/actions/runner-images/pull/7125) - you could simply check if you manually install `pkg-config` (like `brew install pkg-config`) at the beginning of the pipeline.

**Comment by CendioOssman** [comment] 2023-02-23 15:08
Something has been updated/fixed as if I re-run this failed job, then everything now succeeds:

https://github.com/TigerVNC/tigervnc/actions/runs/4224576079/jobs/7399436282

**Comment by bogdan-damian-bgd** [comment] 2023-02-23 15:18
Hi, that's good news :)  For now I am going to close this issue. Feel free to reach us again if you have any concerns.

**Closed by bogdan-damian-bgd** 2023-02-23 15:18 UTC
Labels: Area: C/C++, OS: macOS, bug report
