### ISSUE TITLE
missing DEVELOPER_DIR path: /Applications/Xcode_15.0.app/Contents/Developer

### ISSUE THREAD

**Issue by haniewais** [actions/runner-images#8426] opened 2023-10-02 05:00 UTC
### Description

@Steve-Glass 
When running our build pipeline using macos-13 image, we get the following error:

xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode_15.0.app/Contents/Developer

<img width="745" alt="Pasted Graphic 25" src="https://github.com/actions/runner-images/assets/13974295/d2638e83-d53b-4676-86aa-d830e30db7a7">

<br>
<br>
<br>
The path on the documentation should include the Contents/Developer directory
<br>
<br>

Version | Build | Path
-- | -- | --
15.0 | 15A240d | /Applications/Xcode_15.0.app

https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Operating System
- macOS
- 13.3.1
- 22E261

Runner Image
- Image: macos-13
- Version: 20230417.1

### Is it regression?

No, first time using the new macos-13 vm

### Expected behavior

Expected output:

![Pasted Graphic 24](https://github.com/actions/runner-images/assets/13974295/d78a1cfe-3f09-441e-85de-753df2dccced)

### Actual behavior

In our build pipeline when we get to the step that uses Xcode, the pipeline fails, 

### Repro steps

1. Run build pipeline on macos-13 vm image
2. Have a task that checks the Xcode version like this command: /usr/bin/xcodebuild -version

**Comment by lorenc-tomasz** [comment] 2023-10-02 07:23
Had the same issue today. However I have rerun the failed job and it worked.

**Comment by Alexey-Ayupov** [comment] 2023-10-02 07:25
Hello, @haniewais. You happened to reach a pretty old image, currently, we are in the process of adding capacity so it can happen again. We will update all runners to the latest version shortly.
Duplicate of https://github.com/actions/runner-images/issues/8341.

**Closed by Alexey-Ayupov** 2023-10-02 07:25 UTC
Labels: duplicate, OS: macOS, bug report

**Comment by Cheesebaron** [comment] 2023-10-11 07:47
Still occasionally hitting old images.

See the run here: https://trackman.visualstudio.com/Golf/_build/results?buildId=377041&view=logs&j=ae1899ec-e77c-50f2-7851-b1c197bf7c77&t=0a071d35-96ef-47ad-806c-29c6a53e6674

Mac-1697009699982
