### ISSUE TITLE
watchOS simulators on macOS 12 have inconsistent names

### ISSUE THREAD

**Issue by dfed** [actions/runner-images#6773] opened 2022-12-14 20:53 UTC
### Description

[Last week, the macOS-12 runner documentation was updated](https://github.com/actions/runner-images/commit/ec48677623cba3a4f203230ffe49f0d3cce292b7) to change the name of the watchOS 8.5 simulator from (for example): `Apple Watch Series 6 - 44mm` to `Apple Watch Series 6 (44mm)`.

This change broke CI pipelines, but is pretty easy to fix. However, not all machines seem to have this new simulator names. Some machines are running with the old names, and some with the new names.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

This machine has a `- 44mm` simulator: https://github.com/square/Valet/actions/runs/3698335227/jobs/6264661846#step:6:362

This machine has a `(44mm)` simulator: https://github.com/square/Valet/actions/runs/3698488778/jobs/6264762869#step:6:363

### Is it regression?

Yes. Builds from before last week all had watchOS 8.5 simulators with the suffix `- 44mm`

### Expected behavior

I would expect all machines to have simulator names that match the documentation.

### Actual behavior

Only some machines have simulator names that match the documentation.

### Repro steps

Run the `master` build of https://github.com/square/Valet multiple times. It will sometimes succeed and sometimes fail depending on which machine we're running on. The last commit on that branch tried to revert the simulator name to the old behavior but I'm still seeing sporadic failures in CI.

**Comment by igorboskovic3** [comment] 2022-12-15 07:43
Hi @dfed, thank you, we will check it and get back to you.

**Comment by Brett-Best** [comment] 2022-12-15 09:40
Related: https://github.com/actions/runner-images/issues/6243

I wonder if when building an image the different Xcodes are installed concurrently and that creates a race condition at some point when the default set of simulators are installed.

I would expect that the simulators use the `(  )` format introduced with Xcode 14 consistently.

**Comment by maxim-lobanov** [comment] 2022-12-15 12:33
Hi @dfed,

All macOS VMs with the same image version are identical and have the same simulator names. One of your workflow run was assigned to image version `20221211.1`. Another one was assigned to `20221204.1`. Usually, such situation happens we deploy the new image and during some short period of time workflow runs can be assigned to both previous and new image version.

But for some reason, simulator names are changed between image versions that don't look expected behaviour.
I have the same suspicious as @Brett-Best that it is related to race condition during image generation because we install a lot of Xcode versions side by side and install them in parallel.
We will try to confirm this assumption and will investigate possible fixes.

As a temporary workaround, you can try to the following code snippet to get actual device name in runtime:
```bash
deviceName=$(xcrun simctl list --json | jq -r '.devices."com.apple.CoreSimulator.SimRuntime.watchOS-8-5"[] | select(.name | test("Apple Watch Series 6 .+ 44mm")) | .name')
echo $deviceName
```
This snippet extract the actual simulator name from `simctl list` and then you can pass it to `xcodebuild`

**Comment by igorboskovic3** [comment] 2022-12-16 09:33
@dfed feel free to reach us if yo have any other questions.

**Comment by maxim-lobanov** [comment] 2022-12-23 11:43
**Update:**
I have tried to disable parallel Xcode installation and install Xcode versions one by one. Unfortunately, it didn't fix the issue. 
I also tried to play with Xcode installation order but it doesn't seem to affect the final result somehow.

I also noticed that this issue affects only `watchOS` and `tvOS` simulators. `iOS` seems to be fine.
On tvOS we have the following change 🤦 :
`Apple TV 4K (2nd generation) (at 1080p)` vs `Apple TV 4K (at 1080p) (2nd generation)`

Installation of multiple Xcode versions side by side was always tricky and I think simulators from different Xcode versions can conflict to each other somehow. But we didn't face with the same issue before Xcode 14 was added and we didn't change our installation process somehow.
We will continue investigation after the holidays and will try to make some other experiments to determine root cause.

The workaround that I shared above should work well to unblock you while we are investigating the issue.

**Comment by maxim-lobanov** [comment] 2023-02-23 10:21
Hello everyone, big update here:

I have found out that issue is related to `-downloadAllPlatforms` command which was introduced in Xcode 14.0 and we invoke this command for every Xcode 14.x to install watchOS and tvOS simulators (starting from Xcode 14.0, these runtimes are not included to Xcode by default).

Invocation of `-downloadAllPlatforms` somehow breaks naming of watchOS / tvOS simulators created by Xcode <= 14.0.1.
For me, it looks like this command tries to change naming for all installed simulators to be consistent with new naming (which comes in Xcode 14.1 and 14.2). But for some reason, it renames only part of them (the number of renamed simulators is always different).

I have definitely confirmed that issue is not related to parallel xcode installation because simulators become broken later when we invoke `downloadAllPlatforms` and we invoke this command without parallel invocation.

The weird thing is that the number of simulators with broken naming is always different. I confirmed that it is not race condition. I have tried to add 30 minutes delay before and after every `downloadAllPlatforms` invocation and it doesn't seem to help. I wonder if it can be caused by some bug in this new command.

Installing multiple Xcode versions side by side always was tricky. Especially, such big number of different versions (including multiple major versions 13.x, 14.x).

So I didn't figure out the root cause but I think I have a fix. I have added a logic to rename simulators to correct names at the end of image generation. It is not ideal but should resolve this issue.
Pull-request: https://github.com/actions/runner-images/pull/7181
@mikhailkoliada feel free to merge this PR when you are ready.

**Closed** 2023-03-21 16:07 UTC
Labels: OS: macOS, investigate, bug report
