### ISSUE TITLE
Newest Windows Image has broken vcvarsall.bat

### ISSUE THREAD

**Issue by ThadHouse** [actions/runner-images#9404] opened 2024-02-26 06:56 UTC
### Description

vcvarsall.bat when not passed a `vcvars_ver` parameter should be returning the latest installed VC++ compiler toolset. However, this does not seem to be the case. It is returning an older version. The following build is a minimal reproduction.

https://github.com/ThadHouse/ActionsDebug/actions/runs/8044801044/job/21968983003

The print after `[vcvarsall.bat] Environment initialized for: 'x86_x64'` Should be returning `14.39.33519`. However, it is returning `14.38.33130`. The `dir` command ran afterward shows that the 14.39.33519 folder does exist, and it should be the chosen toolchain.

This makes it so any GitHub actions builds using vcvarsall.bat don't actually detect the newest version of the compiler. However, tools that don't use vcvarsall.bat will find the newest version. Which can result in binaries built in one section of the build not being compatible with binaries built in another section.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
  Version: 2024021[8](https://github.com/ThadHouse/ActionsDebug/actions/runs/8044801044/job/21968983003#step:1:9).2.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240218.2/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240218.2
  
  https://github.com/ThadHouse/ActionsDebug/actions/runs/8044801044/job/21968983003

### Is it regression?

Yes

### Expected behavior

Toolchain 14.39.33519 is selected

### Actual behavior

Toolchain 14.38.33130 is selected

### Repro steps

1. Run vcvarsall.bat
2. See that the selected toolchain is incorrect

**Comment by shamil-mubarakshin** [comment] 2024-02-26 12:32
Hey @ThadHouse,
The issue is a duplicate of https://github.com/actions/runner-images/issues/9086. We keep several v143 VC components pre-installed and available for users, which might cause [troubles in selecting default version](https://developercommunity.visualstudio.com/t/MicrosoftVCToolsVersionv143defaulttx/10041951).
See https://github.com/actions/runner-images/issues/9086#issuecomment-1874194557 for additional links to issues, workarounds.

**Closed by shamil-mubarakshin** 2024-02-26 12:32 UTC
Labels: needs triage, bug report
