### ISSUE TITLE
Windows Server 20221119.1 (and maybe other) images include a problematic CMake 3.25.0 version

### ISSUE THREAD

**Issue by trrwilson** [actions/runner-images#6679] opened 2022-12-01 22:46 UTC
### Description

Apologies if this is already known/addressed; couldn't find a match with a quick search.

[The recent 11/19 WS2019 update, 20221119.1](https://github.com/actions/runner-images/releases/tag/win19%2F20221119.1) includes version 3.25.0 of the CMake tool as part of the runner image.

CMake 3.25.0 released with a fairly nasty bug that was quickly fixed with a 3.25.1 release:

https://cmake.org/cmake/help/latest/release/3.25.html#id1

>On Windows, when targeting the MSVC ABI, the [find_library()](https://cmake.org/cmake/help/latest/command/find_library.html#command:find_library) command no longer accepts .a file names. This behavior was added in CMake 3.25.0, but has been reverted due finding GNU-ABI libraries in cases we did not previously.

My team's Azure DevOps build pipeline hit this when an old external dependency's CMakeLists.txt detected the build environment as "Linux" (GNU libraries, after all!) and attempted to link things it shouldn't; the `ld` errors from clang/llvm are unfortunately a bit cryptic to get to the bottom of.

We've worked around the issue by adding a manual upgrade of CMake to 3.25.1 into our pipeline definition and verified that this resolves the breaks we saw. Impacted customers might not know it's CMake responsible for this, though--it's not at all obvious that a find_library bug is involved.

Selfishly, an upgrade to 3.25.1 in the image will speed up our builds a bit; bigger picture, though, I imagine some customers may be impacted by an inscrutable break upon image upgrade without knowing what's going on.

Thanks!

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win19%2F20221119.1

### Is it regression?

Yes--our prior image, 20221027.1, used CMake 3.24.2; only 20221119.1 with CMake 3.25.0 manifests an issue

### Expected behavior

Our build should continue to work--CMake being upgraded shouldn't be a breaking change.

### Actual behavior

Our build broke. In our instance, the dependency responsible for manifesting the CMake 3.25.0 issue is the `azure-c-shared-utility` library (https://github.com/Azure/azure-c-shared-utility) -- it detects as Linux and attempts to link pthread and rt, which don't exist.

Example, abridged output of the error that appeared:

```
[444/832] Linking CXX shared library lib\libMicrosoft.CognitiveServices.Speech.core.so
FAILED: lib/libMicrosoft.CognitiveServices.Speech.core.so 
cmd.exe /C "cd . && C:\Android\android-sdk\ndk\25.1.8937393\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=i686-none-linux-android21 [...snip...] D:/a/_work/1/s/external/android-openssl/x86/usr/local/lib/libcrypto.a  -lpthread  -lm  -lrt  lib/liblogging.a  lib/libcommon.a  -ldl  -llog  lib/libpal.a   -static-libstdc++ -latomic -lm && cd ."
ld: error: unable to find library -lpthread
ld: error: unable to find library -lrt

clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Repro steps

N/A (covered in the rest of the discussion) -- the bug is documented and fixed by the CMake team and we've confirmed the implemented workaround of a manual upgrade to 3.25.1 resolves the problem.

**Comment by mikhailkoliada** [comment] 2022-12-01 23:47
Duplicate of 6627

**Closed by mikhailkoliada** 2022-12-01 23:47 UTC
Labels: needs triage, bug report
