### ISSUE TITLE
 Failed to fetch http://azure.archive.ubuntu.com/ubuntu/ packages

### ISSUE THREAD

**Issue by blankdots** [actions/runner-images#7596] opened 2023-05-15 12:18 UTC
### Description

 Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/n/node-core-util-is/node-core-util-is_1.0.2-1_all.deb  503  Service Unavailable [IP: 52.252.75.106 80]
 
 trying to access the package mirror it looks something like:

![image](https://github.com/actions/runner-images/assets/47524/b56eb513-6789-4b14-9194-4fd8208bab66)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
 Image: ubuntu-20.04
  Version: 20230507.1
  Included Software: https://github.com/actions/runner-images/blob/ubuntu20/20230507.1/images/linux/Ubuntu2004-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230507.1
```

### Is it regression?

yes

### Expected behavior

packages can be downloaded

### Actual behavior

packages could be installed

### Repro steps

In a step run:
1.  `sudo apt-get update`
2. install some packages `sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev npm pkg-config libfuse-dev upx -y`

**Comment by blankdots** [comment] 2023-05-15 12:38
now it seems it works

**Comment by shamil-mubarakshin** [comment] 2023-05-15 16:40
Hello @blankdots,
I have successfully completed commands from repro steps on ubuntu-20.04 runner, and since you confirmed as well, closing the issue.

**Closed** 2023-05-15 16:40 UTC
Labels: bug report
