### ISSUE TITLE
Chocolatey had an error on fv-az838-323 (with user runneradmin)

### ISSUE THREAD

**Issue by fangq** [actions/runner-images#9477] opened 2024-03-10 02:29 UTC
### Description

Windows runner had been working fine until half day ago - choco fails to install packages in the below action log

https://github.com/fangq/mmc/actions/runs/8217659261/job/22473602280

the error message is
```
  choco install octave.portable --version=8.3.0
  choco install upx
  choco install mingw --version=8.1.0
  echo 'C:\ProgramData\chocolatey\lib\octave.portable\tools\octave\mingw64\bin' >> $GITHUB_PATH
  echo 'C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\' >> $GITHUB_PATH
  echo 'MW_MINGW64_LOC=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/' >> $GITHUB_ENV
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
Chocolatey v2.2.2
Installing the following packages:
octave.portable
By installing, you accept licenses for the packages.
Invalid credentials specified.
Please provide credentials for: https://community.chocolatey.org/api/v2/
User name: Password: Chocolatey had an error on fv-az8[3](https://github.com/fangq/mmc/actions/runs/8217659261/job/22473602280#step:6:3)[8](https://github.com/fangq/mmc/actions/runs/8217659261/job/22473602280#step:6:8)-323 (with user runneradmin):
System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at chocolatey.infrastructure.commandline.ReadKeyTimeout.ConsoleReadKey()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

the last successful build was 9 hours ago

https://github.com/fangq/mmc/actions/runs/8216028448/job/22470141369

choco version is v2.2.2 in both the good and bad builds

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/fangq/mmc/actions/runs/8217659261/job/22473602280

### Is it regression?

https://github.com/fangq/mmc/actions/runs/8216028448/job/22470141369

### Expected behavior

choco install complete successfully

### Actual behavior

choco fails to install package octave

### Repro steps

run `choco install octave.portable --version=8.3.0` in a windows runner

**Comment by binarymaster** [comment] 2024-03-10 14:10
Can confirm: https://github.com/reactos/reactos/actions/runs/8222402434/job/22483856476

**Comment by mikhailkoliada** [comment] 2024-03-10 14:45
Duplicate of https://github.com/actions/runner-images/issues/9476

**Closed by mikhailkoliada** 2024-03-10 14:45 UTC
Labels: needs triage, bug report
