### ISSUE TITLE
Pipeline fails on hosted agent ubuntu-latest (build 20221114.1)

### ISSUE THREAD

**Issue by ksaffarian** [actions/runner-images#6580] opened 2022-11-16 13:38 UTC
### Description

Hi

I noticed that my pipelines are running on different releases of `ubuntu-latest`.

My PowerShell script fails on release `20221114.1` with error **docker: invalid reference format.**. This is happening when my script wants to execute the line `docker run .... some parameters`.

However, those pipelines that are running on release `20221027.1` have no issue. Indeed, we had no issue before  `20221114.1` .

I can also run that PS script and docker command locally and it works.

Can you please investigate this?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Failing on **Current image version: '20221114.1'**
Working on **Current image version: '20221027.1'**

### Is it regression?

20221027.1

### Expected behavior

My PowerShell script, specially the call to `docker run` works without issue.

### Actual behavior

My `docker run` command spreads to multiple lines, like this
```
docker run $ttyFlag --rm `
        -v ${testPath}:/app `
        -w /app/${testFolderPath} `
        --env-file $envFile `
        -e TF_PLUGIN_CACHE_DIR=none `
        -e CHECKPOINT_DISABLE=1 `
        -e GO111MODULE=on `
        $imageName $testPrefix $testTimeout $testParallel | Tee-object -FilePath $tfRawLogPath
```
I think there is something wrong with how parameters are tokenized by PowerShell or consumed by docker executable and I get error [docker: invalid reference format.]

### Repro steps

Try to run a multiline docker run command inside the faulty image.
Make sure you mount path to volumes as part of the command.

**Comment by tamirkamara** [comment] 2022-11-16 15:37
We are also seeing similar errors with Github Actions hosted runners (standard size)

**Comment by ksaffarian** [comment] 2022-11-17 00:45
Hi
Can you please increase severity of this?

We noticed another pipeline that uses PowerShell is failing on image version 20221114.1 for `ubuntu-latest` , when running **Get-AzNetworkServiceTags** with following error:
```
Get-AzNetworkServiceTag: /home/vsts/work/1/s/access-restrictions/functions/Get-AzureIpRestriction.ps1:40
Line |
  40 |  …       $globalData = Get-AzNetworkServiceTag -Location 'australiaeast'
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | GenericArguments[0],
     | 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T
     | MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the
     | constraint of type 'T'.
```

**Comment by ksaffarian** [comment] 2022-11-17 04:39
I noticed an issue is opened for this as it is impacting many people
Linking #6586

**Comment by JacobStruiksma** [comment] 2022-11-17 08:21
> Hi Can you please increase severity of this?
> 
> We noticed another pipeline that uses PowerShell is failing on image version 20221114.1 for `ubuntu-latest` , when running **Get-AzNetworkServiceTags** with following error:
> 
> ```
> Get-AzNetworkServiceTag: /home/vsts/work/1/s/access-restrictions/functions/Get-AzureIpRestriction.ps1:40
> Line |
>   40 |  …       $globalData = Get-AzNetworkServiceTag -Location 'australiaeast'
>      |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | GenericArguments[0],
>      | 'Microsoft.Azure.Management.Network.Models.SecurityRule', on 'T
>      | MaxInteger[T](System.Collections.Generic.IEnumerable`1[T])' violates the
>      | constraint of type 'T'.
> ```
> 
> I can confirm it works on image version `20221027.1`

See also https://github.com/Azure/azure-powershell/issues/18721 for that specific issue. The problem is with powershell 7.3 and azure powershell module

**Comment by erik-bershel** [comment] 2022-11-17 09:17
@ksaffarian 
We are already working on the issue. To temporarily stop the problem, we will return the previous versions of the images to work. We will report on the following decisions separately.

**Comment by mikhailkoliada** [comment] 2022-11-17 11:29
Duplicate of https://github.com/actions/runner-images/issues/6586

**Closed by mikhailkoliada** 2022-11-17 11:29 UTC
Labels: Area: Containers, Area: Scripting and command line, OS: Ubuntu, investigate, bug report

**Comment by MengjiaLiang** [comment] 2022-11-17 20:53
Hi @erik-bershel ,  did you stop using this version already?
We are having issues when using this version of the node. That makes our alpha environment down. We were lucky didn't make the deployment on our production environment.

I wonder if we force retire all our agents in `20221114.1`, whether the version `20221027.1` will be picked to provision new agents?

**Comment by erik-bershel** [comment] 2022-11-18 08:50
@MengjiaLiang yep. We rolled back yesterday. Please send the info about your issues.
