### ISSUE TITLE
[Windows 2022] CodeQL install fails

### ISSUE THREAD

**Issue by McHammar** [actions/runner-images#9356] opened 2024-02-16 08:27 UTC
### Description

We can't build the windows image with the latest release. 
We get this error
 azure-arm.image:   [-] Latest and Prior CodeQL Bundles are unique 1.43s (1.41s|21ms)
    azure-arm.image:    Expected regular expression '2.16.2' to not match '2.16.2', but it did match.
    azure-arm.image:    at $LatestCodeQLVersion | Should -Not -Match $PriorCodeQLVersion, C:\image\tests\Tools.Tests.ps1:65
    azure-arm.image:    at <ScriptBlock>, C:\image\tests\Tools.Tests.ps1:65

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

3.234.0

### Is it regression?

No

### Expected behavior

Build the image

### Actual behavior

Fails

### Repro steps

Run the build for Windows 2022

**Comment by Alexey-Ayupov** [comment] 2024-02-16 10:44
Hello @McHammar , we build images nightly and we haven't faced such issue. Please make sure you are using the latest version of your repository and try again.

**Comment by McHammar** [comment] 2024-02-16 10:46
I have tried the latest and the one from branch releases/win22/20240211
Same issue :/

**Comment by Alexey-Ayupov** [comment] 2024-02-16 15:53
Got it, could you please provide a snippet of code for image generation you are using? We will try to reproduce the issue.

**Comment by McHammar** [comment] 2024-02-16 16:50
```
jobs:
- template: image-generation.yml
  parameters:
    image_type: windows2022
    image_readme_name: Windows2022-Readme.md
    image_template_name: windows-2022.pkr.hcl
    variable_group_name: Image Generation Variables (Windows)
```

And image-generation.yml:
```
# Ideally we would use GitHub Actions for this, but since we use self-hosted machines to run image builds
# we need the following features to use GitHub Actions for Images CI:
# - https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678#M508
# - https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/td-p/31504
# - https://github.community/t5/GitHub-Actions/Protecting-github-workflows/td-p/30290

parameters:
  - name: job_id
    type: string
    default: 'generate_image'

  - name: image_type
    type: string

  - name: image_template_name
    type: string

  - name: image_readme_name
    type: string

  - name: agent_pool
    type: object
    default:
      name: 'vmss-ubuntu'

  - name: variable_group_name
    type: string
    default: 'Image Generation Variables'

  - name: create_release
    type: boolean
    default: false

  - name: repository_ref
    type: string
    default: 'self'

jobs:
- job: ${{ parameters.job_id }}
  displayName: Image Generation (${{ parameters.image_type }})
  timeoutInMinutes: 600
  cancelTimeoutInMinutes: 30
  pool: ${{ parameters.agent_pool }}
  variables:
  - group: ${{ parameters.variable_group_name }}

  steps:
  - checkout: ${{ parameters.repository_ref }}
    clean: true
    fetchDepth: 0
    fetchTags: false

  - task: PowerShell@2
    displayName: 'Download custom repository'
    condition: and(ne(variables['CUSTOM_REPOSITORY_URL'], ''), ne(variables['CUSTOM_REPOSITORY_BRANCH'], ''))
    inputs:
      targetType: 'filePath'
      filePath: ./images.CI/download-repo.ps1
      arguments: -RepoUrl $(CUSTOM_REPOSITORY_URL) `
                 -RepoBranch $(CUSTOM_REPOSITORY_BRANCH)

  - task: PowerShell@2
    displayName: 'Set variables'
    inputs:
      targetType: 'inline'
      script: |
        $ImageType = "${{ parameters.image_type }}"
        $TemplateDirectoryName = if ($ImageType.StartsWith("ubuntu")) { "ubuntu/templates" } else { "windows/templates" }
        $TemplateDirectoryPath = Join-Path "images" $TemplateDirectoryName | Resolve-Path

        $TemplateFileName = "${{ parameters.image_template_name }}"
        $TemplatePath = Join-Path $TemplateDirectoryPath $TemplateFileName
        Write-Host "##vso[task.setvariable variable=TemplateDirectoryPath;]$TemplateDirectoryPath"
        Write-Host "##vso[task.setvariable variable=TemplatePath;]$TemplatePath"

        $ManagedImageName = "${{ parameters.image_type }}-$(Build.BuildId)"
        Write-Host "##vso[task.setvariable variable=ManagedImageName;]$ManagedImageName"

        $TempResourceGroupName = "packer-temp-$ManagedImageName"
        Write-Host "##vso[task.setvariable variable=TempResourceGroupName;]$TempResourceGroupName"

  - task: PowerShell@2
    displayName: 'Build VM'
    inputs:
      targetType: filePath
      filePath: ./images.CI/linux-and-win/build-image.ps1
      arguments: -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -TemplatePath $(TemplatePath) `
                 -ImageName "$(MANAGED_IMAGE_NAME)" `
                 -ImageResourceGroupName $(MANAGED_IMAGE_RESOURCE_GROUP_NAME) `
                 -TempResourceGroupName "group-packer-temp" `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -TenantId $(AZURE_TENANT) `
                 -Location $(AZURE_LOCATION) `
                 -VirtualNetworkName $(BUILD_AGENT_VNET_NAME) `
                 -VirtualNetworkRG $(BUILD_AGENT_VNET_RESOURCE_GROUP) `
                 -VirtualNetworkSubnet $(BUILD_AGENT_SUBNET_NAME)

    env:
      PACKER_LOG: 1
      PACKER_LOG_PATH: "$(Agent.TempDirectory)/packer-log.txt"

  - task: PowerShell@2
    displayName: 'Copy image artifacts to the separate directory'
    inputs:
      targetType: 'inline'
      script: |
        $ImageType = "${{ parameters.image_type }}"
        $rootDirectoryName = if ($ImageType.StartsWith("ubuntu")) { "ubuntu" } else { "windows" }
        $rootDirectoryPath = Join-Path "images" $rootDirectoryName | Resolve-Path

        $readmePath = Join-Path $rootDirectoryPath "${{ parameters.image_readme_name }}"
        $softwareReportPath = Join-Path $rootDirectoryPath "software-report.json"

        Copy-Item -Path $readmePath -Destination "$(Build.ArtifactStagingDirectory)/"
        if (Test-Path $softwareReportPath) {
            Copy-Item -Path $softwareReportPath -Destination "$(Build.ArtifactStagingDirectory)/"
        }

  - task: PowerShell@2
    displayName: 'Print markdown software report'
    inputs:
      targetType: 'inline'
      script: |
        Get-Content -Path "$(Build.ArtifactStagingDirectory)/${{ parameters.image_readme_name }}"

  - task: PowerShell@2
    displayName: 'Print json software report'
    inputs:
      targetType: 'inline'
      script: |
        $softwareReportPath = "$(Build.ArtifactStagingDirectory)/software-report.json"
        if (Test-Path $softwareReportPath) {
            Get-Content -Path $softwareReportPath
        }

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'Built_VM_Artifacts'
    displayName: Publish Artifacts

  - task: PowerShell@2
    displayName: 'Print provisioners duration'
    inputs:
      targetType: 'filePath'
      filePath: ./images.CI/measure-provisioners-duration.ps1
      arguments: -PackerLogPath "$(Agent.TempDirectory)/packer-log.txt" `
                        -PrefixToPathTrim "$(TemplateDirectoryPath)" `
                        -PrintTopNLongest 25

  - ${{ if eq(parameters.create_release, true) }}:
    - task: PowerShell@2
      displayName: 'Create release for VM deployment'
      inputs:
        targetType: filePath
        filePath: ./images.CI/linux-and-win/create-release.ps1
        arguments: -BuildId $(Build.BuildId) `
                   -Organization $(RELEASE_TARGET_ORGANIZATION) `
                   -DefinitionId $(RELEASE_TARGET_DEFINITION_ID) `
                   -Project $(RELEASE_TARGET_PROJECT) `
                   -ImageType "${{ parameters.image_type }}" `
                   -ManagedImageName "$(ManagedImageName)" `
                   -AccessToken $(RELEASE_TARGET_TOKEN)

  - task: PowerShell@2
    displayName: 'Clean up resources'
    condition: always()
    inputs:
      targetType: filePath
      filePath: ./images.CI/linux-and-win/cleanup.ps1
      arguments: -TempResourceGroupName "$(TempResourceGroupName)" `
                 -SubscriptionId $(AZURE_SUBSCRIPTION) `
                 -ClientId $(CLIENT_ID) `
                 -ClientSecret $(CLIENT_SECRET) `
                 -TenantId $(AZURE_TENANT)

```

**Comment by sergei-pyshnoi** [comment] 2024-02-20 11:16
Hello @McHammar . Looks like you are trying to build with branch/commit that >4 month old . Failed pester test in your log was completely modified with removing removing CodeQL duplicate. Here is [commit with changes](https://github.com/actions/runner-images/commit/5669edde7597b63910572942fbc688fa3fa825fe#diff-4985216b5ceed7ef7549613b8347d8845321355494f196c71d7a3afe880861ce) . Please make sure that you use latest commit from main for your builds.
I am closing this issue for now because we cannot reproduce your behavior but if you have additional questions feel free to ask.

**Closed by sergei-pyshnoi** 2024-02-20 11:16 UTC
Labels: OS: Windows, Area: Image administration, bug report

**Comment by McHammar** [comment] 2024-02-20 12:15
Okay, weird. I will try and pull main again
