### ISSUE TITLE
macOS 13 image occasionally missing Ruby

### ISSUE THREAD

**Issue by Saadnajmi** [actions/runner-images#8423] opened 2023-09-30 01:41 UTC
### Description

On a run of my [pipeline](https://dev.azure.com/ms/react-native/_build/results?buildId=501119&view=logs&j=b24eb30e-907c-58af-44ed-713bd1138078&t=4a506423-abc9-526b-2446-c14936653d1f), I'm getting issues where some (but not all) of my images don't seem to have Ruby installed, causing my [useRubyVersion](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-ruby-version-v0?view=azure-pipelines#how-can-i-configure-a-self-hosted-agent-to-use-this-task) to fail.

```
Starting: UseRubyVersion
==============================================================================
Task         : Use Ruby version
Description  : Use the specified version of Ruby from the tool cache, optionally adding it to the PATH
Version      : 0.213.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/tool/use-ruby-version
==============================================================================
##[error]Version spec >= 2.7 for architecture %s did not match any version in Agent.ToolsDirectory.
Available versions: /Users/runner/hostedtoolcache

If this is a Microsoft-hosted agent, check that this image supports side-by-side versions of Ruby at https://aka.ms/hosted-agent-software.
If this is a self-hosted agent, see how to configure side-by-side Ruby versions at https://go.microsoft.com/fwlink/?linkid=2005989.
Finishing: UseRubyVersion
```

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: macos-13
Version: 20230417.1
Included Software: https://github.com/actions/runner-images/blob/macOS-13/20230417.1/images/macos/macos-13-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20230417.1

https://dev.azure.com/ms/react-native/_build/results?buildId=501119&view=logs&j=b24eb30e-907c-58af-44ed-713bd1138078&t=94a14104-cf5f-4300-9f63-3a5c8322afad

### Is it regression?

Yes?

### Expected behavior

Ruby should successfully get used

### Actual behavior

Ruby fails to be used

### Repro steps

Use the `useRubyVersion` task linked above in a job.

**Comment by Alexey-Ayupov** [comment] 2023-10-02 07:20
Hello @Saadnajmi. You happened to reach a pretty old image, currently, we are in the process of adding capacity so it can happen again. We will update all runners to the latest version shortly.
Duplicate of #8341.

**Closed by Alexey-Ayupov** 2023-10-02 07:20 UTC
Labels: OS: macOS, bug report
