### ISSUE TITLE
Value of type 'some WidgetConfiguration' has no member 'contentMarginsDisabled'

### ISSUE THREAD

**Issue by mpivchev** [actions/runner-images#9071] opened 2023-12-27 16:06 UTC
### Description

On a `macos-latest` runner I have a step that runs the following command. 
```
  set -o pipefail && xcodebuild test -project $PROJECT \
  -scheme "$SCHEME" \
  -destination "platform=iOS Simulator,name=iPhone 14" \
  -enableCodeCoverage YES \
  -test-iterations 3 \
  -retry-tests-on-failure \
  | xcpretty
```

The command runs fine locally, but on the runner I get the following errors, all related to SwiftUI and widgets:

<img width="1049" alt="image" src="https://github.com/actions/runner-images/assets/6960329/7ba771b0-8a07-4eee-9480-9fae4d0190c2">

This is the file in question:

```swift
import WidgetKit
import Intents
import SwiftUI

@main
struct SomeWidgetBundle: WidgetBundle {

    @WidgetBundleBuilder
    var body: some Widget {
        DashboardWidget()
        FilesWidget()
        ToolbarWidget()
        LockscreenWidget()
    }
}

struct DashboardWidget: Widget {
    let kind: String = "DashboardWidget"

    var body: some WidgetConfiguration {
        IntentConfiguration(kind: kind, intent: DashboardIntent.self, provider: DashboardWidgetProvider()) { entry in
            DashboardWidgetView(entry: entry)
        }
        .supportedFamilies([.systemLarge])
        .configurationDisplayName("Dashboard")
        .description(NSLocalizedString("_description_dashboardwidget_", comment: ""))
        .contentMarginsDisabled()
    }
}

struct FilesWidget: Widget {
    let kind: String = "FilesWidget"

    var body: some WidgetConfiguration {
        IntentConfiguration(kind: kind, intent: AccountIntent.self, provider: FilesWidgetProvider()) { entry in
            FilesWidgetView(entry: entry)
        }
        .supportedFamilies([.systemLarge])
        .configurationDisplayName("Files")
        .description(NSLocalizedString("_description_fileswidget_", comment: ""))
        .contentMarginsDisabled()
    }
}

struct ToolbarWidget: Widget {
    let kind: String = "ToolbarWidget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: ToolbarWidgetProvider()) { entry in
            ToolbarWidgetView(entry: entry)
        }
        .supportedFamilies([.systemMedium])
        .configurationDisplayName("Toolbar")
        .description(NSLocalizedString("_description_toolbarwidget_", comment: ""))
        .contentMarginsDisabled()
    }
}

struct LockscreenWidget: Widget {
    let kind: String = "LockscreenWidget"

    var body: some WidgetConfiguration {
        if #available(iOSApplicationExtension 16.0, *) {
            return IntentConfiguration(kind: kind, intent: AccountIntent.self, provider: LockscreenWidgetProvider()) { entry in
                LockscreenWidgetView(entry: entry)
            }
            .supportedFamilies([.accessoryRectangular, .accessoryCircular])
            .configurationDisplayName(NSLocalizedString("_title_lockscreenwidget_", comment: ""))
            .description(NSLocalizedString("_description_lockscreenwidget_", comment: ""))
            .contentMarginsDisabled()
        } else {
            return EmptyWidgetConfiguration()
        }
    }
}

extension View {
    func widgetBackground(_ backgroundView: some View) -> some View {
        if #available(iOSApplicationExtension 17.0, *) {
            return containerBackground(for: .widget) {
                backgroundView
            }
        } else {
            return background(backgroundView)
        }
    }
}

```

`macos-latest` is macOS 12 with Xcode 14.2, and it does support iOS 16.2

The minimum available version for this function is 15, so it should be available:

```swift
@available(iOS 15.0, macOS 12.0, watchOS 9.0, *)
@available(tvOS, unavailable)
extension WidgetConfiguration {

    /// Disable default content margins.
    ///
    /// When you disable content margins for a widget, the system doesn't automatically add margins
    /// around the widget's content, and you are responsible for specifying margins and padding around your
    /// widget content for each context. To specify custom margins, use ``EnvironmentValues/widgetContentMargins``
    /// in combination with ``View/padding(_)`` to selectively or partially apply the default content margins.
    ///
    /// - Returns: A modified widget configuration that doesn't use default content margins.
    ///
    ///  This modifier has no effect on operation system versions prior to iOS 17, watchOS 10, or macOS 14.
    public func contentMarginsDisabled() -> some WidgetConfiguration

}
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231216.1
https://github.com/nextcloud/ios/actions/runs/7339762120/job/19984558613

### Is it regression?

No

### Expected behavior

Task should finish

### Actual behavior

Task does not finish

### Repro steps

Run workflow

**Comment by Alexey-Ayupov** [comment] 2023-12-28 08:50
Hello @mpivchev, we will take a look.

**Comment by MaksimZhukov** [comment] 2024-01-10 00:57
Hello @mpivchev!
Unfortunately, we have not found the root cause yet. 
You mentioned that everything works fine locally. Could you share more details with us: Xcode version, installed simulators. This will help further investigation.
Thank you!

**Comment by mpivchev** [comment] 2024-01-10 10:19
Hi @MaksimZhukov 

I use XCode 15, iOS 17 simulator.

Also yes, I use the same commands locally.

**Comment by MaksimZhukov** [comment] 2024-01-10 16:54
Yes, I was able to reproduce the issue in GitHub Actions, but when I tried to reproduce it locally, I got a message saying that I need to install simulators with iOS 17.

`macos-latest` has no simulators with iOS 17 ([documentation](https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md#installed-sdks)), and it seems to me that this can cause the issue.

Is it possible for you to try to run tests locally on Xcode 14.2 with iOS 16.2 or try to adapt your workflow for `macos-13`?

**Comment by MaksimZhukov** [comment] 2024-01-16 22:45
Hello @mpivchev!
Have you had a chance to follow the recommendations?

**Comment by mpivchev** [comment] 2024-01-17 15:11
Hi @MaksimZhukov, not yet, but planning to.

**Comment by MaksimZhukov** [comment] 2024-01-25 23:29
I am closing the issue because it seems that the project is not compatible with the `macos-latest` runner image due to the lack of simulators with iOS 17.
Do not hesitate to contact us if you have additional information after completing the recommended steps.

**Closed by MaksimZhukov** 2024-01-25 23:29 UTC
Labels: OS: macOS, bug report

**Comment by mpivchev** [comment] 2024-01-29 12:11
For now I added a compiler flag to ignore the problematic code during simulator builds:

```
#if !targetEnvironment(simulator)
        .contentMarginsDisabled()
#endif
```
