### ISSUE TITLE
Images built since 11/01 introduced a bug from Docker Compose

### ISSUE THREAD

**Issue by bLuka** [actions/runner-images#9175] opened 2024-01-16 15:19 UTC
### Description

The bug prevents Docker Compose to parse any `docker-compose.yml` when the services contain a dot. This breaks all pipelines in such a case: https://github.com/docker/compose/issues/11336

It appears the runner doesn’t have the bug all the time, even on v2.311.0. However, Ubuntu containers versions `20240114.1.0` (tried on both Ubuntu 22.04 & 20.04) contain the faulty version of Docker Compose (2.24.0).

I believe managed runners are in a rolling upgrade since we have only few of our jobs running on `20240114.1.0`. However, since we have a lot of jobs, all our pipelines started failing.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`v2.311.0` (builds `20240114.1.0` and laters)

### Is it regression?

Yes, since builds `20240107.1.0` and earlier. Docker Compose stopped working completely in specific circumstances due to YAML parsing.

### Expected behavior

Docker Compose should work with no issue on valid `docker-compose.yml` containing dots in service names.

### Actual behavior

Docker Compose bug has been introduced from a failing Docker Compose dependency (https://github.com/docker/compose/issues/11336). The bug appears on a specific circumstances when parsing YAML files with one or multiple services containing a dot in their name.

### Repro steps

1. Prepare a `docker-compose.yml` with services names including dots
2. Run `docker compose` in a pipeline using a runner v2.311.0 & build version `20240114.1.0`
3. See error: `3 error(s) decoding: * 'services[dx-ref-java-quarkus-im-postgres.postgres-db].ports[0]' expected a map, got 'string'`

**Comment by sergei-pyshnoi** [comment] 2024-01-16 15:35
closing as duplicate of https://github.com/actions/runner-images/issues/9172

**Closed by sergei-pyshnoi** 2024-01-16 15:35 UTC
Labels: needs triage, bug report
