### ISSUE TITLE
No option for Xcode 16 + visionOS 

### ISSUE THREAD

**Issue by Saadnajmi** [actions/runner-images#10955] opened 2024-11-12 19:27 UTC
### Description

We use Azure Pipelines to build [React Native macOS](https://github.com/microsoft/react-native-macos). For this, we need both Xcode 16, and the visionOS SDK. Both have been dropped from the image we use: `macos-latest-internal`. I tried switching to macos-15, but that is not an Arm64 pool, so it doesn't have visionOS. 

At this point, I'm left with no image on Azure Pipelines with both Xcode 16 and visionOS, which blocks our workflow. 

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [X] macOS 15
- [X] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://dev.azure.com/ms/react-native/_build/results?buildId=617324&view=results

### Is it regression?

Yes, macos-14 / macos-latest-internal had Xcode 16: https://dev.azure.com/ms/react-native/_build/results?buildId=617191&view=results

### Expected behavior

There should be some image with Xcode 16 and visionOS avaiable

### Actual behavior

There is not

### Repro steps

Try to use both Xcode 16 and visionOS in an Azure Pipelines  pipeline.

**Comment by aartis17** [comment] 2024-11-13 06:17
Hi @Saadnajmi: We will look into the issue and keep you posted with updates.

**Comment by Marquis103** [comment] 2024-11-13 20:05
i have the same regression on macos-14

**Comment by BrentMifsud** [comment] 2024-11-13 20:17
seems like Xcode 16 is missing entirely from the macOS-latest-xlarge as well

![image](https://github.com/user-attachments/assets/322ba7f2-7e96-4cd7-8cd8-bf2544f8b7bb)

**Comment by BrentMifsud** [comment] 2024-11-13 20:35
I managed to fix this by using: `macos-15-xlarge` instead of `macos-latest-xlarge` seems `macos-latest`, is not actually the latest macOS.

**Comment by DonkeyKongJr** [comment] 2024-11-14 07:21
I got the very same problem, XCODE 16 randomly disappeared since yesterday.

https://stackoverflow.com/questions/79187710/hosted-azure-pipeline-for-net-maui-ios-app-fails-with-could-not-find-a-valid-x

**Comment by santihcc** [comment] 2024-11-14 11:12
I have commented the same on the post referenced by @DonkeyKongJr, but I will add it here too for simplicity: https://stackoverflow.com/questions/79187710/hosted-azure-pipeline-for-net-maui-ios-app-fails-with-could-not-find-a-valid-x

It seems that XCode 16 has been removed from macOS-14: https://github.com/actions/runner-images/issues/10703

In my case, I have updated my vmImage to macOS-15 and it works fine but unfortunately some people may have to rework their pipelines if they rely on macOS-14.

**Comment by B4DG3R** [comment] 2024-11-15 12:07
> I managed to fix this by using: `macos-15-xlarge` instead of `macos-latest-xlarge` seems `macos-latest`, is not actually the latest macOS.

I can confirm this worked for us also

**Comment by prasanjitsahoo** [comment] 2024-11-18 07:24
Hey @Saadnajmi :wave:
We are closing this issue as a partial duplicate and to track the updates on this issue here: https://github.com/actions/runner-images/issues/10703

In short: It was decided to return Xcode 16 to the macOS-14 based images including mentioned internal pool. 

Also we should notice that label `latest` not always means exactly `newest available`. It's more like `latest stable`. For now the latest available is `macos-15`, but the image is in `beta` status and once will be available as `latest`.
The problem with certificates is related to the update to OpenSSL@3 which might be tracked here: https://github.com/actions/runner-images/issues/10817. The next images will contain version OpenSSL@1.1 until the task developers prepare for the changes.

**Closed by prasanjitsahoo** 2024-11-18 07:24 UTC
Labels: Area: Apple, Area: Image administration, bug report

**Comment by jpike88** [comment] 2025-03-06 06:36
It's more like `latest stable`

So why isn't it just called `stable`, or like `latest stable`, if it's more like those things, and less like what `latest` means?
