### ISSUE TITLE
Degrade cocoapod version to 1.14

### ISSUE THREAD

**Issue by Computeeeeeeeeee** [actions/runner-images#9332] opened 2024-02-10 04:55 UTC
### Tool name

Cocoapods

### Tool license

Cocoapods 1.14

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.14

### Brief description of tool

Macos images were updates on feb 02 which updated cocoapod version to 1.15 which is not supporting.. any way we can downgrade to 1.14

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by Alexey-Ayupov** [comment] 2024-02-12 09:35
Hello @Computeeeeeeeeee, what kind of problem do you have with CocoaPods v1.15.0? As I can see our nightly builds already have CocoaPods 1.15.2 on the board. I hope the latest version will fix your problem.

**Comment by Alexey-Ayupov** [comment] 2024-02-12 09:58
Closed as duplicate of https://github.com/actions/runner-images/issues/9308

**Closed by Alexey-Ayupov** 2024-02-12 09:58 UTC
Labels: OS: macOS, feature request
