### ISSUE TITLE
Update Cocoapods

### ISSUE THREAD

**Issue by Navaie** [actions/runner-images#9351] opened 2024-02-14 17:54 UTC
### Tool name

Cocoapods

### Tool license

MIT

### Add or update?

- [ ] Add
- [X] Update

### Desired version

1.15.2

### Brief description of tool

[1.15.2](https://github.com/CocoaPods/CocoaPods/releases/tag/1.15.2) [Latest](https://github.com/CocoaPods/CocoaPods/releases/latest)
#### Enhancements
- None.
#### Bug Fixes
- Revert https://github.com/CocoaPods/CocoaPods/pull/12154, https://github.com/CocoaPods/CocoaPods/pull/12165, and https://github.com/CocoaPods/CocoaPods/pull/12158 to fix regressions in 1.15.0 and 1.15.1.
[Paul Beusterien](https://github.com/paulb777)
https://github.com/CocoaPods/CocoaPods/issues/12226

### URL for tool's homepage

https://cocoapods.org/

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Are you willing to submit a PR?

Yes

**Comment by Alexey-Ayupov** [comment] 2024-02-14 19:50
Closed as duplicate of https://github.com/actions/runner-images/issues/9308

**Closed by Alexey-Ayupov** 2024-02-14 19:50 UTC
Labels: duplicate, Area: Ruby, OS: macOS, feature request
