### ISSUE TITLE
Multiple version error when validating dotnet-sdk install in image ubuntu22.04

### ISSUE THREAD

**Issue by mortenlerudjordet** [actions/runner-images#8277] opened 2023-09-13 09:24 UTC
### Description

From pipeline logs building latest version of runner-image repo.
```
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0 (5680fa18f 2023-08-23)`
Multiple versions from list '6.0.413, 6.0.414, 7.0.111, 7.0.203, 7.0.308, 7.0.401' return the same result from regex '^\d+\.\d+\.\d': 6.0.4
At /imagegeneration/SoftwareReport/software-report-base/SoftwareReport.Nodes.psm1:259 char:17
```
SoftwareReport.Generator.ps1
```
$netCoreTools.AddToolVersionsListInline(".NET Core SDK", $(Get-DotNetCoreSdkVersions), "^\d+\.\d+\.\d")
```
From looking at the error the regex does not take into consideration that the last part of the version number can be multiple numbers. And as there are two version with 6.0.4 in them will fail the test.

For this scenario the correct regex to use would be **'^\d+\.\d+\.\d+'**?
Or make sure to remove the conflicting versions?

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

No link

### Is it regression?

No

### Expected behavior

The function ValidateMajorVersionRegex in SoftwareReport.Nodes.psm1 should not throw an error when comparing versions of .NET Core SDK that contains multiple last version digits.

### Actual behavior

Throwing error:
**Multiple versions from list '6.0.413, 6.0.414, 7.0.111, 7.0.203, 7.0.308, 7.0.401' return the same result from regex '^\d+\.\d+\.\d': 6.0.4**

### Repro steps

Build image using the latest version of runner-images repo from main branch.

**Comment by shamil-mubarakshin** [comment] 2023-09-13 09:50
Hello @mortenlerudjordet, thanks for reporting.
It is related to `dotnet-sdk` rather than `rustc`. We are looking into this

**Comment by mroussel** [comment] 2023-09-13 14:35
I am not sure why, but the script https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/dotnetcore-sdk.sh installs the latest version from APT and from a tar.gz file.

Right now, the latest version 614 is not available in the apt repo. https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-6.0/

As a result, two versions are installed in the image.

**Comment by Maetis** [comment] 2023-09-13 14:40
> I am not sure why, but the script https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/dotnetcore-sdk.sh installs the latest version from APT and from a tar.gz file.
> 
> Right now, the latest version 614 is not available in the apt repo. https://packages.microsoft.com/ubuntu/22.04/prod/pool/main/d/dotnet-sdk-6.0/
> 
> As a result, two versions are installed in the image.

Exactly!

**Comment by Jaykul** [comment] 2023-09-13 17:14
Should check the code against that error message. The error messages says "\d+.\d+.\d" (when it should be "\d+.\d+.\d+" with a + on the end), which would lead to treating x.y.1 as "the same" as x.y.199

**Comment by Maetis** [comment] 2023-09-13 18:03
> Should check the code against that error message. The error messages says "\d+.\d+.\d" (when it probably should be "\d+.\d+.\d+" with a + on the end), which would lead to treating x.y.1 as "the same" as x.y.199
> 
> [That pattern is repeated in many copies of that SoftwareReport script](https://github.com/search?q=repo%3Aactions%2Frunner-images%20%5E%5Cd%2B%5C.%5Cd%2B%5C.%5Cd&type=code), so maybe it's intentional, but it looks wrong to me...

Maybe because they suppose that it should have only one major version for each tool.

**Comment by Jaykul** [comment] 2023-09-14 03:28
> > Should check the code against that error message. The error messages says "\d+.\d+.\d" (when it probably should be "\d+.\d+.\d+" with a + on the end), which would lead to treating x.y.1 as "the same" as x.y.199
> > [That pattern is repeated in many copies of that SoftwareReport script](https://github.com/search?q=repo%3Aactions%2Frunner-images%20%5E%5Cd%2B%5C.%5Cd%2B%5C.%5Cd&type=code), so maybe it's intentional, but it looks wrong to me...
> 
> Maybe because they suppose that it should have only one major version for each tool.

I don't follow. This is checking the major.minor.{ First digit of the minor }

You can't treat 1.2.1 and 1.2.2 as different, but treat 1.2.10 as a duplicate of 1.2.1

**Comment by mortenlerudjordet** [comment] 2023-09-14 06:05
Another improvement to consider is to add the name of the package being processed in the error message.
Example:
```
hidden [void] ValidateMajorVersionRegex() {
	$this.Versions | Group-Object { $this.ExtractMajorVersion($_) } | ForEach-Object {
		if ($_.Count -gt 1) {
			throw "$($this.ToolName): Multiple versions from list '$($this.GetValue())' return the same result from regex '$($this.MajorVersionRegex)': $($_.Name)"
		}
	}
}
```
```
"$($this.ToolName): Multiple versions from list '$($this.GetValue())' return the same result from regex '$($this.MajorVersionRegex)': $($_.Name)"
```
Currently it was a bit challenging to track down the actual package that threw the error.

**Comment by mikhailkoliada** [comment] 2023-09-14 19:42
The problem was not in the regex though, we install only latest major releases up to the patch version, we use both apt packages from packages.microsoft.com and the official blob storage to download the latest versions of SDKs, in this specific case the apt repo got updated later than the blob sources, as a result we ended up having two different patch versions for the same major-minor which caused collision. As of now, the apt repo got updated with the latest SDK patch version and the problem is now gone. Do not forget to sync your main before running a new build! I am going to close the issue, but feel free to reach us again if you have questions left.

**Closed by mikhailkoliada** 2023-09-14 19:42 UTC
Labels: OS: Ubuntu, Area: Image administration, bug report

**Comment by Maetis** [comment] 2023-09-14 20:02
> The problem was not in the regex though, we install only latest major releases up to the patch version, we use both apt packages from packages.microsoft.com and the official blob storage to download the latest versions of SDKs, in this specific case the apt repo got updated later than the blob sources, as a result we ended up having two different patch versions for the same major-minor which caused collision. As of now, the apt repo got updated with the latest SDK patch version and the problem is now gone. Do not forget to sync your main before running a new build! I am going to close the issue, but feel free to reach us again if you have questions left.

Just for my understanding, why are you installing the .Net Sdks this way?

**Comment by mikhailkoliada** [comment] 2023-09-17 17:30
@Maetis as far as I remember there were some considerable packaging differences between the apt and blob versions, that is why we install both
