### ISSUE TITLE
Links in the logs of the "Set up job" step of CI jobs returning 404 "not found" errors 

### ISSUE THREAD

**Issue by DeeDeeG** [actions/runner-images#9010] opened 2023-12-13 04:52 UTC
### Description

"Included Software" and "Image Release" links return 404 errors, from the logs of the "Set up job" step of CI jobs. (As seen in GitHub Actions.)

These links _should_ show info like what software is included in the runner. The links are working at the moment for Windows and Linux jobs, however the macOS links point to resources at this repo that don't exist at the time I go to check them.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Example Job 1: https://github.com/pulsar-edit/ppm/actions/runs/7190662896/job/19584151209#step:1:10

> Image: macos-12
> Version: 20230921.1
> **Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230921.1/images/macos/macos-12-Readme.md**
> **Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230921.1**

---

Example job 2: https://github.com/pulsar-edit/ppm/actions/runs/7190724712/job/19584317996#step:1:10

> Image: macos-12
> Version: 20231128.1
> **Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231128.1/images/macos/macos-12-Readme.md**
> **Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231128.1**

**_"Included Software" and "Image Release" links are broken!_**

### Is it regression?

I don't know, but I believe it's been happening for several months now, since I can recall it happening a while ago too.

### Expected behavior

These links should point to real pages (so I can learn more about the version of the runner image the job is running on)

### Actual behavior

Links return 404 errors.

The links apparently point to tags/refs/releases for this repo that are *not* live in this repo at the time I follow the links. Maybe the refs/tags/releases used to exist, but were deleted/pruned since the runner versions were made? Maybe the links point to fictitious resources that never existed -- links that are simply misformed when generated for inclusion in the logs of the CI jobs?

### Repro steps

- Run a CI job on a macOS runner in GitHub Actions.
- Try to follow a link in the output from the "Set up job" step.

(Not sure if it happens on Azure DevOps, as we're just using GitHub Actions at the moment. It may also be unrelated to OS and just an intermittent issue for any OS's images. Only seeing it on the `macos-latest` images at the moment, though.)

**Comment by mikhailkoliada** [comment] 2023-12-13 08:14
Duplicate of https://github.com/actions/runner-images/issues/8642

**Closed by mikhailkoliada** 2023-12-13 08:14 UTC
Labels: Area: Apple, bug report
