### ISSUE TITLE
Linux coretools are missing from Azure Hosted Runners

### ISSUE THREAD

**Issue by bvaughan527** [actions/runner-images#9196] opened 2024-01-19 14:50 UTC
### Description

Linux coretools such as grep are missing form the latest runner image release below:

Starting: Initialize job
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az243-61'
Current agent version: '3.232.1'
**Operating System
Ubuntu
22.04.3
LTS
Runner Image
Image: ubuntu-22.04
Version: 20240116.3.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
Runner Image Provisioner
Current image version: '20240116.3.0'**
Agent running as: 'vsts'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: Bash (3.231.5)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /opt/hostedtoolcache Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: AgentPerflog = /home/vsts/perflog Source: ${VSTS_AGENT_PERFLOG} 
   Knob: AgentEnablePipelineArtifactLargeChunkSize = true Source: $(AGENT_ENABLE_PIPELINEARTIFACT_LARGE_CHUNK_SIZE) 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
   Knob: ProcessHandlerTelemetry = true Source: $(AZP_75787_ENABLE_COLLECT) 
   Knob: IgnoreVSTSTaskLib = true Source: $(AZP_AGENT_IGNORE_VSTSTASKLIB) 
   Knob: CheckForTaskDeprecation = true Source: $(AZP_AGENT_CHECK_FOR_TASK_DEPRECATION) 
Finished checking job knob settings.
Start tracking orphan processes.
Finishing: Initialize job

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: ubuntu-22.04
Version: 20240116.3.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240116.3/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240116.3
Runner Image Provisioner
Current image version: '20240116.3.0'**

### Is it regression?

No

### Expected behavior

The coreutils ubuntu package should be installed in the runner image.

### Actual behavior

Tools that are part of the coreutils package are not found, e.g. grep.

### Repro steps

Steps to reproduce:

1. Create an ADO pipeline that includes a bash task.
2. Use the bash task to run an inline script that uses grep or a tool in the coreutils package
3. Observe that bash returns, `command not found.`

**Comment by sergei-pyshnoi** [comment] 2024-01-19 16:05
Hello @bvaughan527 . Unfortunately we cannot reproduce your issue. 
![image](https://github.com/actions/runner-images/assets/121864472/b9015e2a-38fb-48ea-841a-b081406b4698)

Also its almost impossible that tool such a grep is missing, because some of them used for image generation. Please double check that you pipeline doesn`t use container or etc.  I am closing this issue, but if you have additional questions feel free to ask.

**Closed by sergei-pyshnoi** 2024-01-19 16:05 UTC
Labels: needs triage, bug report

**Comment by bvaughan527** [comment] 2024-01-19 16:40
Thanks @sergei-pyshnoi . My issue was using the ubuntu-latest Azure hosted pool. However, 15 minutes after I logged this issue, I could not reproduce the issue. So it would appear that the runner that was assigned to my build had issues.

**Comment by erik-bershel** [comment] 2024-01-19 17:00
Hey @bvaughan527! Please send a link to the failed job, even if it's a private project - I'll check to make sure the problem was transitive.

**Comment by bvaughan527** [comment] 2024-01-19 18:19
> Hey @bvaughan527! Please send a link to the failed job, even if it's a private project - I'll check to make sure the problem was transitive.

Hi @erik-bershel Thank you for the follow-up. Here are the links to the failed jobs:

- Failure on 19-Jan-24 at 08:11 EST: https://dev.azure.com/nbadev/DTC/_build/results?buildId=307775&view=logs&j=74d61701-3d85-5c6d-5a5b-a6c8178dabc6
- Failure on 19-Jan-24 at 08:10 EST: https://dev.azure.com/nbadev/DTC/_build/results?buildId=307773&view=logs&j=74d61701-3d85-5c6d-5a5b-a6c8178dabc6
