### ISSUE TITLE
Ubuntu2204 image failing after Homebrew

### ISSUE THREAD

**Issue by gstevens-kyriba** [actions/runner-images#6979] opened 2023-01-24 17:01 UTC
### Description

If I run 

```
Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId ... -ResourceGroupName "..." -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "West US 3" -AzureClientId ... -AzureClientSecret ... -AzureTenantId ...
```

It runs for a long time building and then hangs after installing homebrew..   `Missing: SoftwareReport.psm1' was not loaded because no valid module file was found in any module directory.`

Here is the last of the log:

`==> azure-arm.build_vhd:  * [new tag]             3.6.7                   -> 3.6.7
==> azure-arm.build_vhd:  * [new tag]             3.6.8                   -> 3.6.8
==> azure-arm.build_vhd:  * [new tag]             3.6.9                   -> 3.6.9
    azure-arm.build_vhd: HEAD is now at 462c69d3d Merge pull request #14404 from Homebrew/sponsors-maintainers-man-completions
    azure-arm.build_vhd: ==> Tapping homebrew/core
==> azure-arm.build_vhd: From https://github.com/Homebrew/homebrew-core
==> azure-arm.build_vhd:  * [new branch]              master     -> origin/master
    azure-arm.build_vhd: HEAD is now at 2e5889864fb newrelic-cli: update 0.61.4 bottle.
==> azure-arm.build_vhd: ==> Downloading https://ghcr.io/v2/homebrew/portable-ruby/portable-ruby/blobs/sha256:fc45ee6eddf4c7a17f4373dde7b1bc8a58255ea61e6847d3bf895225b28d072a
==> azure-arm.build_vhd: ######################################################################## 100.0%
==> azure-arm.build_vhd: ==> Pouring portable-ruby-2.6.8_1.x86_64_linux.bottle.tar.gz
    azure-arm.build_vhd: Warning: /home/linuxbrew/.linuxbrew/bin is not in your PATH.
    azure-arm.build_vhd:   Instructions on how to configure your shell for Homebrew
    azure-arm.build_vhd:   can be found in the 'Next steps' section below.
    azure-arm.build_vhd: ==> Installation successful!
    azure-arm.build_vhd:
    azure-arm.build_vhd: ==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
    azure-arm.build_vhd: Read the analytics documentation (and how to opt-out) here:
    azure-arm.build_vhd:   https://docs.brew.sh/Analytics
    azure-arm.build_vhd: No analytics data has been sent yet (nor will any be during this install run).
    azure-arm.build_vhd:
    azure-arm.build_vhd: ==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
    azure-arm.build_vhd:   https://github.com/Homebrew/brew#donations
    azure-arm.build_vhd:
    azure-arm.build_vhd: ==> Next steps:
    azure-arm.build_vhd: - Run these three commands in your terminal to add Homebrew to your PATH:
    azure-arm.build_vhd:     echo '# Set PATH, MANPATH, etc., for Homebrew.' >> /home/packer/.profile
    azure-arm.build_vhd:     echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/packer/.profile
    azure-arm.build_vhd:     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    azure-arm.build_vhd: - Install Homebrew's dependencies if you have sudo access:
    azure-arm.build_vhd:     sudo apt-get install build-essential
    azure-arm.build_vhd:   For more information, see:
    azure-arm.build_vhd:     https://docs.brew.sh/Homebrew-on-Linux
    azure-arm.build_vhd: - We recommend that you install GCC:
    azure-arm.build_vhd:     brew install gcc
    azure-arm.build_vhd: - Run brew help to get started
    azure-arm.build_vhd: - Further documentation:
    azure-arm.build_vhd:     https://docs.brew.sh
    azure-arm.build_vhd:
    azure-arm.build_vhd: HOMEBREW_NO_AUTO_UPDATE=1
    azure-arm.build_vhd: HOMEBREW_CLEANUP_PERIODIC_FULL_DAYS=3650
    azure-arm.build_vhd: Validate the installation reloading /etc/environment
    azure-arm.build_vhd: Pester v5.4.0
    azure-arm.build_vhd:
    azure-arm.build_vhd: Starting discovery in 1 files.
    azure-arm.build_vhd: Discovery found 100 tests in 498ms.
    azure-arm.build_vhd: Filter 'FullName' set to ('Homebrew').
    azure-arm.build_vhd: Filters selected 1 tests to run.
    azure-arm.build_vhd: Running tests.
    azure-arm.build_vhd:
    azure-arm.build_vhd: Running tests from '/imagegeneration/tests/Tools.Tests.ps1'
    azure-arm.build_vhd: Describing Homebrew
    azure-arm.build_vhd:   [+] homebrew 144ms (112ms|32ms)
    azure-arm.build_vhd: Tests completed in 868ms
    azure-arm.build_vhd: Tests Passed: 1, Failed: 0, Skipped: 0 NotRun: 99
==> azure-arm.build_vhd: Provisioning with shell script: C:/agent/_work/1/s/images/linux/scripts/base/snap.sh
==> azure-arm.build_vhd: Provisioning with shell script: C:/agent/_work/1/s/images/linux/scripts/base/reboot.sh
    azure-arm.build_vhd: Reboot VM
==> azure-arm.build_vhd: Pausing 1m0s before the next provisioner...
==> azure-arm.build_vhd: Provisioning with shell script: C:/agent/_work/1/s/images/linux/scripts/installers/cleanup.sh
    azure-arm.build_vhd: /usr/bin/journalctl
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/user-1000@847dbd484d4548aab965475b0054ef17-0000000000223f2f-0005f2f6f54ee979.journal (8.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-0000000000224186-0005f2f6f6007cd4.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/user-1000@847dbd484d4548aab965475b0054ef17-00000000002272a5-0005f2f6f75a1149.journal (8.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-000000000022a434-0005f2f6fb603739.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-0000000000230547-0005f2f6fd3a7ecd.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/user-1000@847dbd484d4548aab965475b0054ef17-0000000000235133-0005f2f7056a2aa7.journal (8.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-0000000000236648-0005f2f7092c4f49.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-000000000023cb47-0005f2f70a2b9997.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-00000000002426b7-0005f2f70a764b59.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-00000000002480fb-0005f2f70b051ef0.journal (25.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/system@b5471cca7c004e399fbf3daccc8453c1-000000000024dc01-0005f2f70b6dd1e8.journal (24.0M).
==> azure-arm.build_vhd: Deleted archived journal /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9/user-1000@847dbd484d4548aab965475b0054ef17-000000000024e609-0005f2f70bd6b288.journal (8.0M).
==> azure-arm.build_vhd: Vacuuming done, freed 231.3M of archived journals from /var/log/journal/fced9a6d95204fc38b27441cac2dbfe9.
==> azure-arm.build_vhd: Vacuuming done, freed 0B of archived journals from /var/log/journal.
==> azure-arm.build_vhd: Vacuuming done, freed 0B of archived journals from /run/log/journal.
    azure-arm.build_vhd: Before: 33013 MB
    azure-arm.build_vhd: After : 35912 MB
    azure-arm.build_vhd: Delta : 2899 MB
==> azure-arm.build_vhd: Provisioning with shell script: C:/agent/_work/1/s/images/linux/scripts/base/apt-mock-remove.sh
==> azure-arm.build_vhd: Provisioning with shell script: C:\Users\devops\AppData\Local\Temp\2\packer-shell1068847829

==> azure-arm.build_vhd: [31;1mInvalidOperation: [31;1mThe specified module '/imagegeneration/SoftwareReport/software-report-base/SoftwareReport.psm1' was not loaded because no valid module file was foun
d in any module directory.[0m
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed`

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 22.04

### Is it regression?

idk

### Expected behavior

The image should build

### Actual behavior

the image fails to complete

### Repro steps

Clone the repo, run GenerateResourcesAndImage.ps1 with your env vars.

Import-Module .\helpers\GenerateResourcesAndImage.ps1

GenerateResourcesAndImage -SubscriptionId ... -ResourceGroupName "..." -ImageGenerationRepositoryRoot "$pwd" -ImageType Ubuntu2204 -AzureLocation "West US 3" -AzureClientId ... -AzureClientSecret ... -AzureTenantId ...

**Comment by Alexey-Ayupov** [comment] 2023-01-25 08:15
Hello @gstevens-kyriba, We'll take a look at it.

**Comment by Alexey-Ayupov** [comment] 2023-01-25 11:32
We couldn't reproduce the issue, could you please check the existence of the file "/imagegeneration/SoftwareReport/software-report-base/SoftwareReport.psm1".

**Comment by gstevens-kyriba** [comment] 2023-01-25 16:13
I can confirm it's under: runner-images/tree/main/helpers/software-report-base/SoftwareReport.psm1

but where is "/imagegeneration/SoftwareReport/" ?

**Comment by gstevens-kyriba** [comment] 2023-01-25 16:53
==> azure-arm.build_vhd: Provisioning with shell script: C:\Users\devops\AppData\Local\Temp\2\packer-shell725655390
==> azure-arm.build_vhd: [31;1mInvalidOperation: [31;1mThe specified module '/imagegeneration/SoftwareReport/software-report-base/SoftwareReport.psm1' was not loaded be
cause no valid module file was found in any module directory.[0m
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed

**Comment by gstevens-kyriba** [comment] 2023-01-25 18:45
Well at least it found the script this time...
```
==> azure-arm.build_vhd: Provisioning with shell script: C:/agent/_work/1/s/images/linux/scripts/base/apt-mock-remove.sh
==> azure-arm.build_vhd: Provisioning with shell script: C:\Users\devops\AppData\Local\Temp\2\packer-shell3367337606
==> azure-arm.build_vhd: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : [31;1mThe term 'swift' is not recognized as a name of a cmdlet, function, script file, or executable program.
==> azure-arm.build_vhd: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
==> azure-arm.build_vhd: + CategoryInfo          : ObjectNotFound: (swift:String) [SoftwareReport.Generator.ps1], CommandNotFoundException
==> azure-arm.build_vhd: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1[0m
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed

```

**Comment by gstevens-kyriba** [comment] 2023-01-25 19:31
The Packer logs fails with: 

```
2023/01/25 18:44:02 packer.exe plugin: [DEBUG] starting remote command: chmod +x /tmp/script_842.sh; IMAGE_VERSION='dev' INSTALLER_SCRIPT_FOLDER='/imagegeneration/installers' PACKER_BUILDER_TYPE='azure-arm' PACKER_BUILD_NAME='build_vhd'  /tmp/script_842.sh
2023/01/25 18:44:12 ui error: ==> azure-arm.build_vhd: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : [31;1mThe term 'swift' is not recognized as a name of a cmdlet, function, script file, or executable program.
2023/01/25 18:44:12 ui error: ==> azure-arm.build_vhd: Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2023/01/25 18:44:12 ui error: ==> azure-arm.build_vhd: + CategoryInfo          : ObjectNotFound: (swift:String) [SoftwareReport.Generator.ps1], CommandNotFoundException
2023/01/25 18:44:12 ui error: ==> azure-arm.build_vhd: + FullyQualifiedErrorId : CommandNotFoundException,SoftwareReport.Generator.ps1[0m
2023/01/25 18:44:12 packer.exe plugin: [ERROR] Remote command exited with '1': chmod +x /tmp/script_842.sh; IMAGE_VERSION='dev' INSTALLER_SCRIPT_FOLDER='/imagegeneration/installers' PACKER_BUILDER_TYPE='azure-arm' PACKER_BUILD_NAME='build_vhd'  /tmp/script_842.sh
2023/01/25 18:44:12 packer.exe plugin: [INFO] RPC endpoint: Communicator ended with: 1
2023/01/25 18:44:12 [INFO] 0 bytes written for 'stdout'
2023/01/25 18:44:12 [INFO] 478 bytes written for 'stderr'
2023/01/25 18:44:12 [INFO] RPC client: Communicator ended with: 1
2023/01/25 18:44:12 [INFO] RPC endpoint: Communicator ended with: 1
2023/01/25 18:44:12 packer.exe plugin: [INFO] 0 bytes written for 'stdout'
2023/01/25 18:44:12 packer.exe plugin: [INFO] 478 bytes written for 'stderr'
2023/01/25 18:44:12 packer.exe plugin: [INFO] RPC client: Communicator ended with: 1
2023/01/25 18:44:12 [INFO] (telemetry) ending shell
2023/01/25 18:44:12 ui error: ==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
2023/01/25 18:44:12 ui: ==> azure-arm.build_vhd: Step "StepProvision" failed
```

**Comment by gstevens-kyriba** [comment] 2023-01-25 21:46
So, I was able to get this to work with the main branch, but I had to copy the runner-images-main\helpers\software-report-base to the folder runner-images-main\images\linux\scripts\SoftwareReport.   The SoftwareReport.Generator.ps1 references the base: 
and looks for it in the local path..   after copying this folder, the image build completes.

```
using module ./software-report-base/SoftwareReport.psm1
using module ./software-report-base/SoftwareReport.Nodes.psm1
```

**Comment by Alexey-Ayupov** [comment] 2023-01-26 09:23
Nice to hear that you managed to solve your problem.

We will close the issue in that case, if you have any questions feel free to reach us.

**Closed by Alexey-Ayupov** 2023-01-26 09:23 UTC
Labels: OS: Ubuntu, bug report

**Comment by gstevens-kyriba** [comment] 2023-01-26 15:21
Are the scripts in the correct location?
