### ISSUE TITLE
ubuntu-latest fails CI - 20.04 succeeds

### ISSUE THREAD

**Issue by dromer** [actions/runner-images#8699] opened 2023-11-01 13:11 UTC
### Description

When pushing a docs update one of my CI steps completely fails on the current `ubuntu-latest` image.
Since no code was changed the fault must be with the image.

The last known run to succeed was several weeks ago: https://github.com/Wasted-Audio/hvcc/actions/runs/6512386576/job/17689911222#step:6:22

What is expect is the stdout of a binary is compared line-by-line to a known good output file.
In the case of the faulty run somehow the stdout returns 0 lines.

The CI step before this one is very similar, but succeeds.

It might be related to https://github.com/actions/runner-images/issues/8659 since clang is used.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/Wasted-Audio/hvcc/actions/runs/6716331081/job/18252650852#step:6:22

### Is it regression?

no idea, don't know how to specify versions

### Expected behavior

no failure

### Actual behavior

specific step in my CI fails

### Repro steps

see CI link

**Comment by erik-bershel** [comment] 2023-11-01 17:09
Hi again @dromer! We'll investigate the issue. It will be easier to do since you use public project.

**Comment by erik-bershel** [comment] 2023-11-07 18:36
Hey @dromer!
I apologise that the troubleshoot took so long. I checked the [workaround](https://github.com/actions/runner-images/issues/8659#issuecomment-1785481908) provided in the original issue and it [turns out](https://github.com/erik-bershel/hvcc/actions/runs/6788759356) that the problem is indeed a duplicate of https://github.com/actions/runner-images/issues/8659. In this regard, you can use the specified workaround (it will cost you about 15 seconds for each execution) or continue to use yours (use Ubuntu-20.04) until the image with the fix arrives.
Due to this, I intend to close this issue as a duplicate, please stay tuned for updates here: https://github.com/actions/runner-images/issues/8659. Also feel free to open new items in case of other concerns.

**Closed by erik-bershel** 2023-11-07 18:36 UTC
Labels: duplicate, OS: Ubuntu, Area: Clang, bug report

**Comment by dromer** [comment] 2023-11-07 18:39
@erik-bershel thnx! I just got notified of your successful run and took a look at what you did.

I think I'll wait until that newer image comes out. 20.04 is not a huge issue for me, but I'll follow that other issue and maybe update when the time comes.

Thnx for confirming!
