### ISSUE TITLE
Android-sdk installation error

### ISSUE THREAD

**Issue by saoullabit** [actions/runner-images#6985] opened 2023-01-26 09:00 UTC
### Description

Using the creation script for Windows 2022 (runner-images-win22-20230118.1) the step : Android-sdk fails
The error is : 
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/prefs/AndroidLocationsProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

==> vhd:     + CategoryInfo          : InvalidData: (:) [Install-AndroidSDKPackages], ParentContainsErrorRecordException
==> vhd:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Install-AndroidSDKPackages

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

We build the image on a VM on our own, we do not use GitHub or Azure Devops ...
Image is : win22 20230109.1
https://github.com/actions/runner-images/releases/tag/win22%2F20230109.1

### Is it regression?

Yes, win22/20230109.1 (https://github.com/actions/runner-images/releases/tag/win22%2F20230109.1)

### Expected behavior

The image is build without error.

### Actual behavior

The image is not build

### Repro steps

Reproduce the error is quite easy : 
Run :
```
Import-Module .\helpers\GenerateResourcesAndImage.ps1
GenerateResourcesAndImage `
    -SubscriptionId xxxxx
    -ResourceGroupName "xxxxx" `
    -ImageGenerationRepositoryRoot "$pwd" `
    -ImageType Windows2022 `
    -AzureLocation "xxxxx"
```
Wait for the error message :)

**Comment by Alexey-Ayupov** [comment] 2023-01-26 09:20
Hello @saoullabit, this is a duplicate of issue #6960.
We have fixed this issue several days ago. Could you please update your fork repository to use the latest versions of files?

We will close this issue as a duplicate, if you have any questions feel free to reach us.

**Closed by Alexey-Ayupov** 2023-01-26 09:20 UTC
Labels: needs triage, bug report
