### ISSUE TITLE
runner user is not in the kvm group

### ISSUE THREAD

**Issue by DaanDeMeyer** [actions/runner-images#8542] opened 2023-10-12 18:32 UTC
### Description

On Debian/Ubuntu, access to /dev/kvm, /dev/vhost-vsock and /dev/vhost-net is gated behind membership of the kvm group. Because the runner user is not part of the kvm group, this means that currently sudo has to be used to run qemu if you want to use any of the features that require these device nodes.

Please add the runner user to the kvm group by default so that sudo is not required to use these features.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Latest image

### Is it regression?

This is not a regression

### Expected behavior

I can use KVM or VSOCK with qemu without needing sudo

### Actual behavior

I need sudo to use qemu with KVM or VSOCK.

### Repro steps

Try to run qemu with `-device vhost-vsock-pci,guest-cid=123` without sudo. This will fail with permission denied. If the runner user is added to the kvm group, this will succeed without permission errors.

**Comment by mikhailkoliada** [comment] 2023-10-12 18:37
Marking as duplicate of https://github.com/actions/runner-images/issues/7670 as it has a workaround and the global change is not planned yet

**Closed by mikhailkoliada** 2023-10-12 18:37 UTC
Labels: Area: Apple, OS: macOS, bug report
