### ISSUE TITLE
Build for Windows 2023 and Ubuntu 22.04 fails on Install-WindowsFeature NET-Framework-Features and install-apt-vital.sh/install-powershell.sh respectively

### ISSUE THREAD

**Issue by DevOpsAzurance** [actions/runner-images#9765] opened 2024-04-29 21:06 UTC
### Description

Getting the following on the Windows 2022 build:

`
==> azure-arm.image: Activating Windows Feature 'NET-Framework-Features'...
==> azure-arm.image: Install-WindowsFeature : The request to add or remove features on the specified server failed.
==> azure-arm.image: Installation of one or more roles, role services, or features failed. Error: 0x80072f8f
==> azure-arm.image: At C:\Windows\Temp\script-662ff976-8e58-d562-3c3f-5a1ee43fcdcb.ps1:21 char:19
==> azure-arm.image: +         $result = Install-WindowsFeature @arguments
==> azure-arm.image: +                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : InvalidOperation: (@{Vhd=; Credent...Name=localhost}:PSObject) [Install-WindowsFeature],
==> azure-arm.image:     Exception
==> azure-arm.image:     + FullyQualifiedErrorId : DISMAPI_Error__Failed_To_Enable_Updates,Microsoft.Windows.ServerManager.Commands.AddWind
==> azure-arm.image:    owsFeatureCommand
==> azure-arm.image: Failed to activate Windows Feature 'NET-Framework-Features'
==> azure-arm.image: At C:\Windows\Temp\script-662ff976-8e58-d562-3c3f-5a1ee43fcdcb.ps1:29 char:9
==> azure-arm.image: +         throw "Failed to activate Windows Feature '$($feature.name)'"
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Failed to activ...ework-Features':String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Failed to activate Windows Feature 'NET-Framework-Features'
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
`

For the Linux 22.04 build I get the following:

`
==> azure-arm.build_image: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/b/binutils/binutils-common_2.42-4ubuntu2_amd64.deb  Could not connect to azure.archive.ubuntu.com:80 (40.119.46.219), connection timed out
==> azure-arm.build_image: E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/b/binutils/libsframe1_2.42-4ubuntu2_amd64.deb  Unable to connect to azure.archive.ubuntu.com:http:
    azure-arm.build_image: Err:3 http://azure.archive.ubuntu.com/ubuntu noble/main amd64 libbinutils amd64 2.42-4ubuntu2
    azure-arm.build_image:   Unable to connect to azure.archive.ubuntu.com:http:
`

and

`
==> azure-arm.build_image: Provisioning with shell script: C:/ProgramData/VSTS-Eve-DO-Runners3/_work/9/AgentPacker/images/ubuntu/templates/../scripts/build/install-powershell.sh
==> azure-arm.build_image: Downloading package from http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu72_72.1-3ubuntu2_amd64.deb to /tmp/libicu72_72.1-3ubuntu2_amd64.deb...
==> azure-arm.build_image: curl: (28) Failed to connect to mirrors.kernel.org port 80 after 134251 ms: Couldn't connect to server
==> azure-arm.build_image: Package download failed in 134 seconds
==> azure-arm.build_image: Waiting 30 seconds before retrying (retries left: 20)...
==> azure-arm.build_image: curl: (28) Failed to connect to mirrors.kernel.org port 80 after 133824 ms: Couldn't connect to server
==> azure-arm.build_image: Package download failed in 134 seconds
`

Not sure if maybe it is firewall related on my end, as I see one is over http...not even https and the other one may not have access.  For the windows, if it is going out to the internet, I am not sure what URL that would be.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Current agent version: '3.232.1'
Current image version: 'dev'

### Is it regression?

No

### Expected behavior

The script should download some packages and install features/prerequisites, using the packer install script

### Actual behavior

It fails to build the packer script for the two OSes.  

### Repro steps

From our organizational runner agent, we run the script from the main branch. We also have tried running it from the latest release as well.

**Comment by sergei-pyshnoi** [comment] 2024-04-30 07:28
Hello @DevOpsAzurance . Unfortunately we cannot reproduce your error. Here you can find our nightly builds for [Windows ](https://dev.azure.com/github/runner-images/_build/results?buildId=135527&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f05f5d13-c61c-51fd-2a8c-71d3e56d3e3f)and [Ubuntu](https://dev.azure.com/github/runner-images/_build/results?buildId=135528&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f05f5d13-c61c-51fd-2a8c-71d3e56d3e3f) . Problem could be in your network configuration or temporary problem in packages repos. Please try again later and check your firewall settings. I going closing issue but if you have additional questions or concerns feel free to ask.

**Closed by sergei-pyshnoi** 2024-04-30 07:28 UTC
Labels: needs triage, bug report
