### ISSUE TITLE
Xcode 15.1 isn't available during some runs with macOS 13

### ISSUE THREAD

**Issue by daveisfera** [actions/runner-images#9069] opened 2023-12-27 06:03 UTC
### Description

Xcode 15.1 is listed as [available for macOS 13](https://github.com/actions/runner-images/blob/main/images/macos/macos-13-Readme.md#xcode) but it's not available during some runs

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/maxim-lobanov/setup-xcode/issues/74

### Is it regression?

No

### Expected behavior

Xcode 15.1 would always be available as listed

### Actual behavior

Xcode 15.1 isn't available during some runs so the failed job has to be re-run and hopefully assigned to a runner with 15.1 installed

### Repro steps

Use `setup-xcode` to specify `~15.1.0` and notice that some of the builds fail

**Comment by mikhailkoliada** [comment] 2023-12-27 09:54
Hey, what's the image version ad the build link? Could please you provide those?

**Comment by daveisfera** [comment] 2023-12-27 20:02
All the info in `Set up job` looks the same when it works and when it doesn't, so here's two examples of it failing multiple times and then finally working

1-6 on this one (attempt 7 finally worked):
https://github.com/awresports/pitchaware-charting-app/actions/runs/7335561426/attempts/6
1-2 on this one (attempt 3 worked):
https://github.com/awresports/awresports-app/actions/runs/7335424009/attempts/2

**Comment by mikhailkoliada** [comment] 2023-12-27 20:03
@daveisfera your repo seems to be private so we do not have access

**Comment by daveisfera** [comment] 2023-12-27 20:04
Sorry, I figured you could look up stuff from private repos. Here's the info from `Set up job`:
```
Current runner version: '2.311.0'
Operating System
  macOS
  13.6.3
  22G436
Runner Image
  Image: macos-13-arm64
  Version: 20231218.3
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20231218.3/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20231218.3
Runner Image Provisioner
  2.0.321.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4.1.1' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'extractions/netrc@v1.4.0' (SHA:938ddbfb73b4efee33e57db13aba434b35af2f93)
Download action repository 'actions/setup-node@v4.0.1' (SHA:b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8)
Download action repository 'actions/cache@v3.3.2' (SHA:704facf57e6136b1bc63b828d79edcd491f0ee84)
Download action repository 'maxim-lobanov/setup-xcode@v1.6.0' (SHA:60606e260d2fc5762a71e64e74b2174e8ea3c8bd)
Complete job name: build_ios
```

**Comment by daveisfera** [comment] 2023-12-27 20:06
And then here's the info from one that failed, so it appears that it's an older one that 15.1 hasn't been added to:
```
Current runner version: '2.311.0'
Operating System
  macOS
  13.6.1
  22G313
Runner Image
  Image: macos-13-arm64
  Version: 20231205.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-13/20231205.1/images/macos/macos-13-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-13%2F20231205.1
Runner Image Provisioner
  2.0.321.1
GITHUB_TOKEN Permissions
  Actions: write
  Checks: write
  Contents: write
  Deployments: write
  Discussions: write
  Issues: write
  Metadata: read
  Packages: write
  Pages: write
  PullRequests: write
  RepositoryProjects: write
  SecurityEvents: write
  Statuses: write
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4.1.1' (SHA:b4ffde65f46336ab88eb53be808477a3936bae11)
Download action repository 'extractions/netrc@v1.4.0' (SHA:938ddbfb73b4efee33e57db13aba434b35af2f93)
Download action repository 'actions/setup-node@v4.0.1' (SHA:b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8)
Download action repository 'actions/cache@v3.3.2' (SHA:704facf57e6136b1bc63b828d79edcd491f0ee84)
Download action repository 'maxim-lobanov/setup-xcode@v1.6.0' (SHA:60606e260d2fc5762a71e64e74b2174e8ea3c8bd)
Complete job name: build_ios
```

**Comment by mikhailkoliada** [comment] 2023-12-27 20:25
are you running macOS-13 or macOS-13 xlarge?

**Comment by daveisfera** [comment] 2023-12-27 20:35
`macos-13-xlarge`

**Comment by goergisn** [comment] 2023-12-28 13:44
Same issue here ✋ 

Here the link to an example of a sometimes-failing action: https://github.com/Adyen/adyen-ios/actions/runs/7300509674/job/20005845395?pr=1462

<img width="281" alt="Screenshot 2023-12-28 at 14 42 59" src="https://github.com/actions/runner-images/assets/4838877/b69d5ce2-894f-4e90-bf8e-cff36a6787d2">

**Comment by Alexey-Ayupov** [comment] 2023-12-29 12:25
Hello @daveisfera. After a detailed investigation we have found the root cause of the problem. The problem will gone likely after the next release. Thank you for understanding.

**Comment by daveisfera** [comment] 2023-12-29 16:08
Great to hear! Thanks for helping get this resolved

**Comment by dalemyers** [comment] 2024-01-03 16:26
@Alexey-Ayupov can you share what the issue is? That way we may be able to work around it?

**Comment by mikhailkoliada** [comment] 2024-01-03 18:50
Should be fixed now.

**Closed by mikhailkoliada** 2024-01-03 18:50 UTC
Labels: OS: macOS, bug report

**Comment by mikhailkoliada** [comment] 2024-01-04 16:01
@freef4ll it was fixed without making a new release
