### ISSUE TITLE
Ubuntu 22/04 version 20231217.2.0 does not generate androidx.databinding.DataBindingComponent (part 3)

### ISSUE THREAD

**Issue by stspenke** [actions/runner-images#9080] opened 2023-12-28 13:18 UTC
### Description

This is the third time I am reporting the same issue.
See https://github.com/actions/runner-images/issues/8409 and https://github.com/actions/runner-images/issues/8468

Once more, there is a new runner version that does not generate the androidx.databinding.DataBindingComponent class when I build my project.
This has happened not only twice in October, but also before and after then. Each time, a new release of your runner-images one or more weeks later has fixed it, without anyone ever finding the actual cause.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Ubuntu 22/04 version 20231217.2.0

### Is it regression?

Yes, it worked fine with version 20231205.1.0

### Expected behavior

I expect the build of my project to remain successful with a new version of the runner-image.

### Actual behavior

Since the update to version 20231217.2.0 the build actions for my project fail because the androidx.databinding.DataBindingComponent class is not generated. That is the only error I see, I can't find the reason for this class not being generated anymore.

### Repro steps

I have previously created a public test project which had the same issue as my real project, which is private, but that did not result in any findings. Please have a good look at the differences between the runner-images. Somehow every other new version has this issue.
Let me know if I need to give access to the test project again.

**Comment by Alexey-Ayupov** [comment] 2023-12-28 17:36
Hello @stspenke. Comparing the latest version to 20231205.1.0, only android platform `android-34-ext10` was added to the image in android toolset perspective. In the 20231205.1.0 image version the `android-34-ext8` existed instead, and it still exists in the latest version.
Could you please try to select the `android-34-ext8` in your project and try one more time?

```
Run ls /usr/local/lib/android/sdk/platforms
android-27
android-28
android-29
android-30
android-31
android-32
android-33
android-33-ext4
android-33-ext5
android-34
android-34-ext10
android-34-ext8
```

**Comment by stspenke** [comment] 2024-01-02 16:00
I would love to try your suggestion, but please help me out on how to select the android-34-ext8. How can I specify the SDK platform for the build?

I doubt that this is the problem though, as the previous 2 times I had this issue, the build became successful again after a new update to the runner image. Selecting a specific sdk version was not required then.

**Comment by stspenke** [comment] 2024-01-08 10:09
I have used your piece of script to remove "platforms;android-34-ext10", but I'm sad to see the result is exactly the same.

**Comment by MaksimZhukov** [comment] 2024-01-11 22:00
Hello @stspenke!
Unfortunately, we could not reproduce your issue. Could you please provide us with a link to the public repository where the issue occurs, or create a test project that reproduces the issue? This will help further investigation. Unfortunately, we do not have access to the repositories attached in the previous issues.
Thank you!

**Comment by stspenke** [comment] 2024-01-15 09:48
I have made my test project https://github.com/FDMediagroep/android-failing-build-20231004.git public now. 
It has 2 branches:
- the 'main' one, where the github action 'Manual Dev build' will be unsuccessful with the current runner image (though I have seen successful runs with other runner-images)
- the 'minimizing' one, where all data binding has been removed and the github action is successful.

Thanks a lot for looking into this!

**Comment by stspenke** [comment] 2024-01-24 08:51
@MaksimZhukov @Alexey-Ayupov Is anyone still looking into this?

**Comment by MaksimZhukov** [comment] 2024-01-25 23:14
Hi @stspenke! Sorry for the late reply!
Could you please rerun your builds? Everything works fine with the new image version ([link to the build](https://github.com/MaksimZhukov/android-failing-build-20231004/actions/runs/7661551306)).

**Comment by stspenke** [comment] 2024-01-29 10:56
I noticed that too. Just like the previous 3 times, the problems were resolved after a new image version. Please let me know what the cause of the failing build was. How are you going to prevent that the next image version will (as has happened for 3 times now already) break the builds again?
It makes my work very hard if every new image version might cause me to be without working automatic builds for over a month.
Even though the build is now successful, this issue is not resolved until we know what causes it and the assurance that it can be prevented in the future.

**Comment by MaksimZhukov** [comment] 2024-01-29 22:40
@stspenke, I understand your concerns. 

According to the [support policy](https://github.com/actions/runner-images?tab=readme-ov-file#software-and-image-support), images usually contain the latest versions of packages. New versions of packages may contain bugs. From our side, we test images during their generation and release, but we cannot cover 100% of the cases.

Unfortunately, in your case, we have not found the root cause of the problem. Here is an [image update](https://github.com/actions/runner-images/pull/9214/files) that fixed the problem. I didn't notice anything suspicious. Could you please take a look and tell us if you see anything that your project depends on that might affect your build?
Thank you!

**Comment by stspenke** [comment] 2024-01-30 13:49
And today it's broken again...

With this runner image the builds are successful:
Runner Image
  Image: ubuntu-22.04
  Version: 20240122.3.0

With this runner image the builds fail again
Runner Image
  Image: ubuntu-22.04
  Version: 20240126.1.0

**Comment by stspenke** [comment] 2024-01-30 14:43
20230917.1.0 was OK
20230924.1.0 was not
Between 19 and 24 okt the build was OK, but I do not know version of the images
20231030.2.0 was not
20231115.8.0 was not
20231115.7.0 was OK
20240116.3.0 was not
20240122.3.0 was OK
20240126.1.0 is not

I have taken a look at all of the corresponding ReadMe file updates, but I did not really spot any dependencies for my project (and the test project that I have provided) that might explain why the build would stop/start being successful.

**Comment by Alexey-Ayupov** [comment] 2024-02-19 17:52
Hello @stspenke. It looks like your workflows work fine with the out latest images. Please bear in mind that error can happen again, but for now I will close this issue. You can reach us anytime for other questions.

As @MaksimZhukov said we could not find a root cause, since this error may occur because of OS application dependencies. We do not print all packages located on the image, only what we install. 
To get all apps and dependencies you should run `dpkg -l` .
If you perform this command every time during your workflow run (e.g. additional step in the end of a pipeline) it possibly could help us in the future to understand the root cause.

**Closed by Alexey-Ayupov** 2024-02-19 17:52 UTC
Labels: Area: Android, OS: Ubuntu, bug report
