### ISSUE TITLE
Azure DevOps Pipeline fails to download tasks after using latest vmImage: `windows-2019` released on 20240825.1.0

### ISSUE THREAD

**Issue by robertoandrade** [actions/runner-images#10506] opened 2024-08-28 13:30 UTC
### Description

Described it in detail in this Stackoverflow question: 
https://stackoverflow.com/questions/78923577/azure-devops-pipeline-fails-to-download-tasks-after-using-latest-vmimage-windo

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [X] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`20240825.1.0`

### Is it regression?

20240818.1.0

### Expected behavior

Install tasks correctly

### Actual behavior

Fails to install tasks with generic `##[error]Object reference not set to an instance of an object.` error

### Repro steps

Run pipeline with `windows-2019` latest vmImage with the following extensions in the yml:

Downloading task: PowerShell (2.242.1)
Downloading task: CmdLine (2.244.3)
Downloading task: InstallSSHKey (0.238.1)
Downloading task: Cache (2.198.0)
Downloading task: NuGetToolInstaller (1.238.1)
Downloading task: NuGetCommand (2.244.1)
Downloading task: Bash (3.244.1)
Downloading task: VSBuild (1.231.0)
Downloading task: ArchiveFiles (2.244.1)
Downloading task: PublishPipelineArtifact (1.242.0)

**Comment by mmrazik** [comment] 2024-08-28 16:30
I am almost sure this is a duplicate of https://github.com/microsoft/azure-pipelines-tasks/issues/20356 
It is not an image regression but rather regression in the AzureDevOps agent. It should be fixed by now.

**Comment by Prabhatkumar59** [comment] 2024-08-29 11:42
Hi @robertoandrade - I hope your issue is fixed by now as it is related to AzureDevops agent, this issue is not related to runner images.
Thanks:)

**Closed** 2024-09-03 16:10 UTC
Labels: OS: Windows, bug report
