### ISSUE TITLE
Update/Add bun

### ISSUE THREAD

**Issue by koozz** [actions/runner-images#9799] opened 2024-05-07 09:47 UTC
### Tool name

bun

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

1.1.7

### Approximate size

50MB

### Brief description of tool

Bun is an all-in-one toolkit for JavaScript and TypeScript apps. It ships as a single executable called bun.

At its core is the Bun runtime, a fast JavaScript runtime designed as a drop-in replacement for Node.js. It's written in Zig and powered by JavaScriptCore under the hood, dramatically reducing startup times and memory usage.

### URL for tool's homepage

https://bun.sh/

### Provide a basic test case to validate the tool's functionality.

```bash
`bun --version`
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

Linux & MacOS:

```bash
curl -fsSL https://bun.sh/install | bash
```

Windows:

```psh
powershell -c "irm bun.sh/install.ps1 | iex"
```

### Tool installation time in runtime

2 seconds (MacOS)

### Are you willing to submit a PR?

Sure, let me checkout the repository.

**Comment by erik-bershel** [comment] 2024-05-07 09:55
Hey @koozz!

I'm going to close this item as a duplicate of https://github.com/actions/runner-images/issues/9521. This decision wasn't reconsidered.

**Closed by erik-bershel** 2024-05-07 09:55 UTC
Labels: Area: JavaScript and Node.js, feature request
