### ISSUE TITLE
Unable to instantiate unit test containers in Ubuntu 22.04 version: 20230625.1.0

### ISSUE THREAD

**Issue by abdulmuyeed** [actions/runner-images#7826] opened 2023-06-30 18:13 UTC
### Description

Hi,
We are seeing builds failing since 2 days . The build is private and cannot be shared. When we analyzed the failure we found that the build is failing to run the unit test cases. 

Working versions:
Ubuntu: 22.04
Version: 20230619.1.0
JavaToolVersion: 0.223.0

The same pipeline build fails while executing the unit test cases.
Non-Working version:
Ubuntu : 22.04
Version: 20230625.1.0
JavaToolVersion: 0.224.0

Since we cannot specify the image version as per this thread: https://github.com/actions/runner-images/discussions/3464

We downgraded the Ubuntu version to 20.04 and build is working fine.
Ubuntu: 20.04
Version: 20230623.1.0
JavaToolVersion: 0.224.0

Let me know what has changed in the latest version because of which the unit test suites fails to load the test -containers.

Regards,
Abdul Muyeed M

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Runner Image
Image: ubuntu-22.04
Version: 20230625.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230625.1.0/images/linux/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1.0

### Is it regression?

Yes, with image version 20230625.1.0

### Expected behavior

Build should run as it was running with earlier version of Ubuntu image.

### Actual behavior

Build fails.

### Repro steps

No reproduction steps.

**Comment by erik-bershel** [comment] 2023-06-30 18:38
Hello @abdulmuyeed !
Regarding the main question, you can check the latest changes for [Ubuntu 20](https://github.com/actions/runner-images/releases/tag/ubuntu20%2F20230623.1) and [Ubuntu 22](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1) by the links. Also, considering that you mentioned containers in the text, here is a link to a [similar issue](https://github.com/actions/runner-images/issues/7815). Maybe this will help you in your investigation.

In order for us to start investigating from our side, we definitely need more information. Firstly, at least the error message and which specific step or action triggers it.

**Comment by abdulmuyeed** [comment] 2023-07-01 05:46
Hi Erik, 
Thanks for your response. I shall have that tested with our DevOps team on Monday.
There is an error that is thrown while connecting to the test Container (MySQL instance). below is the error message:
**_org.springframework.jdbc.CannotGetJdbcConnectionException at UserControllerTest.java:353
        Caused by: java.sql.SQLTransientConnectionException at UserControllerTest.java:353
            Caused by: com.mysql.cj.jdbc.exceptions.CommunicationsException at SQLError.java:174
                Caused by: com.mysql.cj.exceptions.CJCommunicationsException at null:-1
                    Caused by: java.net.ConnectException at Net.java:-2_**

Note: The line 353 initiates the JDBCTemplate bean with datasource. 

Below is the Gradle dependencies:

version('testcontainers', '1.17.6')

library('testcontainers-mysql', 'org.testcontainers', 'mysql').versionRef('testcontainers')
library('testcontainers-junit-jupiter', 'org.testcontainers', 'junit-jupiter').versionRef('testcontainers')
library('testcontainers-kafka', 'org.testcontainers', 'kafka').versionRef('testcontainers')
library('testcontainers-postgresql', 'org.testcontainers', 'postgresql').versionRef('testcontainers')

This keeps on running for more than hour and gets cancelled with the below error message.
##[error]The job running on agent Azure Pipelines 5 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134
Pool: [Azure Pipelines](https://dev.azure.com/phm-caremgmt/ba113a58-2760-4284-a865-b02b73303a6c/_settings/agentqueues?poolId=&queueId=121)
Image: ubuntu-22.04
Agent: Azure Pipelines 5
Started: Today at 3:28 AM
Duration: 1h 0m 0s

**Comment by vpolikarpov-akvelon** [comment] 2023-07-05 15:12
Hey @abdulmuyeed. Unfortunately, this information is not enough to understand what may be the cause. The only significant difference between Ubuntu 22 images `20230619.1.0` and `20230625.1.0` is the version of docker-compose, but since your pipeline works on the latest version of Ubuntu 20 image that also includes updated docker-compose it shouldn't affect.

In order to debug this I would suggest you to select one of the commits in you repo that has pipeline completed successfully, re-run pipeline and compare logs thoroughly to see the difference between old successful and new failed runs.

**Comment by aarongable** [comment] 2023-07-13 20:48
Is there a chance this bug is related to https://github.com/actions/runner-images/issues/7916?

**Comment by vpolikarpov-akvelon** [comment] 2023-08-03 12:29
Hey @abdulmuyeed. Are your build failing still? There are updates for both Docker and docker-compose recently that may have fixed this.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-09 11:30
Hey @abdulmuyeed, any updates on this? Did you try running your workflow on new images?

**Comment by abdulmuyeed** [comment] 2023-08-10 16:15
Hi We tried with the latest yet we are facing the same issue. Some of the runs we are seeing OutOfMemory. We increased the Heap memory while running the tests with no result.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-10 16:26
It's a shame that docker updated didn't resolve your issue. Could you please provide any repro steps so we can investigate this issue thoroughly?

**Comment by vpolikarpov-akvelon** [comment] 2023-08-16 08:25
Hey. Unfortunately, there is not enough information still to start investigating this issue. While it may be caused by runner image update, it may also be caused by docker or java update or even by changes in your code. I'm closing this issue for now, but if you have any additional information that may help us to investigate this issue, please feel free to leave a comment and we will reopen this issue. Thanks!

**Closed** 2023-08-16 08:25 UTC
Labels: Area: Containers, Area: Testing and code coverage, OS: Ubuntu, bug report
