### ISSUE TITLE
Update/Add [Az powershell module]

### ISSUE THREAD

**Issue by ProjectsByJackHe** [actions/runner-images#9705] opened 2024-04-17 21:03 UTC
### Tool name

Az

### Tool license

https://github.com/Azure/azure-powershell/blob/main/LICENSE.txt

### Add or update?

- [X] Add
- [X] Update

### Desired version

11.5.0

### Brief description of tool

We use **Az** PowerShell module as part of our CI/CD pipeline for performance testing.

However, because our desired version of Az is not present in **windows-latest**, we have to add a step to install it. 
This process can take upwards of 50 minutes: https://github.com/microsoft/netperf/actions/runs/8727656983/job/23948162545

It would be great if windows-latest came with Az module version 11.5.0

### URL for tool's homepage

https://github.com/Azure/azure-powershell

### Provide a basic test case to validate the tool's functionality.

```bash
$vm = Get-AzVM -ResourceGroupName $ResourceGroupName -Name $vmName

assert $vm is not NULL

$null = $vm | Remove-AzVM -Force

assert $vm is NULL
```

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Can this tool be installed during the build?

```bash
Install-Module -Name Az -Force -AllowClobber -Repository PSGallery
Update-Module Az -Force
```

### Tool installation time in runtime

6 - 50 minutes

### Are you willing to submit a PR?

Yes, if I need to.

**Comment by MaksimZhukov** [comment] 2024-04-18 08:55
Hello @ProjectsByJackHe!
I am closing the issue as a duplicate of [this one](https://github.com/actions/runner-images/issues/9418). Please find details there.

**Closed by MaksimZhukov** 2024-04-18 08:55 UTC
Labels: needs triage, feature request
