### ISSUE TITLE
macOS: Network configuration changed from 11 to 12 and later

### ISSUE THREAD

**Issue by jan-janssen** [actions/runner-images#9534] opened 2024-03-19 05:26 UTC
### Description

In `macOS 11` it was possible to connect to the current CI runner via the `hostname` of the CI runner. Starting in `macOS 12` it is only possible to connect to `localhost` but the resolution of the `hostname` to point to the same IP address like `localhost` does not work any longer. I have a simple example using python and zmq: https://github.com/jan-janssen/macOS-hostname-ci-debug 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [X] macOS 13
- [X] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240218.1

### Is it regression?

20240127.1

### Expected behavior

The `hostname` should be resolved to the same address like `localhost` and the CI runner should allow connecting to this address. 

### Actual behavior

While connecting to `localhost` works, connecting via the `hostname` does not. 

### Repro steps

Simple python example: 
```python
# From: https://zeromq.org/languages/python/

from threading import Thread

import zmq


def client_reply(host, port):
    context = zmq.Context()
    socket = context.socket(zmq.PAIR)
    socket.connect("tcp://" + host + ":" + port)
    message = socket.recv()
    socket.send(b"Client received: " + message)


if __name__ == "__main__":
    context = zmq.Context()
    socket = context.socket(zmq.PAIR)
    port = socket.bind_to_random_port("tcp://*")
    process = Thread(target=client_reply, kwargs={"host": "localhost", "port": str(port)})
    process.start()
    socket.send(b"Hello")
    assert socket.recv().decode() == "Client received: Hello"
```

While the example above works, it breaks when connecting via the hostname: 
```python
# From: https://zeromq.org/languages/python/

from socket import gethostname
from threading import Thread

import zmq


def client_reply(host, port):
    context = zmq.Context()
    socket = context.socket(zmq.PAIR)
    socket.connect("tcp://" + host + ":" + port)
    message = socket.recv()
    socket.send(b"Client received: " + message)


if __name__ == "__main__":
    context = zmq.Context()
    socket = context.socket(zmq.PAIR)
    port = socket.bind_to_random_port("tcp://*")
    process = Thread(target=client_reply, kwargs={"host": gethostname(), "port": str(port)})
    process.start()
    socket.send(b"Hello")
    assert socket.recv().decode() == "Client received: Hello"
```

The only difference is connecting to `tcp://localhost:<port>` vs. `tcp://<hostname>:<port>`.

**Comment by Alexey-Ayupov** [comment] 2024-03-19 10:37
Hello @jan-janssen. Your issue looks like duplicate of this one #8649. I will close this issue, please follow the progress of #8649 issue.
If you have any other questions feel free to reach us.

**Closed by Alexey-Ayupov** 2024-03-19 10:37 UTC
Labels: duplicate, OS: macOS, bug report

**Comment by oliver-sanders** [comment] 2024-04-04 15:27
Yes, that sounds like the same issue. I also maintain a Python application that uses ZMQ, we have pinned our CI to macos-11 to work around the issue. There is a partial workaround on the [linked issue](https://github.com/actions/runner-images/issues/8649#issuecomment-1779548056), I think it should be enough to get your example working again, but it doesn't fix the underlying DNS setup issue so, like us you may get issues with functional tests.

@Alexey-Ayupov, do you know how long the macos-11 runners will be available for?
