### ISSUE TITLE
Powershell task AzurePowerShell@5 fails on Microsoft Hosted Agents windows-2022

### ISSUE THREAD

**Issue by sudhirtibrewal** [actions/runner-images#6978] opened 2023-01-24 16:51 UTC
### Description

Below script was working fine in December 2022 and starts to fail in Jan 2023
$Content = Get-Content -Path $filePath | Out-String
    Write-Host $Content
    $PropertiesObject = @{
        mapType = $mapType
        content = "$Content"
        contentType ="$contentType"
    }
    New-AzResource -Location $location -PropertyObject $PropertiesObject -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Logic/integrationAccounts/maps -ResourceName "$integrationAccount/$mapName" -ApiVersion 2016-06-01 -Force

	

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221204.3

### Is it regression?

The above script ran successful on image '20221204.3' and starts to fail in '20230118.1

### Expected behavior

Expect the script to run successfully 

### Actual behavior

##[error]InvalidMap : The content of map 'TestValidator' of type 'Xslt30' must be a valid XML.
CorrelationId: f632a2d4-f596-483c-9297-a8f0d4ae5a0c
##[error]PowerShell exited with code '1'.

### Repro steps

Run the below script with correct parameters

$Content = Get-Content -Path $filePath | Out-String
    Write-Host $Content
    $PropertiesObject = @{
        mapType = $mapType
        content = "$Content"
        contentType ="$contentType"
    }
    New-AzResource -Location $location -PropertyObject $PropertiesObject -ResourceGroupName $resourceGroupName -ResourceType Microsoft.Logic/integrationAccounts/maps -ResourceName "$integrationAccount/$mapName" -ApiVersion 2016-06-01 -Force

**Comment by mikhailkoliada** [comment] 2023-01-24 17:04
Duplicate of #6947

**Closed by mikhailkoliada** 2023-01-24 17:04 UTC
Labels: needs triage, bug report
