### ISSUE TITLE
Execution failed for task ':app:stripReleaseDebugSymbols'. error=2, No such file or directory

### ISSUE THREAD

**Issue by KMalaimegam** [actions/runner-images#6036] opened 2022-08-09 01:22 UTC
### Description

I have changed the ndk 25 but still getting the same error in **macOS 12 Monterey/macOS 11 Big Sur**
android {  
  defaultConfig {  
    minSdkVersion 23
    generatedDensities = []
    targetSdkVersion 31
  }  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }
  lintOptions {
        checkReleaseBuilds false
  }
  ndkVersion "25.0.8775105"
} 

Execution failed for task ':app:stripReleaseDebugSymbols'.
error=2, No such file or directory

Command ./gradlew failed with exit code 1
the 

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [X] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md

### Is it regression?

No

### Expected behavior

Should build successful

### Actual behavior

Getting Execution failed for task ':app:stripReleaseDebugSymbols'. error=2, No such file or directory

### Repro steps

error in **macOS 12 Monterey/macOS 11 Big Sur**
Changed from ndk21 to ndk 25

**Comment by igorboskovic3** [comment] 2022-08-09 07:53
HI @KMalaimegam , thank you for reporting this one, can you provide repro steps?

**Comment by KMalaimegam** [comment] 2022-08-09 08:07
Hi @igorboskovic3 ,

I have changed the  ndkVersion from "21.4.7075529" to "25.0.8775105" in app.gradle and in azure DevOps used the Agent Specification "macOS-11"

android {
defaultConfig {
minSdkVersion 23
generatedDensities = []
targetSdkVersion 31
}
aaptOptions {
additionalParameters "--no-version-vectors"
}
lintOptions {
checkReleaseBuilds false
}
ndkVersion "25.0.8775105"
}

Error in Azure DevOps

2022-08-09T02:49:00.0248600Z Note: Recompile with -Xlint:unchecked for details.
2022-08-09T02:49:50.2986800Z 
2022-08-09T02:49:50.2989900Z Execution failed for task ':app:stripReleaseDebugSymbols'.
2022-08-09T02:49:50.2990850Z error=2, No such file or directory
2022-08-09T02:49:50.3091580Z 
2022-08-09T02:49:51.4354470Z Command ./gradlew failed with exit code 1
2022-08-09T02:49:52.3949250Z ##[error]PowerShell exited with code '1'.
2022-08-09T02:49:52.3997540Z ##[section]Finishing: Generate Android APK

**Comment by KMalaimegam** [comment] 2022-08-09 08:10
[ErrorLog.txt](https://github.com/actions/runner-images/files/9288493/ErrorLog.txt)

**Comment by dmitry-shibanov** [comment] 2022-08-09 09:28
Hello @KMalaimegam. Thank you for your report. Could you please provide a public repository to reproduce the issue ?

**Comment by KMalaimegam** [comment] 2022-08-09 11:26
@dmitry-shibanov No public repo.
I was successfully build the same code last week.

**Comment by KMalaimegam** [comment] 2022-08-11 01:55
Any updates?

**Comment by dmitry-shibanov** [comment] 2022-08-15 18:34
Hello @KMalaimegam. I was trying to reproduce the issue on simple projects but it works as expected. Could you please provide a public repository to reproduce the issue outside of your project ?

**Comment by al-cheb** [comment] 2022-08-19 08:32
@KMalaimegam, Any updates?

**Comment by dmitry-shibanov** [comment] 2022-08-23 21:50
Hello @KMalaimegam. For now I'm going to close the issue because we can't reproduce it. If you get a public repository or any additional information feel free to ping us.

**Closed by dmitry-shibanov** 2022-08-23 21:50 UTC
Labels: OS: macOS, investigate, bug report

**Comment by rubenstolk** [comment] 2022-09-20 15:56
I'm suddenly getting the same issue in one of our builds:

```Caused by: com.android.ide.common.workers.WorkerExecutorException: 1 exception was raised by workers:
org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip''```

**Comment by wisnhusurya** [comment] 2022-11-14 09:25
> I'm suddenly getting the same issue in one of our builds:
> 
> ```
> org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/usr/local/lib/android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip''```
> ```

Any update regarding this issue?

**Comment by incognos** [comment] 2023-03-20 17:56
This issue should be re-opened as ut is something I am going through the same issue. Tried different ndks - seems like something might be missing from the install.
