### ISSUE TITLE
Add vcpkg to macOS-13-arm64 and macOS-14-arm64

### ISSUE THREAD

**Issue by remyjette** [actions/runner-images#9462] opened 2024-03-07 00:02 UTC
### Tool name

vcpkg

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

match macOS-13 macOS-14

### Brief description of tool

Both macOS-13 and macOS-14 provide vcpkg
macOS-13 currently provides Vcpkg 2024 (build from commit 80403036a)
macOS-14 currently provides Vcpkg 2024 (build from commit 13bde2ff1)

The macOS-13-arm64 and macOS-14-arm64 images are both missing vcpkg and it would nice to be able to validate a vcpkg build on arm64

### URL for tool's homepage

https://vcpkg.io/en/

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by erik-bershel** [comment] 2024-03-07 09:19
Hey @remyjette!
I'm going to close this item as a duplicate of https://github.com/actions/runner-images/issues/9286
Shortly speaking we are not going to add this component to the new macOS images due to a maintenance concern and simplicity of installation in runtime.

**Closed by erik-bershel** 2024-03-07 09:19 UTC
Labels: Area: C/C++, OS: macOS, feature request
