### ISSUE TITLE
Install failure through git.sh

### ISSUE THREAD

**Issue by trend-billy-liu** [actions/runner-images#7788] opened 2023-06-26 10:24 UTC
### Description

When I build image and install git through git.sh

it fails when going to 
`downloadUrl=$(get_github_package_download_url "github/hub" "contains(\"hub-linux-amd64\")")`

and here is the error
`
jq: error (at <stdin>:1): Cannot index string with string "prerelease"
jq: error (at <stdin>:1): Cannot index string with string "tag_name"
`

I think github/hub transfer to another url to download, so the output json is like 
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/401025/releases?per_page=100",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}

So please add some try catch in install.sh to avoid 301 response,
thanks.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

"Set up job" -> "Runner Image" -> "ubuntu20/20230611.1".

### Is it regression?

no

### Expected behavior

Expected to install git through git.sh 

### Actual behavior

jq: error (at <stdin>:1): Cannot index string with string "prerelease"
jq: error (at <stdin>:1): Cannot index string with string "tag_name"

### Repro steps

I transfer json to packer to build image and execute git.sh it fails.

**Comment by mikhailkoliada** [comment] 2023-06-26 10:57
Duplicate of https://github.com/actions/runner-images/issues/7734

**Closed by mikhailkoliada** 2023-06-26 10:57 UTC
Labels: needs triage, bug report
