### ISSUE TITLE
Lack of reproducibility is exhausting: latest Ubuntu 22 changes broke our pipelines

### ISSUE THREAD

**Issue by Adnn** [actions/runner-images#8669] opened 2023-10-26 13:37 UTC
### Description

This [change to ubuntu-22.04](https://github.com/actions/runner-images/commit/388d55d0d741619a8718061d401166ebdc1f01f5) broke one of [our pipeline](https://github.com/ShredEagle/graphics/actions/runs/6642612385/job/18078143540) (in a 3rd party dependency, namely `fmt`).

Notice the all green run less than 24h ago.

We suspect this is because the change introduce a new version of libstdc++ (shipped by GCC), which gets pickeds up by the build and is apparently not compatible with Clang 14 used to compile.

Is there a way to "lock" the runners in a known state / specific image version?

Currently, CI in Cpp seems like a gateway to burnout.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20231022.1.0

### Is it regression?

In a way

### Expected behavior

Things that worked yesterday evening to work the same this morning.

### Actual behavior

Exhaustion.

### Repro steps

1. Read that CI is a good idea to ship software
2. Believe it

**Comment by mikhailkoliada** [comment] 2023-10-26 13:53
Duplicate of https://github.com/actions/runner-images/issues/8659

**Closed by mikhailkoliada** 2023-10-26 13:53 UTC
Labels: OS: Ubuntu, investigate, bug report

**Comment by Adnn** [comment] 2023-10-26 15:10
Does #8659 investigate how to lock a runner to a specific image version @mikhailkoliada?
