### ISSUE TITLE
windows-2022 is missing VS redistributable needed for conda 

### ISSUE THREAD

**Issue by oleksandr-pavlyk** [actions/runner-images#9888] opened 2024-05-17 17:03 UTC
### Description

With merge of gh-9819 conda builds on Windows started failing on "windows-latest" runners, and could be restored to work on windows-2019.

Repository https://github.com/oleksandr-pavlyk/test-ci-windows-latest was created to triage the issue. 

It finds that windows-2022 is missing redistributable 14.38.33130 as required by conda-forge.

Similar issue is to be filed for conda-forge/vc-feedstock maintainers to see whether that version can be updated on their side as well.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Please see action logs for CI jobs in https://github.com/oleksandr-pavlyk/test-ci-windows-latest

### Is it regression?

yes

### Expected behavior

"conda build" jobs are expected to succeed using windows-latest runner.

### Actual behavior

CMake/Ninja fail at configure stage, due to inability to find compiler.

### Repro steps

See  https://github.com/oleksandr-pavlyk/test-ci-windows-latest for the reproducer

**Comment by oleksandr-pavlyk** [comment] 2024-05-17 17:04
The issue has been filed already: https://github.com/conda-forge/vc-feedstock/issues/73

**Comment by jdblischak** [comment] 2024-05-21 14:31
> It finds that windows-2022 is missing redistributable 14.38.33130 as required by conda-forge.
>
> Similar issue is to be filed for conda-forge/vc-feedstock maintainers to see whether that version can be updated on their side as well.

@oleksandr-pavlyk you should try again today. The vc-feedstock recipe was updated to include 14.38.33130. The vs2022-based feedstock I was troubleshooting is working again.

xref: https://github.com/conda-forge/vc-feedstock/pull/76, https://github.com/conda-forge/vc-feedstock/pull/77, https://github.com/conda-forge/vc-feedstock/issues/73#issuecomment-2121251365

I think this Issue can be closed

**Comment by erik-bershel** [comment] 2024-05-22 11:23
My understanding is that the problem is not missing components, but that `conda-forge` support sometimes lags a little behind the latest changes in `Visual Studio` components. Unfortunately, we cannot influence this process. The only tool previously available to us was to install additional previous versions of `Visual Studio` components, but due to a `Visual Studio 2022` bug, this option breaks many other builds.

At the moment, the problem has been resolved, but it will probably arise again from time to time and we have no way to influence it. In this regard, I plan to close this issue.

**Closed by erik-bershel** 2024-05-22 11:23 UTC
Labels: Area: C/C++, OS: Windows, bug report
