### ISSUE TITLE
Windows services take too long to start

### ISSUE THREAD

**Issue by vascodcastro** [actions/runner-images#7794] opened 2023-06-26 18:11 UTC
### Description

Since version 20230620.1.0 builds by this version won't start as Windows Services.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20230620.1.0

### Is it regression?

20230606.1

### Expected behavior

We use an Azure Pipeline to build and deploy into a Nuget repository and then Octopus Deploy deploys the application installingl as a Windows Service in a Windows Server. We have multiple products running like this.

### Actual behavior

Since version 20230620.1.0  the windows service won't start in a timely fashion which is causing failures.  

### Repro steps

Install in a Windows Server a .Net 6.0 Web API solution built by Runner Image version 20230620.1.0

**Comment by erik-bershel** [comment] 2023-06-26 22:04
Hey @vascodcastro!
Please provide a more detailed description of the problem. How much has the delay increased, on which actions exactly (it is very desirable with examples)? And please provide a link to a public repository / a yaml sample / an example project to reproduce the issue.

**Comment by vascodcastro** [comment] 2023-06-27 08:56
Right now I can't provide the solution because the code doesn't belongs to me.
The delay incremented from less then 5 seconds to over 30 seconds, so the services won't start because of these issue.

**Comment by erik-bershel** [comment] 2023-07-07 15:49
I am forced to close this issue due to lack of repro steps. If you have new information about the problem, we can open it again. In case of other problems, feel free to open new issues.

**Closed by erik-bershel** 2023-07-07 15:49 UTC
Labels: Area: .NET Core, OS: Windows, investigate, bug report
