### ISSUE TITLE
Add debian images

### ISSUE THREAD

**Issue by mabed-fr** [actions/runner-images#10564] opened 2024-09-07 11:04 UTC
### Tool name

Debian images

### Tool license

no

### Add or update?

- [X] Add
- [ ] Update

### Desired version

testing , 12 , 11

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

**Comment by hemanthmanga** [comment] 2024-09-07 13:50
Hi @mabed-fr Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by Tylerhazy444** [comment] 2024-09-08 04:06
PR means what exactly. Sorry im just getting the hang of this. I like this platform and want to get good at it. Please if anyone can help me learn and get some assets built up id greatly appreciate it

**Comment by Alexey-Ayupov** [comment] 2024-12-06 16:33
Hi @mabed-fr, closing the issue as duplicate of https://github.com/actions/runner-images/issues/8183

If you have any other questions feel free to reach us.

**Closed by Alexey-Ayupov** 2024-12-06 16:33 UTC
Labels: OS: Ubuntu, feature request
