### ISSUE TITLE
ubuntu-latest: Failing to run NET6 app due to missing Microsoft.NETCore.App

### ISSUE THREAD

**Issue by sebastien-marichal** [actions/runner-images#10139] opened 2024-06-28 14:05 UTC
### Description

After the [latest](https://github.com/actions/runner-images/commit/2c549825eaed806e2c85bbfcd5e50d99ebaa61c1) update in ubuntu-latest we started having issues in our Azure pipeline while running a NET6 app with the error:

```
/usr/share/dotnet/sdk/7.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.
```

This time the issue seems to come from the update of .NET 8 update from 8.0.301 to 8.0.302.

Similar to issues we already reported in #5792, #6925 & #7319.

### Platforms affected

- [x] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20240624.1.0

### Is it regression?

Yes. The previous version was working correctly.

### Expected behavior

Run the App without a runtime error.

### Actual behavior

Following error:

```
/usr/share/dotnet/sdk/7.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(376,5):
error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.
```

### Repro steps

Could not reproduce this locally.

Changing the image to [ubuntu-20.04](https://github.com/actions/runner-images/blob/ubuntu20/20240624.2/images/ubuntu/Ubuntu2004-Readme.md) seems to solve the issue on the pipeline, at least.

**Comment by hemanthmanga** [comment] 2024-06-28 14:30
@sebastien-marichal  We are looking into the issue, we will get back to you after investigating this issue, Thanks.

**Comment by kishorekumar-anchala** [comment] 2024-07-01 05:00
HI @sebastien-marichal ,

 Please provide your comments for below to further investigation:
 1) Which SDK version you're using locally ?
 2) Can you please share your azure pipeline file ?

**Comment by rajravat** [comment] 2024-07-01 10:01
We are also experiencing this issue too, for now we have also changed our ubuntu version to be 20.04

**Comment by kishorekumar-anchala** [comment] 2024-07-01 10:47
> We are also experiencing this issue too with a dotnet 8 project, for now we have also changed our ubuntu version to be 20.04

Could you please share the below details:

1. Which SDK version you're using locally ?
2. Can you please share your azure pipeline file ?

**Comment by eholman** [comment] 2024-07-01 13:13
Ah, I see I've reported the same, I think there is more information: #10147

**Comment by kishorekumar-anchala** [comment] 2024-07-02 03:33
Hi @rajravat , @sebastien-marichal ,

Could you please try to run with MSBuild x64 architecture (VS Build task).

```
    clean: true
    msbuildArchitecture: 'x64'
```

**Comment by rajravat** [comment] 2024-07-02 06:32
> > We are also experiencing this issue too with a dotnet 8 project, for now we have also changed our ubuntu version to be 20.04
> 
> Could you please share the below details:
> 
> 1. Which SDK version you're using locally ?
> 2. Can you please share your azure pipeline file ?

Local SDK is 8.0.302

pipeline snippets as below:
azure-pipelines.yml
![image](https://github.com/actions/runner-images/assets/25839791/5c300a2d-9402-42a4-ac6c-ef92d4930bf9)
build.yml
![image](https://github.com/actions/runner-images/assets/25839791/3e7def3c-f589-4a59-bacc-ca128ecfb1df)
fails on the "build tests" step with an error of

##[error]/usr/share/dotnet/sdk/8.0.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(404,5): Error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.

**Comment by eholman** [comment] 2024-07-02 07:08
Like I've also mentioned in #10147 - The exact same pipeline, only setting the vmimage to `windows-latest`, works without any errors. Can you elaborate on the suggestion to update the Restore task? What was the expected outcome of this change?

**Comment by kishorekumar-anchala** [comment] 2024-07-02 07:36
> Like I've also mentioned in #10147 - The exact same pipeline, only setting the vmimage to `windows-latest`, works without any errors. Can you elaborate on the suggestion to update the Restore task? What was the expected outcome of this change?

Hi @eholman , Started investigation on the same , i will provide details once investigation completed.

**Comment by eholman** [comment] 2024-07-02 07:45
Setting vmimage to `ubuntu-20.04` seems to work too

**Comment by kishorekumar-anchala** [comment] 2024-07-02 10:22
Hi @eholman , @rajravat ,

  Could you please try to run by adding below task (first task) , it is worked for me  for dotnet 8.0.302 .
  
  Note : Change according to your version.
  
```
  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x' # or 8.0.302 
    installationPath: $(Agent.ToolsDirectory)/dotnet 
```

**Comment by rajravat** [comment] 2024-07-02 10:41
This does fix the problem for me when using ubuntu-latest, thanks.

Will this be "fixed" in a future image revision for ubuntu or is the expectation now that we keep this task there permanently?

**Comment by kishorekumar-anchala** [comment] 2024-07-02 12:29
Hey @rajravat ,

   

> This does fix the problem for me when using ubuntu-latest, thanks.

Thanks for confirmation !


> Will this be "fixed" in a future image revision for ubuntu or is the expectation now that we keep this task there permanently?

It depends on new version  upgrades and patches on images , some have older versions and some have new . But i can confirm that the given task will always help us to prevent such issues , it will pin the version which is needed for your project ( if that version will installed on images) . So keep that task in your pipeline permanently (Not needed for some images) .

@eholman , @sebastien-marichal - I hope the above workaround fix your issue. Kindly provide your comments .

Thank you !

**Comment by kishorekumar-anchala** [comment] 2024-07-03 06:00
Hi @eholman @sebastien-marichal , 

   Could you please provide your status ?

**Comment by eholman** [comment] 2024-07-03 06:10
The workaround works, thank you. But I **definitely** consider this a workaround because switching between vmImages should not cause this kind of issues, specifically when the same runner image versions are used, imho. I'd rather consider this as regression because it worked perfectly fine before and without any reason it fails (at least for us, the users). There should be **at least** some breaking changes noted somewhere in release notes.

**Comment by kishorekumar-anchala** [comment] 2024-07-05 04:13
Hi @eholman ,

Currently we don't have any information on it , however, we will work on it, and we'll let you know once we find a solution.

@sebastien-marichal , Could you please provide your comments ?

**Comment by kishorekumar-anchala** [comment] 2024-07-06 10:45
Hi @sebastien-marichal , We have attempted to follow up regarding your response. We hope the issue has been resolved with above workaround .  We are now closing the case. Thank you.

**Closed by kishorekumar-anchala** 2024-07-06 10:45 UTC
Labels: Area: .NET Core, OS: Ubuntu, bug report

**Comment by sebastien-marichal** [comment] 2024-07-08 13:55
I confirm that the issue is resolved for us as well.
Thank you!

**Comment by ckarcz** [comment] 2024-12-11 16:25
this started happening again. example agent:
```
Agent name: 'Azure Pipelines 2'
Agent machine name: 'fv-az113-119'
Current agent version: '4.248.0'
Operating System
Ubuntu
22.04.5
LTS
Runner Image
Image: ubuntu-22.04
Version: 20241117.1.0
Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20241117.1/images/ubuntu/Ubuntu2204-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20241117.1
```

.net6 (global json) and the build seems to be using .net8
```
##[error]/opt/hostedtoolcache/dotnet/sdk/8.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(404,5): Error NETSDK1127: The targeting pack Microsoft.NETCore.App is not installed. Please restore and try again.
```

**Comment by ckarcz** [comment] 2024-12-11 17:03
for others that may run into this issue.

we use a mono repo and our builds use `global.json` files. the UseDotNet task was picking up all the global.json files. we had to set the working directory param for the task to resolve this issue for us.
