### ISSUE TITLE
C# builds fail with `MissingMethodException` in v20240603.1.0

### ISSUE THREAD

**Issue by qwertie** [actions/runner-images#10022] opened 2024-06-10 03:00 UTC
### Description

We have a `VSBuild@1` task that looks like this and used to build OK:

    - task: VSBuild@1
      displayName: Build
      inputs:
        solution: $(buildSolution)
        configuration: Release

I confirmed that the build broke without any changes to our repository (I pushed a new branch that points to an older version of our code; this used to build successfully and now fails).

Notably it is preceded by a `DotNetCoreCLI@2` task that is **still working**:

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: 'test'
        projects: $(testProjects)
        publishWebProjects: true
        arguments: --configuration DevOpsTest

Another change I notice (with a diff tool) between successful and failing builds is that while previous successful builds had messages with a GUID, like

~~~
 CoreCompile:
   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe [...TRUNCATED...]
   CompilerServer: server - server processed compilation - 725a6ff7-f9bb-4f8b-8549-bc7ddebb5b2a
~~~

the new failing builds show the project name instead:

~~~
 CoreCompile:
   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe [...TRUNCATED...]
   CompilerServer: server - server processed compilation - SurveyGridLibrary (netstandard2.0)
~~~

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240603.1.0

### Is it regression?

20240514.3.0, https://dev.azure.com/barreleye/barreleye/_build/results?buildId=1584&view=logs&j=8e2a5b11-fe97-5002-4551-ec7288597841&t=314400c4-c678-49d6-be96-51ecec8a9a82

### Expected behavior

The C# compiler should not fail with `MissingMethodException`s.

### Actual behavior

Some `CoreCompile` steps work normally. But others fail with a `MissingMethodException`:

~~~
 CoreCompile:
   C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:1591,1573,1701,1702 /fullpaths /nostdlib+ /errorreport:prompt /warn:7 /doc:obj\Release\net7.0\ProductnameWebApi.xml /define:TRACE;RELEASE;NET;NET7_0;NETCOREAPP;NET5_0_OR_GREATER;NET6_0_OR_GREATER;NET7_0_OR_GREATER;NETCOREAPP1_0_OR_GREATER;NETCOREAPP1_1_OR_GREATER;NETCOREAPP2_0_OR_GREATER;NETCOREAPP2_1_OR_GREATER;NETCOREAPP2_2_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER /highentropyva+ /nullable:enable /reference:D:\a\1\s\Server\AllPurpose\obj\Release\net7.0\ref\AllPurpose.dll /reference:D:\a\1\s\Server\AllPurpose\Assisticant.dll /reference:C:\Users\VssAdministrator\.nuget\packages\azure.core\1.6.0\lib\netstandard2.0\Azure.Core.dll /reference:C:\Users\VssAdministrator\.nuget\packages\azure.identity\1.3.0\lib\netstandard2.0\Azure.Identity.dll [...TRUNCATED...]
   CompilerServer: server failed - server rejected the request 'Exception during compilation: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.' - ProductnameWebApi (net7.0)
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error : 
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :  [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error : Unhandled Exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'.
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error : Unhandled Exception: System.MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerator`1<Microsoft.CodeAnalysis.NodeStateEntry`1<System.ValueTuple`2<System.__Canon,System.__Canon>>> Microsoft.CodeAnalysis.NodeStateTable`1.GetEnumerator()'. [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.ExternalAccess.RazorCompiler.HostOutputNode`1.AppendOutputs(IncrementalExecutionContext context, CancellationToken cancellationToken) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.UpdateOutputs(ImmutableArray`1 outputNodes, IncrementalGeneratorOutputKind outputKind, Builder generatorRunStateBuilder, CancellationToken cancellationToken, Builder driverStateBuilder) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsCore(Compilation compilation, DiagnosticBag diagnosticsBag, CancellationToken cancellationToken) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsAndUpdateCompilation(Compilation compilation, Compilation& outputCompilation, ImmutableArray`1& diagnostics, CancellationToken cancellationToken)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.GeneratorDriver.RunGeneratorsAndUpdateCompilation(Compilation compilation, Compilation& outputCompilation, ImmutableArray`1& diagnostics, CancellationToken cancellationToken) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommonCompiler.RunGenerators(Compilation input, String generatedFilesBaseDirectory, ParseOptions parseOptions, ImmutableArray`1 generators, AnalyzerConfigOptionsProvider analyzerConfigOptionsProvider, ImmutableArray`1 additionalTexts, DiagnosticBag generatorDiagnostics)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunGenerators(Compilation input, String generatedFilesBaseDirectory, ParseOptions parseOptions, ImmutableArray`1 generators, AnalyzerConfigOptionsProvider analyzerConfigOptionsProvider, ImmutableArray`1 additionalTexts, DiagnosticBag generatorDiagnostics) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit(TouchedFileLogger touchedFilesLogger, Compilation& compilation, ImmutableArray`1 analyzers, ImmutableArray`1 generators, ImmutableArray`1 additionalTextFiles, AnalyzerConfigSet analyzerConfigSet, ImmutableArray`1 sourceFileAnalyzerConfigOptions, ImmutableArray`1 embeddedTexts, DiagnosticBag diagnostics, ErrorLogger errorLogger, CancellationToken cancellationToken, CancellationTokenSource& analyzerCts, AnalyzerDriver& analyzerDriver, Nullable`1& generatorTimingInfo) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.RunCore(TextWriter consoleOutput, ErrorLogger errorLogger, CancellationToken cancellationToken) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommonCompiler.Run(TextWriter consoleOutput, CancellationToken cancellationToken) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.<>c__DisplayClass1_0.<Run>b__0(TextWriter tw) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output[T](Func`2 func) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run(String[] args, BuildPaths buildPaths, TextWriter textWriter, IAnalyzerAssemblyLoader analyzerLoader) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunLocalCompilation(String[] arguments, BuildPaths buildPaths, TextWriter textWriter) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation(IEnumerable`1 originalArguments, BuildPaths buildPaths, TextWriter textWriter, String pipeName) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CommandLine.BuildClient.Run(IEnumerable`1 arguments, RequestLanguage language, CompileFunc compileFunc, CompileOnServerFunc compileOnServerFunc, ICompilerServerLogger logger) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore(String[] args) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 ##[error]C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): Error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\Microsoft.CSharp.Core.targets(85,5): error :    at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args) [D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj]
 Done Building Project "D:\a\1\s\Server\ProductnameWebApi\ProductnameWebApi.csproj" (default targets) -- FAILED.
~~~

### Repro steps

We don't really have time to spare at the moment, so we'd like to know if we can just revert to version 20240514.3.0.

Would it help if you had access to our repo? We might be open to granting access.

**Comment by kishorekumar-anchala** [comment] 2024-06-10 13:41
HI @qwertie , Could you please help us to provide repro steps to investigate further.

**Comment by qwertie** [comment] 2024-06-10 20:01
Sorry, I don't think I'll have time. I was able to work around the issue by using `DotNetCoreCLI@2` instead of `VSBuild@1`:

![image](https://github.com/actions/runner-images/assets/720717/e0f32e56-59fa-4803-b69a-e47a8f9b1ebd)
~~~yml
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: $(buildSolution)
        configuration: Release
~~~

**Comment by kishorekumar-anchala** [comment] 2024-06-11 05:56
Hi @qwertie , 

your investigation is good , also look into your version compatibility and configuration values in the project and pipeline . 

ex : .Net core or .net SDK versions .  .Net 4.8 will support vs2019 and higher. 
        Default value of configuration is Release , verify it from your end

if you have any questions feel free to ask us , hope your workaround works in your case.

**Comment by robrisner** [comment] 2024-06-11 14:27
I'm seeing the same issue and found it's related to VS 2022 17.10. Looks like it's going to be patched soon per https://developercommunity.visualstudio.com/t/Cannot-build-any-project-after-update-to/10664111.

> Thanks for everyone who uploaded the logs. Have a pretty good handle on the situation now. We’ll be patching 17.10 to fix this soon. In the meantime you can work around by installing the following package into impacted projects: Microsoft.Net.Compilers.Toolset at version 4.9.2.

**Comment by kishorekumar-anchala** [comment] 2024-06-12 03:44
HI @qwertie , 

Now developer community has fixed the issue , kindly try it from your end and let us know if you need any other help .

FYI : https://developercommunity.visualstudio.com/t/Cannot-build-any-project-after-update-to/10664111?viewtype=solutions

**Comment by kishorekumar-anchala** [comment] 2024-06-13 03:25
Hi @qwertie ,

Please share your comments on your issue to proceed  to next step. Thank you !

**Comment by karan-joshi-01** [comment] 2024-06-13 07:44
I'm new to Azure Devops, forgive me for my mistakes.

I have re-run my old successful pipeline. The issue is still there. as stated in logs.

**Comment by HeraHjalta** [comment] 2024-06-13 12:51
This is still happening for us on image version 20240610.1.0
We are using .NET 7

**Comment by kishorekumar-anchala** [comment] 2024-06-13 14:03
> I'm new to Azure Devops, forgive me for my mistakes.
> 
> I have re-run my old successful pipeline. The issue is still there. as stated in logs. Using msbuild version '17.10.4.21802'

hi @qwertie ,

kindly try with below task to run your pipeline.

`- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '7.x'`
 
  Could you please look into below link.

 refer : https://developercommunity.visualstudio.com/t/Cannot-build-any-project-after-update-to/10664111

**Comment by kishorekumar-anchala** [comment] 2024-06-14 06:08
@qwertie , 

We hope that this has been fixed and we are closing this issue,  we urge that you file a new ticket if you require any additional assistance.

**Closed by kishorekumar-anchala** 2024-06-14 06:08 UTC
Labels: Area: .NET Core, OS: Windows, bug report
