### ISSUE TITLE
GitHub Action: New M1 runner available to all plans, including open source 🚀

### ISSUE THREAD

**Issue by Steve-Glass** [actions/runner-images#9254] opened 2024-01-30 16:10 UTC
### Breaking changes

The new M1 runner is available for all plans, free in public repositories, and eligible to consume included free plan minutes in private repositories. The new runner operates exclusively on macOS 14 and to use it, simply update the `runs-on` key in your YAML workflow file to `macos-14`. 

[Change log](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/)

### Target date

Available as of 1/30/2023

### The motivation for the changes

N/A

### Possible impact

N/A

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [x] macOS 14
- [x] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Mitigation ways

N/A

**Comment by fwcd** [comment] 2024-01-30 19:24
There's something strange with the Xcode installation in these runners, running `xcrun --show-sdk-version` outputs

```
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

See e.g. https://github.com/fwcd/m1xxx/pull/63

I can't reproduce this locally, even with `xcode-select -s /Library/Developer/CommandLineTools`.

**Comment by darthmaim** [comment] 2024-01-30 19:52
The new `macos-14` runner contain a link at the top of the log to included software:
```
Included Software: https://github.com/actions/runner-images/blob/macOS-14/20240116.1/images/macos/macos-14-arm64-Readme.md
```

This link is a 404 and should instead link to https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md

**Comment by darena-patrick** [comment] 2024-01-30 20:59
Will `arm64` runners be available soon as well? I currently self-hosting, but I would love to use GitHub-hosted ones.

**Comment by Vyazovoy** [comment] 2024-01-30 21:03
@darena-patrick, looks like this ticket says exactly that. If you switch to `macos-14` your jobs will be running on the M1 (aka `arm64`) runner.

**Comment by darena-patrick** [comment] 2024-01-30 21:05
> @darena-patrick, looks like this ticket says exactly that. If you switch to `macos-14` your jobs will be running on the M1 (aka `arm64`) runner.

yea, I deleted my comment once I realized that :)

**Comment by darena-patrick** [comment] 2024-01-30 21:20
@Steve-Glass any plans to support Docker on these images? Otherwise, any word on when `linux-arm64` will be available?

**Comment by darthmaim** [comment] 2024-01-30 21:22
> @Steve-Glass any plans to support Docker on these images? Otherwise, any word on when `linux/arm64` will be available?

No docker for the M1 images:
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#limitations-for-macos-larger-runners:
> Due to a limitation of Apple's Virtualization Framework, which our hypervisor uses, nested-virtualization is not supported by arm64 runners.

**Comment by mikhailkoliada** [comment] 2024-01-30 21:49
> The new `macos-14` runners contain a link at the top of the log to included software:
> 
> ```
> Included Software: https://github.com/actions/runner-images/blob/macOS-14/20240116.1/images/macos/macos-14-arm64-Readme.md
> ```
> 
> This link is a 404 and should instead link to https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md

This is expected as no full public releases happened yet, it should be fixed with the next release :)

**Comment by Korijn** [comment] 2024-01-31 09:36
When is this coming to Azure Pipelines?

**Comment by douglascamata** [comment] 2024-02-01 19:33
@Steve-Glass there's a huge breaking change here: the M1 processor does not support nested virtualization. This will break every workflow out there using Colima/Lima or any other VM-based solution for running Docker in macOS.

**Comment by douglascamata** [comment] 2024-02-01 19:37
QEMU will report `{"level":"debug","msg":"qemu[stderr]: qemu-system-aarch64: Error: HV_UNSUPPORTED","time":"2024-02-01T19:34:57Z"}`

Trying to use Virtualization.framework will report `{"level":"fatal","msg":"Error Domain=VZErrorDomain Code=2 Description=\"Invalid virtual machine configuration. Virtualization is not available on this hardware.\" UserInfo={\n    NSLocalizedFailure = \"Invalid virtual machine configuration.\";\n    NSLocalizedFailureReason = \"Virtualization is not available on this hardware.\";\n}","time":"2024-02-01T19:36:49Z"}`

**Comment by douglascamata** [comment] 2024-02-01 22:33
@Vyazovoy being a documented change doesn’t change the fact that it is a breaking change. They are two different things.

**Comment by cgrindel** [comment] 2024-02-04 18:03
I would like to upvote @fwcd [comment](https://github.com/actions/runner-images/issues/9254#issuecomment-1917734326). [I too am seeing](https://github.com/cgrindel/rules_swift_package_manager/pull/896) an error running `xcrun --show-sdk-version`.

**Comment by Luthaf** [comment] 2024-02-09 17:38
Is the GPU available on these runners? Trying to use them with PyTorch and the MPS (i.e. Metal) backend result in error like this (See https://github.com/lab-cosmo/metatensor/actions/runs/7847356344/job/21416128283)

> RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes, max allowed: 7.93 GB). Tried to allocate 256 bytes on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

Setting `PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0` in the env changes the error message to (see https://github.com/lab-cosmo/metatensor/actions/runs/7847470210/job/21416465675)

> RuntimeError: MPS backend out of memory (MPS allocated: 0 bytes, other allocations: 0 bytes). Tried to allocate 256 bytes on shared pool.

---

There are other reports of the same issue on the PyTorch forums: https://discuss.pytorch.org/t/mps-back-end-out-of-memory-on-github-action/189773

**Comment by janosh** [comment] 2024-02-28 09:29
@Luthaf unfortunately, the new `macos-14` don't have access to MPS hardware, see https://github.com/pytorch/pytorch/issues/111449#issuecomment-1767613883.

**Comment by amitdo** [comment] 2024-02-28 11:56
@Steve-Glass,

>### Target date
>
>Available as of 1/30/2023

You mean 1/30/**2024**

**Closed** 2024-03-07 22:55 UTC
Labels: Announcement

**Comment by ssbarnea** [comment] 2024-03-10 13:36
Apparently the macos-14 also has support to run intel code disabled, qemu reports:
```
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-aarch64: -accel hvf: Error: HV_UNSUPPORTED
```

This a big bummer for someone wanting to build a dual architecture container for example. Doing that on an intel bacsed linux machine is like 5x slower than doing it on a macos arm based machine.

**Comment by mikhailkoliada** [comment] 2024-03-10 14:46
@ssbarnea it is not a GitHub restriction, Apple does not support nested virt on M1 CPU gen entirely

**Comment by qwqcode** [comment] 2024-03-15 17:00
Unfortunately, the current `macos-14` runner which ARM architecture cannot run Docker.

Although it can execute builds on native ARM, this essentially says goodbye to the Docker ecosystem system. 😢

**Comment by slonopotamus** [comment] 2024-03-15 17:12
What's the point using mac runners for Docker tasks if you can use Linux runners?

**Comment by EliahKagan** [comment] 2024-03-15 17:14
> What's the point using mac runners for Docker tasks if you can use Linux runners?

Currently there are no GitHub-hosted ARM-based Linux runners.

**Comment by hovancik** [comment] 2024-04-26 18:17
@fwcd @cgrindel  were you able to fix errors with `xcrun --show-sdk-version`?

**Comment by cgrindel** [comment] 2024-04-28 16:30
Unfortunately, no. I still see the following:

```
++ xcrun --show-sdk-version
2024-04-28 15:28:55.452 xcodebuild[11203:62473] Writing error result bundle to /var/folders/3m/p59k4qdj0f17st0gn2cmj3640000gn/T/ResultBundle_2024-28-04_15-28-0055.xcresult
xcodebuild: error: SDK "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk" cannot be located.
xcrun: error: unable to lookup item 'SDKVersion' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
```

**Comment by hovancik** [comment] 2024-05-08 12:15
I've created issue #9811

**Comment by joffrey-bion** [comment] 2024-05-13 12:02
> What's the point using mac runners for Docker tasks if you can use Linux runners?

I would like to add that sometimes Docker is just here to provide a side service while running native tests that require a specific system. I want to test my web socket client implementation on macOS, not on linux, but I still want to run my docker-based test server during the build.

**Comment by marciniwanicki** [comment] 2024-05-31 22:56
It's now possible to build apps relying on `Virtualization.framework` 🥳, I love it, thank you so much!
