### ISSUE TITLE
Java cannot find certification path

### ISSUE THREAD

**Issue by GergelyKalmar** [actions/runner-images#9354] opened 2024-02-15 21:14 UTC
### Description

We're seeing the following error when running our test suite in GitHub Actions:
```
Caused by: java.io.IOException: Error getting subject token from metadata server: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

The test suite runs fine locally on an Ubuntu 20.04 LTS desktop environment, it also runs fine inside a clean Ubuntu base image from Docker.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

See https://github.com/logikal-io/mindlab/actions/runs/7835150901/job/21629489569

### Is it regression?

Probably not

### Expected behavior

We expect our tests to succeed.

### Actual behavior

The tests fail.

### Repro steps

Run the test suite in the given repository in GitHub Actions.

Note that the issue has also been reported at https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/1106, but as it only appears on GitHub Actions and not when running locally or on a clean Ubuntu image, we think it might be related to the GitHub Actions image.

**Comment by mikhailkoliada** [comment] 2024-02-15 21:37
Hi! Please provide a minimal project to reproduce the problem

**Comment by mikhailkoliada** [comment] 2024-02-16 01:13
Apart from that, as far as I understand the auth failure happens because of the lack of some jvm parameters such as `javax.net.ssl.keyStore` etc, are they handled correctly?

**Comment by mikhailkoliada** [comment] 2024-02-16 11:19
@GergelyKalmar could you please describe your docker local workflow (Dockerfile/build commands/commands you run in container, what docker image is used as base, etc) to compare outputs from docker and from runner then?

**Comment by shamil-mubarakshin** [comment] 2024-02-20 12:16
Hey @GergelyKalmar,
I somehow can not reproduce the exact error. I have [reproduced the workflow](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7973019374/job/21765994151), omitting AWS steps and reducing Actions invocation layers. While it failed at the end, it did so with `'storage.objects.get' denied on resource` error, gs bucket doesn't seem to be public. Log entries before error are resembling that of your local run:
```
----------------------------- Captured stdout call -----------------------------
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.020 UTC|SSLCipher.java:464|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.031 UTC|SSLCipher.java:464|jdk.tls.keyLimits:  entry =  ChaCha20-Poly1305 KeyUpdate 2^37. CHACHA20-POLY1305:KEYUPDATE = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.468 UTC|Utilities.java:73|the previous server name in SNI (type=host_name (0), value=oauth2.googleapis.com) was replaced with (type=host_name (0), value=oauth2.googleapis.com)
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.527 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.529 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.578 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.579 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.631 UTC|Utilities.java:73|the previous server name in SNI (type=host_name (0), value=storage.googleapis.com) was replaced with (type=host_name (0), value=storage.googleapis.com)
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.632 UTC|Utilities.java:73|the previous server name in SNI (type=host_name (0), value=storage.googleapis.com) was replaced with (type=host_name (0), value=storage.googleapis.com)
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.651 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.653 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.656 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.656 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.678 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|10|Thread-3|2024-02-20 11:59:55.679 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.682 UTC|SSLCipher.java:1866|KeyLimit read side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
javax.net.ssl|DEBUG|3C|gcsfs-misc-0|2024-02-20 11:59:55.686 UTC|SSLCipher.java:2020|KeyLimit write side: algorithm = AES/GCM/NOPADDING:KEYUPDATE
countdown value = 137438953472
24/02/20 11:59:55 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: gs://test-data-mindlab-logikal-io/order_line_items.csv.
java.io.IOException: Error accessing gs://test-data-mindlab-logikal-io/order_line_items.csv
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getObject(GoogleCloudStorageImpl.java:1986)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.getItemInfo(GoogleCloudStorageImpl.java:1882)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystemImpl.getFileInfoInternal(GoogleCloudStorageFileSystemImpl.java:861)
	at com.google.cloud.hadoop.repackaged.gcs.com.google.cloud.hadoop.gcsio.GoogleCloudStorageFileSystemImpl.getFileInfo(GoogleCloudStorageFileSystemImpl.java:833)
	at com.google.cloud.hadoop.fs.gcs.GoogleHadoopFileSystem.getFileStatus(GoogleHadoopFileSystem.java:724)
	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:[566](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7973019374/job/21765994151#step:7:567))
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.google.cloud.hadoop.repackaged.gcs.com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
GET https://storage.googleapis.com/storage/v1/b/test-data-mindlab-logikal-io/o/order_line_items.csv?fields=bucket,name,timeCreated,updated,generation,metageneration,size,contentType,contentEncoding,md5Hash,crc32c,metadata
```
I also [tried invoking](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7972366337/job/21763998363) Dockerfile commands directly on a runner with results similar to above.

**Comment by shamil-mubarakshin** [comment] 2024-02-21 17:39
Direct invocation of Dockerfile commands [succeeded](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7992946875/job/21827620985).
Using actions workflow for `logikal-io/make-orb@v1` [failed](https://github.com/shamil-mubarakshin/tests-repository/actions/runs/7992944815/job/21827614167) with various 403 errors to bigquery and s3 bucket.

Those issues doesn't seem image related so far. Since now public access was enabled, could you re-run your workflow for `update-dependencies` branch?

**Comment by shamil-mubarakshin** [comment] 2024-02-27 08:37
@GergelyKalmar, using `WIF` auth instead of `Service Account JSON` has resulted in failure. This leads me to conclusion that error is in how WIF auth creds are handled by application. I also tested adding certificate of URL defined in `ACTIONS_ID_TOKEN_REQUEST_URL` env var to default java keystores (`/etc/ssl/certs/adoptium/cacerts`, `/etc/ssl/certs/java/cacerts`) but that didn't change workflow's behavior. Which certificate is expected by hadoop is unclear.
With above, I will be closing the issue for now. Feel free to reach out in case of further concerns.

**Closed by shamil-mubarakshin** 2024-02-27 08:37 UTC
Labels: Area: Java, OS: Ubuntu, bug report
