### ISSUE TITLE
Getting broken pipe, possibly during git operation

### ISSUE THREAD

**Issue by jessicah** [actions/runner-images#7536] opened 2023-05-05 04:16 UTC
### Description

Example of output from ubuntu-latest runner:
```
$ echo "hrev=hrev$(git ls-remote --tags https://review.haiku-os.org/haiku "hrev*" | sed -e 's:.*refs/tags/hrev::g' | sort -nr | head -n1)" >> "$GITHUB_OUTPUT"
sort: write failed: 'standard output': Broken pipe
sort: write error
```

Expected output should be something like:
```
$ echo "hrev=hrev$(git ls-remote --tags https://review.haiku-os.org/haiku "hrev*" | sed -e 's:.*refs/tags/hrev::g' | sort -nr | head -n1)"
hrev=hrev56969
```

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image: ubuntu-22.04
Version: 20230426.1

Example build: https://github.com/jessicah/haiku-tools/actions/runs/4889775429/jobs/8728587175.

Whilst it's technically not a failed job, it is causing the job to do more work than necessary.

### Is it regression?

No

### Expected behavior

The command to complete successfully, displaying the latest tag from the external git repo.

### Actual behavior

Broken pipe trying to get the latest tag from the external git repo.

### Repro steps

jobs:
  build_package_tool:
    runs-on: ubuntu-latest
    steps:
      - name: Check latest Haiku hrev
        id: get_hrev
        run: |
          echo "hrev=hrev$(git ls-remote --tags https://review.haiku-os.org/haiku "hrev*" | sed -e 's:.*refs/tags/hrev::g' | sort -nr | head -n1)" >> "$GITHUB_OUTPUT"

**Comment by Alexey-Ayupov** [comment] 2023-05-05 07:11
Hello @jessicah, we will take a look.

**Comment by ilia-shipitsin** [comment] 2023-05-12 12:55
Hello, @jessicah 

I ran your pipeline multiple times and I was not able to reproduce failure. I beleive it is rare failure due to network instability or "reviews.haiku-os.org" instability. Such instability can happen.

We cannot fix them on action images side.

However, there are ways how to catch those errors.

you may add "set -o pipefail" in the beginning of your script to catch execution errors in pipes, more [info](https://stackoverflow.com/questions/68465355/what-is-the-meaning-of-set-o-pipefail-in-bash-script).

also, `marvinpinto/action-automatic-releases@latest` is not compatible with strict pipefail, I had to set " set +o pipefail" in the end of my script to prevent automatic releases from fail.

**Comment by ilia-shipitsin** [comment] 2023-05-18 08:46
closing for now.
feel free to reopen if issue will persist

**Closed by ilia-shipitsin** 2023-05-18 08:46 UTC
Labels: OS: Ubuntu, bug report
