### ISSUE TITLE
STL compilation fails "expected Clang 16.0.0 or newer" on windows-2022

### ISSUE THREAD

**Issue by nimrod-gileadi** [actions/runner-images#8153] opened 2023-08-24 11:09 UTC
### Description

Our builds started failing sporadically with the following error:

```
In file included from C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\vector:9:
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\include\yvals_core.h:847:1: error: static assertion failed: Error in C++ Standard Library usage.
_EMIT_STL_ERROR(STL1000, "Unexpected compiler version, expected Clang 16.0.0 or newer.");
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files\Microsoft Visual Studio\[20](https://github.com/deepmind/mujoco_mpc/actions/runs/5956275936/job/16156683950#step:7:21)[22](https://github.com/deepmind/mujoco_mpc/actions/runs/5956275936/job/16156683950#step:7:23)\Enterprise\VC\Tools\MSVC\14.37.32822\include\yvals_core.h:502:5: note: expanded from macro '_EMIT_STL_ERROR'
    static_assert(false, "Error in C++ Standard Library usage.")
    ^             ~~~~~
1 error generated.
```

([link](https://github.com/deepmind/mujoco_mpc/actions/runs/5956275936/job/16156683950))

As commented by @pdimov in https://github.com/actions/runner-images/issues/8125#issuecomment-1691194433, this is likely because 20230820.1.0 image has an updated Visual Studio 2022.

It looks like LLVM will be upgraded soon  (#8125) to fix the issue, but is it possible to stop the current roll-out?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20230820.1.0

e.g.: https://github.com/deepmind/mujoco_mpc/actions/runs/5956275936/job/16156683950

### Is it regression?

Yes. It worked on version 20230804.1.0. e.g.: https://github.com/deepmind/mujoco_mpc/actions/runs/5956157545/job/16156331289

### Expected behavior

Successfully build STL using Clang.

### Actual behavior

Build fails with `"Unexpected compiler version, expected Clang 16.0.0 or newer."`.

### Repro steps

See the linked action above.

**Comment by mikhailkoliada** [comment] 2023-08-24 11:22
Duplicate of https://github.com/actions/runner-images/issues/8125

**Closed by mikhailkoliada** 2023-08-24 11:22 UTC
Labels: bug report
