### ISSUE TITLE
Autotools missing on macos-14 arm64

### ISSUE THREAD

**Issue by rob-p** [actions/runner-images#9302] opened 2024-02-05 18:38 UTC
### Description

I'm trying to use the macOS 14 Arm64 image to build some software.  While everything builds successfully on linux x86_64 and macOS x86_64, the Arm64 build fails.  The problem seems to be a missing autotools, suggested by the corresponding line from the build logs:

```
autoconf: command not found
```

The relevant link to this line in the offending build is [here](https://github.com/COMBINE-lab/piscem/actions/runs/7788874251/job/21239269151#step:7:622).  Any chance I'm missing something? If not, could autotools be added to this image? Thanks!

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [X] macOS 14
- [X] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240116.1

### Is it regression?

No

### Expected behavior

it is expected that `autotools` is installed and `autoconf` can be found in the path.

### Actual behavior

`autoconf` is not found, and the build is failing.

### Repro steps

Attempt to execute `autoconf` on the macos-14 Arm64 image.  Check the full build that is failing [here](https://github.com/COMBINE-lab/piscem/actions/runs/7788874251/job/21239269151#step:7:622).

**Comment by mikhailkoliada** [comment] 2024-02-05 19:21
Duplicate of https://github.com/actions/runner-images/issues/9290, currently there is no plan to pre-install auto tools, at least yet, but it can be reconsidered in the future, please install in runtime.

**Closed by mikhailkoliada** 2024-02-05 19:21 UTC
Labels: OS: macOS, bug report
