### ISSUE TITLE
[macOS] configure-tccdb-macos.sh contains 2 bad rules

### ISSUE THREAD

**Issue by liam-x** [actions/runner-images#8782] opened 2023-11-11 21:09 UTC
### Description

This file contains 2 bad rules:
images/macos/provision/configuration/configure-tccdb-macos.sh

Please see PR #8767 for details.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [X] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

don't have public build link

### Is it regression?

not sure

### Expected behavior

The PR #8767 contain fix.

### Actual behavior

The PR #8767 contain fix.
The correct rule should allow child process of provisioner take screenshot on macOS runner.

### Repro steps

screencapture ~/Desktop/picture.png

**Comment by Alexey-Ayupov** [comment] 2023-11-13 10:18
Hello, @liam-x. We will take a look and add your fix in case it fixes the issue.

**Comment by Alexey-Ayupov** [comment] 2023-11-17 11:57
We are going to close this issue since we could not reproduce it. If you have other questions, feel free to reach us.

**Comment by liam-x** [comment] 2023-11-28 00:55
Hi @Alexey-Ayupov  

Did you verify the content of the png file?
Without this rule, you can still get the png, but it only contain the macOS wallpaper. all its windows elements are not in the image.

**Comment by Alexey-Ayupov** [comment] 2023-11-28 10:27
Hi @liam-x, could you please provide an code example, where some windows in macOS open? I will check it. 
According to my quick test, indeed only wallpapers was on screenshots, but I have not run commands to open windows.

**Comment by liam-x** [comment] 2023-11-28 19:14
Hi @Alexey-Ayupov 

You can just use your script to test. Add 2 open commands before you do screenshot.
Then check the png to see if it contains Finder window.

```
run-name: test issue
on: 
  #[push]
  workflow_dispatch:
      
jobs:
  build:
    strategy:
      fail-fast: false
      matrix: 
        os: [macos-13, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    - name: check issue
        shell: bash
        run: |
            open ~/
            open ~/Downloads
            mver=$(sw_vers | grep "ProductVersion" | tail -c 5)
            screencapture /Users/runner/Desktop/picture${mver}.png
            azcopy cp "/Users/runner/Desktop/picture${mver}.png" "https://AureStorageAccount.blob.core.windows.net/scr?[SAS]"

```

**Comment by mohan-dope** [comment] 2023-12-06 04:53
> Hi @Alexey-Ayupov
> 
> Did you verify the content of the png file? Without this screen recording permission, you can still get the png, but it only contain the macOS wallpaper. all its windows elements are not captured.
> 
> And I am 100% certain the rule is wrong.
> 
> "'kTCCServiceScreenCapture','/usr/local/opt/runner/provisioner/provisioner',0,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159"
> 
> It should be `1` at the 3rd column here.
> 
> "'kTCCServiceScreenCapture','/usr/local/opt/runner/provisioner/provisioner',1,2,4,1,NULL,NULL,0,'UNUSED',NULL,0,1687786159"

@liam-x thank you for identifying the exact issue here. I was able to proceed further after updating the rule with the suggested changes. I will continue using this workaround until it is updated in the default runner image. 👍

**Comment by cmorten** [comment] 2023-12-10 00:18
Have noticed that I'm facing issues with the macos-13 agent when trying to use the `screencapture` command for screen recording which I wonder if is as a result of the inaccuracy described in this issue as well?

The script attempts to run something like...

```bash
/usr/sbin/screencapture -v -C -k -T0 -g ./recordings/playwright-voiceover-darwin-22.6.0-webkit-17_4-attempt-0-1702164859912.mov
```

Resulting in:

```log
stderr: screencapture: capture error The operation could not be completed
stdout: type any character (or ctrl-c) to stop screen recording
```

I'm unable to provide a screenshot (because of said issue) but I'm fairly certain a system privacy popup is being presented as I'm seeing `Open System Settings button` being returned by screen-reader output in my tests (See https://github.com/guidepup/guidepup/actions/runs/7154160984/job/19481351868, specifically the logs of `Run yarn --cwd ./examples/playwright-voiceover test:webkit`).

The stderr message of `screencapture: capture error The operation could not be completed` is also what I see locally if I don't allow the screen recording privacy option (`kTCCServiceScreenCapture`) for an application, and it pops up with a couple of "allow permission" like system dialogs.

**Comment by mikhailkoliada** [comment] 2023-12-21 19:01
Will be rolled out next year after holidays!

**Comment by mikhailkoliada** [comment] 2024-01-24 10:34
Should be deployed

**Closed by mikhailkoliada** 2024-01-24 10:34 UTC
Labels: awaiting-deployment, OS: macOS, bug report
