### ISSUE TITLE
Update/Add Debian sid

### ISSUE THREAD

**Issue by AlanCui4080** [actions/runner-images#9383] opened 2024-02-21 06:53 UTC
### Tool name

Debian 

### Tool license

Not applicable

### Add or update?

- [X] Add
- [ ] Update

### Desired version

unstable

### Approximate size

20GiB

### Brief description of tool

Debian ([/ˈdɛbiən/](https://en.wikipedia.org/wiki/Help:IPA/English)),[[5]](https://en.wikipedia.org/wiki/Debian#cite_note-debfaq-def-5)[[6]](https://en.wikipedia.org/wiki/Debian#cite_note-debianorg-about-6) also known as Debian GNU/Linux, is a [Linux distribution](https://en.wikipedia.org/wiki/Linux_distribution) composed of [free and open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software) and optionally [non-free firmware](https://en.wikipedia.org/wiki/Proprietary_firmware) or [software](https://en.wikipedia.org/wiki/Proprietary_software)[[7]](https://en.wikipedia.org/wiki/Debian#cite_note-Explaining_Why_We_Don't_Endorse_Other_Systems-7)[[8]](https://en.wikipedia.org/wiki/Debian#cite_note-General_Resolution:_non-free_firmware:_results-8) developed by the community-supported Debian Project.

ubuntu 2204 is too old for some project following upstream rapidly
e.g. c++23 support, libboost 1.83 support etc.
we can give it a pipeline to fetch debian sid daily build.

### URL for tool's homepage

debian.org

### Provide a basic test case to validate the tool's functionality.

```bash
Not applicable
```

### Platforms where you need the tool

- [X] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
Not applicable
```

### Tool installation time in runtime

Not applicable

### Are you willing to submit a PR?

Yes

**Comment by sergei-pyshnoi** [comment] 2024-02-21 11:31
closing as duplicate of https://github.com/actions/runner-images/issues/8183

**Closed** 2024-02-21 11:31 UTC
Labels: Area: Image administration, feature request
