### ISSUE TITLE
Add MAUI workload to macOS runner

### ISSUE THREAD

**Issue by thomasbach-dk** [actions/runner-images#7052] opened 2023-02-06 22:58 UTC
### Tool name

MAUI Workload

### Tool license

Unknown

### Add or update?

- [X] Add
- [ ] Update

### Desired version

Latest

### Brief description of tool

MAUI Workload is nescessary to build or publish a MAUI application with iOS target. MAUI Workload is pre-installed within the windows-latest image.

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [X] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
It can be installed during build with the following command:

dotnet workload install maui
```

### Tool installation time in runtime

5+ minutes

### Are you willing to submit a PR?

Yes

**Comment by mikhailkoliada** [comment] 2023-02-10 08:11
Duplicate of https://github.com/actions/runner-images/issues/6936

**Closed by mikhailkoliada** 2023-02-10 08:11 UTC
Labels: OS: macOS, needs eyes, feature request
