### ISSUE TITLE
EACCES: permission denied when running `yarn install` in a devcontainer

### ISSUE THREAD

**Issue by georgewitteman** [actions/runner-images#8160] opened 2023-08-24 23:53 UTC
### Description

Our CI jobs for devcontainers started failing with permission errors. This was initially detected in a private repository, but I was able to recreate the issue in this public repository: https://github.com/georgewitteman/devcontainer-ci-test. I haven't been able to reproduce a successful build there since I'm not able to use a previous runner version.

I tried searching for similar issues. https://github.com/actions/runner-images/issues/8157 seems similar but could also be unrelated.

I also checked versions for the `devcontainer` CLI, base docker images for the devcontainer, and `yarn` version and there wasn't anything that changed between the successful build and the failing build.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20230821.1.0
Build link: https://github.com/georgewitteman/devcontainer-ci-test/actions/runs/5970033316/job/16196937280

### Is it regression?

yes, it worked with 20230814.1.0 (no link since failure was noticed in a private repository first)

### Expected behavior

There would not be any permission error

### Actual behavior

```
[2023-08-24T23:47:46.776Z] + yarn install --immutable
[2023-08-24T23:47:47.435Z] Internal Error: EACCES: permission denied, mkdir '/workspaces/devcontainer-ci-test/.yarn/cache'
Error: EACCES: permission denied, mkdir '/workspaces/devcontainer-ci-test/.yarn/cache'
```

### Repro steps

Set up devcontainer and CI jobs following the template in https://github.com/georgewitteman/devcontainer-ci-test.

**Comment by Alexey-Ayupov** [comment] 2023-08-25 07:12
Hello @georgewitteman, we will take a look.

**Comment by shamil-mubarakshin** [comment] 2023-08-29 13:32
Hello @georgewitteman, issue seems to be in conflicting groups on host (`uid=1001(runner) gid=998(docker) groups=998(docker)`) and container (`uid=1000(node) gid=1000(node) groups=1000(node),998(nvm),999(npm)`). With [following](https://github.com/microsoft/vscode-remote-release/issues/7284#issuecomment-1271214932) suggestion in `devcontainers`, I was able to finish builds after additions to `Dockerfile`: 
- on ubuntu20 runner - `RUN delgroup nvm`
- on ubuntu22 runner - `RUN delgroup npm`

Issue looks like a duplicate of https://github.com/actions/runner-images/issues/8157. I will close this issue for now. Feel free to reach out in case of further concerns

**Closed by shamil-mubarakshin** 2023-08-29 13:32 UTC
Labels: Area: Containers, OS: Ubuntu, bug report
