### ISSUE TITLE
Windows builds fail with runner image 20221127.1

### ISSUE THREAD

**Issue by Salim-Khan-Techsmith** [actions/runner-images#6663] opened 2022-11-30 15:09 UTC
### Description

Our azure pipelines are occasionally picking up the 20221127.1 image, instead of the 20221120.1 image that is documented in this repo. It seems to be every 4-6 runs we get the new image.

The issue we are having is that we are calling the vcvars64.bat script from visual studio to populate compiler information for a CMake build. Something has changed and now this fails, and CMake is unable to run, as it has no compiler information.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

20221127.1

### Is it regression?

20221120.1

### Expected behavior

vcvars64.bat should populate the right environment variables for Cmake to run.

### Actual behavior

Cmake is unable to find compiler information in the proper environment variables

### Repro steps

We are unable to get the 20221127.1 image consistently to do dedicated testing. 

If we did we would reproduce with
1. run vcvars64.bat
2. Run a cmake configure

**Comment by mikhailkoliada** [comment] 2022-12-01 07:35
Possible duplicate of: #6627

**Closed by mikhailkoliada** 2022-12-01 07:35 UTC
Labels: needs triage, bug report
