### ISSUE TITLE
Add MAUI support on MacOS runner

### ISSUE THREAD

**Issue by md-owes** [actions/runner-images#7994] opened 2023-07-28 10:56 UTC
### Tool name

MAUI workload

### Tool license

MIT

### Add or update?

- [X] Add
- [ ] Update

### Desired version

MAUI .Net6 and .Net7 SDK

### Brief description of tool

MAUI will allow cross platform development of softwares/application written using .Net SDK. This tool is installed via a dotnet workload command as shown below
`sudo dotnet workload install maui --source https://api.nuget.org/v3/index.json`
Note: above code is referenced from [Microsoft docs](https://learn.microsoft.com/en-us/dotnet/maui/mac-catalyst/cli)

The tool is already available as part of windows-latest github runner as shown [here](https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#workloads-components-and-extensions)

### URL for tool's homepage

https://github.com/dotnet/maui

### Platforms where you need the tool

- [ ] Azure DevOps
- [X] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
dotnet workload install maui
```

### Tool installation time in runtime

~ 2-3 mins

### Are you willing to submit a PR?

yes

**Comment by sergei-pyshnoi** [comment] 2023-07-28 12:12
Hello @md-owes , we will take a look.

**Comment by sergei-pyshnoi** [comment] 2023-07-28 16:27
Closing as duplicate of https://github.com/actions/runner-images/issues/6936

**Closed by sergei-pyshnoi** 2023-07-28 16:27 UTC
Labels: Area: .NET Framework, OS: macOS, needs eyes, feature request

**Comment by md-owes** [comment] 2023-07-28 16:33
@sergei-pyshnoi, issue #6936 talks about MAUI installation on windows runner which is completed. In this ticket, my request is to provide MAUI support on mac runner. I guess both are not duplicate of each other.

**Comment by md-owes** [comment] 2023-08-28 08:58
@sergei-pyshnoi, Apologies if i am being impatient. But can i have some response on my previous comment?
