### ISSUE TITLE
Signature Thumbprint do not match expected when building Windows-2022

### ISSUE THREAD

**Issue by jdesbois** [actions/runner-images#10226] opened 2024-07-15 12:14 UTC
### Description

When attempting to build the windows 2022 agent using the packer file it will produce an error:
`    azure-arm.image: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.image: Package downloaded in 0.22 seconds
    azure-arm.image: Signature thumbprint do not match expected.
    azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
    azure-arm.image: +         throw "Signature thumbprint do not match expected."
    azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.`

This has been pretty consistent since last Thursday

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/tree/win22/20240707.1

### Is it regression?

No

### Expected behavior

Build to complete uninhibited

### Actual behavior

Our pipeline that builds the Runner Image for Windows 2022 is failing when attempting to install Visual Studio Enterprise and producing thumbprint error

### Repro steps

Checkout lastest release for windows 2022
Run Packer build fiel

**Comment by kishorekumar-anchala** [comment] 2024-07-15 12:34
Hi @jdesbois , We're working on your issue, we will update you shortly. Thankyou !

**Comment by jdesbois** [comment] 2024-07-15 12:42
Hi @kishorekumar-anchala,

We currently have a pipeline that checks out the latest release for Windows-2022 agent and then just runs the build command on the packer file. The only changes we make to any files is to add tags to the azure resources built by Packer. 
The build is being run on an Ubuntu 22.04 Docker container with the associated tools for Packer installed if that has an precedence on the issue?

Thanks for the help

**Comment by kishorekumar-anchala** [comment] 2024-07-15 12:56
No , This issue came when signature mismatches. I have verified the thumbprint value is correct. Please look into below issue.

Similar [issue ](https://github.com/actions/runner-images/issues/10201)

**Comment by kishorekumar-anchala** [comment] 2024-07-16 06:33
Hi @jdesbois ,

  We're unable to reproduce the issue with vs signature , hence closing the issue. 
  
  Thankyou !

**Closed by kishorekumar-anchala** 2024-07-16 06:33 UTC
Labels: OS: Windows, bug report

**Comment by jdesbois** [comment] 2024-07-16 08:08
@kishorekumar-anchala 
Thank you for the quick response. I believe the issue was that I was checking out the latest release of the image rather than the fixed main branch.
Does that mean that the releases of images can sometimes not be depended on since its not buildable in its current state?

Thanks in advance

John
