### ISSUE TITLE
Error during SuperTux CPack packaging step since 20230803.1

### ISSUE THREAD

**Issue by tobbi** [actions/runner-images#8078] opened 2023-08-13 09:50 UTC
### Description

I noticed that the CPack step in our build script started failing after updating to the latest runner version.

You can find our build script here: https://github.com/SuperTux/supertux/blob/master/.github/workflows/macos.yml

The script that gets called is this: https://github.com/SuperTux/supertux/blob/master/.ci_scripts/package.sh

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20230803.1
https://github.com/SuperTux/supertux/actions/runs/5840469967/job/15839754031

### Is it regression?

20230709.1
https://github.com/SuperTux/supertux/actions/runs/5803629706/job/15732010068

### Expected behavior

The packaging passes

### Actual behavior

This is the error that I'm getting during the "package" step for SuperTux:

```
CPack: Create package using Bundle
CPack: Install projects
CPack: - Run preinstall target for: SUPERTUX
CPack: - Install project: SUPERTUX []
CMake Error at /usr/local/Cellar/cmake/3.27.1/share/cmake/Modules/BundleUtilities.cmake:458 (message):
  otool -l failed: 1

  error:
  /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic:
  can't open file: @loader_path/../../../../opt/glib/lib/libglib-2.0.0.dylib
  (No such file or directory)

Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.27.1/share/cmake/Modules/BundleUtilities.cmake:527 (get_item_rpaths)
  /usr/local/Cellar/cmake/3.27.1/share/cmake/Modules/BundleUtilities.cmake:649 (set_bundle_key_values)
  /usr/local/Cellar/cmake/3.27.1/share/cmake/Modules/BundleUtilities.cmake:933 (get_bundle_keys)
  /Users/runner/work/supertux/supertux/build/cmake_install.cmake:123 (fixup_bundle)


CPack Error: Error when generating package: SuperTux
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
Error: Process completed with exit code 64.
```

### Repro steps

1. Run the macos workflow for SuperTux
2. See it fail during the package step.

**Comment by shamil-mubarakshin** [comment] 2023-08-14 07:56
Hello @tobbi.
Thanks for reporting, we will investigate the issue

**Comment by vpolikarpov-akvelon** [comment] 2023-08-15 16:47
Hey @tobbi. It's related with [harfbuzz](https://github.com/harfbuzz/harfbuzz) package. There was a major release recently and it seems to break your workflow. I succeeded fixing your workflow by rolling that update back: https://github.com/vpolikarpov-akvelon/supertux/actions/runs/5869174222

**Comment by tobbi** [comment] 2023-08-15 16:53
Thank you so much! Could we somehow raise this to the homebrew or harfbuzz guys?

**Comment by tobbi** [comment] 2023-08-15 18:02
@behdad Do you have any idea why this happens?

**Comment by behdad** [comment] 2023-08-15 19:45
Where can I see the harfbuzz-related error. I couldn't find.

It's this a cmake issue or compile issue? I think we made some changes to our cmake setup. cc @khaledhosny

**Comment by tobbi** [comment] 2023-08-15 23:47
I feel like it might be a cmake or install issue.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-16 05:08
@behdad, there is no harfbuzz error, but issue emerged as a result of the release of harfbuzz version 8. You can mitigate it by rolling it back to 7.3.

**Comment by vpolikarpov-akvelon** [comment] 2023-08-16 16:14
@tobbi, I think it would be more productive if you escalate this to harfbuzz repo yourself as you definitely have a lot more experience with this software then me.

**Comment by behdad** [comment] 2023-08-16 16:30
> @tobbi, I think it would be more productive if you escalate this to harfbuzz repo yourself as you definitely have a lot more experience with this software then me.

I'm a harfbuzz developer. I'm trying to figure out what's up here.

**Comment by behdad** [comment] 2023-08-16 18:58
I don't know what I can do with the little information available here.

**Comment by tobbi** [comment] 2023-08-17 03:08
> I don't know what I can do with the little information available here.

What more information do you need?

**Comment by vpolikarpov-akvelon** [comment] 2023-08-23 08:48
Hey @behdad. We would greatly appreciate your assistance in helping us resolve this issue. If you have any insights or suggestions, or if there are specific details you require from our end to diagnose the problem more effectively, please do not hesitate to let us know. Your expertise in Harfbuzz would be invaluable in getting to the bottom of this issue. Thanks.

**Comment by tobbi** [comment] 2023-08-23 12:07
Technically, `git bisect` could be used to find the offending commit. I just don't know how to best use it in the context of this issue

**Comment by tobbi** [comment] 2023-08-23 14:55
Local build works fine. I'm currently running a git bisect on the build machines with some homebrew trickery.

**Comment by tobbi** [comment] 2023-08-23 15:19
@vpolikarpov-akvelon Do you know if the download speed gets throttled after running a build multiple times?

**Comment by vpolikarpov-akvelon** [comment] 2023-08-23 15:21
What kind of download you are talking about?

**Comment by vpolikarpov-akvelon** [comment] 2023-08-23 15:27
Unfortunately, I don't know. I hope it will gone soon.

**Comment by behdad** [comment] 2023-08-23 19:02
> Hey @behdad. We would greatly appreciate your assistance in helping us resolve this issue. If you have any insights or suggestions, or if there are specific details you require from our end to diagnose the problem more effectively, please do not hesitate to let us know. Your expertise in Harfbuzz would be invaluable in getting to the bottom of this issue. Thanks.

I'm out of my depth here. The error I see:
```
  error:
  /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool-classic:
  can't open file: @loader_path/../../../../opt/glib/lib/libglib-2.0.0.dylib
  (No such file or directory)
```
is not HarfBuzz-specific per se. Just happens that HB links to glib. But that hasn't changed in a long time. Other than that I have no clue what's going on. Sorry.

**Comment by tobbi** [comment] 2023-08-23 20:08
https://github.com/SuperTux/supertux/pull/2601/files#diff-7b74d73de878e0e53f6768bbf3a3d4b50c3c6f1f16f9b64518690028b8206b1cR53-R54

I found out that removing the preinstalled version of harfbuzz from the build machines and then reinstalling them with `--build-from-source` will work.

If it also works without `--build-from-source`, we can be certain this is an issue with the way harfbuzz is preinstalled on the build machines (as opposed to an issue with the way brew installs it)

**Comment by tobbi** [comment] 2023-08-23 20:33
Alright! Apparently, it doesn't work without `--build-from-source`. I'm assuming the issue is therefore with the way homebrew installed harfbuzz. 

@behdad Sorry for roping you in when this wasn't a harfbuzz issue after all.

**Comment by behdad** [comment] 2023-08-23 20:47
> @behdad Sorry for roping you in when this wasn't a harfbuzz issue after all.

No problem. I'm glad this is being figured out.

**Comment by tobbi** [comment] 2023-08-23 21:03
https://github.com/orgs/Homebrew/discussions/4735 for the homebrew discussion

**Comment by vpolikarpov-akvelon** [comment] 2023-08-28 13:08
I'm closing this issue as it doesn't seem to be caused by runner image. Feel free to reach out if you have other questions or need extra support. Thank you.

**Closed by vpolikarpov-akvelon** 2023-08-28 13:08 UTC
Labels: Area: C/C++, OS: macOS, investigate, bug report

**Comment by ZhongRuoyu** [comment] 2023-09-04 08:14
FYI: this should be addressed. See Homebrew/homebrew-core#140930 for more information.
