### ISSUE TITLE
Running `patch` on windows-2022 started failing with "Can't rename file"

### ISSUE THREAD

**Issue by gh-andre** [actions/runner-images#8632] opened 2023-10-22 19:38 UTC
### Description

This started happening withing a week or a couple of weeks, maybe. Even repositories that used to patch source without problems are now failing with the same error.

It appears that the new version of `patch` on `windows-2022` has a bug in how it handles temporary files when applying patches.

I verified that the source is in place and that directories where patches are applied have write permissions.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

See this run:

https://github.com/StoneStepsInc/exiv2-nuget/actions/runs/6605674497/job/17941093858

Expand _Patch source_ to see errors.

### Is it regression?

yes

### Expected behavior

A patch used to apply properly in the source tree just a couple of weeks ago.

### Actual behavior

Patches now are failing with messages like this:

> patching file include/exiv2/basicio.hpp
> patch: **** Can't rename file include/exiv2/basicio.hpp.oO03KIQ to include/exiv2/basicio.hpp : No such file or directory

### Repro steps

Have a patch and run it in `cmd` shell like this on a `windows-2022` image:
```
patch -p1 --unified --input ..\patches\03-cmake-find-zlib-expat.patch
```

**Comment by ilia-shipitsin** [comment] 2023-10-23 08:29
thank you for the report, we'll have a look

**Comment by ilia-shipitsin** [comment] 2023-10-23 08:39
our investigation shown that regression is the same (most likely) as https://github.com/actions/runner-images/issues/8598
new image is to be deployed this week

**Comment by mikhailkoliada** [comment] 2023-10-23 20:00
Marking as a duplicate of https://github.com/actions/runner-images/issues/8598 as it has workaround inside

**Closed by mikhailkoliada** 2023-10-23 20:00 UTC
Labels: awaiting-deployment, OS: Windows, Area: Common Tools, bug report

**Comment by gh-andre** [comment] 2023-10-23 20:59
Disappointing. Instead of fixing the broken image GitHub forces people to change a ton of actions with a hack of modifying their paths, without even providing any idea when this broken image will be fixed.

Anyway, if anybody using `cmd` shell stumbles upon this issue, here's the fix that worked for me.
```
      run: |
        PATH %PATH:C:\Strawberry\c\bin;=%
        patch ...
```
