### ISSUE TITLE
Windows processes are started with a lower process priority class

### ISSUE THREAD

**Issue by Cyberboss** [actions/runner-images#7663] opened 2023-06-02 21:30 UTC
### Description

Linux builds are spawned with normal niceness

Windows builds are spawned with BelowNormal process priority.

This causes issues in systems that expect it to be normal upon launch.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

See repro: https://github.com/Cyberboss/actions_testbed/actions/runs/5159892878

### Is it regression?

Unknown

### Expected behavior

Processes run at Normal priority

### Actual behavior

Processes run at BelowNormal priority

### Repro steps

There's a repro workflow here: https://github.com/Cyberboss/actions_testbed/blob/main/.github/workflows/windows_process_priority_fail.yml

Results: https://github.com/Cyberboss/actions_testbed/actions/runs/5159892878

### Workarounds

Processes seem to be able to change this, so they can fix it themselves. See https://github.com/tgstation/tgstation-server/commit/50c657ea32bfe76655599dd90f45f4af408ad050

**Comment by Iamgoofball** [comment] 2023-06-03 00:49
░░░░░░░░░░░░▄▄                     
░░░░░░░░░░░█░░█                  
░░░░░░░░░░░█░░█                  
░░░░░░░░░░█░░░█                  
░░░░░░░░░█░░░░█                  
███████▄▄█░░░░░██████▄ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█░░░░ Github, ░░░░░█ 
 ▓▓▓▓▓▓█░░░░Fix This░░░░░█  
▓▓▓▓▓▓█░░░░Please!░░░░░█ 
▓▓▓▓▓▓█░░░░░░░░░░░░░░█ 
▓▓▓▓▓▓█████░░░░░░░░░█   
██████▀░░░░▀▀██████▀

**Comment by shamil-mubarakshin** [comment] 2023-06-05 09:16
Hi @Cyberboss,

We will check this behavior

**Comment by vpolikarpov-akvelon** [comment] 2023-06-06 09:25
Hey @Cyberboss. This behavior is caused by the way how runners provisioning works. Worker process itself runs with PriorityClass `BelowNormal` and this is unlikely to be changed.

If you need your process to run with higher priority you can either:
- Set priority class for the current step using this command in the beginning of your script:
  ```powershell
  [System.Diagnostics.Process]::GetCurrentProcess().PriorityClass = [System.Diagnostics.ProcessPriorityClass]::Normal
  ```
- Set priority class for all the upcoming steps by changing class for Worker process:
  ```yaml
  - name: Set Priority Class for Runner.Worker
    shell: powershell
    run: |
      (Get-Process -Name "Runner.Worker").PriorityClass = [System.Diagnostics.ProcessPriorityClass]::Normal
  ```

**Comment by vpolikarpov-akvelon** [comment] 2023-06-09 12:21
Well, I'm closing this issue. Feel free to reopen it or create a new one if you still have questions or experience other problems.

**Closed by vpolikarpov-akvelon** 2023-06-09 12:21 UTC
Labels: OS: Windows, Area: Image administration, bug report
