### ISSUE TITLE
pip installs binaries to location outside the PATH after upgrading to ubuntu-22.04

### ISSUE THREAD

**Issue by erikkrieg** [actions/runner-images#7476] opened 2023-04-21 16:05 UTC
### Description

Hello!

My team recently upgraded our self-hosted runner images from:
```
summerwind/actions-runner:v2.300.2-ubuntu-20.04 -> summerwind/actions-runner:v2.303.0-ubuntu-22.04
```

After making the upgrade, we noticed some of our jobs failing because binaries installed in those jobs were no longer on the `PATH`. Example error from a failing job: `cookiecutter: No such file or directory`

For this particular job, we were using `pip` to install a binary called `cookiecutter` like so: `pip install cookiecutter`

While the install step exited successfully, we are getting these warnings that indicate `pip` is installing to `/home/runner/.local/bin`, which is no longer on the `PATH`:

Example warnings from installing cookiecutter:
```
WARNING: The script slugify is installed in '/home/runner/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script normalizer is installed in '/home/runner/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script chardetect is installed in '/home/runner/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: The script cookiecutter is installed in '/home/runner/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

For now we are getting around this by modifying paths in the affected jobs, but we would rather know how we can patch this in our runner images. We have attempted adding layers to our runner image like `ENV PATH="${PATH}:/home/runner/.local/bin"` or by updating the PATH in `/home/runner/.bashrc` without success.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Current runner version: '2.303.0'
Runner image: 'summerwind/actions-runner:v2.303.0-ubuntu-22.04'

We are using a custom image built `FROM` summerwind/actions-runner:v2.303.0-ubuntu-22.04. The bug surfaced after a change to the tag of that base image. No other layers in our custom image were modied.

We do not have public build to link to, unfortunately.

### Is it regression?

summerwind/actions-runner:v2.300.2-ubuntu-20.04

### Expected behavior

Package managers like `pip` install binaries that are executable without manipulating paths in the CI job directly. In this case either `/home/runner/.local/bin` is in the `PATH` loaded into the shell running our jobs or `pip` installs to a location that is on the `PATH` without additional configuration.

### Actual behavior

`/home/runner/.local/bin` is not in the `PATH`. Jobs need to manually modify their `PATH` in order to execute binaries installed by package managers like `pip`.

### Repro steps

Steps to reproduce are very simple:
- In one step install the binary: `pip install cookiecutter`
- In the next step, attempt to execute it: `cookiecutter --help`

**Comment by erikkrieg** [comment] 2023-04-21 16:12
Just heard from my colleague who tells me that `pip` was installing to `/home/runner/.local/bin` in the previous image we used, so we think it is the `PATH` that has changed.

**Comment by erik-bershel** [comment] 2023-04-22 15:26
Hi @erikkrieg!
Hmmm. I cannot reproduce the issue with our latest Ubuntu 22.04 runner. Are you sure that your workflow didn't change $PATH?
Example:
```
jobs:
  pip-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check ENV
      run: echo $PATH
    - name: PIP install
      run: pip install cookiecutter
    - name: test run
      run: cookiecutter --help
```
Result:
<img width="1069" alt="Screenshot 2023-04-22 at 17 24 34" src="https://user-images.githubusercontent.com/110455084/233793110-149391a1-1ef8-423f-9171-d2203e2f2938.png">

So, please provide more info or I'll be forced to close the issue.

**Comment by erik-bershel** [comment] 2023-04-22 15:27
echo $PATH will result this for ubuntu-latest:
```
/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

**Comment by erikkrieg** [comment] 2023-04-23 15:44
> echo $PATH will result this for ubuntu-latest:
> 
> ```
> /home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> ```

When we echo `$PATH` from the failing job we see: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by erikkrieg** [comment] 2023-04-23 15:48
Our job looks like this (with some names obfuscated):

```
job-name:
    runs-on: [self-hosted, ci]
    steps:
    - uses: actions/checkout@v2
    - name: Install cookiecutter
      run: pip install cookiecutter
    - name: Do something with cookiecutter
      run: make use-cookiecutter
```

**Comment by erikkrieg** [comment] 2023-04-23 15:55
This job was not modified directly, the change was to the image running on our self-hosted "ci" runner.

This is the diff of the change the broke us:

<img width="1622" alt="Screenshot 2023-04-23 at 11 51 26 AM" src="https://user-images.githubusercontent.com/10244162/233850314-43cd0651-8b96-4b3d-b319-943cedf39a4e.png">

**Comment by erik-bershel** [comment] 2023-04-23 20:53
@erikkrieg $PATH variable already correctly set in our images. Take a look here: https://github.com/actions/runner-images/blob/main/images/linux/scripts/installers/python.sh#:~:text=prependEtcEnvironmentPath%20%27%24HOME/.local/bin%27
I cannot be sure that your self-hosted runner assembled with using of all the scripts without any changes. At first glance, and at second glance, the problem lies precisely in how your runner is built, and not in our runners or scripts.
Please use the instructions for assembling a self-hosted runner: https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md

**Closed by erik-bershel** 2023-04-23 20:53 UTC
Labels: Area: Packages, OS: Ubuntu, bug report

**Comment by erikkrieg** [comment] 2023-04-23 21:11
Thanks for taking a look and providing the links. I'll bring this back to my team. Seems like we are going to need to inspect the layers to understand where things are going awry.

**Comment by erikkrieg** [comment] 2023-04-26 16:23
Seems like I opened this issue in the wrong project. We think that the [actions-runner-controller is where the issue could be](https://github.com/actions/actions-runner-controller/issues/2540) originating from.
