### ISSUE TITLE
Docker Compose v2.19.0 needs to be patched to v2.19.1 to fix "container not connected to network" errors

### ISSUE THREAD

**Issue by cgaudette** [actions/runner-images#7862] opened 2023-07-05 23:09 UTC
### Description

I'm writing this on behalf of my customer who filed an issue where they were seeing this error:

```
Error response from daemon: container 7377e46299f8ca5ba254a9491d390cf9599f86cfd299d505a120271017850627 is not connected to the network kind
```
Through their investigative work, they found we pushed a [new base image](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1) last week, pushing docker to 2.19.0. Docker released a bug fix for this specific error in v2.19.1:

- https://docs.docker.com/compose/release-notes/#2191

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230625.1

### Is it regression?

yes

### Expected behavior

The container should connect to network during `compose up` job.

### Actual behavior

Error that occurs during workflow run:

```
Error response from daemon: container 7377e46299f8ca5ba254a9491d390cf9599f86cfd299d505a120271017850627 is not connected to the network kind
```

### Repro steps

1. Set up Docker Composer services which connect to a Kind docker network
2. Make sure the runner-image is up to date and using Docker Compose v2.19 
3. Run an action which attempt to establish connection to the network and you may see this error (the bugfix notes this is `sporadic`)

**Comment by clementai** [comment] 2023-07-06 08:26
Duplicate https://github.com/actions/runner-images/issues/7857

**Comment by shamil-mubarakshin** [comment] 2023-07-06 09:47
Hello @cgaudette,
I will close this issue as a duplicate of https://github.com/actions/runner-images/issues/7857.
Feel free to reach out in case of concerns

**Closed by shamil-mubarakshin** 2023-07-06 09:47 UTC
Labels: duplicate, Area: Common Tools, bug report
