### ISSUE TITLE
Windows Server 2022 image fails to build ARM32 components

### ISSUE THREAD

**Issue by eduardo-vp** [actions/runner-images#11123] opened 2024-12-06 23:09 UTC
### Description

The dotnet-netnative pipeline was working correctly but seems like the latest version of the Windows Server 2022 image doesn't allow to build ARM32 components and the pipeline suddenly stopped working. 

You may find at the bottom of the logs of this step the errors https://dev.azure.com/dnceng/internal/_build/results?buildId=2593135&view=logs&j=d25e1be0-2c40-54f7-c4f2-6c08c695c10f&t=0d994932-ea73-5332-d629-cb50e0ff4f0b. The step is marked as green by Azure pipelines but it actually failed.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image version: 20241125.1.0

https://dev.azure.com/dnceng/internal/_build/results?buildId=2593135&view=logs&j=d25e1be0-2c40-54f7-c4f2-6c08c695c10f&t=0d994932-ea73-5332-d629-cb50e0ff4f0b (The step is marked as green by Azure pipelines but it actually failed)

### Is it regression?

Yes, the latest image version that worked is 20241021.1.0, build link: https://dev.azure.com/dnceng/internal/_build/results?buildId=2590038&view=results

### Expected behavior

ARM32 components should be able to build.

### Actual behavior

ARM32 components don't build, I believe the image might be using x86 binaries when ARM32 ones were expected.

### Repro steps

Don't know if there's a better way than updating the pipeline image and running the pipeline.

**Comment by hemanthmanga** [comment] 2024-12-09 09:58
Hi @eduardo-vp, Thank you for bringing this issue to our attention. We are looking into this issue and will update you on this issue after investigating.

**Comment by zufuliu** [comment] 2024-12-11 12:14
Duplicate of issue #10981.

**Closed** 2024-12-13 17:44 UTC
Labels: OS: Windows, bug report
