### ISSUE TITLE
Exception setting "Version" error during provisioning for Ubuntu 22.04

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [actions/runner-images#6922] opened 2023-01-15 21:33 UTC
### Description

I am trying to build the runner image for Ubuntu 22.04 and everything proceeds well for around 2 hours until I get to the provisioning step where `SoftwareReport.Generator.ps1` is executed. At this point, the packer build fails with the following error:

```
==> azure-arm.build_vhd: Provisioning with shell script: D:/Sayak/Work/Misc/runner-images/images/linux/scripts/base/apt-mock-remove.sh
==> azure-arm.build_vhd: Provisioning with shell script: C:\Users\mukho\AppData\Local\Temp\packer-shell3143520940
==> azure-arm.build_vhd:  ›   Warning: Our terms of service have changed:
==> azure-arm.build_vhd:  ›   https://dashboard.heroku.com/terms-of-service
==> azure-arm.build_vhd: /imagegeneration/SoftwareReport/SoftwareReport.Generator.ps1 : Exception setting "Version": "The argument is null or empty. Provide an argument that is not null or empty, and then try the command again."
==> azure-arm.build_vhd: + CategoryInfo          : NotSpecified: (:) [SoftwareReport.Generator.ps1], SetValueInvocationException
==> azure-arm.build_vhd: + FullyQualifiedErrorId : ExceptionWhenSetting,SoftwareReport.Generator.ps1
==> azure-arm.build_vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> azure-arm.build_vhd: Step "StepProvision" failed
==> azure-arm.build_vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?
```

I am not sure as to exactly what is causing the issue as it takes a couple of hours to come to this issue.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

I am building locally on my workstation.

### Is it regression?

Don't know as this is the first time I am trying this

### Expected behavior

I expected the packer build to complete successfully.

### Actual behavior

The packer build is throwing an error and then cleaning up and exiting with exit code 1.

### Repro steps

I am executing the packer build by running `GenerateResourcesAndImage -SubscriptionId 12345678-1234-1234-1234-12345678901 -ResourceGroupName my-rg -ImageType Ubuntu2204 -AzureLocation "Central India"` according to https://github.com/actions/runner-images/blob/main/docs/create-image-and-azure-resources.md#prepare-environment-and-image-deployment

I tried running 2 times and the error happened both the times. Since its almost at the end of the build flow, it takes a couple of hours before the error shows and hence I am not able to try and get to the root cause of this. Still, if there is a quicker way I can get this error to trigger, I can update the repro steps in here.

**Comment by oramoss** [comment] 2023-01-16 07:15
I get same issue for Ubuntu 22.04.
I'd successfully been running the build daily for several days and then it started failing on 12th January 2023 without any changes in my process.
Like above, it fails after a number of hours of build time.
I've rerun several times across several days but still failing - last run 15th January 2023.
Running the call with powershell scripting against a VM Scale Set Agent managed by Azure DevOps.

Call to run the generate:

GenerateResourcesAndImage -SubscriptionId "$SubscriptionId" -ResourceGroupName "$ResourceGroupName" -ImageGenerationRepositoryRoot "$pwd" -ImageType "$ImageType" -AzureLocation "$AzureLocation" -AzureClientId "$AADApplicationID" -AzureClientSecret "$AADApplicationSecret" -AzureTenantId "$AADTenantID" -Force

Sanitised log uploaded.

[ImageBuildFailLog.txt](https://github.com/actions/runner-images/files/10423339/ImageBuildFailLog.txt)

**Comment by davidhoferzeni** [comment] 2023-01-16 08:54
+1

Running the process via Azure DevOps pipeline on a VMSS (Linux) agent as well.
Additionally, I have tried creating a vhd for Ubuntu 20.04 with the same error message.

Will try to aggregate some more logs/information in the meantime.

PS: Is PR #6919 related to this? Running the pipeline again right now to test.

FYI @mikhailkoliada

**Comment by erik-bershel** [comment] 2023-01-16 09:02
@davidhoferzeni yes, issue is related to that PR you mentioned. Should be fixed already.

**Comment by erik-bershel** [comment] 2023-01-16 09:03
@SayakMukhopadhyay please try again with the latest changes and update your status.

**Comment by SayakMukhopadhyay** [comment] 2023-01-16 09:06
I should be able to test in 6 hours or so, so just hold on.

**Comment by oramoss** [comment] 2023-01-16 09:29
I'm rerunning now....report back in few hours...

**Comment by davidhoferzeni** [comment] 2023-01-16 09:43
@erik-bershel absolutely awesome, thanks for the fast reply!
Since I had already triggered a run two hours ago, I can confirm that from my side the pipeline is now finishing correctly and generating the image successfully.

**Comment by oramoss** [comment] 2023-01-16 10:58
Yes, Ubuntu-2204 working for me now as well. Thanks.

**Comment by erik-bershel** [comment] 2023-01-16 11:33
So I close that issue. 
@SayakMukhopadhyay please feel free to ping me here if you have something to add. Or you may open new one if you have another troubles or concerns.

**Closed by erik-bershel** 2023-01-16 11:33 UTC
Labels: OS: Ubuntu, Area: Image administration, bug report

**Comment by SayakMukhopadhyay** [comment] 2023-01-16 16:06
yep, the build worked. Thanks for making the quick fix!
