### ISSUE TITLE
hub command missing in Ubuntu github runner

### ISSUE THREAD

**Issue by jayshah123** [actions/runner-images#8531] opened 2023-10-11 04:20 UTC
**Describe the bug**

We use following in our github runner:
```
        PR_URL=$(hub pull-request -m "$PR_TITLE" -b $TARGET_BRANCH -h $SOURCE_BRANCH -l "$LABELS")
```

In recent versions of github runners since last week, with `ubuntu-latest` as a runner we see following:
```
/home/runner/work/_temp/85ff9435-66c6-4f75-9dfe-d490b6091f11.sh: line 23: hub: command not found
``` 

**To Reproduce**
1. User runner `ubuntu-latest`
2. Try using `hub` command
3. See error

**Expected behavior**
`hub` comamnd should be present in Github runner, if this was a breaking change, it should have been announced.

## Runner Version and Platform
Version of your runner?
ubuntu-latest

OS of the machine running the runner? OSX/Windows/Linux/...
ubuntu

## What's not working?

```
/home/runner/work/_temp/85ff9435-66c6-4f75-9dfe-d490b6091f11.sh: line 23: hub: command not found

```

## Job Log Output

```
/home/runner/work/_temp/85ff9435-66c6-4f75-9dfe-d490b6091f11.sh: line 23: hub: command not found

```

## Runner and Worker's Diagnostic Logs
If applicable, add relevant diagnostic log information.  Logs are located in the runner's `_diag` folder. The runner logs are prefixed with `Runner_` and the worker logs are prefixed with `Worker_`. Each job run correlates to a worker log.  All sensitive information should already be masked out, but please double-check before pasting here.

**Comment by thboop** [comment] 2023-10-11 18:54
Hey @jayshah123 thanks for the report. I've gone ahead and transferred this to the runner images channel, which owns image generation for hosted runners

**Comment by gariem** [comment] 2023-10-11 19:34
Same error here! It would be nice to have a workaround meanwhile. All actions fail because of that :(

**Comment by wojsmol** [comment] 2023-10-11 23:11
This is expected behaviour - see [announcement](https://github.com/actions/runner-images/issues/8362) with mitigation steps.

**Comment by vpolikarpov-akvelon** [comment] 2023-10-12 08:07
Please see recent announcement: https://github.com/actions/runner-images/issues/8362
There are workaround for each operation system there.

**Closed by vpolikarpov-akvelon** 2023-10-12 08:07 UTC
Labels: bug
