### ISSUE TITLE
Update/Add [tool name]

### ISSUE THREAD

**Issue by nwcm** [actions/runner-images#8740] opened 2023-11-06 06:02 UTC
### Tool name

pnpm

### Tool license

The MIT License (MIT)

### Add or update?

- [X] Add
- [ ] Update

### Desired version

whatever is latest

### Approximate size

57.6 MB - 71.5 MB

### Brief description of tool

An alternative package manager similar to `npm` and `yarn`

Supporting this would allow alignment with local package management and the CI/CD builds. 

Would speedup complex builds where `npm install` may be called multiple times, or multiple installs which share dependencies.

### URL for tool's homepage

https://pnpm.io

### Provide a basic test case to validate the tool's functionality.

```bash
pnpm --version
```

### Platforms where you need the tool

- [X] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Can this tool be installed during the build?

```bash
sudo npm install pnpm --global
```

### Tool installation time in runtime

20s

### Are you willing to submit a PR?

Yes

**Comment by shamil-mubarakshin** [comment] 2023-11-06 08:33
Duplicate of https://github.com/actions/runner-images/issues/2279 and https://github.com/actions/runner-images/issues/6460

**Closed by shamil-mubarakshin** 2023-11-06 08:33 UTC
Labels: needs triage, feature request
