### ISSUE TITLE
Add older version of Parallels to macos-12

### ISSUE THREAD

**Issue by zadesai** [actions/runner-images#10340] opened 2024-07-24 22:05 UTC
### Tool name

Parallels + Parallels SDK

### Tool license

Paid.

### Add or update?

- [ ] Add
- [X] Update

### Desired version

older version of Parallels - 19.3.0-54924 and Parallels SDK - 19.3.0-54924

### Brief description of tool

On Macos-12 we have Parallels v19.4.1-54985 installed. However, we cannot start a Windows 11 VM using this version. 
Can we install an older version of Parallels 19.3.0-54924 on Macos-12?

### URL for tool's homepage

https://download.parallels.com/desktop/v19/19.3.0-54924/ParallelsDesktop-19.3.0-54924.dmg

### Platforms where you need the tool

- [ ] Azure DevOps
- [ ] GitHub Actions

### Runner images where you need the tool

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [X] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Tool installation time in runtime

around 1 minute

### Are you willing to submit a PR?

Yes

**Comment by sureshe456** [comment] 2024-07-25 05:15
@zadesai, Will take a look into this issue. Will keep you posted.

**Comment by sureshe456** [comment] 2024-08-01 04:51
@zadesai,  We were able to start "Windows 11" VM successfully using  Parallels v19.4.1-54985 in our local (used trial version in local since we do not have the license). Can you please check if the issue is related to your license?

Also please share us a workflow with the error you are facing.

**Comment by zadesai** [comment] 2024-08-01 18:08
@sureshe456 we use Packer to create and start our Parallels vm. Packer-Parallels plugin uses "prlctl start" command to start the vm. When "prlctl start" is called, we get an operation canceled error.

I am curious about testing the runner macos images locally, can you share the steps for it? I can try running my script locally on them.

**Comment by sureshe456** [comment] 2024-09-19 14:21
Hi @zadesai Sorry for delay response.Can you please validate parallels of windows 11 once on macOS 12/13 images with the newer version as mentioned below since we don't have license to test parallels with older version.

New Version parallels : https://download.parallels.com/desktop/v20/20.0.1-55659/ParallelsDesktop-20.0.1-55659.dmg
Older version paralles: https://download.parallels.com/desktop/v19/19.3.0-54924/ParallelsDesktop-19.3.0-54924.dmg

**Comment by sureshe456** [comment] 2024-09-30 14:47
Hi @zadesai, We are closing the issue for now. If you face the same issue again, it can be reopened and we will work on it.

**Closed by sureshe456** 2024-09-30 14:47 UTC
Labels: OS: macOS, investigate, feature request
