### ISSUE TITLE
x32 broken support

### ISSUE THREAD

**Issue by Cyan4973** [actions/runner-images#8397] opened 2023-09-27 21:18 UTC
### Description

`x32` ABI support seems to be broken in latest Ubuntu image 22.04.
It used to work fine previously, and started failing 1-2 weeks ago.
It's still possible to compile `x32` binaries, but running them will fail, sometimes generating impressive stack traces.

Ubuntu 20.04 still works fine, so the issue seems limited to 22.04.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

```
Current runner version: '2.309.0'
Operating System
  Ubuntu
  [2](https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773#step:1:2)2.04.[3](https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773#step:1:3)
  LTS
Runner Image
  Image: ubuntu-22.0[4](https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773#step:1:4)
  Version: 2023091[7](https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773#step:1:8).1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20230[9](https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773#step:1:10)17.1/images/linux/Ubuntu2204-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230917.1
Runner Image Provisioner
  2.0.299.1
  ```

Example:
https://github.com/facebook/zstd/actions/runs/6295202061/job/17088139699?pr=3773

### Is it regression?

yes

### Expected behavior

`x32` binaries can run

### Actual behavior

Immediately fail, generally with a message like "exec format error".

### Repro steps

- compile source code with `-mx32` flag
- run produced binary
- -> crash

**Comment by ilia-shipitsin** [comment] 2023-09-28 07:12
@Cyan4973 , we can try to find out. do you have smaller repro steps ?

**Comment by Cyan4973** [comment] 2023-09-28 08:27
Really, just compile any simple program with `-mx32` flag, even "Hello World", and run it.
Use Github Action, set Ubuntu 22.04 image.

**Comment by sergei-pyshnoi** [comment] 2023-09-29 12:49
After investigation, we discovered that your problem is due to an updated version of the kernel. The update date coincides with the time when the error began to occur. The main problem is that starting from Kernal version 5.16+, the CONFIG_X86_X32 parameter is disabled in Ubuntu. A bug report has already been created on this topic (more [details here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1994516)). Unfortunately look like fix is not planned. I am closing this issue for now because current  behavior is expected and working by design. But if you have additional questions feel free to ask.

**Closed by sergei-pyshnoi** 2023-09-29 12:49 UTC
Labels: Area: C/C++, OS: Ubuntu, bug report
