### ISSUE TITLE
Build 'azure-arm.image' errored after 4 hours 7 minutes: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

### ISSUE THREAD

**Issue by sivaspf2010** [actions/runner-images#9911] opened 2024-05-22 07:11 UTC
### Description

Build 'azure-arm.image' errored after 4 hours 7 minutes: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

NA

### Is it regression?

no

### Expected behavior

should create the image.

### Actual behavior

    azure-arm.image: Running tests from 'C:\image\tests\Miniconda.Tests.ps1'
    azure-arm.image: Describing Miniconda
    azure-arm.image:   [+] Miniconda Environment variables is set.  883ms (640ms|243ms)
    azure-arm.image:   [+] Miniconda C:\Miniconda\python.exe  107ms (101ms|5ms)
    azure-arm.image:   [+] Miniconda C:\Miniconda\Scripts\conda.exe  988ms (972ms|16ms)
    azure-arm.image: Tests completed in 5.88s
    azure-arm.image: Tests Passed: 3, Failed: 0, Skipped: 0 NotRun: 0
==> azure-arm.image: Provisioning with powershell script: D:/a/1/s/runner-images/images/windows/templates/../scripts/build/Install-AzureCosmosDbEmulator.ps1
    azure-arm.image: Downloading package from https://aka.ms/cosmosdb-emulator to C:\Users\packer\AppData\Local\Temp\seecsw1y.msi...
    azure-arm.image: Package downloaded in 2.13 seconds
==> azure-arm.image: Checksum verification failed: expected 6312237EE3E06C730F8DCFB3D26F5202D9E713C0603039231A72DB56DD2605B4, got
==> azure-arm.image: 34D8E1968A868CEBBC31D1484C473FC61D3174D6C3B9AB71D4CE94F6618D7670
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:919 char:9
==> azure-arm.image: +         throw "Checksum verification failed: expected $expectedHash,  ...
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Checksum verifi...4CE94F6618D7670:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Checksum verification failed: expected 6312237EE3E06C730F8DCFB3D26F5202D9E713C0603039231
==> azure-arm.image:    A72DB56DD2605B4, got 34D8E1968A868CEBBC31D1484C473FC61D3174D6C3B9AB71D4CE94F6618D7670
==> azure-arm.image:
==> azure-arm.image: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

### Repro steps

Build 'azure-arm.image' errored after 4 hours 7 minutes: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]

**Comment by kishorekumar-anchala** [comment] 2024-05-24 09:20
Hi @sivaspf2010 ,
   
Duplicate of [9909](https://github.com/actions/runner-images/issues/9909)

**Closed** 2024-05-24 09:21 UTC
Labels: OS: Windows, bug report
